### ISSUE TITLE
CREATE - create text file from keyboard input

### ISSUE THREAD

**Issue by eswenson1** [PDP-10/its#100]
SYS3; TS CREATE
SYS1; TS PLAN => SYS3; TS CREATE
SYSEN2; CREATE 72

**Comment by eswenson1** [comment]
In PI distribution, source is in SYSENG; CREATE 72, not SYSEN2.

**Comment by eswenson1** [comment]
If you use PLAN rather than CREATE, you get the file <hsname>;<hsname> PLAN created by default  rather than <hsname>;<hsname> >.

**Comment by larsbrinkhoff** [comment]
Are those legal file name syntax? I'd never guess.

**Comment by eswenson1** [comment]
No. sorry, github ate half of the characters. It creates ejs;ejs plan, when jname is plan. Creates ejs; ejs > when jname is create -- assuming the hsname is ejs.
