### ISSUE TITLE
MACSYMA : ARRAY SHARE package missing 

### ISSUE THREAD

**Issue by TheFausap** [PDP-10/its#1006]
Hello,

it seems the file "array fasl" (in the share directory) is missing.
The source code should be called like "marray >"

```
DB ITS.1648. DDT.1546.
TTY 11
You're all alone, Fair share = 5%
:login fausap 
To see system messages, do ":MSGS<CR>"
macsym↑K!

This is MACSYMA 999

(C1) array(zz,8);
(D1)                                 ZZ

(C2) fillarray(zz,2.3);
Could not find file which matches "DSK:SHARE;ARRAY FASL"

(C3) 
```

regards,
Fausto

**Comment by eswenson1** [comment]
Thanks! I’ll fix.

**Comment by eswenson1** [comment]
I don’t think the source is marray >.  I think it is:

MAXSRC; ARRAY 5

I also know that there exists version 1, 2, 3, and 4.  I have MAXSRC; ARRAY 1, but believe the SHARE; ARRAY FASL that we have was compiled from MAXSRC; ARRAY 3.  So once I get versions 3, 4, and 5, I’ll try them all and update the build with one that works best.  I’ll compare the three sources to see what the differences are and whether I think it is safe to upgrade from 3 to 5.

**Comment by eswenson1** [comment]
I got MAXSRC; ARRAY 5 and when I compiled it to SHARE; ARRAY FASL and retried array(zz,8); this is what I got:

> macsym^K!
> 
This is MACSYMA 999
> 
> (C1) array(zz,8);
> Call to an undefined function 'ARRAYP' at Lisp level.
> 
> Error during display
> 
> (C2)

So there is more to this.  Gotta find ARRAYP now.

**Comment by eswenson1** [comment]
Interesting, ARRAYP is defined in LSPSRC; MLSUB 17.  It is compiled to LISP; MLSUB FASL.  If you breakpoint Macsyma and load LISP; MLSUB FASL, and then retry the array(zz,8); you get a result that appears like it might be correct:

> Back to MACSYMA, at LISP level.  LISP-BREAK.
> (load "lisp;mlsub fasl")
> 139217
> $p
> (C2) array(zz,8);
> (D2)                                                           ZZ

But if you then call fillarray on zz, you get this:

> (C3) fillarray(zz,2,3);
> 
> ARRAY FASL DSK SHARE being loaded
> DEFMAC FASL DSK LISP being loaded
> Loading done
> Loading done
> [ZZ, 2, 3] TOO MANY ARGUMENTS - APPLY to function ((LAMBDA) ((MLIST) ARY1 ARY2))
> [(C4)

So that isn't it either.  I don't know (yet) what's wrong how to fix.

**Comment by TheFausap** [comment]
@eswenson1 I notice a weird behaviour, with the existing MACSYMA, array command works without any error. Maybe ARRAY 5 is too new and it introduces some regressions or maybe can you try to load the file not compiled ?

**Comment by TheFausap** [comment]
I found also an ARRAY.11 in LMMAX with the fillarray function, maybe this could be useful

**Comment by TheFausap** [comment]
@eswenson1 I noticed just now, but fillarray wants only two args, you wrote with 3. The syntax is fillarray(zz,<value>); so put value in all array elements (8 in this case).

**Comment by TheFausap** [comment]
By the way ARRAY.11 in LMMAX is working without any problem.

**Comment by eswenson1** [comment]
Where are you finding LMMAX; ARRAY 11?

**Comment by eswenson1** [comment]
Also, I called fillarray with 3 args because you did in your first post!

**Comment by eswenson1** [comment]
Also, the issue with using files from LMMAX is that they were never used in ITS macsyma.  The latest ARRAY for ITS macsyma was MAXSRC; ARRAY 5.

**Comment by eswenson1** [comment]
LMMAX; ARRAY 11 is not a valid ITS Macsyma source. It doesn’t define Macsyma functions with the correct macros and doesn’t use the appropriate macsyma-module macro (whatever it is called) to load appropriate macros.

**Comment by TheFausap** [comment]
In my first post it was fillarray(zz,2.3) with "dot", not "comma". :-) 
Ok, but it's a coincidence it has the fillarray function, and it's working. But maybe fillarray() is not a standard MACSYMA function as array().
I mean array() is working without ARRAY FASL, only fillarray need it.

**Comment by eswenson1** [comment]
Ok, this works fine in my current Macsyma (I"ll commit soon).  The syntax for fillarray is that the second argument must be a list or array.  So fillarray(zz,2.3); is invalid.  You need fillarray(zz,[2.3]);  You can determine this by using describe(fillarray);  In any case, you need MAXSRC;ARRAY 5, which is the latest version of ARRAY used in ITS Macsyma.  I will commit this soon.
