### ISSUE TITLE
PRUFD - list files on disk volume

### ISSUE THREAD

**Issue by eswenson1** [PDP-10/its#101]
SYS1; TS PRUFD
SYSEN2; PRUFD 10

**Comment by eswenson1** [comment]
Also requires JSF; STNDRD MACROS

**Comment by eswenson1** [comment]
This will require debugging. It does a .VAL 0 when run on DB.  I'll look into it.

**Comment by larsbrinkhoff** [comment]
So output went to a printer in the original? Can you make a new issue about that?

**Comment by eswenson1** [comment]
Yes. Will do.

-- Eric

**Comment by eswenson1** [comment]
See #195
