### ISSUE TITLE
primer(); in macsyma doesn't work

### ISSUE THREAD

**Issue by eswenson1** [PDP-10/its#1011]
If you invoke it, you get this:

> (C4) primer();
> 
> PRIMER FASL DSK MACSYM being loaded
> Loading done
> [USER, PROFIL, DSK, ALJABR]  FILE NOT FOUND
> (C5)

**Comment by TheFausap** [comment]
Interesting… ALJABR was one of the commercial names of Macsyma from MIT.

**Comment by eswenson1** [comment]
Adding ALJABR; USER PROFIL gets a little further.  Now:

> (C7) primer();
> [SCRIPT, INTRO, DSK, ELLEN]  FILE NOT FOUND
> (C8)

**Comment by eswenson1** [comment]
Now looking for ELLEN; SCRIPT INTRO.

**Comment by eswenson1** [comment]
I have multiple versions of ELLEN; SCRIPT INTRO. Will find best one and see if I can get the primer working. Will presumably lead to more primer files — with luck I have all of them as well.

**Comment by eswenson1** [comment]
Not having much luck so far.  With ELLEN; SCRIPT INTRO present, I get this:

> *macsym^K!
> 
> This is MACSYMA 1000
> 
> (C1) primer();
> 
> PRIMER FASL DSK MACSYM being loaded
> Loading done
> 
> SCRIPT INTRO DSK ELLEN being loaded
> 
> You have run out of SYMBOL space.
> Do you want more?
> Type ALL; NONE; a level-no. or the name of the space.
> 
> all;
> Loading done
> 
> NON-FIXNUM VALUE: UNBOUND
> 
> (C2)

Attempting to debug runs out of memory.  Will keep trying....

**Comment by eswenson1** [comment]
Got primer() running with a later version of ELLEN; PRIMER 239 and some additional files in the right places.  Will commit this soon.
