### ISSUE TITLE
TELNET configuration 

### ISSUE THREAD

**Issue by TheFausap** [PDP-10/its#1016]
Hello,

I noticed with supdup the connection to ITS is quite easy and also the terminal is already ok to work with emacs and other programs.
With TELNET, I had some problems to figure out which is the correct terminal emulation.
I'm using PuTTY and I tried first with TCTYP vt52, but EMACS output is quite messy, then I tried with CRTSTY vt100, and there's no output at all from EMACS when I open a file.

So maybe, could be useful add a little documention about how to setup a telnet client (or maybe a preferred telnet client to use). 

What do you think ?

**Comment by larsbrinkhoff** [comment]
I recently learned that ANSI may be the best terminal type for modern terminal emulators.

**Comment by TheFausap** [comment]
I tried with Putty (in XTERM mode) and VT52, but EMACS is not so happy 

![e1](https://user-images.githubusercontent.com/1846443/41812700-f3e8c7c8-7727-11e8-85db-d2ac45f7755f.PNG)

**Comment by larsbrinkhoff** [comment]
First of all, you have to send the terminal a special escape sequence to enter VT52 emulation mode.  It's "ESC [ ? 2 l".

But I'm not sure PuTTY implements this escape sequence.

**Comment by TheFausap** [comment]
I think I have also a problem closing a connection (I close PuTTY), because if I do a PEEK I have this:

```
 20 ___020 TELSER SYN027     TCPI    ?         4   0   0%
 21 ___021 TELSER SYN027     TCPI    ?         4   0   0%
 22 ___022 TELSER SYN027     TCPI    ?         4   0   0%
 23 ___023 TELSER SYN027     TCPI    ?         4   0   0%
 24 27TLNT TELSER HST004     SLEEP   ?         1   0   0%
 25 FAUSAP HACTRN FAUSAP     TTYI    T27      31   9   0%
 26 33TLNT TELSER HST004     SLEEP   ?         1   0   0%
 27 ___027 TELSER SYN027     TCPI    ?         4   0   0%
 30 ___030 TELSER SYN027     TCPI    ?         4   0   0%
 31 FAUSA0 HACTRN FAUSAP     HANG    >        31   9   0%
 32  FAUSA0 EMACS  FAUSAP    TTYI    T33      64  28   0%
 34 ___034 TELSER SYN027     TCPI    ?         4   3   0%
 35 ___035 HACTRN      0     HANG    >        30   9   0%
 36  ___035 PEEK        0    +TTYBO  T0       11   1   0%
Fair Share 80%     Totals:                   349       0%          7
Logout time = 22      Lost 0%  Idle 0%  Null time = 6:56
```
how I could kill all the TELSER and also FAUSAP session ?

**Comment by TheFausap** [comment]
I found this nice terminal emulator for Windows (in C#). 

https://github.com/kgober/VT52

I compiled with Visual Studio 2017 and it's working really nice (I have to use :CRTSTY vt100 and I have a clean EMACS session). 
It's also quite vintage :-)

**Comment by larsbrinkhoff** [comment]
Note that if you just close the TELNET connection, your ITS job may linger around.

I'm not good at this, but there are ways to get at the jobs.  You should be able to say <code>foo<kbd>$</kbd>j</code> or `:ujob user foo` and then `:kill` to kill them.

**Comment by TheFausap** [comment]
Should I kill the ___XXX TELSER processes ? 
How can I do to proper close the SUPDUP connection, after the :LOGOUT ? 

At the moment, my workaround is to shutdown the system and boot again :)

**Comment by larsbrinkhoff** [comment]
I think you can go ahead and kill them.  The worst that can happen is that you kill the one your're currently using and then you're thrown off the system.

I usually quit SUPDUP by typing "Control-^ q".

**Comment by TheFausap** [comment]
Ok. But the problem is if I do, for example, :ujob ___013 telser, the system replies with #! and if I do :kill nothing is killed.
If I do a :PEEK I can see that process again.

**Comment by eswenson1** [comment]
What does PEEK say about the process?  I ask because when Lars had some hung processes on one of his ITS systems, we could not kill them because they were hung in a .logout system call.  Peek showed us that this was the state they were in. I wonder if the same thing is happening to you.

**Comment by TheFausap** [comment]
PEEK shows something like this:

```
DB ITS 1648  Peek 630   6/27/2018 23:07:07  Up time = 2:19:59
Memory: Free=365   Runnable Total=11 Out=5     Users: High=14 Runnable=1
Index Uname Jname Sname     Status   TTY    Core Out %Time    Time PIs
  0 SYS    SYS    SYS        HANG    ?        56   0   0%
  1 CORE   JOB    CORE       UUO     ?         0   0   0%
  2 COMSAT JOB.07 SYS        HANG    ?         3   0   0%
  3 COMSAT IV     IV         HANG    ?        30   8   0%
  4 FAUSAP HACTRN FAUSAP     HANG    >        31   9   0%
  5  FAUSAP PEEK   FAUSAP    +TTYBO  T0  C    11   3   0%
  7 PFTHMG DRAGON DRAGON     HANG    ?         6   0   0%
 13 ___013 TELSER SYN027     TCPI    ?         4   0   0%
Fair Share 10%     Totals:                   141       0%
Logout time = 2       Lost 0%  Idle 1%  Null time = 3:29
```

maybe those HANG processes create some problems.

**Comment by eswenson1** [comment]
Actually no.  That TELSER job just looks like it is hanging waiting on TCP input.  And the other HANGs are correct -- those daemons are HANGing around waiting for something to happen (as most good daemons do)

**Comment by larsbrinkhoff** [comment]
Maybe HANG means they are executing the .HANG UUO?  I should pay more attention to what PEEK says.

`!` means DDT made a new inferior job.  It doesn't mean that the job itself is new (obviously in this case), just that this instance of DDT created a connection to the job.  (:FORGET will remove this connection.)

`#` means the job isn't a direct inferior.

**Comment by TheFausap** [comment]
Thanks. So why :KILL doesn't kill the job ? Is seems kills only the connection.
I tried also to :LOGIN with user ___013, but it says illegal UNAME.
By the way, if I use the sequence (to exit supsud) @larsbrinkhoff wrote before, the TELSER process correctly killed.

**Comment by larsbrinkhoff** [comment]
Since you can attach to the job (in my case I couldn't even do that), you can examine where it's hung.

After :ujob, press <code><kbd>$</kbd><kbd>^K</kbd></code> to load the symbols.  The value of `.` should be the PC, so type e.g. `.=`.  Or `./` to see the instruction.  Move up and down the program with `^` and <code><kbd>^J</kbd></code>.

**Comment by TheFausap** [comment]
@larsbrinkhoff thanks. I'll do that... by the way as Eric told in the mailing list, GUN command (from LOCK) killed correctly the processes.

**Comment by larsbrinkhoff** [comment]
I wonder what LOCK does that DDT doesn't?

Checking LOCK... Oh, it uses the .GUN UUO.

**Comment by larsbrinkhoff** [comment]
Hey, PEEK has an undocumented command X which does .GUN.
