### ISSUE TITLE
CHESS.144

### ISSUE THREAD

**Issue by TheFausap** [PDP-10/its#1024]
I completed the transcription. MIDAS got some errors... I'll try to fix them 

https://gist.github.com/TheFausap/a7ef893335715d65c3104f64ef49659c

**Comment by larsbrinkhoff** [comment]
Great, thanks!

**Comment by TheFausap** [comment]
Updated the GIST. Now it compiles and runs and it's waiting for a move. :-)
Is there any manual out there ?

**Comment by larsbrinkhoff** [comment]
To print the board in OCM, type ^L.  To print the boad in CHESS2, type ^B.

Do any of those work in CHESS 144?

**Comment by TheFausap** [comment]
Not at all.
It starts with a debug version. I have to understand how to remove this.

Here is the output

```
CHESS.144
DEBUG VERSION
W 1   f2;f3+
AMBIGUOUS
W 1   f1 f5
ILLEGAL
W 1   


```

**Comment by larsbrinkhoff** [comment]
This looks like a set of commands, and the correponding jump targets:  
https://gist.github.com/TheFausap/a7ef893335715d65c3104f64ef49659c#file-chess-144-L493-L517

`BD` should print the board.

**Comment by TheFausap** [comment]
With BD it says AMBIGUOUS

**Comment by larsbrinkhoff** [comment]
It would probably be helpful to examine the program in DDT.  Set some breakpoints where it reads input from the TTY, and see what happens.  The RP1 table is searched in RSP.  How do we reach RSP?

Some hints:

- Create a job: <code>chess<kbd>$</kbd>J</code>
- Load the program: <code><kbd>$</kbd>L ts chess</code>
- Set a breakpoint: <code>gnup1<kbd>$</kbd>B</code>
- Another breakpoint: <code>rdip1<kbd>$</kbd>B</code>
- Run: <code><kbd>$</kbd>G</code>

**Comment by TheFausap** [comment]
Ok. Commands starts with "."
So .BD prints the board.

**Comment by larsbrinkhoff** [comment]
Great!  From what I've seen in the source, the bord should look similar to OCM/MacHack.  Is that correct?

**Comment by TheFausap** [comment]
Yes. The program use the descriptive notation and the player is white by default.

https://en.wikipedia.org/wiki/Descriptive_notation

![chess1](https://user-images.githubusercontent.com/1846443/41933442-27f2f22e-7984-11e8-8df2-0496ecd86941.PNG)

**Comment by TheFausap** [comment]
http://archive.computerhistory.org/projects/chess/related_materials/text/4-0.Issue_2_Computer_Chess_Newsletter/Issue_2_Computer_Chess_Newsletter.1977.062303031.sm.pdf

at page 18 - Greenblatt vs Bobby Fischer!!!! :-)

**Comment by larsbrinkhoff** [comment]
Nice.  I suppose this should be ready for addition.

I see in the gist the whitespace is off in some lines.  E.g. the indentation is two tab characters in some lines.

**Comment by TheFausap** [comment]
I tried to reproduce the pdf output, but if you want to modify it there's no problem.
I also found a typo, and I updated the gist.

**Comment by larsbrinkhoff** [comment]
Thanks, I'm doing some edits.

**Comment by larsbrinkhoff** [comment]
Still editing.

I wonder if the ASCIZ at label PMKB should be spaces or a single TAB?

**Comment by larsbrinkhoff** [comment]
Done.  Pull request #1045.
