### ISSUE TITLE
ITSTAR - LOAD error

### ISSUE THREAD

**Issue by TheFausap** [PDP-10/its#1038]
Hello,
I have no problem to dump file from its and move them between my installations, but I got this error when I create a tape (with itstar) on the host and then I try to load in ITS:

MAG TAPE STATUS TM03 error status decode routine needs to be written ?

I'm using KLH10 and I create the tape with the following command:

./itstar -cf fausap.tape FAUSAP

where FAUSAP is the directory name.

I will try also with SIMH.

**Comment by TheFausap** [comment]
With SIMH I have no problem.

**Comment by atsampson** [comment]
Have you tried rewinding the tape before loading? (Do "rewind" at the DUMP prompt.)

**Comment by TheFausap** [comment]
Ok, with KLH10, I need first a rewind (so maybe could be useful update the doc), but I got another error:

```
TAPE NO      1 CREATION DATE  180628
ERROR: OPEN:  DSK: FAUSAP; _DUMP_ OUTPUT - DIRECTORY FULL
```

is there a maximum number of files allowed in a directory ? 
If I do ^F, it seems I have some space available

`FREE BLOCKS #0=19906`

**Comment by eswenson1** [comment]
The #0 refers to disk unit 0 and shows that you have that many blocks free on that drive. There is an ITS-build-time max number of directory entries. You hit it. 

In this case, delete some files in order for your load to work, or cross retrieve into a new/different directory.

**Comment by TheFausap** [comment]
Thanks!
