### ISSUE TITLE
SUPDUP escape character change

### ISSUE THREAD

**Issue by TheFausap** [PDP-10/its#1039]
Modifying some SAIL code using the extended character set, I got a problem with ^^ (used in SUPDUP client to send internal command).
That sequence ^^ is used to type the EQV glyph, but now it's impossible to use it.

I also found that SUPDUP client can set the TOP bit (I suppose it's related to the TOP key, correct?) but I tried to use it, according the SAIL character set from saildart.org, but I had no luck (that glyph should be TOP-1).

So, is it possible to change the escape character in SuPDUP client?

thanks
Fausto

**Comment by TheFausap** [comment]
it's the supdup unix client. Ok thanks, it works in that way !

**Comment by larsbrinkhoff** [comment]
I'm not sure how ITS and programs handle the TOP bit.  I think maybe applications need to tell ITS they want the full set of SAIL bucky bits, in which case they may also get separate META and CONTROL bits.  There's a SUPDUP bit called %TOSAI for enabling the SAIL character set, but I think that's only for the output side.  There should be something similar for the input.

You should read the SUPDUP and TTY documentation in ITS.  For example SYSDOC; ITSTTY >

**Comment by rmaldersoniii** [comment]
The alternative way to enter the EQV character in EMACS is with the TECO command 30I$ (or 36.I$) from a minibuffer, or if you have the M-X 0$ command available the use M-X 0$36.i$$<CR>
More characters than simply doubling the character, but tasty, IMO.

**Comment by larsbrinkhoff** [comment]
The same goes for ^Z.  If you want to enter it in EMACS, you can use ^Q and then ^_ ^Z, or ^_ 33.  Or the TECO way ◊◊ 33I ◊◊.  Using the SAIL rendition of ALTMODE.

**Comment by larsbrinkhoff** [comment]
Can this be closed?
