### ISSUE TITLE
Books

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#1040]
Anything and everything vaguely related to hacking, PDP-10, ITS, Project MAC, ARPANET, etc.

- Hackers: TMRC, the AI Lab etc
- Free as in Freedom: about RMS' crusade
- The Dream Machine: Licklider and the Dynamic Modeling group
- Unix-Hater's Handbook
- Hacker's Dictionary
- The Cuckoo's Egg

**Comment by atsampson** [comment]
Jon Peterson's "Playing at the World", about the origins of D&D and similar roleplaying games, has a section about ties between MIT games (Spacewar p607, Zork p617) and roleplayers at MIT including Dave Lebling.

Phil Lapsley's "Exploding the Phone", a history of phone phreaking, has various stories about phreaking at MIT in the early 60s and quotes Levy on phreaking with the PDP-6.

Katie Hafner and Matthew Lyon's "Where Wizards Stay Up Late: The Origins of the Internet" has a few mentions of MIT and Project MAC (e.g. some 1976 stats for the AI Lab mail system) and obviously a lot about the development of the ARPANET.

Several of Douglas Hofstadter's books talk about the history of AI; e.g. "GEB" and "Le ton beau de Marot" both have sections on SHRDLU. Daniel Dennett's "Brainchildren" also has various stuff about later AI lab projects.

Bruce Sterling's "The Hacker Crackdown" has a few references to MIT as the ideal of the hacker ethos. (It might be worth hunting through Jason Scott's collection on textfiles.org for some of his sources.)

Glyn Moody's "Rebel Code", a history of the open source movement, has a chapter about GNU, where RMS describes how he got into programming and joined the AI lab.

There isn't yet an MIT Press [Platform Studies](https://mitpress.mit.edu/books/series/platform-studies) book on the PDP-10. But there should be!

**Comment by larsbrinkhoff** [comment]
"The Brain Makers: Genius, Ego, and Greed, and the Quest for Machines That Think", by Harvey Nyquist.  About Lisp machines.

"Core Meory", by Mark Richards.  Pictures of vintage computers.

"Computing in the Middle Ages: A View From the Trenches 1955-1983", by Severo Ornstein.

["Dealers of Lightning: Xerox PARC and the Dawn of the Computer Age"](http://library.globalchalet.net/Authors/Startup%20Collection/%5BHiltzik,%201999%5D%20Dealers%20of%20Lightning%20-%20Xerox%20Parc%20and%20the%20Dawn%20of%20the%20Computer%20Age.pdf), by Michael A. Hiltzik.  Mentions MAXC.

**Comment by Alexey-Slyusar** [comment]
Hofstadter, Douglas R. 1979. Gödel, Escher, Bach: An Eternal Golden Braid. New York:
Basic Books.

I learned about this book from SICP.
In my humble opinion the book is very successful in providing some kind of hacking related philosophy for a broader audience.

If you think that it is not so relevant, I'll delete the post.

**Comment by eswenson1** [comment]
I read that book the month it came out. It was a tremendously good book! I should re-read it. Thanks for the memory/reminder.

**Comment by larsbrinkhoff** [comment]
""Where Wizards Stay Up Late" online PDF:  
https://monoskop.org/images/e/ee/Hafner_Katie_Lyon_Matthew_Where_Wizards_Stay_Up_Late_The_Origins_Of_The_Internet.pdf

**Comment by larsbrinkhoff** [comment]
"Minskys and Trinskys", http://www.blurb.com/b/2172660-minskys-trinskys-3rd-edition

**Comment by Alexey-Slyusar** [comment]
Wow, it is just fantastic book!
It is where MIT AI Lab intellectual heritage personified as an act of art!
Mathematics can be very beautiful and joyful  in the hands of wizard, Isn't
it? :-)

It is sad that in common we are not taught in such way in schools.

Lars, Thank you very much for the link to this gem!

I'll dive into as soon as I have some free time.
And I'll definitely show this to my kids.

Thanks again!


вт, 26 февр. 2019 г. в 9:15, Lars Brinkhoff <notifications@github.com>:

**Comment by larsbrinkhoff** [comment]
I'm reading **The Dream Machine** now, and not only does it describe Licklider's fascinating career, but also the historical backdrop of how digital computers evolved mostly at Hardward and MIT.

**Comment by larsbrinkhoff** [comment]
"Digital At Work" in PDF form:  
http://gordonbell.azurewebsites.net/digital/digital%20at%20work%201992.pdf

> Alan Kotok remembers that “Gordon came running into the lab one day in 1962, as he was wont to do, and said, ‘Time to build a big computer, guys!’ MIT was looking for a large time- sharing system and Gordon felt that there was no reason that we shouldn’t build one for them. So we started designing what would become the PDP-6.”
> &nbsp; “By time-slicing a computer among many users, we provided each user with what appeared to be their own large computer,” says Gordon Bell. “The idea of timesharing came from two PDP-1 customers-Bolt Beranek and Newman, and MIT. We designed the PDP-6 from scratch to be the first commercially available timesharing system ever offered, so that everybody could have their own piece of a large computer for interactive personal computing.”

As we know, Project MAC selected Honeywell instead.  But DEC donated a PDP-6 to the AI group, so everyone was happy.

**Comment by Alexey-Slyusar** [comment]
Here is a link to "Minskys and Trinskys" related video where R. William Gosper talks about:
https://youtu.be/lXsVWwPa7bc

**Comment by atsampson** [comment]
Blair Jackson and David Gans' "This Is All A Dream We Dreamed: An Oral History of the Grateful Dead"  includes a 2001 interview with [Ned Lagin](https://en.wikipedia.org/wiki/Ned_Lagin), where he says:

> Then my friends and I got the idea to invite the Grateful Dead to do a concert at MIT. I helped organize that. They arrived on May 4, 1970, having just come from Yale. Kent State had just occurred. [...]
>
> The next couple of days, they [played an outdoor gig](https://archive.org/details/gd1970-05-06.sbd.gmb.95817.flac24) at the student center, the same place that I practiced piano in every night, under very cold and tough circumstances. And the next night they [played with the New Riders](https://archive.org/details/gd1970-05-07.aud.sirmick.32276.sbeok.flac16) inside the auditorium next door. Between that time, Phil [Lesh] and I and Jerry [Garcia] and I -- alternately, 'cause I could only take one at a time -- would go down into the basement and play the first computer game, Space Wars. We played Space Wars through the night.

**Comment by larsbrinkhoff** [comment]
Grateful Dead making another appearance: https://www.dead.net/deadcast/long-strange-tech-part-1
