### ISSUE TITLE
Samson's DECtape files

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#1048]
Someone better go through and catalogue the files.

Tape images are here:  
https://github.com/PDP-10/its-vault/tree/master/dectape

My [macdmp tool](https://github.com/larsbrinkhoff/pdp10-its-disassembler/blob/master/macdmp.c) can extract the files.  Maybe check deleted files too.

**Comment by larsbrinkhoff** [comment]
I think M79 TTST > is notable.  It's a MIDAS program for running on ITS.  Given many other files mention dates around 1965-1966, this must be a very yearly PDP-6 timesharing program.

It also contains initials and nicknames for some ITS hackers.

**Comment by larsbrinkhoff** [comment]
SUDSUD 9 on the same tape is dated 700829.  Maybe not quite that early, then.

**Comment by larsbrinkhoff** [comment]
PKS P15, MAYAN 31.  Timesharing program for Mayan calender.

**Comment by larsbrinkhoff** [comment]
PSamsonI, FTN 10B.  FORTRN ... COMPILER.  Years mentioned 1965 and 1968.  Timesharing.

**Comment by larsbrinkhoff** [comment]
Many versions of BIG.  PSamsonIX, BIG 82 may be the oldest: 690702.  Standalone.

**Comment by larsbrinkhoff** [comment]
RandomSystem, CHESS BIN.  Uses obsolete UUO .SETMSK.

**Comment by larsbrinkhoff** [comment]
RandomSystem, @ HACTRN.  I'm guessing the part starting at 34000 is DDT.  At least parts below that is a chess program.

**Comment by larsbrinkhoff** [comment]
RandomSyste, MIDAS 16K.  Probably linked together from MIDAS, MACTAP, and ASSEMB.  So presumably this runs standalone and accesses MACDMP files.

Has the telltale message "CONSTANTS AREA INCLUSIVE" which we recognize from MIDAS.

**Comment by larsbrinkhoff** [comment]
The PSam_tornLabel directory looks ok, but the file contents don't.  Seems like the block order is scrambled.

**Comment by larsbrinkhoff** [comment]
M11_P12, FOO3 BAR.  Uses 340 display.

**Comment by aap** [comment]
I put all the extracted files here http://pdp-6.net/misc/samson_tapes.zip
There's lots of cool stuff in there, even an early LISP binary it seems!

**Comment by larsbrinkhoff** [comment]
RandomSystem, tape name RND has a file DDTYP TS5.  It uses the obsolete and removed UUO .GSNAM.

It's timesharing program which reads a file name from TTY.  An interesting detail is that the device defaults to DD0, which is a Data Disc.

**Comment by larsbrinkhoff** [comment]
The MusicDemo tape is in bad shape, but if you shift things around the directory file names are readable:

```
MUSIC  B6.2
MUSIC  RULEBR
MUSIC! EKNM3!
VISUAL NOISE
MUSIC  EKNM2
MUSIC  SHEILA
MUSIC  GODSAV
MUSIC  BANANA
MUSIC  MARS
MUSIC  BRAND6
MUSIC  EKNM1
MUSIC  WINSTO
MUSIC  DOWNTN
MUSIC  LIUTLE
