### ISSUE TITLE
AI KA10 processor modifications

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#1063]
Would be good to document the changes.  Master prints here: http://bitsavers.org/pdf/mit/ai/MIT-AI-Lab-KA10-modified.pdf

- Paging, including XTCR(I), LPM, SPM
- MAR
- Quantum clock
- CIRC
- One proceed
- JPC
- Indexing off PC
- Shared I/O bus
- PI channel 1 multiplexing

**Comment by larsbrinkhoff** [comment]
CC @aap, @rcornwell, @brouhaha.

**Comment by aap** [comment]
We should really try to get the schematics for the pager.

**Comment by larsbrinkhoff** [comment]
I half-remembered TK saying he has he schematics, but now that I check I see it was the TEN11.

Maybe Lothberg has them?  Around 1985 there was talk of sending him copies of the ML pager prints.  See the KS-ITS mailing list.
