### ISSUE TITLE
Pre-ITS tool set

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#1064]
For the PDP-6 sim/emulators, we should bring up a complete set of tools:

- SYSTEM GEN (#1030)
- MACDMP (#449)
- DDT (#1460)
- MIDAS (#663, #681)
- STINK (#662, #656)
- TECO (#662, #655)
- LISP

Anything else?

Outside the scope of this, there are also programs like games or for music.  See https://github.com/PDP-10/its/issues?q=label%3Apdp6

**Comment by aap** [comment]
display hacks. if we don't find any, i wanna see if i can port the PDP-1 Minskytron http://www.masswerk.at/minskytron/.
MACHACK VI
Spacewar!

**Comment by larsbrinkhoff** [comment]
We have plenty of those now, and many are quite interesting.  But they are not in the the "basic toolbox" category.

**Comment by larsbrinkhoff** [comment]
Progress:

- [ ] SYSTEM GEN, assembles
- [ ] MACDMP, assembles
- [x] DDT, assembles and runs
- [ ] MIDAS
- [ ] STINK
- [x] TECO, binary seems to work
- [ ] LISP, not found

**Comment by aap** [comment]
SYSTEM GEN built me a system tape that boots into MACDMP (modified 6U32 to 6U16) just now. Still having some issues with macdmp but i suspect my dectape emulation to be the culprit.

**Comment by larsbrinkhoff** [comment]
Great!  I checked the SYSTEM GEN and MACDMP boxes.

There's a good chance DDT will work... just have to avoid the 340 display for now.

As for TECO, we just have a binary and it's using the 340 too.  It seems to work when run on the KA10 simulator, so it'll probably run fine when you have a 340 in place.

**Comment by aap** [comment]
DDT is sort of working on the 6 when DISON is set to 0. Loading it from ITS with auxcpu and starting at IFIX doesn't seem to give it symbols. Next project: get it onto a dectape and load from MACDMP.

**Comment by larsbrinkhoff** [comment]
NTSDDT gets symbols from MACDMP or DSKCMP when using the $T command.

Loading the PDP-6 from TS DDT doesn't write symbols where NTSDDT expects them.  TS DDT maintains a symbol table in its own job.

But since your're loading NTSDDT, it doesn't make sense to load symbols anyway.  The symbol table is for the program being debugged, not for DDT itself.

**Comment by larsbrinkhoff** [comment]
I'm checking off MIDAS in the list.  @aap tested the .; @ MIDAS file timestamped 1972-12-22.  It's using the command set described in [AI memo 90](https://github.com/larsbrinkhoff/its-archives/blob/master/ailab/AIM-90.pdf).

I'm thinking there should be a pdp6.md guide, and/or an INFO; PDP6 > describing how to use the PDP-6 standalone, as well as how to interact with it from ITS.

**Comment by larsbrinkhoff** [comment]
Hello @MattisLind,

We saw your YouTube video booting RT-11 using DECtapes.  Excellent video!  We're playing with a simulated PDP-6 with Microtape drives, and find transfer rates to be very slow.  This seems in line with your video.  How long does it take for a TU56 to read a block?

**Comment by MattisLind** [comment]
It is slow. I remember correctly it reads a three bit word every 35us. A full 18 bit word is thus 200 us. I think a block is 256 18-bit words. That would make it approx 50 ms per block. Doing anything with at Dectape is very timeconsuiming. But maybe that biggest problem is the time it takes to search for a block. It spends a lot of time just go back and forth. And since the OS doesn't buffer much it keeps reading/writing the directory (which is among the first blocks on the tape) all the time.

**Comment by larsbrinkhoff** [comment]
Thanks for confirming.

**Comment by larsbrinkhoff** [comment]
@patbarron, see this for some PDP-6 tools we have running.

I think we can close this now.  STINK isn't tested yet, but all the other programs worked fine out of the box.

**Comment by larsbrinkhoff** [comment]
@ LISP found, but is it fully functional?

**Comment by larsbrinkhoff** [comment]
It probably is.  Character input uses the FSC instruction and depends on the unnormalizing PDP-6 behaviour.
