### ISSUE TITLE
WUMPUS - hunt the wumpus interactive game

### ISSUE THREAD

**Issue by eswenson1** [PDP-10/its#108]
SYS1; TS WUMPUS
source missing?

**Comment by larsbrinkhoff** [comment]
https://en.wikipedia.org/wiki/Hunt_the_Wumpus

**Comment by larsbrinkhoff** [comment]
I compared WUMPUS.MID with TS WUMPUS, and they are almost identical, except for the system calls of course.

HTML rendition:  
http://pdp-10.trailing-edge.com/SRI_NIC_PERM_SRC_3_19910112/01/utilities/wumpus.mid.html

**Comment by eswenson1** [comment]
Nice! That shouldn't be too hard to re-create -- unless there are lots of system calls!

**Comment by larsbrinkhoff** [comment]
@atsampson, I see you reconstructed this.  Yes, it would be good to keep the original file as a separate version.
