### ISSUE TITLE
TTY scanners

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#1105]
Apparently MIT didn't use any DEC TTY scanners for the KA10s.  These are the options:

- Datapoint kludge 
- Knight kludge
- Morton box
- NOVA

**Comment by larsbrinkhoff** [comment]
### Datapoint kludge

- DPKPP
- Used on AI only.
- 9 ttys.
- Device DKP=604

**Comment by larsbrinkhoff** [comment]
### Knight kludge, aka TK10

- TK10P
- Used on AI only.
- 16 ttys.
- Device NTY=600

**Comment by larsbrinkhoff** [comment]
Morton box

- MTYP
- Used on DM and ML.
- 27 ttys
- Device MTY=400

**Comment by larsbrinkhoff** [comment]
### NOVA

- No information other than "used to have?"

**Comment by atsampson** [comment]
I don't know if it's the same thing, but in [Richard Greenblatt's commentary](http://projects.csail.mit.edu/films/aifilms/Podcasts/40-logo.mp3) on [AI film 40](http://projects.csail.mit.edu/video/history/aifilms/40-logo.mp4), he says (transcribed):

> In the school, as it says here in the note, one of the things we had at that stage was a Data General SuperNOVA, which was a so-called minicomputer of those days. It was a kind of portable refrigerator kind of size, and it was used to support this display, so we had a display terminal.

**Comment by larsbrinkhoff** [comment]
@jh95468 wrote about the DM PDP-10:

> TTY lines were usually pretty slow - 9600bps max.  But we had a student (Steve Morton - SGM) who really, really wanted to do a hardware project.  He wanted to build a disk controller.  But we had a disk controller, so he was assigned to build a TTY controller to handle all of the new terminals.  He did that, and it worked great.  When we later were working on the IMLAC client/server setup, I discovered that Steve's TTY controller had been designed more like a disk controller.  In particular, it was capable of speeds much greater than TTYs needed.  So I installed some better wiring (RG174-coax from the 9th to 2nd floors - twisted pair hadn't been discovered yet), and got the PDP-10 <-> Imlac connections running at something like 50+ kbits/second.

**Comment by larsbrinkhoff** [comment]
I also see in ITS that DM had a TK10 device to talk to a PDP-11.

**Comment by jh95468** [comment]
During my tenure at MIT-DM (1970 through late 1977), the only PDP-11 I recall attached to the DM machine was an 11/05 or /10 that we used as a signal processing front-end for the "Hand Sent Morse Understanding" project.  That PDP-11 was in a small lab on the 2nd floor, and connected to the PDP-10 through the same coax lines we used to connect the Imlacs.  So it almost certainly went through the "Morton box".   The PDP11 interfaced via RS232 to a Collins radio in the lab as well as some custom hardware we built (I remember spending many hours wire-wrapping and debugging augat boards).  The PDP-11 did things like A-D conversion and then FFTs of incoming signals, and the custom hardware contained PLLs to lock on to and track individual Morse signals.

It's possible that the PDP-11 was hooked up to check it out in the 9th floor computer room, and connected to the PDP-10 locally - possibly through a TK10.    I don't remember; if you can find Ed Black (EHB@MIT-DM) he might know more; he did most of the PDP-11 code.

I found another old document - in the ARPA online archives at DTIC - and attached it here.  It is a paper written by several of the DM crew about the Morse project in which the PDP-11 was used.  Not much technical detail, but it's probably the largest project we built, with all the PDP-10 code in MDL and the PDP-11 in assembler of course.  It should give an idea of the kinds of things that were done with the DM system at the time.
[MorseProjectPaper.pdf](https://github.com/PDP-10/its/files/2242589/MorseProjectPaper.pdf)

**Comment by larsbrinkhoff** [comment]
According to diff between SYSTEM; CONFIG 27 and 39, DM had a TK10 but lost it in 1976.

**Comment by jh95468** [comment]
I don't recall ever taking out a TTY controller.  Are you sure the TK10 was a TTY interface?   I think the removal in 1976 may have been the Dectape drive, not the TTY controller.  Can't remember all the model numbers...    FYI, we did take out the Dectape drive circa 1976, after we had enough disk drives that no one used Dectapes any more.  Removing the tape support from ITS freed up space for more code.  But it also caused problems --- e.g., the no-tapes ITS would crash and debugging traced the problem to a "JRST .+1202"  (or something like that) instruction somewhere in the DSK code, which was jumping to whatever was now at .+1202 in the new ITS.  We surmised that someone had tweaked the DSK code (something about PCLSRing IIRC) and noticed that the necessary cleanup was already included in the Dectape code.  So rather than duplicate the code, or spend time to make it into a callable subroutine, a patch was made to just JRST from the DSK code into the tape code.    Worked fine, until we removed the tape code....

**Comment by larsbrinkhoff** [comment]
Thanks @jh95468, that's interesting information.

I don't have much to go on here.  Just these lines from the SYSTEM; CONFIG file.  The first snippet is from CONFIG 27:

```
IFE MCOND DM,[
...
DEFOPT TK10P==1         ;HAS TK10 TTY SCANNER, STILL
```

Then, in CONFIG 39 (we don't have the others in between):

```
DEFOPT TK10P==0         ;NO TK10 TTY SCANNER

**Comment by larsbrinkhoff** [comment]
About DECtape drives, I see this in CONFIG 17, which is the earliest record of DM ITS configuration:

```
DEFOPT NUNITS==0        ;NUMBER UTAPE UNITS (USED TO BE 8, REMOVED 9/30/75)

**Comment by jh95468** [comment]
It sounds like the "TK10" was the TTY scanner we used before Steve Morton built the "Morton Box" which became the primary TTY interface.  I don't remember "TK10" specifically, but my memory associated "TKxx" as a DEC term for tape drives.  Maybe it wasn't a DEC device - perhaps TK10 meant Tom Knight's PDP-10 device.

I can believe that we removed the DECtape drives in 1975.  But I suspect that setting NUNITS==0 avoided using memory for tables and buffers, but the code was probably still there.  So it may have been sometime later that someone (Mike Brescia comes to mind) tried removing the code itself.

**Comment by aap** [comment]
TK10 is the so called Knight Kludge (obviously built by Tom Knight). I talked to Greenblatt a bit about it. Apparently this was built for the PDP-6 already, they did not use the TTY scanners from DEC. I don't know if it was only on AI at the time or also on DM, RG doesn't seem to know or remember that much about DM. The things they bought are the GE (as in general electric) thing, which even had video terminals and the datapoint kludge.

**Comment by larsbrinkhoff** [comment]
Ok, I call dibs on TK10!  Datapoint kludge and Morton box still up for grabs.

**Comment by larsbrinkhoff** [comment]
@jh95468, I found this about the alleged DM PDP-11 attached through TK10:

    SUBTTL  INTERFACE (?) TO DM PDP11 ON NTY (REALLY WANT A CAIOS)

So maybe some kind of networking processor?  Note: CAIOS = Chaosnet.

**Comment by jh95468** [comment]
This "DM PDP11"  code probably occurred after I left MIT in mid-1977.  At that time, the only PDP11 connected to the PDP10 was a small PDP11 in a lab on the 2nd floor used for the Understanding Morse Code project.  It was connected to the PDP10 by a TTY line, similar to the Imlacs on the 2nd floor.  

Chaosnet hadn't propagated to DM by then; I believe it was still mostly an AI project.  Networking was all accomplished by using the ARPANET IMP, e.g., the AI:, ML:, MC:, DM: devices.  ChaosNet and CAIOS were not in our vocabulary.

So I'm not sure if that PDP11-related code fragment refers to that same Morse PDP11, or some other PDP11 that was added after 1977 for a later project

**Comment by larsbrinkhoff** [comment]
The KS10 DZ11 device has speed settings.  I see they are set in DZINIT which is called when ITS starts.  Maybe they aren't set anywhere else, which would explain why TCTYP SPEED doesn't change the speed.

I don't see any speed setting in the TK10/Knight kludge.  I'm guessing ITS speed settings 25k, 40k, 50k, and 80k is for the Morton box, but I have yet to see how they enter the hardware.

This comment is interesting.  ITS updates its idea of a terminal port speed, but doesn't poke the hardware.  `;SET SPEED.  MAYBE THIS SHOULD CHANGE IT IN HARDWARE ALSO?`

The TTY output routine labelled `TYP` does seem to care about output speed:  
`LDB J,[220300,,TTYTYP(I)] ;GET TTY OUTPUT SPEED.`  
But I don't see how `J` is used later.  Also `220300` seems wrong, shouldn't it be `220400`?

**Comment by jh95468** [comment]
IIRC, those higher speeds (50K, 80K) were probably results of using the Morton box (on DM) to connect to the Imlacs on the 2nd floor.  IIRC, changing speeds on lines from the Morton box involved physically changing the hardware (jumpers or such) rather than by PDP10 I/O commands.  We didn't have dial-in modems so there was no need to change speeds after a particular terminal was connected.  I remember changing the settings on the Imlac lines for higher and higher speeds until I started seeing errors, then backing off a little bit.  80K sounds like the fastest it would go over the long runs from the 9th to 2nd floor.

**Comment by larsbrinkhoff** [comment]
I see the IMLAC terminal type has SPEED set to 50K.  Also, the Morton box on ML had 32 lines attached at one point, so maybe that was the maximum.  DM had 16 lines.

**Comment by larsbrinkhoff** [comment]
@rcornwell, TK10 is device 600 and DPK is 604.  Will they both dispatch to the same simulator device handler?

**Comment by larsbrinkhoff** [comment]
The Morton box is done.

I found a memo for the Datapoint kludge, aka Systems Concepts DK-10.  It's in progress.
