### ISSUE TITLE
ARCCPY - copies archives (maybe converts from old to new?)

### ISSUE THREAD

**Issue by eswenson1** [PDP-10/its#111]
SYS2; TS ARCCPY
SYSEN2; ARCCPY 13

**Comment by eswenson1** [comment]
Yes, ARCCPY takes an old-format archive and converts it to new format. This will allow us to access any old-format archives we find.

**Comment by eswenson1** [comment]
@larsbrinkhoff Do you have any old-format archives I can try this out on?

**Comment by larsbrinkhoff** [comment]
I think one in RMS' directory was of the old flavor.

**Comment by eswenson1** [comment]
Didn't find any in RMS's directories.    What would a filename be for an old-format archive?  Same pattern: AR? XXXXX?  Or are they recognizable by name?

**Comment by larsbrinkhoff** [comment]
No, I misremembered.  Maybe it was CSTACY.

It didn't have any special name.  If you remove your DEVICE; OARCDV BIN, you can be sure that the old archives won't open.  That's how I found out about them.

**Comment by eswenson1** [comment]
Just went through all of the archives in CSTACY; and didn't have any issues opening any of them (after first removing DEVICE; OARCDV BIN).  So that wan't it.  If you do come across an old-format archive, please let me know its location.

**Comment by larsbrinkhoff** [comment]
I wil.

All new archives should start with SIXBIT ARC1!!.  In our Unix files, that should translate to \370r\215\012A.  I tried to find AR?.* files without that, but didn't succeed.  So maybe what I saw wasn't an old-format archive after all.  I distinctly remember not being able to open an archive unti I added OARCDV.  But now I'm not so sure any more.

**Comment by eswenson1** [comment]
I just confirmed this too.  All the AR* files that I have access to appear to start with ARC1!!.

**Comment by larsbrinkhoff** [comment]
I'm writing a Unix tool to access ITS archives.  When running it, it seems to me these are old-format archives.  The first word is `ARC!!!`, not `ARC1!!`.  That's easy to overlook.

AI: BAWDEN; AR69 SPCWAR  
AI: KSC; AR1 TIMER  
AI: KSC; AR2 HAKPRG
