### ISSUE TITLE
BUILD failure - lisp.tcl typo

### ISSUE THREAD

**Issue by TheFausap** [PDP-10/its#1114]
Hello,

the latest lisp.tcl has a typo. I got a build failure (tested two times):

```
# ITSter

respond "*" "complr\r"

respond "_" "games;_hibou;itster\r"

respond "_" "\032"

type ":kill\r"
```

the call to complr should have a \013 not a \r, as in the previous pass (compiling chase game).

**Comment by larsbrinkhoff** [comment]
Just interesting observation.  Most early AI memos start programs with ^H.

**Comment by eswenson1** [comment]
I do that too. Makes sure that if you already have one running it resumes rather than replaces job. Lots of people used to set DDT clobber flag to not warn.
