### ISSUE TITLE
WEBSER not running ?

### ISSUE THREAD

**Issue by TheFausap** [PDP-10/its#1116]
Hello,

a simple question, is the WEBSER started at boot ? If no, how can I start it ?

thanks
Fausto

**Comment by TheFausap** [comment]
Sorry, WEBSER is ok, my firewall script was not updated.
Btw, is there a document describing how the network config is done (I mean the devices, the link to network servers binaries, etc).

Thanks,
Fausto

**Comment by larsbrinkhoff** [comment]
I don't think there is such a document.

Configuration is mostly done by adding or removing links in the DEVICE directory.  Chaosnet services use CHAOS <contact>, and TCP/IP uses TCP SYN<port>.  The programs usually sit in the SYSBIN directory.

**Comment by larsbrinkhoff** [comment]
Or if you want a program run from boot, link it from CHANNA; RAKASH \<name>.

**Comment by larsbrinkhoff** [comment]
Probably just an oversight.  I should have caught that when I reviewed the pull request.
