### ISSUE TITLE
master branch won't build for me

### ISSUE THREAD

**Issue by eswenson1** [PDP-10/its#1134]
I get the following when trying to build the master branch:

```*:cwd games
*:midas jotto
JOTTO HACK
JOTTO HACK
Constants area inclusive
From    To
54362   54633
Run time = 0.03
1621 Symbols including initial ones (59% used)

:KILL
*:job jotto
!
*:load jotto bin
*erase0$b   beg$g
$1B; ERASE0>>MOVE R,54456   utopen/   656470   $1'   dsk$
b/   0   $1'jotto$
c/   0   $1'dict$
beg7$g

6627.
IT IS NOW  5:53:18 PM EDT, THURSDAY, AUG 2,2018
words
$1B; ERASE0>>MOVE R,54456
The last command timed out.
Makefile:50: recipe for target 'out/klh10/rp0.dsk' failed
make: *** [out/klh10/rp0.dsk] Error 1
eswenson@eswenson-ThinkPad-W520:~/ITS/ws/its$```

It seems that darned "IT IS NOW..." message breaks the expect (ations).

**Comment by eswenson1** [comment]
This has happened three times in a row!  Not entirely sure why this is reproduceable for me.  In any case, I'm trying with the ". words" changed to "words" misc.tcl -- looking for that "6627. words".  Seems for me, the "6627." is always on a line by itself, followed by the "IT IS NOW..." message, followed by the "words" output.

This expect matching stuff is SO BRITTLE.  Can't think of how many times the build has failed for us all because of this.

**Comment by atsampson** [comment]
SYSJOB messages appearing in random places is kind of hard to work around. I guess we could add a flag to ITS to disable them, or we could do the build process against a TTY that isn't the console...
