### ISSUE TITLE
GMSGS - copy system messages into user's mail file

### ISSUE THREAD

**Issue by eswenson1** [PDP-10/its#114]
SYS2; TS GMSGS
SYSEN1; GMSGS 92
.INFO.; GMSGS ORDER
DEVICE; CHAOS GMSGS => SYS2; TS GMSGS
DRAGON; DAILY EXPIRE => SYS2; TS GMSGS
SYS2; TS EXPIRE => SYS2; TS GMSGS

Also of Chasnet server of some kind.

**Comment by eswenson1** [comment]
This errors out due to a missing SYS: :MSGS TIMES file.  I'm not sure, yet, how this file is created, but I'll dig in and try to figure it out. This file exists in my PI distribution as a binary file.  So some daemon must have created it.

**Comment by eswenson1** [comment]
Apparently, this file keeps track of the last message a user has viewed. It is managed by the MSGS library (syseng; msgs 47).  It is used by GMSGS and the :MSGS DDT command.

**Comment by eswenson1** [comment]
I have not yet figured out how to get the file SYS;:MSGS TIMES created.  The MSGS library just maps it in -- doesn't create it. I haven't found any source file yet that creates this file. Creating an empty file doesn't work (DDT reports a DDT bug if it encounters an empty file).  I may have to reverse engineer the format of this file in order to create a dummy one. Still digging.

**Comment by eswenson1** [comment]
I tried creating a file with a single byte in it, so that the page occupied one page.  This allows msgs"mapmsg to work.  The first time someone does a :msgs command, the file is rewritten to be correctly formatted.  So I'm going to include a dummy (1-byte long) SYS; :MSGS TIMES file so that DDT won't barf and :GMSGS will work.

**Comment by eswenson1** [comment]
The above turned out not to work. I had to write out a single page file (2000 words) with the first word being  a valid sixbit value. This seemed to work fine.

**Comment by eswenson1** [comment]
It looks like a file with a single page (2000 words) of 0 will work. It doesn't have to have a valid sixbit value in word 0.

**Comment by larsbrinkhoff** [comment]
Good detective work.

Aren't all words valid SIXBIT?

**Comment by eswenson1** [comment]
Right. But I thought the first word had to contain something (and what is placed there on successful :MSGS is the HSNAME of a user, followed by a word of date/time info. Turns out, though, that an empty page is sufficient. The file cannot be zero length.
