### ISSUE TITLE
MACSYMA - SHARE DESOLN not found

### ISSUE THREAD

**Issue by TheFausap** [PDP-10/its#1154]
Hello,

I'm trying to solve a differential equation (non partial), but MACSYMA cannot find the file to do that.
This is my session:

```
:login fausap 
To see system messages, do ":MSGS<CR>"
macsym↑K!

This is MACSYMA 1000

(C1) atvalue(diff(f(t),t),t=0,v);

AT FASL DSK MAXOUT being loaded 
Loading done
(D1)                                  V

(C2) atvalue(f(t),t=0,0);
(D2)                                  0

(C3) assume(k>0);
(D3)                               [K > 0]

(C4) ho:desolve([diff(f(t),t,2)+k*f(t)=0],[f(t)]);
Could not find file which matches "DSK:SHARE;DESOLN LISP"

(C5) 

```
Could be possible to add it ? 

thanks,
Fausto

**Comment by eswenson1** [comment]
I added share/desoln.lisp to the its-vault repo https://github.com/PDP-10/its-vault/blob/master/files/share/desoln.lisp, but I'm not sure this is what you need. Can you give it a try and report on what happens when this file is in place?

**Comment by TheFausap** [comment]
It works :)
