### ISSUE TITLE
Old version of Maclisp

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#1157]
For hysterical raisins and general lunacity, we may want to have an old version of Maclisp.

**Comment by larsbrinkhoff** [comment]
The oldest interpreter file I see is L; *LISP 536 from 1987-04-15.

**Comment by eswenson1** [comment]
@larsbrinkhoff I think L;*LISP 536 is dated 1978 not 1987.

**Comment by eswenson1** [comment]
Oh, I see you've edited your post. Never mind -- was looking at the email I got with your post.

**Comment by larsbrinkhoff** [comment]
I also see some interesting files in the LISP directory.  I'm not sure if they are binary or source, though.

- LISP; LISP 229DC - 1972
- LISP; LISP 262 - 1973
- LISP; LISP 386 - 1973
- LISP; *LISP 106 - 1975
- LISP; LISP 117 - 1976

I wonder if the LISP version number wrapped around?  Or if the LISP and *LISP files used different version series.

**Comment by larsbrinkhoff** [comment]
Having an early Maclisp would probably make running SHRDLU (#147) a lot easier.

CC @lbickley

**Comment by eswenson1** [comment]
I did notice a version number shift between lisp and *lisp. Might have been a wrap.

**Comment by lbickley** [comment]
On Tue, 23 Apr 2019 05:36:09 +0000 (UTC)
Lars Brinkhoff <notifications@github.com> wrote:

> Having an early Maclisp would probably make running SHRDLU (#147) a
> lot easier.

I've got a LOT on my plate right now - and haven't been able to devote
any time to the SHRDLU project. I'll be very glad when I'm free to be
able to have fun with ITS and SHRDLU :)

Cheers,
Lyle

-- 
73   NM6Y
Bickley Consulting West Inc.
https://bickleywest.com

"Black holes are where God is dividing by zero"

**Comment by larsbrinkhoff** [comment]
Old compiler versions to go along with the old interpreter:

- JONL; TS COMPLR, 1973-02-09
- JONL; TS OCOMPL, 1973-01-15
- JONL; TSCOMP 226, 1972-03-19
- JONL; TSCOMP 275, 1972-10-6
- SYS; TS NCOMPL, 1976-11-3
- SYS; TS ONCOMP, 1976-06-21
- JONL; TS COMPLR, 1973-05-06
- JONL; TS OCOMPL, 1973-05-06
- JONL; TS OOCOMP, 1973-04-17

**Comment by larsbrinkhoff** [comment]
Old compiler versions to go along with the old interpreter:

- JONL; TS COMPLR, 1973-02-09
- JONL; TS OCOMPL, 1973-01-15
- JONL; TSCOMP 226, 1972-03-19
- JONL; TSCOMP 275, 1972-10-6
- SYS; TS NCOMPL, 1976-11-3
- SYS; TS ONCOMP, 1976-06-21
- JONL; TS COMPLR, 1973-05-06
- JONL; TS OCOMPL, 1973-05-06
- JONL; TS OOCOMP, 1973-04-17

**Comment by larsbrinkhoff** [comment]
See #1679 for more detailed information.
