### ISSUE TITLE
SYSTEM; CONFIG changes.

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#1168]
Go through all SYSTEM; CONFIG * files and note what has changed.

**Comment by larsbrinkhoff** [comment]
| Version | Change
| --- | ---
| 17 | (from ITS 785) ...
| 27 |
| 39 |
| 40 |
| 52 |
| 53 |
| 54 |
| 55 |
| 56 |
| 57 |
| 59 |
| 60 |
| 61 |
| 62 |
| 63 |
| 64 |
| 71 |
| 75 |
| 76 |
| 77 |
| 78 |
| 79 |
| 81 |
| 89 |
| 92 |
| 93 |
| 94 |
| 96 |
| 97 |
| 114 |
| 115 |
| 116 |
| 122 |
| 123 |
| 131 |
| 133 |
| 135 |
| 136 |
| 138 |
| 140 |
| 147 |
| 148 |
| 153 |
| 154 |
| 155 |
| 167 |
| 168 |
| 169 |
| 171 |
| 172 |
| 173 |
| 174 |
| 175 |
| 186 |
| 188 |
| 191 |
| 192 |
| 193 |
| 195 |
| 196 |
| 202 |

**Comment by larsbrinkhoff** [comment]
@philbudne, I believe you like these things.

**Comment by philbudne** [comment]
@larsbrinkhoff thanks!!!
