### ISSUE TITLE
Years from now - complete repository history rewrite?

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#1173]
Fair warning in advance.

If at some point in the future we consider having a rather complete set of ITS backup files, I would seriously consider working them into the git repository.  The individual file versions would probably each be a single commit, replaced by subsequent versions.  The commit date could match the file timestamp.

To make this work with the current repository history, we would have to rebase it on top of the historical file set.  After having done this, everyone would have to forcibly update their clones.

**Comment by atsampson** [comment]
I've thought about doing this as well - I've previously done a reverse-engineered [history repository](https://gitlab.com/atsampson/multics-history-repo) for Multics, inspired by DDS's [Unix history repository](https://github.com/dspinellis/unix-history-repo).

With ITS, we have lots of historical versions of files - from a wide variety of sources - but very little "commit history". So we'd need a tool that generated the history from the ITS files plus whatever extra information we can give it - as an example, we can specify dates and authors for many of the MIDAS versions based on the changelog file and SAILDART info, and based on that it could estimate dates within a range for others.

Rebasing isn't the only way to make this available as part of the main repo's browsable history; we could also use [git replace](https://mirrors.edge.kernel.org/pub/software/scm/git/docs/git-replace.html) or the older Git graft mechanism. As the history repo is likely to be rewritten quite often this may well be preferable.

We could also generate a parallel repository in which binaries were disassembled (in some kind of diff-able way, e.g. with relative addresses everywhere).

**Comment by larsbrinkhoff** [comment]
Good points.  On second thought, maybe it's better to have a separate repository for this.

**Comment by ams** [comment]
Please keep dates.
Please keep dates.
Please keep dates.


I forgot what I wanted to say...
