### ISSUE TITLE
Com links HOWTO

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#1180]
Make simple "howto" document about how to use com links.

**Comment by larsbrinkhoff** [comment]
<code><kbd>^_</kbd><kbd>C</kbd></code>foo<code><kbd>CR</kbd></code> enters a com link with user *foo* or terminal *foo*.  An octal number specifies a terminal number.  Multiple users can enter the same com link.

In com link mode, user can see what the other users type.  And normally programs can't do terminal /O.

<code><kbd>^_</kbd><kbd>N</kbd></code> terminates the com link.

**Comment by eswenson1** [comment]
You said that "normally programs can't do terminal i/o".  Is there a way of letting them?  Are there other commands?  Can you use this mechanism to take over a user's terminal so that you can assist the user?  If so, can both users control the session?

**Comment by eswenson1** [comment]
Looks like all of this is documented in the ITSTTY INFO documentation.  For example, slaving a terminal is done with ^_S.

**Comment by larsbrinkhoff** [comment]
Right, I was going to add that.  I'm not sure how it works yet.

I think ^_I and ^_O will let your own programs do terminal I/O in com link mode.  So you can demo things.

^_S slaves a terminal, but that in itself doesn't do much.  You must also ^_E do send it input.

**Comment by eswenson1** [comment]
I just tried it out and it does appear to work. I was able to enter a com link, slave the other terminal, send it input, and see its output.  However, while the display seemed perfectly fine on the "other" terminal, the output from the other terminal on my terminal was a bit strange.  For example, I issued the "who^K" command and on the slaved terminal the output looked like this:

**Comment by larsbrinkhoff** [comment]
Duplicates #1207.
