### ISSUE TITLE
UUCP

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#1196]
Add UUCP to ITS.  So minicomputer people can access the ARPANET mailing lists.

**Comment by larsbrinkhoff** [comment]
@lisper's [copy of Chaosnet for 4.1BSD](https://github.com/LM-3/chaos/releases/tag/chaos-1982-08-12) includes UU for uucp.

**Comment by ams** [comment]
https://github.com/LM-3/chaos/issues/21
