### ISSUE TITLE
NICNAM - lookup up someone in ARPAnet directory (!)

### ISSUE THREAD

**Issue by eswenson1** [PDP-10/its#121]
I wonder what this would do if we tried it?  :-)

SYS2;TS NICNAM
AR2:CSTACY; NICNAM 31

**Comment by eswenson1** [comment]
Also: NICWHO, which appears related

SYS2; TS NICWHO
AR2: CSTACY; NICWHO 30

**Comment by eswenson1** [comment]
This requires KSC; MACROS >, KSC; IVORY >, KSC; OUT >, and SYSENG; NETWRK > to assemble. All of these files are available in DB file system (as files or links).

**Comment by larsbrinkhoff** [comment]
According to http://textfiles.com/hacking/INTERNET/arpanet2.txt, SRI-NIC used to operate a "NICNAME" server which could be queried for information about Arpanet users.

I'm guessing this service doesn't exist any more!

**Comment by atsampson** [comment]
WHOIS is alive and well, and the protocol is still the same (send a query line terminated by a CRLF, read text response until the connection is closed). So it'd probably work fine if you pointed it at whois.arin.net and queried for an IP address, for example.
