### ISSUE TITLE
The Magic Switch

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#1232]
I grabbed this from http://www.catb.org/jargon/html/magic-story.html.  I was thinking it should be in some ITS backup file, but I couldn't find it.

> Some years ago, I (GLS) was snooping around in the cabinets that housed the MIT AI Lab's PDP-10, and noticed a little switch glued to the frame of one cabinet. It was obviously a homebrew job, added by one of the lab's hardware hackers (no one knows who).
> 
> You don't touch an unknown switch on a computer without knowing what it does, because you might crash the computer. The switch was labeled in a most unhelpful way. It had two positions, and scrawled in pencil on the metal switch body were the words ‘magic' and ‘more magic'. The switch was in the ‘more magic' position.
> 
> I called another hacker over to look at it. He had never seen the switch before either. Closer examination revealed that the switch had only one wire running to it! The other end of the wire did disappear into the maze of wires inside the computer, but it's a basic fact of electricity that a switch can't do anything unless there are two wires connected to it. This switch had a wire connected on one side and no wire on its other side.
> 
> It was clear that this switch was someone's idea of a silly joke. Convinced by our reasoning that the switch was inoperative, we flipped it. The computer instantly crashed.
> 
> Imagine our utter astonishment. We wrote it off as coincidence, but nevertheless restored the switch to the ‘more magic’ position before reviving the computer.
> 
> A year later, I told this story to yet another hacker, David Moon as I recall. He clearly doubted my sanity, or suspected me of a supernatural belief in the power of this switch, or perhaps thought I was fooling him with a bogus saga. To prove it to him, I showed him the very switch, still glued to the cabinet frame with only one wire connected to it, still in the ‘more magic’ position. We scrutinized the switch and its lone connection, and found that the other end of the wire, though connected to the computer wiring, was connected to a ground pin. That clearly made the switch doubly useless: not only was it electrically nonoperative, but it was connected to a place that couldn't affect anything anyway. So we flipped the switch.
> 
> The computer promptly crashed.
> 
> This time we ran for Richard Greenblatt, a long-time MIT hacker, who was close at hand. He had never noticed the switch before, either. He inspected it, concluded it was useless, got some diagonal cutters and diked it out. We then revived the computer and it has run fine ever since.
> 
> We still don't know how the switch crashed the machine. There is a theory that some circuit near the ground pin was marginal, and flipping the switch changed the electrical capacitance enough to upset the circuit as millionth-of-a-second pulses went through it. But we'll never know for sure; all we can really say is that the switch was magic.
> 
> I still have that switch in my basement. Maybe I'm silly, but I usually keep it set on ‘more magic’.

**Comment by larsbrinkhoff** [comment]
Here's the switch, caught on camera!
![magicswitch1](https://user-images.githubusercontent.com/775050/45706381-6df65880-bb7c-11e8-821e-ccb73baaa901.jpg)
![magicswitch2](https://user-images.githubusercontent.com/775050/45706400-764e9380-bb7c-11e8-962f-b3067c9d5323.jpg)

**Comment by larsbrinkhoff** [comment]
GLS: 
> Tom Knight has affirmed to me that he is the one who originally installed the switch.

**Comment by larsbrinkhoff** [comment]
MOON:
> The story is true.
> 
> It would be nice if Tom Knight would append his position on the purpose of the switch to the end of the story.  I assume that the other side of the switch used to be connected, and it used to do something useful, and I further assume that the need for it went away when the paging box was added. But I don't know.

**Comment by larsbrinkhoff** [comment]
> Daniel Weinreb wrote:
> > Tom,
> > Do you know, or know anyone who might know, who installed the More Magic switch on the AI KA-10?
> 
> That would be me.

MOON:
> Daniel Weinreb wrote:
> > Tom Knight wrote:
> > > And it was on the PDP-6, not the KA-10.
> > 
> > Actually, I very distinctly remember it being in the leftmost bay of the KA-10, over by the Knight TV's. But it's been a very long time.
> 
> The one I know about was on the KA-10. Maybe the pdp-6 had one too.
> 
> Notice Tom didn't say what it did, back when it was still connected.

Tom Knight wrote:
> I think the "magic"is, but the "more magic" is not. My recollection is that this switch was installed for a mod which I put into the PDP-6 which took accumulator 17 and, when it was in index register position, replaced the contents by the PC, so that you could do PC relative addressing. It was disabled later, and the switch was left installed (with only the ground wire connected).

**Comment by larsbrinkhoff** [comment]
Post to alt.sys.pdp10, from http://www.inwap.com/pdp10/usenet/history.9603

> On another topic, I installed the "magic/more magic" switch on the MIT-AI PDP-6 which was mentioned here recently.  Originally, the switch was labelled "magic" and implemented a now-forgotten special mode in the machine (I think it had to do with allowing user mode I/O instructions for device codes > 700, if I recall).  The feature was permanently removed, the switch stayed, and someone later labelled the other position "more magic."  At this point, it was disconnected, except for a wire to ground.  I think the story from there is apocryphal.

**Comment by larsbrinkhoff** [comment]
```
Date: 02/20/79 09:45:42
From: BIM at MIT-AI
Re:   Heisenberg and the AI machine

It is my unfortunate duty to report that on Monday, February the 19, 1979,
The Magic Switch was removed from the AI KA-10 CPU by GJS and HIC, with
myself, RG and others in attendance.
For those of you who are unaware, the magic switch connected a ground pin
in the CPU address calculation logic to a piece of unterminated wire.
When the switch was in the "Magic" position, the wire connected was about
4 inches long. In the "More Magic" position, the length grew to 6 inches.
On Monday afternoon the machine crashed and GLS determined that it had been
swapping itself out. After the appropriate dumping &cetra, the machine was
restarted. GLS then went to flip the Magic Switch. As he touched the plate
on which it was mounted, the machine stopped in a wedged state in which
neither RUN nor Program Stop were lit. Further experimentation revealed that
anyone, not just GLS, could have the same effect by touching the switch.
HIC arrived and attempted to investigate the situation with a scope.
Needless to say, the presence of the scope probe cured the problem. (some of
the time) In spite of GJS's strong belief that the ground connection to the switch
should simply be improved, HIC and RG decided that the switch was to be
disconnected. Thus after many years of faithful service the magic switch
now sits in disgrace on a counter somewhere on the 9th floor.
It was a good switch, and it deserves a moment of contemplation from all
of us.

**Comment by larsbrinkhoff** [comment]
@atsampson spotted that the switch is a Honeywell 1TW3-1 MS27716-23.  They are still made.

**Comment by DavidGriffith** [comment]
Expensive little thing.  Mouser has it for $58.60.  Onlinecomponents for $45.87.

**Comment by larsbrinkhoff** [comment]
I ordered one for $31 from eBay.  What a bargain!

**Comment by DavidGriffith** [comment]
What did it look like on a terminal and front panel when the Magic Switch flip caused a crash?

**Comment by larsbrinkhoff** [comment]
I believe all terminals would have just froze.

As for front panel, I don't know except the text says "the machine stopped in a wedged state in which
neither RUN nor Program Stop were lit".

**Comment by larsbrinkhoff** [comment]
Brand new in bag.
![20200224_180454](https://user-images.githubusercontent.com/775050/75177143-df551600-5735-11ea-8371-e6eb2a4b0ba3.jpg)

**Comment by mseddon** [comment]
Oh my... I never thought I would see the Magic Switch with my own eyes!

Thanks! :D

**Comment by brouhaha** [comment]
Although the body and contacts dimensions of the C&K 7101SDCGE toggle are different, I think the front-of-panel dimensions and appearance will be close enough, and it costs under $10 from Digi-Key or Mouser.

Since the original Honeywell/Microswitch 1TW1-3 toggle is ON-NONE-ON, apparently there was not a "NO MAGIC" setting in the middle. I might use a C&K 7103 ON-OFF-ON instead, functionally equivalent to Honeywell/Microswitch 1TW1-1.

**Comment by lproven** [comment]
> Oh my... I never thought I would see the Magic Switch with my own eyes!

Same. o_O
