### ISSUE TITLE
WEBSTER

### ISSUE THREAD

**Issue by eswenson1** [PDP-10/its#1259]
EMACS;WEBSTE :EJ
EMACS1;WEBSTE 46
EMACS1;WEBSTE COMPRS
SYSENG;WEBSTE 63
.INFO.;WEBSTE INFO

Used to look up words in dictionary. Present in ES/PI. Probably uses a web service (that probably doesn't exist any more).  ITS version uses chaosnet.

I think SYSENG; WEBSTE > is the chaosnet client that supports webster queries. EMACS1;WEBSTE > is the emacs interface to this service. Not sure where the service is.

**Comment by larsbrinkhoff** [comment]
Duplicates #522.  See also #525.
