### ISSUE TITLE
TCTYP location

### ISSUE THREAD

**Issue by eswenson1** [PDP-10/its#1261]
I noticed that on DB, we have SYS; TS TCTYP as a link to SYSBIN; TCTYP BIN.  However, on ES/PI, we have SYS1;TS TCTYP as the binary file.  May way to see which was more historically correct.  I don't think TCTYP is PDUMP'ed, is it?  If not, then we don't really need the SYSBIN; TCTYP BIN.

**Comment by larsbrinkhoff** [comment]
Yes, we can write to SYS1 directly.
