### ISSUE TITLE
TS TECO location

### ISSUE THREAD

**Issue by eswenson1** [PDP-10/its#1262]
On DB, we have SYS3; TS TECO as a link to .TECO.;TECPUR >.  On ES/PI, we have SYS; TS TECO as a link to .TECO.;TECPUR 928.  I have a hard time believing that TECO, as critical as it was, was in SYS3; on MC/AI/etc.

**Comment by larsbrinkhoff** [comment]
Maybe a typo?

**Comment by larsbrinkhoff** [comment]
I see back in the olden days, SYS; TS T was a link to TECO.  But since 1) that practice ended in 1976, and 2) TECO is no longer as important, I don't think there's a great need to add this link to DB.
