### ISSUE TITLE
Split macsyma build out from lisp build

### ISSUE THREAD

**Issue by eswenson1** [PDP-10/its#1283]
Lisp is pretty fundamental and lots of things depend on lisp.  Macysma is a very big app that takes a long time to build and has a limited audience. We shouldn't combine the lisp and macsyma builds and should make it possible to build ITS without macsyma (but with LISP).  

This ticket is to create a task of moving the macsyma-specific build steps out of lisp.tcl and into its own macsyma.tcl.

**Comment by larsbrinkhoff** [comment]
Good point.

Maybe I can piggy-back onto this.  misc.tcl is getting big.  Is there some chunk that can be split off?

**Comment by eswenson1** [comment]
On the branch where I've done this, I added a new environment variable (MACSYMA).  If NOT set, it is defaulted to "yes".  If set, we don't change it.  Then, we only build macsyma if the value is yes.  So the behavior is as it is now -- we get a Macsyma out of the build, unless MACSYMA=no (or non-yes) is provided.  Ok?

**Comment by atsampson** [comment]
Sounds like a good idea!
