### ISSUE TITLE
Cleanup UNFASL files in LISP; and LIBLSP; directories

### ISSUE THREAD

**Issue by eswenson1** [PDP-10/its#1289]
In my latest commits to build all LISP; fasl files from source, I didn't clean up all the UNFASL files created by the build. There is some value to UNFASL files (for debugging and investigatory purposes) but in some case, they cause too many entries in a directory and therefore have to get pruned. I have a bunch of DELETE commands in lisp.tcl to clean up UNFASL files that prevented the build from succeeding (due to directory full conditions) and may wish to clean these up so that they don't accumulate and prevent future futures builds.  But I consider this a lower priority than actually getting things to work so am not updating my previous commit, but rather entering another ticket.

**Comment by atsampson** [comment]
For the FASL-deleting step, would it be easier to do this with DIRED? (That is, is it just deleting all the FASL files, or are there some that it keeps?)

**Comment by larsbrinkhoff** [comment]
I have suggested maybe the DIR device could be of help.  Something like `:delete DIR: LIBLSP; SECOND FASL`

**Comment by larsbrinkhoff** [comment]
Oops, deleting the FASL files wouldn't be helpful.  But you know what I mean.

**Comment by eswenson1** [comment]
```
*:delete dir:liblsp;second fasl
DIR: LIBLSP; SECOND FASL - WRONG TYPE DEVICE
```

**Comment by larsbrinkhoff** [comment]
That's right.  I was thinking maybe DIR: could be updated to handle deletions.  Previously discussed in #745.

**Comment by eswenson1** [comment]
@atsampson You mentioned using DIRED for deleting the * UNFASL directories. Two questions: 1) do you know if you can actually do wildcard deletes with it?  2) Can it be invoked to do a wildcard delete from the command line?  I ask because we need this scripted -- lisp.tcl currently has a bunch of :DELETE commands with each filename explicitly mentioned. What we'd really like is the equivalent of "rm *.unfasl".  I didn't think this could be done with DIRED (from the command line).  @larsbrinkhoff's suggestion of updating the DIR device to support deleting is a good one -- however a dangerous one.  At least with DIRED (standalone and emacs), you have to explictly say "YES" to delete the files you've marked for deletion upon performing the delete command.

**Comment by larsbrinkhoff** [comment]
When I examined the DIR device, I saw that it should be possible to invoke DIRED using the DIR device so that DIRED only acts on a subset of files provided by DIR:.  I think this is PDL's standalone DIRED, not the EMACS version.  Or maybe they both have the same capability.

**Comment by eswenson1** [comment]
Yes, but at issue here is the ability to script this in lisp.tcl.   How can we use DIRED (a GUI program) to do this?

**Comment by larsbrinkhoff** [comment]
I think we can script DIRED by sending it text and examining the output.

I got this to work:

```
*:dired
@act llogo;
@delete * unfasl
Delete? (Y or N): yes

**Comment by eswenson1** [comment]
Oh! Sorry.  I thought DIRED (standalone) used the UI from emacs.  I didn't realize it was a text program that could be scripted. Thanks.

**Comment by atsampson** [comment]
Yes, I use TS DIRED to do wildcard deletion - I learned about this because [WHAT pretends to do it](https://github.com/PDP-10/its/blob/4e2ea8e4d851a0ea1f910c3001e5c2ddb9ff528c/src/syseng/what.204#L977)!

```
*^F
DB   TEST  
FREE BLOCKS #0=5403 
  0   FOO    1      1 ! 10/3/2018 12:44:29
  0   FOO    2      1 ! 10/3/2018 12:44:29
  0   THING  1      1 ! 10/3/2018 12:44:29
  0   THING  2      1 ! 10/3/2018 12:44:29
  0   THING  3      1 ! 10/3/2018 12:44:29
  0   THING  X      1 ! 10/3/2018 12:44:29
  0   THING  Y      1 ! 10/3/2018 12:44:29
*:dired
This is new dired. [...]
@sorry
@d foo *
@d * y
@q

:KILL
*^F
DB   TEST  
FREE BLOCKS #0=5406 
  0   THING  1      1 ! 10/3/2018 12:44:29
  0   THING  2      1 ! 10/3/2018 12:44:29
  0   THING  3      1 ! 10/3/2018 12:44:29
  0   THING  X      1 ! 10/3/2018 12:44:29
*
```

`sorry` stops it prompting for confirmation.

**Comment by larsbrinkhoff** [comment]
If DIRED takes a JCL like WHAT says, it's even more scriptable.

... why don't I just test this now ...

It doesn't.

**Comment by eswenson1** [comment]
Well, it does take JCL but I haven't figured out (yet) how to give it more than one command.  

With my current HSNAME/MSNAME set to EJS; I can do:

 :DIRED A .temp.; d BAZ 2

And I get this:

```
*:dired a .temp.;, d baz

This is new dired.  No warranty is expressed or implied.
Type ? for command list, ? <cmd> for each command.

   01  BAZ    2      1 (4) !10/3/118 08:45:17 (10/3/118) EJS
@
```

That file (BAZ 2) is in .TEMP. not EJS.  So the "A .temp.;" command "took".  But the "d baz" command didn't -- I tried comma and space as delimiters.  Haven't tried anything else yet.

**Comment by eswenson1** [comment]
Well, looking at the source, it appears to only process one command and it defaults to the ACT command.  So doing :DIRED .temp.; reads in .temp.; and awaits an interactive command.  This matches what is written in the first entry of .INFO.; DIRED RECENT.  It doesn't look like you can delete from the command line (as @larsbrinkhoff confirmed).
