### ISSUE TITLE
EINE - EINE is not Emacs

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#1293]
Some traces:

EINE; BASIC EINE  
EINE; CATALOG TAGS  
EINE; ECMD QFASL  
EINE; EDIS QFASL  
EINE; EINSER QFASL  
EINE; EPL1 QFAL  
EINE; ESCREE QFASL  
EINE; EUTIL QFASL  
EINE; EVIEW QFASL  
EINE; EWRLDS QFASL  
EINE; MACRO QFASL  
EINE; .SAVE. 1  
EINE; .SAVE. 2  

LISPM1; EINE 8  

LMDOC; BUG EINE  
LMDOC; EINED 5  
LMDOC; EINEID 13  
LMDOC; EINEID 14  

LMMAN; EINE 7  
LMMAN; EINE 8  

MINSKY; EINE DEMO  

PLASMA; EINE 1

**Comment by larsbrinkhoff** [comment]
@ams, any comments?

**Comment by larsbrinkhoff** [comment]
I suppose we should try to have a look at some of those files.  I'll be back...

**Comment by larsbrinkhoff** [comment]
I think I have exhausted all venues to find EINE code.  I only found this documentation:

LISPM1; EINE 8  
LMDOC; BUG EINE  
LMDOC; EINED 5  
LMDOC; EINEID 14  
LMMAN; EINE 8

**Comment by larsbrinkhoff** [comment]
I found EINE sources on ToTS tape 9004365.

DLW; EINE 7 and 8  
DLW2; E.... files.

Timestamps from 1977.

**Comment by larsbrinkhoff** [comment]
One more copy on tape 3100052, in directory LISPM2.

**Comment by larsbrinkhoff** [comment]
LMDOC; LISMP BUGS, ToTS 3100052, timestamp 1977-12-20:
```
DLW@MIT-AI 08/08/77 04:26:09
To: (BUG LISPM) at MIT-AI
        The Lisp machine editor has now officially been named "EINE",
which stands for EINE Is Not Emacs.  (Apologies to Ted Anderson,
the creator of "TINT").

**Comment by eswenson1** [comment]
These files:
```
EINE; .SAVE. 1
EINE; .SAVE. 2
```
are 0-length in ToTS, so I won't ask for these to be extracted.

**Comment by eswenson1** [comment]
@larsbrinkhoff Don't you also want the sources for EINE?  There can be found in the DLW2 directory on ToTS tape 9004365.

**Comment by larsbrinkhoff** [comment]
@eswenson1, yes of course.  Everything.  Note that many early files are not called EINE, and are not in the EINE directory.
