### ISSUE TITLE
start GT40 fail

### ISSUE THREAD

**Issue by TheFausap** [PDP-10/its#1294]
Hello,

I tried to start sims emulator with GT40 option, but it seems pdp11 executable doesn't recognize the devices. This is the gt40.log

```
PDP-11 simulator V4.0-0 Current        git commit id: e1db7dec
Disabling XQ
build/sims/gt40-9> at dli 10005,connect=localhost:10000
Listening on port 10005
build/sims/gt40-10> set vt enable
Non-existent device
build/sims/gt40-11> set vt crt=vr14
Non-existent device
build/sims/gt40-12> set vt scale=1
Non-existent device
build/sims/gt40-13> set vt address=17772000
Non-existent device

HALT instruction, PC: 000010 (HALT)
sim> 
```

regards,
Fausto

**Comment by larsbrinkhoff** [comment]
I think the SIMH makefile auto detects the presence or absence of libraries and builds a PDP11 simulator accordingly.  So you need to install libsdl2-dev or similar as appropriate for your operating system.  After that, you can cd to tools/simh and `make clean pdp11`.

I hope this fixes the problem!

**Comment by larsbrinkhoff** [comment]
I'm glad someone other than me is testing the GT40.

It will probably have some other problems.  When the "Console Free" message comes up, you can type ^Z and log in.  However, the VT11 ROM has very minimal terminal capabilities.  When the text reaches the bottom of the screen, it will overflow.  There is no scrolling or wrap around.

So the best bet is to first run another program to load more capable code into the GT40.  The GTLOAD program can be used for this.  However, I haven't tested it yet.  And then there's the matter of what to load.  There are some options:

- Lunar Lander, GT40; GTLEM 91.
- VT07, see #942.
- CCONS, see #1076.

**Comment by larsbrinkhoff** [comment]
See #652 for some information on how to use GTLOAD.  It seems to accept CCONS BIN and feed it using the GT40 loader format.

**Comment by TheFausap** [comment]
rebuilding PDP11 and now it's working:

![image](https://user-images.githubusercontent.com/1846443/46404232-dd378500-c704-11e8-9ab8-0ab65df894ea.png)

Are all those spurious chars expected ?

**Comment by larsbrinkhoff** [comment]
Maybe you can type ^H.  In that case, you could try Lunar Lander.

1. From HACTRN, start <code>gtload<kbd>^H</kbd></code>.
2. At the `*` prompt, type <code>gt40; gtlem bin<kbd>CR</kbd></code>.
3. Hopefully, now Lunar Lander should load and run!

**Comment by larsbrinkhoff** [comment]
I'm adding the VT07 Datapoint emulator in #942.

It should load with GTLOAD and provide a better terminal experience.  You should try to run `:TCTYP GT40` but of course that's hard without a working `:` key.

**Comment by TheFausap** [comment]
Ok... it seems if I start GT40 terminal with italian keyboard, it takes that keyboard layout, and you cannot change after, but if I start GT40 with english keyboard, all is fine.

**Comment by TheFausap** [comment]
> Maybe you can type ^H. In that case, you could try Lunar Lander.
> 
> 1. From HACTRN, start `gtload^H`.
> 2. At the `*` prompt, type `gt40; gtlem binCR`.
> 3. Hopefully, now Lunar Lander should load and run!

it says NON-EXISTENT DIRECTORY, but if I do a gt40^F I can see the files!

**Comment by larsbrinkhoff** [comment]
My mistake.  You must type the file name in all upper case.

**Comment by larsbrinkhoff** [comment]
I tried GTLOAD with VT07, GTLEM, and CCONS now.  They all seem to enter the loader mode, but the GT40 display just freezes and becomes unresponsive.

**Comment by larsbrinkhoff** [comment]
I believe the original problem was fixed.

**Comment by larsbrinkhoff** [comment]
There has been an update.  Now you can type:

```
*:GTLOAD
*GT40;VT07 BIN29
```

And wait a few minutes.  Yes, minute*s*!  After a long while the Datapoint emulator will be running, and you can log in and run EMACS etc.
