### ISSUE TITLE
Zelazny books

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#1295]
"Lord of Light" - source of Taraka, Channa, Rakash, Sam/Mahasamatman.

"The Chronicles of Amber" - source of Chaos and Amber.

**Comment by larsbrinkhoff** [comment]
Hello @cbf9427 and @taa01776,

There's a well known link between Chaosnet and Amber: https://lm-3.github.io/amber.html.  Is there a connection to your Amber operating system?

**Comment by cbfc** [comment]
Well, some of the same people were involved in naming both. And yes, Amber was named based on the Zelazny novel.

**Comment by cbf9427** [comment]
Well, some of the same people were involved in naming both. And yes, Amber was named based on the Zelazny novel.

**Comment by larsbrinkhoff** [comment]
Thank you.  The book must have made quite an impression.  I will have to read it.

**Comment by larsbrinkhoff** [comment]
@eswenson1 found this for $1 in Tallinn.
![9princes](https://user-images.githubusercontent.com/775050/47155039-3813d380-d2e4-11e8-91bb-b80183ef1bbe.jpg)

**Comment by cbfc** [comment]
Yup. Bear in mind that this is closer to Fantasy than Sci Fi, and I don't generally read fantasy anymore. But Zelazny's writing style is engaging. Just beware of what happens to the Shan.

**Comment by eswenson1** [comment]
Actually, it cost €1, not $1, but close! I didn’t buy it, but considered doing so as i’ve never read any of his work.

**Comment by cbf9427** [comment]
Yup. But in mind it's more fantasy than SF. But Zelazny has some engaging writing style.

Watch out for what happens to the Shan.

**Comment by eswenson1** [comment]
Actually, i decided to run back to the store (while waiting for hors d’oeuvres at dinner) and pick up the book after all. If someone wants it after I finish reading it and can’t find it, i’ll send it along!
