### ISSUE TITLE
KA10 ITS time

### ISSUE THREAD

**Issue by eswenson1** [PDP-10/its#1298]
Forgive me if this has been discussed before (or if I just don't know what I'm doing).  I booted ITS under the ka10 emulator for the first time today.  Each time I do, I have to set the time.  I realize that ka10 doesn't have networking support, but is it really the case that the KA10 hardware didn't have a clock that kept track of the time even when the system was not running ITS?  Or is ITS not capable of asking the hardware what the time was on startup?  Does ITS *only* set the time from the network?

I would think we could have KA10 ask the host what the time is and then return it to ITS when ITS asks the time.

**Comment by larsbrinkhoff** [comment]
There is the PD clock device.  But at one point ITS wouldn't run stably, so I disabled it.

There is #702 for looking into this.

**Comment by larsbrinkhoff** [comment]
- About src/system/config.\*, it's no longer kept there.  It's fine to delete it and rebuild.  It's now in out/\*/system/config.*.

- We do have some software for the GT40.

   - Lunar Lander: GTLEM
   - Debugger: URUG
   - Datapoint emulator and Lisp display slave: VT07
   - CONS console: CCONS

   See #1294 for some recent exploration.

**Comment by larsbrinkhoff** [comment]
I should look into this soon.   Some programs crash if the time isn't set.

**Comment by larsbrinkhoff** [comment]
> I booted ITS under the ka10 emulator for the first time today. Each time I do, I have to set the time. 

@eswenson1, #702 now has a fix for this.  Can you please test that it works for you?
