### ISSUE TITLE
Support for time zones and non-US DST

### ISSUE THREAD

**Issue by bictorv** [PDP-10/its#1309]
I propose incorporating the patches in http://up.update.uu.se/PATCH%3bTIME%20COMPAR (and related patches for SYSENG;CTIMSR, SYSENG;DATIME, KLH;OUT, SYSEN2;TIME and SYSENG;TIMOON) to support time zones other than 5 and DST calculations other than US (in particular, EU).

The description (from http://up.update.uu.se/patch;):

 TIME   COMPAR

    This patches SYSTEM;TIME - time code in ITS.

    Y2K patch: use realyear-1900 instead of realyear mod 100
    in MFD date.

    Use bits in .RYEAR/.RLPDTM result to return a local time zone,
    TZONE (definable in SYSTEM;CONFIG).
    TZONE should be the integer timezone offset (hours West of UTC)
    	Bit 4.4      => timezone known (otherwise, assume EST/EDT = 5)
    	Bit 4.3      => sign bit of timezone offset
    	Bits 3.5-3.1 => absolute value of timezone offset
    See e.g. TIME2 COMPAR for how to use it.

    If DSTEU is defined and != 0, calculate daylight savings time
    according to European Union rules: 
    - starts at 2:00 (standard time) on the last Sunday in March,
    - ends at 2:00 (standard time) on the last Sunday in October.
    (This code is not tested, but should work... ;-)

**Comment by larsbrinkhoff** [comment]
Yes, this has been on the radar for a while.

I think most Y2K bugs have been fixed.

**Comment by bictorv** [comment]
Solved by #2040 when approved.
