### ISSUE TITLE
LSPSRC; VECTOR 75 has wrong HERALD version number

### ISSUE THREAD

**Issue by eswenson1** [PDP-10/its#1318]
I updated VECTOR to make allow it to compile in DB, but I forgot to update the HERALD version number.  We have two choices:  

a) update the HERALD expression to (herald VECTOR /75) or
b) update the HERALD expression to just (herald VECTOR)

b) will use FN2 as the version.  In both cases, the version will be displayed when the FASL is loaded.

The *only* reason I'm raising this as a choice--since b) is ealier to maintain going forward--is that some systems don't know how to use the filename to extract the version number.  And because historically, this file had an explicit version number in the herald expression.  Thoughts?

**Comment by larsbrinkhoff** [comment]
I'd say b) looks tempting.  The main reason to go with a) is to stay closer to the original.
