### ISSUE TITLE
lisp interpreter version

### ISSUE THREAD

**Issue by eswenson1** [PDP-10/its#1321]
From what I can tell, the last LISP interpreter created on real ITS machines back in the day was PURQIO 2149.  It was created on 4/21/1986.  DB ITS creates PURQIO 2154.  Are we happy with this, or should we use 2150?  Or bump up to some nice even number like 2200 or 2500 or 3000?

**Comment by larsbrinkhoff** [comment]
I don't have a strong opinion on this.  Maybe 2150 would be proper, but 2154 is close enough?

**Comment by eswenson1** [comment]
Ok, let's leave as 2154 then.  If we go "backwards" from 2154 to 2150, someone might think there is an issue.
