### ISSUE TITLE
OSX building

### ISSUE THREAD

**Issue by TheFausap** [PDP-10/its#1325]
Hello,

I found a couple of issues during a build under OSX (High Sierra).

1) touch under OSX is different: -d option is not present, so I modified the makefile with the correct syntax, using a check for the OSTYPE

2) ka10 simulator seems is not able to find the correct X11 libraries. After installed XQuartz, I modified the makefile, when it searches for libXt, adding to OS_CCDEFS the X11 include path, and everything went fine.

Now I'm building, and it seems everything ok.

If you want I can create a new branch with these changes.

**Comment by TheFausap** [comment]
Created a new branch : osx-build
I also modified the makefile under tools/sims, but I'm not authorized to push to that repo.

Just few notes about running under OSX / XQuartz: to be able to create the X11 window for 340 display, the sim needs to be start from an XTERM terminal (not the standard OSX terminal app).
The GT40 terminal start without any problem, because it's an SDL application.

Could be possible, modify the 340 display to use SDL too ? If so, we could skip the XQuartz part.

**Comment by larsbrinkhoff** [comment]
Thanks, I'll take a look some time soon...ish.

I'm afraid the 340 display is outside our jurisdiction.  As far as I know, direct use of SDL is not allowed.  You will have to go to http://github.com/simh/siimh and check with the people there.

**Comment by larsbrinkhoff** [comment]
I pushed another commit onto your branch to build it with Travis CI:  
https://travis-ci.org/PDP-10/its/branches

**Comment by larsbrinkhoff** [comment]
I need more changes to appease Travis CI, so I made a new branch off yours: lars/osx.

- KLH10 builds, but the expect script doesn't.
- KA10 sims complains about not finding X11/X.h.  Maybe your OS_CCDEFS fixes that?
- KS10 simh completed a full build.

**Comment by larsbrinkhoff** [comment]
Logs here:  
https://travis-ci.org/PDP-10/its/builds/439271789

**Comment by TheFausap** [comment]
Yes Lars, OS_CCDEFS is needed to find X11/X.h
In the DARWIN section of makefile, I added `OS_CCDEFS += -I/usr/X11/include`

**Comment by rmaldersoniii** [comment]
Back in the mists of time, I had to make some changes to KLH10 to build on OSX. I don't know whether these are helpful, but I put them on my personal web site in 2011:
http://www.panix.com/~alderson/klh10-2.0h_for_OSX.6.8/

**Comment by larsbrinkhoff** [comment]
Maybe we can use `touch -t` everywhere.

**Comment by TheFausap** [comment]
Hello, I found a typo in the timestamps lists

rrs/subsys.order 1978080144.12 

is missing some part of the timestamp, I suppose hours and minutes.

**Comment by larsbrinkhoff** [comment]
Fixed by #1983.
