### ISSUE TITLE
Smoking Clover

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#1326]
The original jargon file doesn't say much:

    SMOKING CLOVER n. A psychedelic color munch due to Gosper.

The print edition is more elaborate, and the current online version has this:

> A display hack originally due to Bill Gosper. Many convergent lines are drawn on a color monitor in such a way that every pixel struck has its color incremented. The lines all have one endpoint in the middle of the screen; the other endpoints are spaced one pixel apart around the perimeter of a large square. The color map is then repeatedly rotated. This results in a striking, rainbow-hued, shimmering four-leaf clover. Gosper joked about keeping it hidden from the FDA (the U.S.'s Food and Drug Administration) lest its hallucinogenic properties cause it to be banned.

There's even a [Wikipedia page](https://en.wikipedia.org/wiki/Smoking_clover).

@mettacrawler and @pacew implemented the hack for X11, and it can be found [on SourceForge](https://sourceforge.net/projects/smokingclover/).  Someone used it to make a [YouTube video](https://www.youtube.com/watch?v=Os3DP3haTEs).  I dusted the program off and [put it on GitHub](https://github.com/larsbrinkhoff/smoking-clover).

There is also a [program made by Chris Kent](https://stuff.offog.org/its/news/1989-wexler-clover), and the shar archive includes Lisp Machine code.

**Comment by larsbrinkhoff** [comment]
The SourceForge README says "The code for drawing the clover itself is taken from the X11 port by
Kenneth Stailey (around 1989)."  Indeed the `clipLine` function is almost identical to the one in the 1989 Usenet post.

**Comment by mettacrawler** [comment]
Oh God, 1989 was when I was living in the late Louis Herbert Ressijac's
rented townhouse on 16th just one block from Washington DC.  I probably had
my first home UNIX workstation, a 66 MHz 486 which I later upgraded to a
Pentium with a drop-in replacement CPU.  I had NetBSD 0.8 running on it at
first.  The buss mouse didn't have interrupt protection and the system
would panic while scrolling a window under heavy load.  I submitted a
kernel patch and it got re-written.  Strawman patches are often very good
bug reports.

**Comment by mettacrawler** [comment]
If you're looking for my artifacts search http://cvsweb.openbsd.org/ for
kstailey
For instance
http://cvsweb.openbsd.org/src/sys/miscfs/specfs/Attic/spec_vnops.c

**Comment by larsbrinkhoff** [comment]
It's now here:  
http://github.com/larsbrinkhoff/smoking-clover
