### ISSUE TITLE
Update programs.md with new inquir programs

### ISSUE THREAD

**Issue by eswenson1** [PDP-10/its#1337]
A recent commit added these programs to the inquir; directory:

INQEXM
INQREP
INQCHK
INQUPD

@larsbrinkhoff had suggested that these get added to programs.md.  Do we want to do that?  These are not in any SYS: directories and are pretty obscure hacks for fixing INQUIR issues.  I'm entering this ticket so we can decide, and if we decide to include them, so that we don't forget to actually do that!

**Comment by larsbrinkhoff** [comment]
My reasoning is that, for this file, we should rather err on the side of verbosity.  Are their function documented anywhere else, other than the source code and commit comments?

**Comment by eswenson1** [comment]
Probably not. I’ll figure out a one liner for them and add to programs.md. Maybe a readme for the inquir directory too.

**Comment by larsbrinkhoff** [comment]
Sounds great!
