### ISSUE TITLE
Scheme chip

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#1364]
Collecting notes about the Scheme chip, or chips.  Maybe eventually there could be some files to check in.

![scheme79](https://user-images.githubusercontent.com/775050/47480470-d813b480-d830-11e8-9b74-60fd5fc4db2a.JPG)

**Comment by larsbrinkhoff** [comment]
[AI memo 559](https://dspace.mit.edu/handle/1721.1/6334), "The SCHEME-79 Chip".

The appendix has a complete listing of the microcode, including detailed comments.

**Comment by larsbrinkhoff** [comment]
[Scheme-79, Lisp on a Chip](https://www.computer.org/csdl/mags/co/1981/07/01667431.pdf).

**Comment by larsbrinkhoff** [comment]
PDFs and microcode by @nguyentito.

https://github.com/threonorm/simulisp/tree/master/SCHEME-79

**Comment by ams** [comment]
I have files for the Scheme-79.  Compiler and ucode and I think a simulator.

**Comment by larsbrinkhoff** [comment]
Great, @ams.  Please upload somewhere and posts pointers here.

**Comment by larsbrinkhoff** [comment]
A photo of the Scheme Chip layout.  Source: https://www.computerhistory.org/collections/catalog/102803894
![schip](https://github.com/PDP-10/its/assets/775050/9503c06d-1f4c-4bbb-aa8e-186fb1873fcb)
