### ISSUE TITLE
ZONE - Muddle compile batcher

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#1401]
SYS; ATSIGN ZONE

No ITS source found.  Try to use \<combat>zone.mid.3.

**Comment by larsbrinkhoff** [comment]
ZONE.MID is updated for TOPS-20 with no ITS traces.

**Comment by larsbrinkhoff** [comment]
ZONE.MID has title RUNCMP.  It wants to start PCOMP.EXE.

I'm not sure whether this version will be useful, since it may not retain ITS demon functionality.

**Comment by larsbrinkhoff** [comment]
COMBAT; MASTER > seems to be the Muddle source, because it calls `<IPC-ON "COMBAT" "ZONE">`

**Comment by eswenson1** [comment]
I’ve gotten permission from MIT to release this, and related code. I’m trying to get it all to work first, though, before I commit.

**Comment by larsbrinkhoff** [comment]
Closing as duplicate of #2149.
