### ISSUE TITLE
Enable "message slurper" (DM only?)

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#1421]
Set MSPP in ITS to get the IPC device, which Muddle uses.

If #1323 has been solved, only enable this when building DM ITS.

**Comment by larsbrinkhoff** [comment]
This is necessary to run Muddle, so by extension Zork, Trivia, etc.

**Comment by atsampson** [comment]
It shouldn't be necessary to run Muddle unless you've got a program that uses it. Our Muddle 56 is built with IPC support, and it's [documented in MUDMAN](https://jxself.org/git/?p=mudman.git;a=blob;f=md/language.md;h=d1a266d9b3f7329dab9b672214ee30b82eaad9bc;hb=HEAD#l8845).

**Comment by larsbrinkhoff** [comment]
Some version of Zork or Trivia, I don't quite remember, was unhappy without it.

I'm increasingly thinking there should be a separate image for a DM-like machine.  Most things would be ok on the KA image, but certainly the 340 and E&S displays can't be on the same machine simultaneously.  There are some minor things like TVBUG which were totally different programs on AI and DM: a Knight TV hack, or bug report for Trivia.

**Comment by atsampson** [comment]
I've rebuilt my ITS with this enabled, and the Muddle IPC channels seem to at least initialise happily (which saves patching Muddle when loading images that have open IPC channels - `ipcbls/ popj p,`). Anyone mind if I submit a PR to do this in the default images?

**Comment by larsbrinkhoff** [comment]
I don't mind.  I have had an ITS running with MSPP==1 and no ill effects that I could see.
