### ISSUE TITLE
CROSS Assembler Doesn't Work

### ISSUE THREAD

**Issue by everyfan** [PDP-10/its#1462]
I've spent the last few weeks trying the PDP10 "CROSS" Assembler on ITS, TOPS-10, and TOPS-20 machines. I can't remember if I ever got the ITS version working, as you could imagine with the different OS and file system, it was a little picky.

But! I have never gotten any version to output anything resembling the proper code. Granted, I've only tried the 6502 CPU, since that's the only one I'm familiar with. I've tried both using Kermit to get the binary file, and storing it on an emulated TOPS-10 backup tape and then extracting that.

For instance, my test program listing says it outputted (in hex) "00 10 A9 01 8D 00 04 4C 07 10"

Looking in a hex editor at the extracted binary file, it instead contains: "00 00 08 00 08 02 00 00 10 00 00 1A 28 00 46 09 40 20 10 03 00 03 28 00 00 00 00 00 01 00 00 60 00 00 1F 10 00 00 00 00"

???????

I've come to the conclusion that, at least on the 6502 CPU, it's simply not outputting correctly.

**Comment by larsbrinkhoff** [comment]
CROSS is used to assemble Apple II Logo, and it does run on an emulator.  So I think the 6502 code should be ok, if you know how to use the output format.

I don't know what the binary file format is.  I *think* it resembles the PDP-11 absolute loader format.  We have used the "PTP" output format which is similar to Intel HEX.

**Comment by everyfan** [comment]
Thanks so much! That works like a charm.

I think Commodore's assembler for the C64 is based on this cross assembler; it has some similar pseudo-ops, and also assembles to Intel HEX.

**Comment by larsbrinkhoff** [comment]
That's an interesting observation.  I suppose the Commodore C64 assembler should be similar (or same) as the one for PET?

As far as I know, many microcomputer vendors back in the day used minis or mainframes to host their development tools.  I wonder if Commodore had a DEC-10?

**Comment by larsbrinkhoff** [comment]
The PET came with Microsoft's BASIC, right?  And Microsoft used DEC-10 for development.  So maybe Commodore used the same tools.

**Comment by everyfan** [comment]
> That's an interesting observation. I suppose the Commodore C64 assembler should be similar (or same) as the one for PET?
> 
> As far as I know, many microcomputer vendors back in the day used minis or mainframes to host their development tools. I wonder if Commodore had a DEC-10?

Yeah, the C64 Assembler was based on the one on the PET (I think the VIC-20 one was too?) The other similarity to CROSS is it has the 6 character limit on symbols. All internal commodore C64 code, including the version of BASIC, the OS, and the Disk Drive's DOS, were all written in the PET Assembler - which is why all OS routine and memory variable names in official Commodore docs are 6 characters or less.

**Comment by everyfan** [comment]
I'm talking about the commercial assembler package and development environment sold by Commodore when the C64 first came out. I joke that it's the Assembler Without a Name - the manual says Macro Assembler Development System, the box says ASSEMBLER, and the disk says C64101.

I guess MADS would be the best thing to call it; you could also call it Macro if you wanted a third assembler called that XD

You can find the disk image that assembler along with a disassembly of it here https://github.com/dmarlowe69/Assembler64

You can find the original internal Commodore code which I believe I've read was written in a near-identical assembler for the PET (tho at the moment I can't find that information on this GitHub) here: https://github.com/mist64/cbmsrc

Most of that internal code came from disk images made available by an old Commodore guy here: http://6502.org/users/sjgray/dj/

**Comment by everyfan** [comment]
My guess would be, whoever wrote the original PET assembler either wrote it in CROSS or was familiar with it.

**Comment by larsbrinkhoff** [comment]
Thanks, that's interesting.

In case you didn't know, CROSS is really native to TOPS-10, not ITS.
