### ISSUE TITLE
Why is PWORD/PANDA build in lisp.tcl?

### ISSUE THREAD

**Issue by eswenson1** [PDP-10/its#1465]
PWORD and PANDA are MIDAS programs and don't depend on lisp at all.  The build of these should be moved out of lisp.tcl and into another .tcl file (misc.tcl?).

**Comment by larsbrinkhoff** [comment]
I think I put it there, and I think the reasoning was that it depends on INQUIR.

**Comment by eswenson1** [comment]
I don't think it depends on the lisp code for inquir does it?

**Comment by larsbrinkhoff** [comment]
It looks like PANDA/PWORD only depends on the MIDAS file LSRTNS.  I considered it a part of the INQUIR ecosystem as a whole.  Can you make an INQUIR database without the INQUIR tools?

**Comment by eswenson1** [comment]
I think the answer is yes.  CSTACY (I believe) wrote a MIDAS tools to create an empty INQUIR database.  But our build just puts an empty database there, if I remember correctly.  The empty database came from backup tapes. I don't think I'd found the MIDAS program that created the empty one at that point.

**Comment by larsbrinkhoff** [comment]
Ok, I'll accept it's a bug to be fixed.

**Comment by eswenson1** [comment]
I think the file INQUIR; LSR1 EMPTY is an empty INQUIR database.  As I said, I think there is a program to create this file.  We just load it from tape and then do a :copy inquir;lsr1 empty,lsr1 >.

**Comment by larsbrinkhoff** [comment]
Can you look into which program that is, so we can create LSR1 EMPTY in the build script rather than copy it from tape?

**Comment by eswenson1** [comment]
Sure.  I know I've seen it somewhere.....

**Comment by larsbrinkhoff** [comment]
Maybe it's this: #519.

**Comment by eswenson1** [comment]
I’m writing a Midas program to create INQUIR; LSR1 EMPTY.
