### ISSUE TITLE
SYSBIN; PWORD BIN is built as PANDA and SYSBIN; PANDA BIN is built as PWORD

### ISSUE THREAD

**Issue by eswenson1** [PDP-10/its#1466]
The lisp.tcl (!) script builds PWORD and PANDA thus:

```
respond "*" ":midas sysbin;pword bin_sysen1;pword\r"
respond "Is this to be a PANDA?" "yes\r"
expect ":KILL"
respond "*" ":midas sysbin;panda bin_sysen1;pword\r"
respond "Is this to be a PANDA?" "no\r"
expect ":KILL"
```

This is backwards.

**Comment by larsbrinkhoff** [comment]
Looking further down in the script, ATSIGN PWORD is linked to this PWORD BIN which is really PANDA, and TS PANDA is linked to PANDA BIN which is really PWORD.  How can this work?

**Comment by larsbrinkhoff** [comment]
By the way, JOBS categorizes PANDA and KOALA as "Magic".  What is KOALA?  And JCOPY?

**Comment by eswenson1** [comment]
Never heard of them.  But...

GUEST4; KOALA 1
RLB; JCOPY 21

could presumably be found.

**Comment by eswenson1** [comment]
> Looking further down in the script, ATSIGN PWORD is linked to this PWORD BIN which is really PANDA, and TS PANDA is linked to PANDA BIN which is really PWORD. How can this work?

DB is not using either PWORD or PANDA.  So it probably doesn't work.  Everything works fine on ES because I've correct build both of these and done the appropriate magic so that things are setup fine.

**Comment by larsbrinkhoff** [comment]
I found a TECO program which calls KOALA and JCOPY "special jobs reserved for sys hackers!"
