### ISSUE TITLE
Add UPTINI program for creating UPTIME DATA

### ISSUE THREAD

**Issue by eswenson1** [PDP-10/its#1471]
This ticket is for adding the new program, EJS; UPTINI 1 and building EJS; TS UPTINI for creating the file .TEMP.;UPTIME DATA.  A subsequent ticket may call for using this program to build the data file and then copying the result to BAWDEN; UPTIME DATA rather than loading a pre-built one from tape.

**Comment by larsbrinkhoff** [comment]
Maybe you like to have a ticket for everything, and then it's fine.  But if you submit a pull request, I don't think if necessary to create a ticket if there wasn't one already.
