### ISSUE TITLE
.INFO.; ITS ....IX

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#148]
What are they?  They're not ASCII text.  I'm guessing they're compressed files, but USQ won't have anything to do with them.

**Comment by eswenson1** [comment]
Index files?  Are they maybe used by PR?  If you look at this code, in PR, it seems likely:

FOPEN0:	MOVEM	A,FNAME2
	JUMPE	B,FOPEN1
	TRZ	A,7777
	IOR	A,[SIXBIT /    IX/]
	MOVEM	A,IXNAME

In my commit of the PR stuff, I didn’t include the IX files (not having a clue what they were), but I wonder if we should. I wonder how they are generated?  

— Eric

**Comment by larsbrinkhoff** [comment]
Thanks, that's it!  From PR:

            MOVE    PSBP,[440700,,[ASCII /New documentation file, must index, hang on.../]]

So PR generates them automatically.

**Comment by eswenson1** [comment]
You beat me to trying this out.... :-)

**Comment by larsbrinkhoff** [comment]
I didn't try it yet, just followed the trail backwards from FOPEN0.  Please let me know if you verify that this message pops up when you delete the file and run PR.

**Comment by eswenson1** [comment]
Just tried it. Didn't see the message. Didn't get an IX files created.  Otherwise, PR worked as expected.  Will investigate when I have a moment.
