### ISSUE TITLE
Build Fails for both KLH10 and SIMH

### ISSUE THREAD

**Issue by everyfan** [PDP-10/its#1484]
It gets to this point in the build script and then just times out due to ITS giving an error and not recognizing the input command:

```
:copy sysbin;name bin,sys;ts name
*name$j!
*$l  sys;ts name
*debug/'NAME$:   -1   0
$g
New sys, must initialize--
Take paws off keys and wait
$^K
*:pdump sys;dsk:ts name
*$p
Init done
:$ Urk! AAAAAAIIIIIEEEEeeeeeeeeee... $
*:SL SYS;TS NAME
*:PDUMP CRASH;NAME >
*:BUG NAME A NAME crash was just dumped to CRASH;NAME > !!^_:SYS: SYS3; TS BUG - FILE NOT FOUND
:INPUSH ink ?U? sys1;?U? ts ?U? when,?U? sys;?U? ts ?U? name
?U? 
The last command timed out.
Makefile:87: recipe for target 'out/klh10/rp0.dsk' failed
make: *** [out/klh10/rp0.dsk] Error 1
```

**Comment by larsbrinkhoff** [comment]
Building NAME will scream bloody murder (or AAAIIIEEEeee) if something is off with the host table.  I don't know exactly what is off in this case.  If you scan upwards, there should be a call to `hosts3`.  Does it report any errors?

Is your repository really clean, or did you change any configuration?  Add or subtract host names?  Add a new ITS machine?

**Comment by everyfan** [comment]
Oh, that'll do it. I was trying to configure some hosts file in the conf directory, that must have used it incorrectly (it might be a good idea to add more documentation on how to do that). I'll just clear the file out for now.

**Comment by larsbrinkhoff** [comment]
That should do it, I hope.  Add to this if the problem persists, or else close if the build goes through.
