### ISSUE TITLE
ITSTTY Info Doc is incorrect

### ISSUE THREAD

**Issue by everyfan** [PDP-10/its#1486]
INFO;ITSTTY > is supposed to link to SYSDOC;ITSTTY >, but instead it links to INFO;ITSTTY > -- its own dang self, and INFO refuses to open it.

**Comment by larsbrinkhoff** [comment]
Thanks.

Would you submitting a pull request to fix this?  The link is in `doc/info`.

**Comment by everyfan** [comment]
What is the format of the link in the normal directory? Just a symlink, or what?
