### ISSUE TITLE
A guide / short intro for ITS Logo versions (#documentation)

### ISSUE THREAD

**Issue by Alexey-Slyusar** [PDP-10/its#1496]
@larsbrinkhoff wrote:

>We have some starter guides for various things in ITS here: https://github.com/PDP-10/its#documentation It would be good to add one for Logo too.

It is very good point.
It is worth to summarise the information into some kind of starter guide for Logo versions that we have running on ITS. So I am writing the document. I use for the document the similar style as `its/doc/games.md` has.

**Comment by larsbrinkhoff** [comment]
Thanks!

**Comment by Alexey-Slyusar** [comment]
My pleasure.

Don't have enough time to finishing the document these days. But I will be
able to PR draft of the gide not later then weekend, I think.

вс, 20 янв. 2019 г. в 19:43, Lars Brinkhoff <notifications@github.com>:

**Comment by Alexey-Slyusar** [comment]
I've created `alexey/logoguide` branch to work with the document. 
Searching how can I reference the branch from this issue.

**Comment by Alexey-Slyusar** [comment]
Thank you Lars! I'll try.

вс, 27 янв. 2019 г. в 8:29, Lars Brinkhoff <notifications@github.com>:
