### ISSUE TITLE
NAMDRG dies with .VALUE under KLH10

### ISSUE THREAD

**Issue by eswenson1** [PDP-10/its#1498]
NAMDRG dies at location NAME1+2, which is a call to OPEN T35.  I suspect there is no T35 in KLH10 ITS. Does this mean that ITS is configured incorrectly, since we don't have TV11 support under KLH10?
Or is NAMDRG missing some check to determine whether there are any TV11s on the system, and if there aren't, to exit gracefully?

**Comment by larsbrinkhoff** [comment]
I'm surprised NAMDRG comes to NAME1+2.  Does it not call .EVAL to see if TT11P is present in the first few instructions after NAME?

**Comment by eswenson1** [comment]
It does do this. Here's what happens on ES (KLH10):

```
*namdrg◊j!
*◊l (Load Bin File) ◊
DSK: EJS; NAMDRG BIN    sysbin;namdrg bin
*◊0g
NAME>>.CLOSE A,   A/   0      ↑N
NAME+1>>MOVE P,40437   P/   0   40437/   -100,,MNAME+1      ↑N
NAME+2>>.SUSET 40440   40440/   54,,A      ↑N
NAME+3>>TLO A,LOTUP4+1   A/   30000,,0      ↑N
NAME+4>>.SUSET 40441   40441/   SETZ A,A(U)      ↑N
NAME+5>>MOVE B,40442   B/   0   40442/   22473,,602523      ↑N
NAME+6>>.EVAL B,   B/   22473,,602523      v/'NAME◊:   0   b/   22473,,602523   &◊0&NF11TY   ↑N
NAME+10>>SETZ C,   C/   0      b/   35
```

So you see, it is evaluating NF11TY and it is getting 35 back.  I believe this is the TTY number after all the other (real) TTYs that have been defined.

**Comment by larsbrinkhoff** [comment]
It looks to me you're not using the latest update of NAMDRG.  It starts like this:

```
name:   .close 1,       ;close the channel we were loaded on
        move p,[-lpdl,,pdl-1]
        move b,[squoze 0,tt11p]
        .eval b,
         jsr die

**Comment by eswenson1** [comment]
Indeed. I was bitten by the fact that you updated NAMDRG 149 (not incrementing the version number), and I already had the previous NAMDRG 149 on ES.  I didn't notice that it had changed.  I updated ES to have the latest NAMDRG 149 and now it works as it should. Thanks.
