### ISSUE TITLE
TVFIX should probably die gracefully if there are no TVs configured in ITS

### ISSUE THREAD

**Issue by eswenson1** [PDP-10/its#1499]
TVFIX, under KLH10, hangs on an OPEN call forever. It is unlikely to ever succeed, since there is no TV11 support in KLH10.  So rather than having the daemon job stay around forever, taking up a job slot and memory resources, it should die gracefully (perhaps logging a message).

**Comment by larsbrinkhoff** [comment]
I updated STUFF to check for TT11P in #1476.  Does this not work for you?

**Comment by eswenson1** [comment]
I was running STUFF 92 on ES.  Upgraded to STUFF 93 and TVFIX goes away gracefully.
