### ISSUE TITLE
Remove duplicate EMACS executable

### ISSUE THREAD

**Issue by eswenson1** [PDP-10/its#15]
The current build results in two TS EMACS links. One in SYS and the other in SYS3.  In the PI distribution, the TS EMACS link is in SYS2.  Shouldn't we put it there too?

**Comment by larsbrinkhoff** [comment]
I made two links by mistake.

SYS2 sounds good to me.  I don't quite understand how the search works.  Can any binary be in any directory?  In some case, the binary location seemed hardwired to a specific directory.

**Comment by eswenson1** [comment]
As far as I know, the system searches SYS, SYS1, SYS2, and SYS3. — Eric

**Comment by larsbrinkhoff** [comment]
Ok, it's just when a search fails, it always says it's missing in SYS3.

Links fixed.

**Comment by eswenson1** [comment]
Yes, that’s because that is the last directory it searches.
