### ISSUE TITLE
NAME looks for SYSBIN; TTLOC DATA; doesn't exist in DB

### ISSUE THREAD

**Issue by eswenson1** [PDP-10/its#1504]
When name starts up, it looks for the file sysbin;ttloc data. This file doesn't exist in DB.  It seems to not care if it doesn't exist, but we should determine whether we should create this file as part of DB build. I believe this file is a database of the locations (text) of all terminals. This may not make sense for DB, but we should document how to create it and perhaps put a dummy one in place.

**Comment by larsbrinkhoff** [comment]
It's created when the TTLOC program is run for the first.  I don't think it needs to be created by the build script.

**Comment by eswenson1** [comment]
We should include instructions (somewhere) saying this should be run, then.  I just ran it on EX and it did create SYSBIN; TTLOC DATA.  Thanks.

**Comment by larsbrinkhoff** [comment]
"Should" is a bit strong.  A user may run TTLOC to enter his terminal location into the database.  FINGER can then access this information.  If users decline to do so, there will be no TTLOC DATA, and that's OK too.

The information in doc/programs.md is a good start: "TTLOC, advertises physical location of logged in users."

**Comment by eswenson1** [comment]
Ok. I'll close this issue.
