### ISSUE TITLE
PDP-6 problem

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#1530]
When ITS boots with an attached pdp6 simulator, @aap reports this happening:

```
GARBAGE POINTER IN TV-11 MEMORY
BUGHALT.  FIND A WIZARD OR CONSIDER TAKING A CRASH DUMP.
THE SYSTEM HAS CRASHED AND CANNOT BE REVIVED WITHOUT EXPERT ATTENTION.
IF YOU CAN'T FIND HELP, RELOAD THE SYSTEM.
YOU ARE NOW IN DDT.
BUGPC/   CAI SYS11U+5   $Q-2/   CAIL A,CALSXB+14

**Comment by larsbrinkhoff** [comment]
I suspect there's an overlap between the PDP-6 memory range, and the one for 10-11.

**Comment by larsbrinkhoff** [comment]
When fixed, also update the pdp6 submodule.

**Comment by larsbrinkhoff** [comment]
I wasn't able to reproduce this.  What I did:

1. Updated to latest master: 5ca2eca2a778193ecdf8b7e9deb2537d512f07a4
2. Updated all submodules.
3. Compiled pdp6 and ka10.
4. Edited pdp6/emu/init.init.
5. Started ka10 with `./start`
6. Started pdp6.
7. Booted ITS.
8. Set `PDP6UP` to -1.
9. Made a PDP6 job.
10. Read and wrote location 100.

**Comment by larsbrinkhoff** [comment]
Making a new run with a fresh clone.

**Comment by larsbrinkhoff** [comment]
Still no problem.

Maybe if some other can beta test this.  @Alexey-Slyusar and @everyfan, if you have time can you try the PDP-6 simulator connected to ITS?  See comment above for the procedure.

The init.ini edit change the file tools/pdp6/emu/init.ini to uncomment the netmem line and refer to localhost instead of its.pdp10.se.

**Comment by larsbrinkhoff** [comment]
Starting pdp6 is best done from another terminal: `cd tools/pdp6/emu` and then `./pdp6`.

Setting PDP6UP to -1 is done by typing `sys$j`, `$$^R`, `pdp6up/ -1`.

Making a PDP6 job is just `pdp6$j`.

Reading and writing location 100 is `100/ -1`.  The pdp6 simulator will log the read and write operations.

**Comment by larsbrinkhoff** [comment]
Make sure the pdp6 simulator says "connecting to localhost 10006" when it starts.  If it doesn't check that ka10 writes

```
> at auxcpu 10006
Listening on port 10006

**Comment by Alexey-Slyusar** [comment]
Hi Lars!
I'll do this evening.


сб, 9 февр. 2019 г. в 11:35, Lars Brinkhoff <notifications@github.com>:

**Comment by Alexey-Slyusar** [comment]
> Updated to latest master: 5ca2eca

It seems that it takes some more time that I expected.
I get back with the results tomorrow.

**Comment by everyfan** [comment]
I can try it tonight or tomorrow.

**Comment by larsbrinkhoff** [comment]
Thanks guys!

**Comment by Alexey-Slyusar** [comment]
Here is the output from `./pdp6`. 
```
alexey@ITS:~/its/tools/pdp6/emu$ ./pdp6 
[powerff]
[powercore]
[powercore]
[powercore]
[powercore]
connecting to localhost 10006
couldn't open file /tmp/6tty
couldn't open file ../code/test.rim
couldn't open file ../test/test.dt6
> [simthread] start
```
It seems that I did something wrong. But I cannot figure out what is exactly wrong yet.

**Comment by Alexey-Slyusar** [comment]
Second attempt:
```
alexey@ITS:~/its/tools/pdp6/emu$ ./pdp6 
[powerff]
[powercore]
[powercore]
[powercore]
[powercore]
connecting to localhost 10006
couldn't open file /tmp/6tty
couldn't open file ../code/test.rim
couldn't open file ../test/test.dt6
> [simthread] start
netmem botch, closing
unknown netmem message 0
```

**Comment by aap** [comment]
never mind the missing files, they're not needed, just for testing. netmem should connect to the KA and then tell you its fd (in the latest commit). when you then start ITS it crashes for me.

**Comment by Alexey-Slyusar** [comment]
It seems that netmem doesn't connected to KA in my case. I don't see `"connecting to localhost 10006"` message when PDP6 starts.

I've uncomented the line in the init.ini file and it looks like this:
`mkdev netmem netmem localhost 10006`

**Comment by Alexey-Slyusar** [comment]
Where I should type this:

>Setting PDP6UP to -1 is done by typing sys$j, $$^R, pdp6up/ -1.

Making a PDP6 job is just pdp6$j.

**Comment by Alexey-Slyusar** [comment]
At least, ITS doesn't crash for me.

**Comment by Alexey-Slyusar** [comment]
It seems that netmem doesn't connect in my case. I do not see the fd.

**Comment by Alexey-Slyusar** [comment]
@aap , @larsbrinkhoff I've passed this steps:
```
1. Updated to latest master: 5ca2eca
2. Updated all submodules.
3. Compiled pdp6 and ka10.
4. Make a full make clean all.
5. Edited pdp6/emu/init.init.
6. Started ka10 with ./start
7. Started pdp6.
8. Booted ITS.
```
I did steps from 2 to 8 several times.
ITS didn't crash.
But I am not sure that netmem really connected to the KA in my case, because I didn't see the fd.
And I don't know where I should type:
>Setting PDP6UP to -1 is done by typing sys$j, $$^R, pdp6up/ -1.
Making a PDP6 job is just pdp6$j.

**Comment by Alexey-Slyusar** [comment]
I tried from PDP6 prompt:
```
> [simthread] start

> sys^[j
sysj: not found
```

**Comment by aap** [comment]
the fd is printed here: https://github.com/aap/pdp6/blob/master/emu/netmem.c#L123 maybe you don't have the latest commit, i only added that line for debugging earlier.

**Comment by larsbrinkhoff** [comment]
`sys$j` etc and `pdp6$j` are DDT commands.

**Comment by larsbrinkhoff** [comment]
ITS doesn't have the very latest pdp6 commit yet.

**Comment by Alexey-Slyusar** [comment]
Thanks!
I've got the right result I think. My pdp6 simulator loged the read and write operations.
```
alexey@ITS:~/its/tools/pdp6/emu$ ./pdp6 
[powerff]
[powercore]
[powercore]
[powercore]
[powercore]
connecting to localhost 10006
couldn't open file /tmp/6tty
couldn't open file ../code/test.rim
couldn't open file ../test/test.dt6
> [simthread] start
read 000100 000000000000
write 000100 777777777777
```
I'll try the things with the latest commit as soon as I get it on my machine.

**Comment by larsbrinkhoff** [comment]
Thank you @Alexey-Slyusar, that is the same result I got.

**Comment by Alexey-Slyusar** [comment]
Glad to be useful in the process. Thanks you @larsbrinkhoff and @aap for working on this.

**Comment by eswenson1** [comment]
@larsbrinkhoff why am I getting this when I start ka10:

```
build/sims/run-17> set auxcpu enabled
Non-existent device
build/sims/run-18> at auxcpu 10006
Non-existent device

 DSKDMP
```

What do the non-existent devices mean?  I'm running pdp6 and got the following console output from it:  

```
./pdp6
[powerff]
[powercore]
[powercore]
[powercore]
[powercore]
connecting to localhost 10006
error: Connection refused
couldn't connect
couldn't open file /tmp/6tty
couldn't open file ../code/test.rim
couldn't open file ../test/test.dt6
[simthread] start
>
```

**Comment by eswenson1** [comment]
I did get this to work -- by explicitly checking out the origin/lars/pdp6 branch of sims and rebuilding ka10.  And I, too, had no issues reading/writing pdp6 memory.  

I don't recall seeing instructions that the I needed to check out a specific sims branch though, so I'm wondering what I missed?  I did verify that I had pulled the master branch (of its) and that a "git status" showed no submodules out-of-date after I had done a "sync" and "update" on them.  And yes, I did rebuild ka10 after that.  And there was no ka10_auxcpu.c module in the version of sims that I had -- until I checked out the origin/lars/pdp6 branch.

**Comment by eswenson1** [comment]
Just confirmed that the sims submodule has this:

```
[remote "origin"]
        url = https://github.com/larsbrinkhoff/ka10-simh
        fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
        remote = origin
        merge = refs/heads/master
```

And that the master branch doesn't have PDP10_auxcpu.c in it.  

I tried repeated "git submodule sync" and "git submodule update" commands, and I finally got the branch to say that it was the ITS branch. This appears to be what I'm supposed to use. So I rebuilt ka10 and tried the test again. No issues.  Could repeatedly read/write pdp6 memory.

**Comment by larsbrinkhoff** [comment]
You  figured it out, Eric.  Yes, you do need a specific branch.  Sometimes the submodules have updates that are required by the toplevel its repository.  The submodule remote and commit are recorded in git, so "sync" and "update" is the right thing to do.  If you clone a fresh repository, this will be done automatically.  But if you update an existing repository, it will not.

**Comment by eswenson1** [comment]
Except that I started the process with a “git submodule sync” followed by “git submodule update”. No clue why I didn’t get the right ka10 branch.

**Comment by larsbrinkhoff** [comment]
There's probably a way to do this right, but it's hard to say now.

Anyway, sorry @aap, there seems to be a problem on your end.  All I can advice is to make very sure everything is up to date and no previously built files are clogging the system.  But if you make a fresh clone, I don't see that there's anything that can cause trouble.

**Comment by aap** [comment]
Most likely caused by a non-attached TV11. Hard to reproduce reliably but there's a fix in the 10-11 code soon.
