### ISSUE TITLE
Color scope

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#1534]
There was a color display device.  Device code 420 (same as Spacewar consoles), symbolic name CLR or CSCOP.

**Comment by larsbrinkhoff** [comment]
Michael Beeler wrote:
> The color scope was a prototype made by DEC.  They were considering producing a color scope for sale, but never did.  There were two prototype scopes built; one they gave to the AI lab, and I don’t know what happened to the other one.
> 
> It used a regular color TV CRT tube, but all the driving electronics were special purpose stuff built by DEC.  It had only 9 bits of deflection in X and Y, so it was less precise than the 340.  Its spot size was larger than the 340, partly because it had to cover enough of the red, green and blue phosphor spots to have a consistent color.  It was slow!  I don’t remember just how long it took the deflection amplifiers to settle, but it was well longer than the 340.  The color was 6 bits of red, 6 of green, and 6 of blue.  It was only point-plotting, no line, character, or other capability.
> 
> There was no connection between the 340 and the color scope.  “Solar Corona” was shot on the color scope for the sun images, and on the 340 for the titles.  The developed, original film was spliced by hand to make the movie.
> 
> The color scope had a major problem with “convergence”, that is, making the beams from the red, green and blue electron guns all hit the screen at the same point.  This was a problem in color TVs too, but was especially so with the color scope.  For each gun, there was a correction factor that was a weighted sum of a constant factor, X, X^2, Y, and Y^2.  That is, there were constant, linear, and quadratic dependancies on both X and Y, for each of the three electron beams.  The weighting was done with potentiometers (variable resistors) on printed circuit borads, very hard to access.  I made new PC boards with shielded cable to a panel that sat on the tabletop next to the display (where the electronics were under the table).  The panel had a whole bunch of potentiometers, each with a knob and graduated scale, so it was easier to adjust the convergence.  Nevertheless, it was a frustrating thing to work on, and it was always an approximation — no setting ever made all spots just right.
> 
> There also was in interesting feature; if you sent the command to display a point (turn on the beam for a few microseconds) before the deflection amplifiers had settled, the point would be smeared into a short streak between (0,0) (the bottom left corner of the screen) and its correct position.  This is because the
deflection registers were first cleared and then loaded with the new value.  Mostly this was just a limitation on how fast you could run the display, but I used it in one program, “WORM”, that makes a curvy line that crawls around the screen.  By turning on the beam early for each point along the curve, the points were smeared into short strokes, and the effect was sort of like drawing with a calligraphic pen.
> 
> Making a movie of the color scope was a bit of a challenge.  I got the nominal emission spectrum of the P22A phosphors used in the CRT.  I got the nominal sensitivity curves of some color movie films.  I compared them to find a reasonable match, then looked for what color correction (CC) filters would be
best to adjust the light of the phosphors to the sensitivity of the film.  I decided that a small magenta plus a small yellow correction would be good.  With these filters placed in front of the movie camera lens, what came out on film was reasonably close to what a person saw looking at the CRT.

**Comment by larsbrinkhoff** [comment]
Although some programs set say CLR is device 420, it seems to be some kind of input device.  CONO'ing 40 sets it to read the Spacewar consoles.  400000 is the "robot switches".  And those are all I can find.

TJ6 uses it to check that one particular switch is set and comments "COLOR SCOPE (SIGH)".

**Comment by larsbrinkhoff** [comment]
Maybe this photo?  https://www.computerhistory.org/collections/catalog/102753199

If only it were on display.

**Comment by larsbrinkhoff** [comment]
Found software!  MB; TITLER 3

Interesting snippets:

```
CSCOP==420

WHITE==333733

;CONO 420 BITS (20 BIT IS ENABLE, SO INTENSITIES < 20 = OFF)
;370000 RED INTENSITY (<22 = OFF)
;003700 GREEN INTENSITY (ENTIRE RANGE USABLE)
;000037 BLUE INTENSITY (<25 = OFF)

;DATAO 420 BITS
;0,,777000 X DEFLECTION
;0,,000777 Y DEFLECTION

**Comment by larsbrinkhoff** [comment]
According to Greenblatt, the deflectors took around 50 microseconds to settle.

**Comment by larsbrinkhoff** [comment]
Note how CONO 40 or 400000 doesn't conflict with the color bits.

**Comment by larsbrinkhoff** [comment]
Work in progress.  Output from TITLER.

https://youtu.be/X1bFUShpcaA

**Comment by larsbrinkhoff** [comment]
From [AI memo 238, "ITS Status Report"](https://dspace.mit.edu/bitstream/handle/1721.1/6194/AIM-238.pdf), page 37:

> A color display with X-Y point-plotting capability only is also attached to the Artificial Intelligence Laboratory system. The slowness of this display and various problem related to focusing and convergence presumably led to its manufacturer's generosity in giving it to the Artificial Intelligence Laboratory.  There are currently no routines in ITS for the use of this device but is has been used to a limited extend from the PDP-6.

**Comment by larsbrinkhoff** [comment]
More software:
- CSLAVE/CMASTR, #1654.
- COLOR HACK, #1658.

**Comment by larsbrinkhoff** [comment]
```
********** I. INTRODUCTION

THERE NOW EXISTS A DISPLAY SLAVE FOR THE COLOR SCOPE, WHICH RUNS
ON THE PDP-6 (AND HOPEFULLY ON THE PDP-10 IF NECESSARY). IT PROVIDES
BASIC CAPABILITIES FOR DRIVING THE SCOPE, MAINTAINING PROPER TIMING,
AND MANAGING DISPLAY ITEMS.


********** II. THE COLOR SCOPE

THE COLOR SCOPE ITSELF IS DESCRIBED IN HARDWARE MEMO #6. A BRIEF
RUNDOWN IS PROVIDED HERE:
THE SCREEN OF THE COLOR SCOPE IS NINE BITS EACH WAY, THEREFORE
PROVIDING HALF THE RESOLUTION OF THE 340. THE SCREEN IS
ADDRESSED BY EIGHTEEN BITS: TWO NINE-BIT BYTES <X,Y>. <0,0>
IS THE LOWER LEFT-HAND CORNER. IT CAN ONLY DISPLAY
RANDOM POINTS; THAT IS, THE HARDWARE DOES NOT PROVIDE VECTOR
CAPABILITY. SINCE POINTS CAN ONLY BE DISPLAYED AT A RATE OF 1 EVERY
210. MICROSECONDS, ONLY ABOUT 400. POINTS CAN BE DISPLAYED WITHOUT
UNREASONABLE FLICKER. THE COLOR USED TO DISPLAY A POINT IS CONTROLLED
BY FIFTEEN COLOR BITS; THESE ARE PACKED IN AN EIGHTEEN-BIT PDP-10
HALFWORD AS THREE SIX-BIT BYTES, WHICH SPECIFY RED, GREEN,
AND BLUE INTENSITIES. WITHIN EACH BYTE, THE HIGH BIT IS NOT
APPLICABLE TO COLOR (USED FOR SOMETHING ELSE), THE NEXT BIT
IS AN ENABLE BIT, AND THE LOW FOUR SPECIFY THE INTENSITY FOR
THAT COLOR.

**Comment by larsbrinkhoff** [comment]
KLH writes:
> I think one source of confusion is the fact the 420 device was
> different things on the 6 and the 10. Only the 6 had it as a 36-bit
> (one-word) input array, and the Spacewar and DazDart "consoles" were
> just different things that you had to physically switch between

> The color display was off in a small dark room, possibly locked most
> of the time, hooked to the 10 and with essentially no hacks of
> interest except a fireworks display.

**Comment by larsbrinkhoff** [comment]
Wireforks:
http://projects.csail.mit.edu/video/history/aifilms/36-wireforks.mp4

**Comment by larsbrinkhoff** [comment]
This just in.  HW memo 6.

[HwMemo6-Device-420-710628.pdf](https://github.com/PDP-10/its/files/4143192/HwMemo6-Device-420-710628.pdf)

**Comment by larsbrinkhoff** [comment]
Recorded these videos:  
- Wireforks: https://www.youtube.com/watch?v=oQKr_jBMViE
- Ocean: https://www.youtube.com/watch?v=3WH4yAwaU6I
- Forms: https://www.youtube.com/watch?v=6EQTX2aX3gA
- Spiral: https://www.youtube.com/watch?v=2fh8zFXcLYE
- Titler: https://www.youtube.com/watch?v=ymJ5D9exvUw

**Comment by foxkit** [comment]
The most surprising thing I saw on the color display was a perceptual
psychology experiment.

The display would flash color names, either in the named color, or a
different color.   You were instructed either to name the color or to read
the word.

It was disturbing to experience how difficult it was.

**Comment by larsbrinkhoff** [comment]
Thanks for the recollection @foxkit.  That's part of COLOR HACK (#1658) and the entry point is called PSYCH.

**Comment by larsbrinkhoff** [comment]
Beeler's feedback on the emulator: 

> WIREWORKS certainly shows the feel of the original color scope.  As was the case on the
hardware and also the movie, the tiny red blips showing the mortar going up to where it bursts,
are essentially impossible to see.  Bad design on my part.
> 
> OCEAN came out especially well in your emulator.  Nice job.
> 
> FORMS is very satisfying to me.  I never actually filmed it, so I saw it only directly on the
> color scope, and it was so slow that it looked like a lot of random flickering.  In your emulator,
> the lines, circles, grid bursts, and so on are clearly present.  After so many years, I am
> very happy to finally see that it gives the sort of “modern art” impression I hoped for!
> 
> SPIRAL is nice, I didn’t even remember that.
> 
> TITLER is good, and reminds me what it was about.  It was to make titles for movies.
> The letters in the words (only a few words) of a title are made of dot-matrix characters.
> These stay on screen for a few seconds, then change into the next title.  The trick is that
> each of the original dots gets assigned one of the dot positions in the new title, and
> slowly moves from its original position to its new position.  So the old title dissolves into
> a random looking mess, which sorts itself out and the new title emerges.  If there are a
> different number of dots in the old versus new title, some of the dots in the title with
> fewer dots are duplicated.  If the words in the new title are in different colors, the color
> of each dot changes before it starts moving into its new position, making the “mess that
> sorts itself out” an even stronger effect.  The titles in your video are just test words,
> never used in movies.
> 
> The color range on the original color scope was greater than in your YouTube videos.
> You have good white, blue, pink and light green, but not much red, orange or yellow.
