### ISSUE TITLE
CRTSTY  and / or  TCTYP

### ISSUE THREAD

**Issue by mstram** [PDP-10/its#1539]
Which program is preferable when using :

1) Linux xterm  (Gnome Terminal)

2)  Putty  (Linux)

How do the CRTSTY  and TCTYP programs "relate" to each other ?

E.g.  the CRTSTY  options  / height  refers to using the TCTYP PAGEL N  command,  which seems to imply that TCTYP has "priority" over CRTSTY ?

**Comment by larsbrinkhoff** [comment]
I mostly use xterm from Linux, and PuTTY from Windows.

**Comment by larsbrinkhoff** [comment]
TCTYP changes ITS' internal terminal settings (the "kernel").  `:TCTYP AAA` works well with xterm.

CRTSTY is a separate terminal emulator.  It can translate control codes between many different terminal types, some of which are not supported by ITS.
