### ISSUE TITLE
MIT backup tapes

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#154]
I'm in touch with Pandora Berman (CENT) and Hal Abelson about accessing MIT backup tapes.

**Comment by larsbrinkhoff** [comment]
> Some of the backup tapes from the various mainframes in Tech. Sq. were preserved for a while, and eventually shipped to a firm that specialized in such matters that read them back.  Of those tapes, not all of them came through the storage & processing well -- some were unreadable, some had errors in some files, and only some were apparently in good enough shape to be read completely.  And while all the tapes that we had left in storage were read in this fashion, the previous processes of choosing which ones to save had not necessarily saved entire dumps; in many cases random sections of full dumps were arbitrarily discarded.

**Comment by larsbrinkhoff** [comment]
>  I've contacted MIT's archivist, who is interested in the issues around digital archiving of this historically important collection. The archives are getting ready to take (copies of) the files. But I think it will be a while before they would be ready to release information due to the need to vet the files for privacy issues.

**Comment by larsbrinkhoff** [comment]
Ron Schnell (see #146) pointed out that MIT should be able to release personal files to the persons how made them.

**Comment by larsbrinkhoff** [comment]
From Devon, a year ago:

> In December I handed a ToTS (Tapes o’ Tech Square) drive to MIT archivist Kari Smith - sad that with our high speed campus network, sneakernet still works best due to aggravating access controls & software impedance mismatch.  Previously we’d kept it quiet lest MIT’s lawyers order us to destroy the lot.  Sadly, it seems J.B. 100% failed to read even one bit of the all-important GFR tapes from the original 7-bit media which I fear are destroyed or lost.  The bits we did get, were much more recent and to my mind of much less interest.  Alan Bawden says when the final ITS tapes were spun at MIT, some sources such as the old format ARchive device drivers had already gone missing.

**Comment by larsbrinkhoff** [comment]
@b4 This is what I heard about the state of MIT's backups.

**Comment by ams** [comment]
@larsbrinkhoff I’ll check with Brad Parker if he might have leads, he did secure some bits from MIT.

**Comment by larsbrinkhoff** [comment]
News from Hal:
> We gave the files to the MIT archives in the fall.
> 
> The are going to think about the appropriate way to handle these, but it will take a while, since it's a new policy area. I'm cc-ing this message to Kari Smith, the Institute Archivist.

CC @kossow

**Comment by larsbrinkhoff** [comment]
@atsampson, you asked about MIDAS from DM ITS.  I have been prodding the Infocom people about PDP-10 software, but it seems they don't have any.

We do know there were backup tapes being made, but we don't know what happened to them.  The Dynamic Modeling organization was quite separate from the AI Lab.  DynaMod was closed down around 1980ish, wereas the AI Lab lived on.  This may explain why there is a lot more AI Lab material around than from DynaMod.

I don't want to wear down the patience of the MIT people.  Can you ask around?

I have tried to locate Al Vezza, who was some kind of director or the Dynamic Modeling group, but so far I haven't found any way to contact him.

**Comment by larsbrinkhoff** [comment]
@jh95468 told me DynaMod used to recycle backup tapes, at least in the early days.

But I found this exchange about DM backups:

Alan asked:
> Do we have a way to read DM backup tapes? Did anyone write such a tool when the DM users moved to XX?

Moon replied:
> I don't know of any way to do it, but the format is so simple. Each file on the tape is a file (i.e. there are tape marks between the files) and just has some header information at the front.

I'm guessing this means at least some backup tapes were not recycled.  But since the tape format is (supposedly) different from standard (i.e. MIT-AI/ML/MC)  ITS DUMP maybe it's not easy to extract the files even if there would be tape images.

**Comment by larsbrinkhoff** [comment]
I should add this information from http://www.boogles.com/local/papers/tcfs-thesis/thesis.html

Machine | Density | Tracks | Years | Tapes
-- | -- | -- | -- | --
DM KA-10 | 800 | 9 track | 1976--83 | 330
AI KA-10 | 800 | 7 track | 1971--82 | 362
ML KA-10 | 800 | 7 track | 1973--83 | 203
MC KL-10 | 800 | 7 track | 1976--85 | 511
MC KL-10 | 1600 | 9 track | 1981--86 | 60
All KS | 6250 | 9 track | 1985--90 | 159

**Comment by larsbrinkhoff** [comment]
> DM was dumped in a very strange fashion; for most of its early history, only incrementals and MUDSAV (some sort of special dumping of MUDDLE sources) seem to have been done.  Starting in 1980 there are occasional regular ITS-style full dumps

**Comment by eswenson1** [comment]
Where did you learn this -- and did it lead to any source of the dump tapes?  :-)

**Comment by larsbrinkhoff** [comment]
It's in CENT; TAPES SAVE2.  No new source.

**Comment by larsbrinkhoff** [comment]
CC @kcr.

**Comment by larsbrinkhoff** [comment]
So far I don't think we've seen a trace of those 330 DM tapes, incremental or not.

Some individual files or directories seem to have found their way to other machines.

**Comment by larsbrinkhoff** [comment]
Martin Frost says MIT failed to preserve their archives:  
https://www.youtube.com/watch?v=I8UvPNM22bw&t=487

**Comment by larsbrinkhoff** [comment]
> So far I don't think we've seen a trace of those 330 DM tapes, incremental or not.

Here's a trace:  
http://people.csail.mit.edu/devon/archive/WW15-DM.png

The picture says "DM" in many places, and even "DM KA" in a few.

**Comment by ams** [comment]
Is there a link to the (public) archive that Martin Frost is referencing to?

**Comment by larsbrinkhoff** [comment]
That would be http://Saildart.org/

**Comment by ams** [comment]
Ah, I was understanding it as it being MIT tapes not SAILDART.  Thanks!

**Comment by larsbrinkhoff** [comment]
Maybe Frost referred to this:  
https://youtu.be/N4_7xC1mvY8?t=134

McCarthy doesn't say MIT failed to preserve their tapes, just that they haven't done anything like Saildart.

**Comment by ams** [comment]
Is it the CSAIL archive thing being referenced? Maybe Devon can fill in?

http://people.csail.mit.edu/devon/archive/

**Comment by larsbrinkhoff** [comment]
I think that's the closest thing to Saildart, but apparently the effort has stalled.
