### ISSUE TITLE
"master" console  / user ?   - kill process / login - messed up terminal

### ISSUE THREAD

**Issue by mstram** [PDP-10/its#1540]
Ubuntu 14.04  :  gnome terminal.

I was messing with the TCTYP options to try to increase the number of lines INFO displayed

I set TCYTP Pagesize=40,  ... but should have set it to 32.

When I ran emacs, the screen filled with "@^".

Now the terminal doesn't respond to any keyboard input.

Is it possible to "force" that user ("mike") off  and (hopefully) reset the terminal ?

That terminal, (unfortunately) is where ITS was started from, so I assume if it's killed,
the kn10-ks-its / ITS system will also shut down?

Not a huge deal, I haven't done anything but write a few small scripts / hello world programs, that
I've already copied out via putty.

**Comment by larsbrinkhoff** [comment]
If ^Z doesn't work, maybe you need to login on another terminal line and kick MIKE off.  Are you using the KA10 emulator, aka "sims"?  Then telnet to port 10003, start PEEK, and identify the user index to the left.  Type that number, and then X.  I will ask GUN DOWN TREE, so answer Y.

**Comment by mstram** [comment]
Thanks, that solved it !.

The INFO / General Information programs / :

"(PEEK, WHOIS,  W,  LOOKUP,  INQUIR,  WHEN,  etc should be mentioned here)"

*PEEK*,  should at least be updated there  :)

Mike

**Comment by eswenson1** [comment]
Yeah. I'm writing some updated INFO files and noticed those placeholder sections. I'll try to write some of these up.  Ideally, we should make sure that all important ITS TS programs get documented in INFO.

**Comment by larsbrinkhoff** [comment]
This seems resolved.
