### ISSUE TITLE
webser document (directory)

### ISSUE THREAD

**Issue by mstram** [PDP-10/its#1541]
I ran the 'make webser' file with xfile, the server is running.

Where is it getting the "home page" from ?

Looking through the source code it looks like it reads the command line for the document file path.

I haven't found how the program ( device ; tcp syn120) gets loaded.

I assume it's somehow automatic, as I didn't launch it  intentionally ?

**Comment by larsbrinkhoff** [comment]
It will serve files as specified by the URL you give it.  E.g. `http://foobar/SYSTEM;ITS >` should get you the ITS source code if your PDP-10 emulator is `foobar`.  This will only work with the KLH10 emulator for now.

DEVICE; TCP SYN120 is loaded whenever someone opens port 80.
