### ISSUE TITLE
ITS at Vintage Computer Festival Pacific North West

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#1555]
Hello,

I'm posting this to GitHub to let everyone know about the VCF PNW event.  It's held at the Living Computers Museum in Seattle.  They have the former AI KS10 running ITS, and I'll do a presentation about ITS.  Details are here:

http://vcfed.org/vcf-pnw

They also have the MC KL10 in storage.  I will demo simulators running ITS, 11LOGO, Dazzle Dart, Spacewar, etc.

CC @david-moon, @taa01776, @jh95468, @cbf9427, @ms0, @GuySteele, @gregt590, @kaleberg

**Comment by Alexey-Slyusar** [comment]
Great event, Lars! I wish you and other ITS folks the best on the Festival and look forward for video and photo from the event. Amazing KS10/KL10 machines, the presentation, social part - all these are interesting to see at photo and video.
And please, let me know if I can help / do something useful regarding Logo part of the presentation.

**Comment by aloofschipperke** [comment]
Lars, I'll be driving up from the Portland area.

**Comment by larsbrinkhoff** [comment]
Great, see you there!

I also want to point out that this is the latest incarnation of an ITS mailing list:
http://its.victor.se/mailman/listinfo/its-hackers_its.victor.se

As far as I understand ITS-LOVERS at MIT no longer works.
