### ISSUE TITLE
Adding links

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#156]
Now that DUMP is fixed, there's nothing stopping us from adding links by putting them on, say, the sources tape.  This may or may not be more convenient than adding them in the build script.  @eswenson1, what do you think?

**Comment by larsbrinkhoff** [comment]
I already added these before:

bin/sys2/ts.emacs -> EMACS; TS >  
bin/sys/atsign.hactrn -> SYS; ATSIGN DDT  
bin/emacs/emacs.:ej -> EMACS; [PURE] >  
bin/emacs/purify.:ej -> EMACS; [PRFY] >  
src/sysen1/system.999999 -> SYSENG; SYSTEM >

**Comment by eswenson1** [comment]
I'd be ok with doing this. One thing I like about the explicit :LINK commands in the build.tcl is that, well, they are explicitly spelled out in the script -- i.e. more visible.  On the other hand, this is artificial, given that the presence of absence of files is implicit (since they come from the tape). I guess there is no reason we shouldn't treat links just like files -- in other words, have them come from the tape.

**Comment by larsbrinkhoff** [comment]
Thans for the input.  I'm not sure which way is better.  I think the links add clutter to the build script.  On the other hand, it's good to document which programs need which links.  But this could be done somewere else.

Also, I'm not fond of the 999999 links.  I'd much rather fix the .INSRTs.

**Comment by eswenson1** [comment]
Regarding the .INSRTs, I agree. However, I think we should first duplicate PI and then start working on tickets cleaning things up.

I'm happy with using the tapes to drop down links.  I actually think it would be nice to document "how to build and install" each of the components. But this could be in a document.  I think some facts that might be nice to collect are:  the set of all source files needed, where the binaries go, where the TS executables go, what links need to be where, and what data files or other dependencies each component has. If you're game, we could create some .md document and start populating it when we add new components, and as time allows, backfill it with all the info for components we've already built.

**Comment by larsbrinkhoff** [comment]
Good idea!  It's a bit of extra work, but we don't shy away from that, do we? ;-)

**Comment by larsbrinkhoff** [comment]
Closing this for now.  Anyone wanting to work on this, feel free to reopen or create new issue.
