### ISSUE TITLE
RG interview

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#1578]
Some last minute random ideas for the RG interview later today.

Show some programs:

- MacHack
- 340 display: Pornism, Gas.
- 11SIM
- Logo
- MLIFE
- Dazzle Dart
- Muddle

Pictures???

- Use of down arrow in TECO.

Other topics:

- TECO use of lights.
- PDP-10 switches without debouncing.
- Alan Snyder: C.
- Daniel Silver: Flight sim, robot arm.
- Maze War.
- Sylvania tablet.
- ARDS
- GE Bag-biters, Datanet 760.
- CONS: how did it evolve, what happened to it?
- 340D: Datapoint emulator on PDP-6.

**Comment by larsbrinkhoff** [comment]
- Robot console (ties back to tablet).
- Morse code broadcast device.
- Color scope.
- Vidissectors.  TVA, TVB, TVC.  BAT.

**Comment by larsbrinkhoff** [comment]
From @atsampson:

- One thing I'd ask is about tips and tricks for using the AI lab environment. If you had a new person, what cool stuff would you show them to make their life easier?

**Comment by larsbrinkhoff** [comment]
What I already heard the previous days:

- The PDP-10 didn't run timesharing until it was fitted with paging hardware.  This was a bit of a surprise for me, but it sounds plausible.  If the PDP-10 arrived in 1967-68 and didn't work properly for a year due to problems with the switches, we could be well into 1969.  And we have document about the pager from early 1970.

**Comment by aap** [comment]
Some more, in parentheses are questions we already (mostly) know about:

* (story about driving out to DEC while the PDP-6 was being built)

* (trading in the PDP-1 for the 6 and porting TECO over the weekend)

* what makes the PDP-6 or 10 a nice machine?

* how did timesharing come to the 6?

* how did the Knight TV system come about?

* CONS and CADR manual has examples of pdp-11 and IBM 1130 emulation. Was that just an example or was there actual non-lispm code running on those?

* his take on LMI vs. Symbolics

**Comment by larsbrinkhoff** [comment]
That reminds me.

- (Porting MIDAS to PDP-1 over a weekend.)

**Comment by larsbrinkhoff** [comment]
I added TK's answer about the origin of the TV system in #279, but yes, good to hear the RG side.

**Comment by larsbrinkhoff** [comment]
RG says CTSS was in a very early stage at 1961 and not actually usable until around 1963.

**Comment by rcornwell** [comment]
Sounds about right. Ask him if he knows how CTSS stored the system source... I.e. what accounts they were in? Might also let him know CTSS still lives.

**Comment by larsbrinkhoff** [comment]
TK made a kind of a prototype before the full timesharing ITS.

**Comment by larsbrinkhoff** [comment]
TJ6 typesetting software.  6 as in version, or PDP-6?

**Comment by larsbrinkhoff** [comment]
PDP-6.

**Comment by larsbrinkhoff** [comment]
(Sylvania) tablet was unreliable and not used much.

**Comment by larsbrinkhoff** [comment]
RG says they attempted to use ARDS terminals for Logo, but they weren't good enough for that.

**Comment by larsbrinkhoff** [comment]
https://toobnix.org/videos/watch/913dfa1b-1e69-4be6-9b54-6d368c1be7e3
