### ISSUE TITLE
Swordfish movie

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#1579]
From [the script](http://www.dailyscript.com/scripts/swordfish.pdf):

> The screen shows the MIT University logo.  Then "ACCESS DENIED."  His fingers work the keyboard.
> 
> INT. MIT BASEMENT - NIGHT
> 
> As he talks, we TRACK DOWN an old, concrete stairwell and down a long, dank hallway.
> 
> *"My senior year at M.I.T., I created the source code for the worm that I've been using for years."*
> 
> We TRACK AROUND a corner.
> 
> *"In the basement and through a file room is the only P.D.P.-10 still active and on the internet, although only a few people know this.  It's an I.T.S. machine and kept online just for historical sake."*
> 
> We DOLLY INTO a CLOSEUP ON a large, ominous, dark mainframe.
> 
> CLOSEUP ON STANLEY'S FINGER
> 
> hitting a key.
> 
> ANGLE ON PDP-10
> 
> as it HUMS TO LIFE.

**Comment by larsbrinkhoff** [comment]
Executive producer: Bruce *Berman*.  Coincidence?

**Comment by larsbrinkhoff** [comment]
Someone claimed the scene was changed to have ITS located at Caltech because one of the actors went there.

CC @bictorv, you asked why here: https://its.victor.se/wiki/setup

**Comment by bictorv** [comment]
Aha! Do you know who claimed that? Or which actor?

**Comment by larsbrinkhoff** [comment]
Yes, it's the person behind https://www.orinrin.land/

He doesn't remember which actor, or were he heard or read it.

**Comment by bictorv** [comment]
Ah, I "know" him.

**Comment by larsbrinkhoff** [comment]
Still no word from Skip Woods.

Here's the good part.  https://www.youtube.com/watch?v=gpegWPoSIEY

**Comment by larsbrinkhoff** [comment]
![swordfish1](https://user-images.githubusercontent.com/775050/65630843-79bdfb80-dfd6-11e9-85ff-4c3ad28dcf95.png)
![swordfish2](https://user-images.githubusercontent.com/775050/65630850-7e82af80-dfd6-11e9-8adf-efe77590f643.png)
