### ISSUE TITLE
KS10 TV-11

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#1580]
@SMJ suggesting making a Knight TV system for the KS10.  @aap and I explained it would be a lot of work.

**Comment by larsbrinkhoff** [comment]
For this to make sense, it would have to look the same as the Knight TV to user level applications:

- It should be possible to map frame buffers into PDP-10 memory.
- Some hardware registers should be visible.

We probably don't want to write new TV-11 software from scratch, so that implies a a PDP-11/20 class computer should be involved to run the code.  It doesn't necessarily have to be  a real vintage PDP-11; it could be an FPGA, or a software simulator.

We should consider whether it's better to make a rather faithful replica of the frame buffer and video switch hardware, or make a new design and adapt the TV-11 software.

KS hardware resources available are:

- A "free" Unibus adator.  The KS10 can adress four Unibuses.  Two are alreay in use, one is free to use, and the fourth isn't electrically hooked up to anything.  This is according to my understanding, and may be wrong.
- 20 bit physical addressing.  The KS10 comes with 512K memory, but is expandable to 1024K.

So it looks like it would not be impossible to make something similar to the Rubin 10-11 interface.  Hook up a PDP-11 to the third UBA.

There is some flexibility in the ITS (monitor) implementation.  We would not be constrained to emulate the Rubin 10-11 exactly.

**Comment by larsbrinkhoff** [comment]
Maybe something similar to the Massbus Disk Emulator, or Unibone could be used?

**Comment by larsbrinkhoff** [comment]
@aap's Knight TV resurrection article is interesting:  
http://pdp-6.net/knight-tv/knight-tv.html

**Comment by larsbrinkhoff** [comment]
A completely different solution to have graphical terminals for ITS, would be to focus on SUPDUP graphics instead.  This doesn't need any hardware changes at all.  However, all interesting applications would have to be updated to use SUPDUP graphics instead of, or in addition to the TV display.

**Comment by atsampson** [comment]
I've wondered in the past whether there are any real Unibus framebuffer devices that would be usable in a KS10, given constraints of power and the weirdness of the Unibus interface adaptor.

**Comment by larsbrinkhoff** [comment]
I believe the Plasma Physics TV system used (a) Grinnell frame buffer(s).  I don't know if there was just one, or more.  Some searching revealed the product name GMR274.  I also see RAMTEK 9050 and 9400.

At the very least, there would have to be some bit twiddling interface if 32-bit frame buffer words are to appear left aligned in 36-bit PDP-10 words.

**Comment by larsbrinkhoff** [comment]
If new frame buffers were made, it would add a certain flair if they used Intel 1103 chips.  How's the supply these days?
