### ISSUE TITLE
CALICO

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#1586]
Some kind of DM software.

**Comment by larsbrinkhoff** [comment]
ARPANET information for MIT-DMS:

> SUBSYSTEM PROMPT CHARACTERS =
> * for DDT (normal top-level), MIDAS
> @ for CALICO, BATCH, IMLOAD

**Comment by larsbrinkhoff** [comment]
DMCG memo SYS.11.21, "Using MDL's Calico User Interface", Edward H. Black, 1976

**Comment by larsbrinkhoff** [comment]
https://jxself.org/LCSTR294Lebling.pdf

> COMBAT'S user interface is patterned after, though not identical to, a CALICO interface

**Comment by larsbrinkhoff** [comment]
@jh95468 wrote:
> Another OS project was to put in mechanisms for assuring the integrity of files across crashes.  Much of our work depended on having what you would now call a shared database that endured in a multi-user
environment.  This was before techniques such as Relational Databases, Two-phase Commit, the understanding of "ACID" properties, and database technology in general had appeared.  So we effectively built our own multi-user shared database system as a part of Calico.  But we didn't realize it was a "database".

**Comment by larsbrinkhoff** [comment]
From [Project MAC Progress Report IX, 1971-1972](https://ban.ai/multics/doc/MAC-PR-09-756689.pdf):

> "The CALICO World" is a system of programs intended to provide users with convenient ways of carrying out most of the basic information-processing tasks that arise frequently in interactive computing and, at the same time, with proven and documented building blocks for use in the contsructing application programs.  "CALICO" is derived from the names of three of its main subsystems: the call-and-return mediator CARE, the library LIB, and the command interpreter COIN.  Most of CALICO has been prepared in the assembly language MIDAS. it is consistent with a subset of PL/1. it emphasizes a small set of data types and structures compatible with those of MUDDLE but admits a wider range, laying down conventions and procedures for registering data types and structures. It defines several classes of subroutines and a preferred calling-and-returning sequence format, but it is hospitable to subroutines written in any language if they have been translated into loadable, callable, and executable PDP-10 code.
> 
> CALICO subsumes a set of facility programs and a library of modular subprograms. The facility programs handle the functions shown in Fig. 2. The library consists of about 500 subroutines (callable entries), each with documentation available (but vide infra) on-line through the consoles as well as in print-out form in files near the consoles Most of the effort of the two-and-a-half groups has go-ie into CALICO, and it must be said at the present time to be the main part of the Dynamic Modeling System created by the effort.

**Comment by larsbrinkhoff** [comment]
SYS.11.21 found.  It's a 2000-line text file.

**Comment by larsbrinkhoff** [comment]
The [earliest preserved DIRED](https://github.com/PDP-10/its-vault/blob/master/files/syseng/dired.mdl121) seems to link with CARE.  The code .INSRTs a file from CAREDL.  Unfortunately I can't find any CAREDL or even CARE in any backup records.

```
CARESW==0       ; this switch controls whether the resulting
                ; DIRED will work under CARE.  Zero implies a
                ; MONIT version, one a CARE version.
```

```
; HERE ARE DEFINITIONS FOR WHEN WE ARE IN "CARE" MODE

IFN CARESW,[
ALLMAC==0
.SWACS==1
.SWEXT==1
.SWHDR==1
.SWSTK==1
.INSRT DSK:CAREDL;MACRO TS

EXTERN  [RDFLNM SCNAME RCMD SCMD RDSDIR]
EXTERN  [TYO TYI OPEN IOT CLOSE LINAOU LINACR AFRET AFREE]
EXTERN  [ARCA,ARCI,ARCE,ARCD,ARCL]
STACK   [PRTF,PRTF1,PRTF2,USRSAV,SCDEV,SCN1,SCN2,SCUSR,COMPTR,COMMND] M
.GLOBA OASC OASCR OSIX
]
```

This is the entry point in "CARE mode".  Apparenly macros take care (no pun intended) of some boilerplate code.

```
IFN CARESW,[
MAKPRO  ACS,[A,B,C,D,E,F,G,H,I,J,K,L,M]
ENTRY   [DIRED]
ISR     DIRED
START:  STOACS  ACS
]
```

**Comment by jh95468** [comment]
Nice find.   PDL (who wrote DIRED) might remember more.

IIRC, CARE stood for "CAll and REturn", and defined a convention for how one routine would call another.   I don't recall the details, but it included rules like which register was the stack pointer, which registers to push/pop, where the results were passed back, and how to indicate success or failure when returning to the caller (e.g., return to PC+1 on fail, PC+2 on success.  

So, as a convention, I don't think you "linked with" CARE.  It wasn't a separate package of code (IIRC).  But if your program followed CARE conventions, it was straightforward to call and return from any other routine in other packages that followed CARE.   The macros made it easy to follow the conventions, by emitting the proper instruction sequences for calling other routines and returning.

Looking back, CARE et al was a very early mechanism for organizing a collection of programs into a "library" of modular routines and data structures somewhat similar to what appeared later as "object oriented" systems.
