### ISSUE TITLE
Old INFO

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#1596]
I took a look at an ancient 1971 version of [SYSENG; INFO 35](https://github.com/PDP-10/its-vault/blob/master/files/syseng/info.35).  I expected the pre-EMACS versions of INFO to be essentially an assembly language version of the later EMACS-based INFO.  But INFO 35 is much simpler, and a little puzzling.

I haven't tested it yet, but its basic function seems to be to display files from the .INFO. directory.  In addition to INFO files (fn2=INFO, no special formatting), it can also display RECENT and ORDER files.

The thing that puzzles me is the "SIMUL" command.  Is it simulating something?  The function is to load and run a file called .INFO.; *FOO* PROG.  What on earth is this?

**Comment by larsbrinkhoff** [comment]
For example, typing `X◊D` or `X^P` will display the file .INFO.; X INFO.  `DIR◊I` displays .INFO. DIR ORDER. 
 Just `CC` and CR displays .INFO.; CC RECENT.

**Comment by larsbrinkhoff** [comment]
I put a little "hello world" program in .INFO.; TEST PROG and typed `TEST◊S`.  INFO seemed satisfied and replied "END OF SIMULATION".

**Comment by larsbrinkhoff** [comment]
Fascinatingly, the SIMUL command creates an inferior job and primes it with code to load and run an SBLK file instead of using .CALL LOAD.

**Comment by larsbrinkhoff** [comment]
There's some bitrot: `.ACCESS DSKC,43` should be `.ACCESS DSKC,[43]` to work with current ITS.

"ITS 1.5 Reference Manual" from 1969 documents .ACCESS as setting the access pointer from the effective address of the .ACCESS UUO.  The latest version of SYSDOC; UUOS has the access pointer taken from the location at the effective address.  I believe ITS 724 from 1972 implements the latter behaviour.

**Comment by larsbrinkhoff** [comment]
@bawden, this GitHub issue has some information about the archaic pre-EMACS INFO program.

**Comment by larsbrinkhoff** [comment]
Evidence suggests the EMACS-based INFO replaced the older program around 1976-1977, which is consistent with [Alan Bawden's recollection](https://en.wikipedia.org/wiki/Talk:Incompatible_Timesharing_System#INFO_predates_does_not_predate_EMACS).

| Filename | Dating
| --- | ---
| SYSENG; INFO 33 | No timestamp; backed up April 1971
| SYSENG; INFO 35 | 1971-10-29
| SYSENG; INFO 36 | 1975-09-15
| SYSENG; INFO 40 | 1976-04-17 (last pre-EMACS version)
| EMACS; INFO :EJ | 1977-03-24 (first EMACS-based version)
| EMACS1; INFO 88 | 1980-04-04 (first source file on record)

**Comment by larsbrinkhoff** [comment]
Here is the contents of the file .INFO.; INFO INFO.  I left out the tell-tale garbage at the end that is an indication it was originally stored on DECtape.

I was thinking the SIMUL command was a copy-paste leftover from another program, but here we see it as a documented part of INFO.

```
NOTE: "COMMAND" AS USED HEREIN REFERS TO A                                      
SYSTEM PROGRAM LOADABLE BY A ^K IN DDT. AS A
SPECIAL CASE, "DDT" IS ALSO A COMMAND.                                          

WHEN THE MESSAGE "--MORE--" APPEARS,                                            
TYPING A SPACE WILL CAUSE TYPEOUT
OF THE REMAINING INFORMATION; ANY OTHER                                         
CHARACTER WILL CAUSE TYPEOUT TO BE STOPPED.

XXX<CR> LIST RECENT CHANGES TO XXX COMMAND
XXX$A   ADD FOLLOWING TEXT STRING TO                                            
        XXX RECENT (TEXT ENDS WITH CTL C,
        CTL G WILL ABORT)
   ^B   OUTPUT INFORMATION FROM XXX$X
        COMMANDS TO LINE PRINTER
XXX$D   DESCRIBE XXX IN GENERAL
   ^D   COMPLEMENT 340 DISPLAY USAGE
        (INITIALLY ON FROM T00, T03)
XXX$E   LIST ERROR MESSAGES USED BY XXX                                         
   ^E   STOP OUTPUT TO LINE PRINTER
   ^F   LIST AVAILABLE INFO FILES                                               
XXX$I   LIST INSTRUCTIONS IN XXX
   ^Q   FLUSH PROGRAM ($^X.)                                                    
   ^R   RESET LPT BUFFER
XXX$S   SIMULATE XXX
   ^S   STOP TYPEOUT
   ^T   LIST COMMANDS
   ^Z   STOP SIMULATING
   ?    TYPE OUT THIS CRUFT

XXX MAY BE OMITTED; LAST VALUE USED.

**Comment by bawden** [comment]
Wow, I have no idea what this was!  This pre-dates me for sure.  Perhaps @david-moon remembers what this was?

**Comment by david-moon** [comment]
Alan wrote: 
> Perhaps @david-moon remembers what this was? 
I never saw that thing before in my life. 
--Dave

**Comment by larsbrinkhoff** [comment]
While very intresting, I don't think this program is appropriate for adding to this repository.  It certainly is for the OO ITS project: https://github.com/larsbrinkhoff/ooits

**Comment by larsbrinkhoff** [comment]
The memo SYS.00.00 "A Novice's Introduction to the Dynamic Modeling System" calls this OINFO:

> The  system program INFO provides structured access to files in the INFO directory  that  document  various  system  programs  and  ITS features.   Since  it is a fairly new  program, not many INFO files are yet available, but no doubt the list will grow.  If you want to try out INFO, it will tell you how to use it.   Meanwhile, much on-line documentation is accessible through INFO's predecessor OINFO.
> 
> The  system program  OINFO is not  in itself very  exciting, but it gives you easy  access to  a good deal  of information  -- none  of which  is guaranteed to  be up-to-date -- about  the System and its programs.  The information is kept in character-flavor files in the disk directory '.INFO.'.

>  At the appearance of  OINFO's prompt '*', you  can type a  command.  As  usual, the command '?' gives  you a list of available commands.  I'll just note the ones that are used most often, along with  their DDT  equivalents  and  English   meanings.    In  this  table   the substitutable  string 'foo' stands for the  name of either a system program or an ITS feature.
> 
> | OINFO |  DDT | English
> | --- | --- | ---
> | ^F | :LISTF DSK: .INFO.; | List available OINFO files.
> | foo ESC D | :PRINT foo INFO | Describe foo in general.
> | foo ESD I | :PRINT foo ORDER | List instructions (commands) for foo.
> | foo ESD E | :PRINT foo ERROR | List error messages used by foo.
> | foo CR | :PRINT foo RECENT | Describe recent changes to foo.
> | fn ESC ESC sn CR | :PRINT fn sn | Print whatever info is in the file.
> 
>  There  are also commands  for sending the  information to the line-printer, and for prefixing new information to 'foo RECENT'.
> 
> The  oldest  OINFO  files  (and  the  program  itself)  were  taken unmodified  from the A.I. Lab ITS  system, and they may be obsolete or inapplicable.   On  the other  hand some  old OINFO  files  have become  part of our System documentation  and have been updated, so it's a mixed bag.   You can get updates to this document (if  there are any) from the file NOVICE RECENT.

**Comment by larsbrinkhoff** [comment]
Link to J. M. Winett's thesis "On-Line Documentation of the Compatible Time-Sharing System", which describes CTSS' INFO program.  I checked it, but I didn't see any similarity with the INFO in this issue.

https://apps.dtic.mil/sti/pdfs/AD0624110.pdf

**Comment by larsbrinkhoff** [comment]
Actually, one thing.  The CTSS INFO has a `D` command for "description", and ITS INFO has `$D`.
