### ISSUE TITLE
No .INFO. directory

### ISSUE THREAD

**Issue by eswenson1** [PDP-10/its#16]
The build should create the .INFO. directory and populate it with documentation as we're adding the corresponding commands and functionality to the system.

While there is a "doc" subdirectory of the source tree, and it is populated with various directories, including .INFO. and INFO, as well as other documentation directories, none of this content is making it into the build image.

**Comment by larsbrinkhoff** [comment]
Still not there?  I think I saw an `.INFO.` when I checked it in ITS.

The build log seems to say that the directory is created, but not with any files:
https://travis-ci.org/PDP-10/its/jobs/178403051#L1736

**Comment by larsbrinkhoff** [comment]
Testing with SIMH.  There is an `.INFO.` with the expected contents.

**Comment by larsbrinkhoff** [comment]
Tested with KLH10, and `.INFO.` seems good.

This is using latest `master`, commit 95d3233e007175261387ca111397b5ebda36bcbc "Include documentation in the sources tape."

**Comment by larsbrinkhoff** [comment]
Be sure to `make clean` first.

**Comment by larsbrinkhoff** [comment]
Fixed now.
