### ISSUE TITLE
Some ARDS files at bin/-pics- do show errors when displayed with "tek4010 -ARDS"

### ISSUE THREAD

**Issue by rricharz** [PDP-10/its#1604]
Examples:
  chain.pic
  3d.pic

I have looked through the ARDS decoder code and do not believe that there is a trivial error there. Could it be that the data has errors?

**Comment by larsbrinkhoff** [comment]
They work with three other decoders, so I'm inclined to believe they are fine.

The files may not work as is when you take them from this repository and feed them to Tek4010.  The files are encoded specially for transfer to ITS.  Plain text files will be OK, but binary files and some control characters will receive special treatment.

**Comment by rricharz** [comment]
I‘m not convinced that this is the problem. The ARDS files are text files, with bit 1-7 being ASCII, and bit 8 parity. The „binary“ data for the plots is just a special use of the ASCII codes, and should not interfere with any control characters. When I look at chain.pic, everything is fine, except a few vectors go in the opposite direction of where they should go. Are you sure that this happens only with tek4010? There does not appear to be an additional byte, or a missing byte.

**Comment by larsbrinkhoff** [comment]
Here is ITS' Knight TV rendition:
![chain](https://user-images.githubusercontent.com/775050/57198002-3357f980-6f6e-11e9-9a44-00c724d5dc9b.png)

A Maclisp program translated it to SVG:  
http://up.update.uu.se/DSK%3A-PICS-%3BCHAIN%20SVG

**Comment by rricharz** [comment]
OK. I think you can close this issue and I open it as a bug in tek4010.

**Comment by larsbrinkhoff** [comment]
Problem found.  A byte 315 in the file as stored in Unix, is decoded to be the two bytes 177 115 on ITS.

So the files are not bad, and the ARDS decoder is not at fault.
