### ISSUE TITLE
Patch to work around problem in expect or possibly SIMH

### ISSUE THREAD

**Issue by dpeschel** [PDP-10/its#1611]
At one point, misc.tcl sends an ASCII null to ITS. (STINKR uses the null as a command.) On my Mac, with SIMH, STINKR never receives the null, and expect times out and quits. (Note SIMH is still running.) Sending two nulls in a row fixes the problem; STINKR receives one.

Unfortunately I am not sure yet what causes this behavior, or if the double null could be bad in some configurations. I haven't managed to build sims or klh10 to compare with SIMH yet, for one thing. And the single null might work with SIMH for other people. Therefore I propose the attached patch which uses the ITS ^_ feature instead. I have tested it with SIMH (and therefore ASCII, not SUPDUP or TV-11 input).

**Comment by dpeschel** [comment]
[misc.tcl-patch.txt](https://github.com/PDP-10/its/files/3200088/misc.tcl-patch.txt)

**Comment by larsbrinkhoff** [comment]
Thank you.  We had this problem with some BSD too.  CC @aap.

Your workaround is good.  Is there any chance you can submit a pull request?

**Comment by dpeschel** [comment]
Certainly. Since I assume I don't have write access and so I need to create a branch, do you have a branch naming convention? e.g. user/dpeschel Thanks, I am still new to the intricacies of github.

**Comment by larsbrinkhoff** [comment]
You do have write access, as is befitting of the ITS philosophy.  You can create a branch in this repository, and I'd suggest the name "dpeschel/null" or similar.

**Comment by larsbrinkhoff** [comment]
@turbo wrote:
> I haven't gotten ITS to build even in BASICS mode on BSD (lot's of small differences need to be corrected and compile switches created in some of the submodules). I'll try again if I have some more time.

I believe the patch in this issue should fix one of the problems.

**Comment by turbo** [comment]
@larsbrinkhoff That wasn't was I was running into. Expect worked just fine for me after being installed, rather, GCC compilation of certain C files failed. I'm using `gmake` and `tcl-expect` from `pkgin` (since the Makefiles are GNU). I'll try to get a log for you soon and will open an issue. Thanks for looking into this.

**Comment by turbo** [comment]
Misc is also not built in basis mode AFAICT: https://github.com/PDP-10/its/blob/master/build/build.tcl#L149

**Comment by larsbrinkhoff** [comment]
Ok, it's yet another problem.

**Comment by dpeschel** [comment]
[https://github.com/PDP-10/its/pull/1612](url)
