### ISSUE TITLE
CStacy's book about ITS

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#1636]
Hello @cstacy,

> If you want to learn more about ITS and the surrounding history, watch for my upcoming book.  The material in the above message is Copyright 2004 Christopher Stacy.

Did ever something become of this?

https://groups.google.com/forum/#!original/alt.sys.pdp10/0b0MZ-5tfzc/ryir8SKaCJMJ

**Comment by ams** [comment]
What was the answer, if any?

**Comment by larsbrinkhoff** [comment]
There was no answer.

**Comment by cstacy** [comment]
I still have some notes and outlines somewhere, and would
probably be interested in collaborating.    I am unfortunately
in very poor health these days and have lost most of my
eyesight.  So I can't produce as quickly as I used to.

What target audience are you interested in, and what
kind of publication (paper book?) are you thinking of?

**Comment by larsbrinkhoff** [comment]
Thank's for getting back on this.  And sorry to hear about your health!

What I have in mind would be perhaps an expanded version of this:  
https://github.com/larsbrinkhoff/its-presentation/blob/master/PITCHME.md

It's mostly a historical overview of ITS' development from around 1965 to 1988.  I sometimes branch off into tangents about Lisp, AI, Logo, Emacs, Zork, Arpanet, etc.  It's light on technical details but does throw around names for machines and programs.  I imagine the audience would mostly be programmers, or people interested in the history of technology.
