### ISSUE TITLE
Systems Concepts DC-10

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#1641]
I'm adding a simulation of the Systems Concepts DC-10 disk controller to @rcornwell's KA10.

According to ITS, disk packs are 406 cylinders and 20 surfaces.  The track format is software defined; ITS stores two 1028-word blocks per track.  I have seen various references to IBM 2311, 2314, and Calcomp drives.

The controller has two device numbers, 610 and 614, and is programmed with channel programs.

**Comment by larsbrinkhoff** [comment]
Some more information here: https://github.com/rcornwell/sims/issues/116

**Comment by larsbrinkhoff** [comment]
AI memo 161A says the PDP-6 had 2311 drives.

It seems the PDP-10 at some point had Memorex 2314-compatible drives.  They were upgraded to Calcomp dual density drives.

**Comment by larsbrinkhoff** [comment]
Hello @davidgiven,

I listened to your VCF presentation and it was interesting to hear about FM and MFM encoding.  I  hope you don't mind a question related to this.

I have studied the software used to format disks using a one-off disk controller for MIT's AI PDP-10.  The program to format a disk track looks at two data bits at a time and encodes them into three bits that are written to the disk.  However, if the first two bits are 00, it considers the next two bits as well:

| Input | Output
| --- | ---
| 00 00 | 010 101
| 00 01 | 010 111
| 00 10 | 110 101
| 00 11 | 110 111
| 01 | 011
| 10 | 101
| 11 | 111

Do you recognize this as some version of MFM encoding, or anything else you know of?

There is more information in https://github.com/rcornwell/sims/pull/116, including gaps, sector headers, etc.

**Comment by davidgiven** [comment]
This looks like a variant of (1,7) RLL encoding (he says after looking it up on Wikipedia): https://en.wikipedia.org/wiki/Run-length_limited However the actual bits used are different.

I haven't seen RLL used for floppy drives. MFM still beats it --- MFM encodes one bit per interval while this implements 3/2 bits per interval. I vaguely remember reformatting old hard drives from RLL to MFM to get more storage...

**Comment by larsbrinkhoff** [comment]
Thank you.  It certainly looks very much like (1,7) RLL, except the encoding rules are quite different:

**Original**: (x, y) becomes (NOT x, x AND y, NOT y), except (x, 0, 0, y) becomes (NOT x, x AND y, NOT y, 0, 0, 0).  
**Systems Concepts**: (x, y) becomes (x, y, 1), except (0, 0, x, y) becomes (x, 1, 0, 1, y, 1).

Note, this is not for floppies but removable disk packs from around 1970.
