### ISSUE TITLE
RH10 -> RP06 Support

### ISSUE THREAD

**Issue by eswenson1** [PDP-10/its#1648]
I added conditionalization to SYSTEM; RH10 > to support either the existing RP04 geometry or RP06 geometry.  I then built DDT, SALV, ITS, and DSKDMP with this support.  I created a MAGDMP tape with magdmp.bin (unchanged), xddt bin, and xsalv bin.  

I booted MAGDMP, loaded ddt and xsalv, and ran MARK$G.  SALV hung after the PACK NO = prompt.  Since no ddt disk code should have been executed here, and only SALV code, and my SALV config was identical to that of pdp10-kl -- except for the RHRP06==1 setting that selected the RP06 geomery, I'm wondering if there is something in the RH10 support that would not accommodate this geometry (from my updated RH10 >):
```
;DISK PHYSICAL PARAMETERS (RH10 CONTROLLER)

IFE RHRP06 [
DEFSYM  NCYLS==406.             ;# CYLINDERS NORMALLY USED (RP04)
DEFSYM  XCYLS==411.-NCYLS       ;# CYLINDERS FOR SPARES, HACKS, ETC.
DEFSYM  NHEDS==19.              ;# TRACKS/CYLINDER
DEFSYM  NSECS==20.              ;# SECTORS/TRACK
DEFSYM  SECBLK==8               ;# SECTORS/BLOCK
]
IFN RHRP06 [
DEFSYM  NCYLS==812.             ; # CYLINDERS NORMALLY USED (RP06)
DEFSYM  XCYLS==815.-NCYLS       ; # EXTRA CYLINDERS FOR SPARES, HACKS, ETC.
DEFSYM  NHEDS==19.              ; # TRACKS/CYLINDER
DEFSYM  NSECS==20.              ; # SECTORS/TRK
DEFSYM  SECBLK==8               ; # SECTORS/BLOCK
]
DEFSYM  NBLKSC==NHEDS*NSECS/SECBLK ;# BLOCKS/CYLINDER
DEFSYM  NBLKS==NCYLS*NBLKSC     ;# BLOCKS NORMALLY USED
DEFSYM  XBLKS==XCYLS*NBLKSC     ;# BLOCKS FOR HACKS
DEFSYM  TBLKS==NBLKS+XBLKS      ;TOTAL BLOCKS
```
@rcornwell any ideas?

Note: it mattered not whether I used:
   DEFSYM  NTUTBL==2               ;2 BLOCKS PER TUT
or
  DEFSYM  NTUTBL==4               ; 4 BLOCKS PER TUT
Both caused the same hang.

**Comment by eswenson1** [comment]
Making no other changes, if I set RHRP06==0 (RP04 geometry), everything works fine.  So it is definition something with the RP06 geometry.

**Comment by eswenson1** [comment]
Well, there was this pesky "set rpa rp06" in my ka10 init file.  I'm sure it was put there by evil creatures since I last looked in there.  Changing it to "set rpa rp06" allowed me to format an RP06 pack with RH10/RP06 configured in SALV.

**Comment by eswenson1** [comment]
I was able to boot ITS with RH10/RP06 drives starting from the pdp10-kl build.

**Comment by larsbrinkhoff** [comment]
That's good to hear!

It looks like we could follow the example set by RH11 + RP06.  Move the RP04 geometry to a separate RH04 DEFS similar to RP06 DEFS.  Then have SYSTEM; DISK > insert RP04 DEFS or RP06 DEFS depending on RP04P and RP06P.
