### ISSUE TITLE
PDP-8 ITS

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#1655]
Fun idea: make a super tiny ITS for PDP-8.

**Comment by everyfan** [comment]
Why don't we port ITS to the Altair while we're at it :P

**Comment by larsbrinkhoff** [comment]
Maybe.  I wanted to target a small computer that had some flavour of the PDP-10.  For example, ITS makes pervasive use of skip instructions and skip returns.  A machine with a fixed instruction length is more amenable to this, which is why I consider typical 8-bit micros are not a good fit.

**Comment by larsbrinkhoff** [comment]
Maybe Nova?  CC @rcornwell

**Comment by turbo** [comment]
> why I consider typical 8-bit micros are not a good fit.

Unless one employs some brains to emulate it directly. Emulation wizard Dmitry Grinberg had [full-on Linux](https://dmitry.gr/?r=05.Projects&proj=07.%20Linux%20on%208bit) running on 8bit by writing a complete ARM emulator. I guess an ITS emulator should be easier :)

**Comment by larsbrinkhoff** [comment]
I think "Small ITS" is close to what I wanted: #1730.
