### ISSUE TITLE
DQX device doesn't work on pdp10-kl emulator (KA10s)

### ISSUE THREAD

**Issue by eswenson1** [PDP-10/its#1669]
The DQ device (actually DQX) code appears to rely on the KS10 or KL10 processors. It fails on KA10 (and presumably KI10) processors.
 
It uses the adjbp instruction, which apparently is not supported on KA10 and KI10 processors:
 
```
IBP Increment Byte Pointer

Increment the byte pointer at location E, setting the byte alignment to zero
if the incrementing crosses a word boundary, as explained above.
Notes. Giving this instruction code with bits 9-12 nonzero produces the
ADJBP instruction described at the end of the section. In the KIlO and
KAlO, only the IBP form is available and bits 9-12 are ignored (but should
be zero).
```
 
MIDAS is correctly setting the 9-12 bits to non-zero:
 
```qt.ptr+14/   IBP 1,2225   =133040002225```
 
but since these are ignored on KA10 processors, the instruction is being treated and IBP instruction rather than an ADJBP instruction.
 
This results in PTR requests failing. This causes COMSAT to fail. 
 
I think we need to either a) rewrite this in an processor agnostic manner or b) conditionally assemble this based on target processor.

**Comment by larsbrinkhoff** [comment]
ITS programs seem to mostly favour conditionals for this, but either way
is fine with me.

The C library also has/had this problem.  It used to have a code
sequence for converting a float to an integer.  It was patched to use
the KL/KS instruction FIX, supposedly after the KA10 machines went away.
Now we had to undo that patch.

I'm guessing the use of ADJBP was also introduced after the KA10 era.

**Comment by eswenson1** [comment]
Here is a fix for this problem:

```
*:srccom sysnet;dqxdev 41,^X42

;COMPARISON OF DSK:SYSNET;DQXDEV 41 AND DSK:SYSNET;DQXDEV 42
;OPTIONS ARE    /3

**** FILE DSK:SYSNET;DQXDEV 41, 8-16 (10161)
          adjbp a,[440700,,qname]       ; point at where trailer should be
**** FILE DSK:SYSNET;DQXDEV 42, 8-16 (10161)
;;;       adjbp a,[440700,,qname]       ; point at where trailer should be
          move t,[440700,,qname]
          ibp t
          sojg a, .-1
          move a,t
***************
```
