### ISSUE TITLE
Build pdp10-kl under RaspberryPI

### ISSUE THREAD

**Issue by TheFausap** [PDP-10/its#1672]
Hello,

I'm trying to build the pdp10-kl version under RaspberryPI.
A part the timeout problems I fixed modifying the expect jobs, the build stopped after MACLISP building, with this error message:

*SYS: SYS3; TS COLR - FILE NOT FOUND

It seems everything was fine before that... maybe am I missing something?

thanks
Fausto

**Comment by larsbrinkhoff** [comment]
Hello,

I have also tried to fix the timeout problems building on a Rasperry Pi, so I'm curious to see your changes.

As for TS COLR not found, this seems to be due to something trying to run `:colr`.  I can't see that it's part of the build scripts.

**Comment by TheFausap** [comment]
Hi Lars,
when I go back at home I'll post them here... but at the moment they very crude ones :-) But the biggest issue is dealing with tape operation, for those steps I used a timeout of 300000, but this depends also on the SD card speed... mine is quite slow!

About COLR, I cannot find, also, the source in SYS3. Is it generated in other way?

**Comment by larsbrinkhoff** [comment]
There is no COLR program in SYS3.  I don't think there's any COLR program at all.

The message usually appears when you try to start a program which doesn't exist in SYS, SYS1, SYS2, or SYS3.  Because ITS searches in that order, it will print a message that the program is missing from SYS3.

**Comment by TheFausap** [comment]
OK, I understood why I want to run COLR. Something is really messed up with expect during the LISP building, and running COMPLR... became COLR, basically MP disappear.
So I put some sleep commands between the several MIDAS steps and the problem disappeared.
After long, very long time, I found everything a little bit freezed at

```
(dump-it)
;Loading MLMAC 93
;Loading MACSYMA-SOURCE-FILES 73
;Loading DEFSTRUCT 280
(COMMAND-LOOP)
```
I suppose everything stopped during the night and in the morning I found still at this point.
I'm trying to disable completely the GUI and redo the entire process.

**Comment by TheFausap** [comment]
Again looking better at the output I found some problems related to the speed loading the several modules during macsyma building.
I put some sleep commands and I'm retrying right now.

**Comment by TheFausap** [comment]
Eventually, the build completed! :-) after setup other increased timeout for MUDDLE building.
But I'm experiencing the same booting issue described in the other issue, after I modified the run config.

**Comment by TheFausap** [comment]
ok. boot is working now, also under raspberry.
