### ISSUE TITLE
booting KL under Ubuntu 19.04 (virtualbox)

### ISSUE THREAD

**Issue by TheFausap** [PDP-10/its#1678]
Trying to boot KL version under Ubuntu 19.04.
The build is ok, but running start script it doesn't boot
On the screen I have only this:

`KA-10 Simulator V4.0-0 Current            git commit-id: 10110700`

even if I press ENTER, CTRL-E, CTRL-C, nothing happens.
I have to kill the process.

**Comment by larsbrinkhoff** [comment]
Please try starting `./tools/sims/BIN/pdp10-ka` manually and enter
the lines from `./build/pdp10-kl/run` one by one.

Maybe it's the very last `load` command that fails?

**Comment by TheFausap** [comment]
I found the problem: the dskdmp.rim is empty, for some reason.

**Comment by larsbrinkhoff** [comment]
It shouldn't be empty.  If you `checkout HEAD --
bin/kl10/boot/dskdmp.rim` does it become 6276 octets long?

**Comment by TheFausap** [comment]
I noticed you removed the rim file for pdp10-kl and load directly DDT (if you see the changes in the boot and boot2 files. Run has the rim instead... is it correct?

**Comment by TheFausap** [comment]
anyway there's no file in bin/kl10/boot called dskdmp.rim

**Comment by larsbrinkhoff** [comment]
Oh, right!  Sorry, I was looking at the wrong branch.

No, there shouldn't be any dskdmp.rim file any more.  I see I forgot to
update the `build/pdp10-kl/run` file.  It should do the same thing
`boot2` does: `load -i bin/kl10/boot/@.ddt` and then `go`.

Apologies, my mistake.

**Comment by TheFausap** [comment]
No problem at all.
Anyway I tried but it seems still not working...

```
KA-10 simulator V4.0-0 Current        git commit id: 10110700
sim> set console wru=034
sim> set cpu its
sim> set cpu 512k
sim> set pd off
sim> att rpa0 out/pdp10-kl/rp04.0
sim> att rpa1 out/pdp10-kl/rp04.1
sim> att rpa2 out/pdp10-kl/rp04.2
sim> load -i bin/kl10/boot/@.ddt
sim> go
```

after that, nothing happens.

**Comment by TheFausap** [comment]
ok... maybe I miss the point about manually startup.
If I do

```
$L ITS

$G
SALVAGER.315


KL ITS 1648 IN OPERATION
KL ITS 1648 SYSTEM JOB USING THIS CONSOLE.DECORIOLIS CLOCK HAS BEEN POWERED OFF!
, IF THE TIME
CANNOT BE DETERMINED FROM THE NETWORK, YOU MAY HAVE TO :PDSET
PDTIME OFFSET, NOT ON DISK.
PLEASE SETLOC APPROPRIATELY.
 LOGIN  TARAKA 0
TARAKA NETIME IOTLSR


                              Attention!

                              Attention!

The time could not be set because:
No host responded.
It will be necessary for someone to set the time
manually by logging in and running :PDSET.

TOP LEVEL INTERRUPT 200 DETACHED JOB # 3, USR:TARAKA CNAVRL

KL ITS 1648 SYSTEM JOB USING THIS CONSOLE.

```

and now I have to run PDSET, I suppose.

**Comment by eswenson1** [comment]
Type “./“ followed by ENTER. Do you get DDT output?

If so, you are at DDT, and must type:

 $l its
 $g

**Comment by eswenson1** [comment]
Yup. First time you’ll have to run PDSET. Make sure your “run” script has enabled the clock, otherwise your PDSET will not be persistent.

**Comment by TheFausap** [comment]
Thanks @eswenson1 . Anyway even if I put "set pd on" in my config, I have the same message at boot

`DECORIOLIS CLOCK HAS BEEN POWERED OFF!`

Is this expected?

**Comment by TheFausap** [comment]
ok... it's not `set pd on`, but `set pd ena`

**Comment by larsbrinkhoff** [comment]
#1639 adds some fixes for this issue.

**Comment by TheFausap** [comment]
@larsbrinkhoff please can you update the timeout in the file include.tcl for KL10, to a bigger value like 30000? The disk formatting under raspberry is very very slow

**Comment by larsbrinkhoff** [comment]
I'm making some updates for building on rPi, but I'd prefer not to raise
the default timeout value for all actions.  You can see my changes in
#1613 and the lars/rpi branch.

**Comment by TheFausap** [comment]
ok, right. I can use that branch... so I can test it also on my PI.

**Comment by larsbrinkhoff** [comment]
FYI, I have built ITS on an rPi4 with the file system on a USB 3 memory.  It didn't need any changes to the timeouts.  I'm not sure if this is because of the faster processor, or the faster file system.  But from what I hear, running off an SD card is quite slow.

**Comment by TheFausap** [comment]
Maybe both. For sure, SD card is very very slow, you should use fast SD cards more expensive than the rPi :)

**Comment by larsbrinkhoff** [comment]
I got a cheap SD card and a higher end USB drive.

**Comment by TheFausap** [comment]
I have only a cheap SD card and rPi3B+. So I have to try booting from USB3, maybe also with rPi3 the standard timeouts are ok.

**Comment by larsbrinkhoff** [comment]
I'm still working on this: #1613, but it has been a while since I made any update.  Sorry about that.  Still, it does all the important parts on an rPiB with slow SD card.
