### ISSUE TITLE
Old versions of Maclisp

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#1679]
As per LISP; -READ- -THIS-, file names beginning with B are binaries.

The version numbers sometimes seem inconsistent.  I'm not sure all of these are Maclisp.  BIB means Bibop.

| File | Version | Timestamp | Type
| --- | --- | --- | --- 
| JONL;VRYOLD LISP | | 1968-01-01 | Binary
| JONL;OLD LISP | | - | Binary
| SYSENG; LISP 131 | 131 | 1970-12-07 | Database
| LISP;LISP 218 | 218 | 1971-07-16 | Database
| LISP;LISP 220 | 220 | 1971-07-26 | Database
| LISP;LISP 225 | 225 | 1971-08-03 | Database
| LISP;LISP 226 | 226 | 1971-08-06 | Database
| LISP;LISP 228 | 228 | 1971-08-14 | Database
| LISP;LISP 229 | 229 | 1971-08-16 | Database
| BACKUP;BLISP 131E | 131 | 1971-08-25 | Binary
| LISP;LISP 236 | 236 | 1971-08-28 | Database
| LISP;LISP 238 | 238 | 1971-09-01 | Database
| LISP;LISP 239 | 239 | 1971-09-02 | Database
| LISP;LISP 262 | 262 | 1972-02-28 | Source
| BACKUP;BBLISP 229KE | 229 | 1972-03-17 | Binary
| BACKUP;BLISP 229KE | 229 | 1972-03-17 | Binary
| SYSENG;LISP 229KE | 229 | 1972-04-19 | Database
| SYSENG;LISP 229Y | 229 | 1972-04-19 | Database
| BACKUP;BBLISP 229Y | 229 | 1972-04-19 | Binary
| SYS;TS NLISP | 262 | 1972-08-24 | Binary
| LISP;LISP 229CY | 229 | 1973-02-11 | Source
| LISP;BBLISP 229CY | 229 | 1973-02-12 | Binary
| LISP;LISP 229DB | 229 | 1973-02-15 | Source
| LISP;LISP 229DC | 229 | 1973-02-25 | Source
| SYS;TS LISP | 229 | 1973-02-26 | Binary
| LISP;BBLISP 229DC | 229 | 1973-02-27 | Binary
| LISP;LISP 277 | 277 | 1973-03-01 | Source
| LISP;LISP 229EF | 229 | 1973-06-05 | Source
| LISP;BBLISP 378NIO | 378 | 1973-06-06 | Binary
| LISP;LISP 386 | 386 | 1973-06-11 | Source
| LISP;BBLISP 229EF | 229 | 1973-06-11 | Binary
| LISP;LISP 388 | 388 | 1973-06-12 | Source
| LISP;LISP 390 | 390 | 1973-06-12 | Source
| LISP;LISP 392 | 392 | 1973-06-12 | Source
| SYS;TS LISP | 229 | 1973-06-12 | Binary
| LISP;BBLISP 382 | 382 | 1973-06-12 | Binary
| LISP;BBLISP 391BIB | 391 | 1973-06-12 | Binary
| SYS;TS OLISP | 229 | 1973-05-10 | Binary
| SYS;TS OOLISP | 229 | 1973-08-04 | Binary

**Comment by larsbrinkhoff** [comment]
Note, binary file has version at location LDFNM2.

**Comment by larsbrinkhoff** [comment]
Old compiler versions to go along with the old interpreter:

- JONL; TS COMPLR, 1973-02-09
- JONL; TS OCOMPL, 1973-01-15
- JONL; TSCOMP 226, 1972-03-19
- JONL; TSCOMP 275, 1972-10-6
- SYS; TS NCOMPL, 1976-11-3
- SYS; TS ONCOMP, 1976-06-21
- JONL; TS COMPLR, 1973-05-06
- JONL; TS OCOMPL, 1973-05-06
- JONL; TS OOCOMP, 1973-04-17

**Comment by larsbrinkhoff** [comment]
Of note is that VRYOLD LISP doesn't have DEFUN built in, which should make it predate the 3/1/69 announcement that introduced DEFUN.

**Comment by larsbrinkhoff** [comment]
ToTS tape 3100150, file LISP; OLDLSP NOTE

```
11/16/70

        NLISP HAS BECOME THE SYSTEM LISP,
AND THERE IS NOT YET A NEW NLISP.  IN
SOME FEW DAYS, THERE WILL APPEAR A NEW
NLISP, INCORPORATING MANY NEW CHANGES,
SOME NEW FEATURES, AND SOME OLD BUGS(?)
CORRECTED.  IT WILL BE FULLY DOCUMENTED
WHEN IT APPEARS.

        RIGHT NOW, WITH LISP 131, USE

E LAP           (LAP E24)
C LAP           (LAP C24)
GRIND LISP      (GRIND 5)
TRACE LISP      (TRACE 8)
INDEX LISP      (INDEX >)
DIS EXPR        (DISXPR 2)

ALL FOUND ON THE COM DEVICE (NAMES IN
PARENTHESES ARE FOR BACKUP VERSIONS ON
DECTAPE)

        NLISP (LISP B/131B) HAS SUCCESSFULLY
OPERATED FOR MANY MONTHS NOW, BUT IF YOU
MUST RETURN TO A PRIOP LISP, START
OUT WITH OLISP, AND SEE JONL ABOUT
AUXILLIARY FILES TO GO WITH IT.

**Comment by texdraft** [comment]
Are those old COMPLR versions publicly accessible?

**Comment by larsbrinkhoff** [comment]
@texdraft, sorry they are not.  The files are on PDP-10 backup tapes, and have to go through a lengthy process to be released to the public.
