### ISSUE TITLE
FORTRAN

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#170]
Is there a Fortran compiler?

Some files in DECSYS; look promising.

**Comment by larsbrinkhoff** [comment]
DECSYS; F10 LOW  
DECSYS; F10 SHR  
DECSYS; FORT* SHR  
DECSYS; FORLIB REL

**Comment by larsbrinkhoff** [comment]
@philbudne 
> ISTR the versions of FORTRAN-10 (and perhaps its predicessor F40) in ITS DECSYS; were ANCIENT

The FORTRAN files are dated 1976.  F10.HLP says it's from 1973!  Is there a way to check the versions in the binary files?

> I have a hard time ingaining anything in DECSYS would have been built from source, or if it had, that the sources were hanging around.

Right, I see no FORTRAN source here.  But I have a desire to build as much as possible from source, and if the ITS binaries are outdated, all the more reason to get newer versions.  (There's a tension here between software preservation versus having an updated system.)

Somewhat ironically, FORTRAN would mostly be needed to install games.

**Comment by larsbrinkhoff** [comment]
Running :DEC SYS:X work for these values of X:

- F10
- F40
- FORTRA

**Comment by larsbrinkhoff** [comment]
F40 installed in #647.

**Comment by eswenson1** [comment]
Do we know what version of Fortran each of F10, F40, and FORTRA supported?  I assume F40 is Fortran IV.  But what are the others?

**Comment by eswenson1** [comment]
I just had this interaction with F10:

```
*:dec sys:f10
*/h

FORTRA.HLP -- HELP FILE FOR FORTRAN-10 FIELD-TEST RELEASE.    29 MAR 73

COMMAND-STRING:  OBJFILSPEC,LISTFILSPEC=SOURCEFILSPEC/SWITCH/SWITCH...
--------------
DEFAULT SOURCE-FILE EXTENSION IS .FOR OR .F40,
SOURCEFILSPEC & LISTFILSPEC DEFAULTS ARE SAME AS FOR F40.
```

**Comment by larsbrinkhoff** [comment]
Maybe Phil can guess, or maybe there are some documents on bitsavers.

- http://www.bitsavers.org/pdf/dec/pdp10/TOPS10/AA-0944E-TB_FORTRAN-10_Programmers_Reference_Ver_5_Jan77.pdf  
- http://www.bitsavers.org/pdf/dec/pdp10/TOPS10/DEC-10-AFC0-D_PDP-10_FORTRAN_IV_Programming_Manual_Aug69.pdf  
- http://www.bitsavers.org/pdf/dec/pdp10/TOPS10/DEC-10-LFORA-B-D_FORTRAN-10_Language_Manual_Ver_1A_Jan74.pdf

**Comment by philbudne** [comment]
F10/FORTRA (FORTRAN-10) was FORTRAN-IV (FORTRAN 66) until version 7,
which supported the FORTRAN-77 standard.  I seem to recall finding
version 1 of F10 in ITS' DECSYS directory.  I can't IMAGINE anyone
ever running v7 on ITS, and I wouldn't be shocked if it used TOP-10
monitor calls not supported by DECUUO.

phil
