### ISSUE TITLE
pdp10-ka tape reading frequently gives BAD HEADER errors and doesn't load all files

### ISSUE THREAD

**Issue by eswenson1** [PDP-10/its#1708]
As previous tickets have indicated TM10A tape support is not reliable under pdp10-ka.  So I'm now using TM10B.  Now, I'm seeing issues with TM10B.  Tapes that were written under KLH10 (and can be read without issues under KLH10) and that appear perfectly fine to itstar, are getting BAD HEADER errors while being read with DUMP/LOAD under ITS under pdp10-ka.

I've done this many a time with similar errors.  Here is one example.  With a tape (I can provide upon request) called emacs-xfer.tape, that can be read on KLH10/ITS with no issues and which itstar reports:

```
$ itstar tvf emacs-xfer.tape
Tape 32, reel 0, created 08/27/19, type=random
EMACS;SAVMAC :EJ   1984-9-21
EMACS1;SAVMAC 3   1984-9-21
EMACS1;SAVMAC COMPRS   1985-3-14
$
```

When I attempt to read with pdp10-ka and TM10B, I get:

```
dump↑K!
DUMP  .445

_rewind

_load
FILE=*;* *


BAD HEADER  EMACS1 SAVMAC 3
 E-O-T
_
```
After this failed attempt, only one of the three files is loaded on my pdp10-ka ITS:
```
*:find savmac
EX:EMACS1;
  0   SAVMAC COMPRS   0 +360  ! 4/14/1985 18:37:20 (8/27/2019) EJS

:KILL  EMACS◊J
*
```
DUMP's LIST command reports:
```
*dump↑K!
DUMP  .445

_rewind

_list
 LIST DEV =
TAPE NO     32 CREATION DATE  190827

     1 EMACS  SAVMAC :EJ        0      10/21/1984 14:12:11
     2 EMACS1 SAVMAC 3          0      10/21/1984 14:11:33
     3 EMACS1 SAVMAC COMPRS     0      4/14/1985 18:37:20 E-O-T
 REEL =      0

_
```

**Comment by rcornwell** [comment]
Hi Eric,

> I can try the same experiment with no chaosnet and imp. Also, i’m
> using the source tree that Mark sent me — that includes his network
> changes. I should try the pdp10-ka source tree that we’re using for
> the DB/ITS build.

  I have the patches that Mark posted. The problem is that he does not
  appear to start the DHCP request unit. Hence it never finishes the
  init sequence. Once that it working I will try it again with IMP. I
  need info on a valid Chaosnet node I can come up as and hook to.

Rich

-- 
==========================================================================
Richard Cornwell
rich@sky-visions.com
http://sky-visions.com
LinkedIn:   https://www.linkedin.com/in/richard-cornwell-991076107
==========================================================================

**Comment by larsbrinkhoff** [comment]
I am quite confident that KLH10, itstar, and SIMH all use the same tape image format, which includes a padding byte for records with an odd length.

**Comment by larsbrinkhoff** [comment]
I'm surprised, because I have used KA10 ITS quite a bit and not seen this problem.  But then, I haven't used the latest simulator versions as much.  My "TT" ITS is months old.  But it's due for a refresh soon.

**Comment by larsbrinkhoff** [comment]
Listing is OK:

```
_list
 LIST DEV =tty
TAPE NO     32 CREATION DATE  190827

     1 EMACS  SAVMAC :EJ        0      10/21/1984 14:12:11
     2 EMACS1 SAVMAC 3          0      10/21/1984 14:11:33
     3 EMACS1 SAVMAC COMPRS     0      4/14/1985 18:37:20 E-O-T
 REEL =      0
```

Loading the files seem to work too.  There wsa no BAD HEADER message.  I'm looking at SAVMAC 3 and I don't see any obvious errors.

Now, this is an old "ka10" simulator, so this doesn't prove much.

**Comment by larsbrinkhoff** [comment]
By the way, if the tape image format is off, SIMH will complain.

**Comment by larsbrinkhoff** [comment]
What I have done when DUMP complains, is to single step the tape I/O.  That will answer exactly where and why DUMP is unhappy.  Is the header too short?  Too long?  Contents wrong?

**Comment by larsbrinkhoff** [comment]
@rcornwell wrote:
> I expect these timing issues with the tape might exist in real KA. I think some of these issues with the tape comes from bit rot. MIT stopped using the TM10A before they switched to the KL.

The bit rot theory is reasonably plausible.  It should be tested.  I'd like to check this with ITS from say 1980, but I don't think I have access to those files.  I can also do some tests with ITS 724 and 785, but they need 7-track tapes so that's an extra complication.

**Comment by larsbrinkhoff** [comment]
For the (tape) record, this is ITS' history with different tape drives:

- PDP-6 ITS had a tape drive, probably later shared with the AI lab KA10.
- DM ITS starts out without disks and possibly no magtape.  Later gets DF10/RP10/TM10B.
- 1972, ITS 724 on the AI lab KA10 has a TM10A, as per the binary file.
- 1973, ITS 785 sources with both AI and ML having TM10A.
- 1975, ITS ported to KL10: MC has a TM10B.  AI/ML have A, DM has B.
- 1983-84, KA10 machines flushed.  This would be the last use of TM10A.  MC still has the TM10B.
- 1985, ITS ported to KS10.
- 1988, KL10 flushed.  Last use of TM10B.
- 1990, Last MIT version of ITS; this is the one we're using.

**Comment by larsbrinkhoff** [comment]
@eswenson1, can you do a test on your machine?  Make a plain vanilla KA ITS and test reading the tape again.

**Comment by ams** [comment]
`git clean -xfd`

**Comment by larsbrinkhoff** [comment]
Thanks Eric!  So it would seem there's something about EX as currently
configured.  Maybe RH10?  It does share a DF10 with TM10B, so that may
be something to look at.

**Comment by eswenson1** [comment]
@larsbrinkhoff suggested that it would be good to check the KL (pdp10-kl) build to see if the tape problem exists there.  The KL build uses RH10 and TM10B -- just like EX.

I built KL and ran the test -- the tape loaded fine.  I then compared the settings in SYSTEM; CONFIG > between EX and KL.  There were many -- the reason is that EX was based on KA, not KL.  

So I updated the KL config to be much closer to the EX config, but a new ITS, updated the "run" script to include the required devices (dk, tk, mty, ch, imp) and updated the memory from 512k to 1024k.  The resulting ITS still reads the tape correctly.

I don't want to believe that the RP04 -> RP06 change has made any difference.  I'm looking for other differences first....

**Comment by eswenson1** [comment]
Closing this issue because it appears it is pilot error on my part.

**Comment by rmaldersoniii** [comment]
> Date: Tue, 27 Aug 2019 22:19:29 -0700
> From: Lars Brinkhoff <notifications@github.com>

> I am quite confident that KLH10, itstar, and SIMH all use the same tape image
> format, which includes a padding byte for records with an odd length.

KHL10 can use either E11/itstar format *or* SimH format for virtual tape files.
See the file doc/vtape.txt:

    "TPS" FILE FORMAT (.TAP, .TPS, .TPE)
    ====================================

    	This is the format used by Bob Supnik's SIMH emulators.  It is
    almost the same as John Wilson's E11 format, which it was intended to
    resemble.

    A TPS file is assumed to consist of 8-bit bytes.

    Each record starts with a 4-byte header in little-endian order.
    The high bit of this 32-bit header is set to indicate an error of
    some kind (similar to the 'E' flag in a RAW-format control file) and
    the remaining 31 bits contain the record length N.

    This header is followed by N data bytes plus, if N is odd, a padding
    byte (of undefined value) at the end.  Following this is a copy of the
    4-byte record header.

    Tapemarks are represented by a single header with N=0.

    The reason for having the record length both before and after the
    record data is so tape motion in the reverse direction can be more
    easily simulated.

    The E11 (.TPE) format is identical except there are no padding bytes.

Note that last line.

I continually run into this when moving between KLH10 and SimH with foreign
tape images (such as those from Trailing Edge) which do *not* have a padding
byte on odd length blocks.

                                                                Rich

**Comment by larsbrinkhoff** [comment]
Thanks Rich, good point.

I'm adding support for reading the E11 version to itstar, because I also encountered tape images of that format.
