### ISSUE TITLE
Maclisp and Lisp machine Lisp linage?

### ISSUE THREAD

**Issue by ams** [PDP-10/its#1717]
Anyone know when the split of? How was code shred between the two?

**Comment by larsbrinkhoff** [comment]
There are Maclisp libraries to emulate some Lispm features.

**Comment by ams** [comment]
I know that there were various special files one had to load to get some compatibility.  But was more curious on when the two diverged.

**Comment by larsbrinkhoff** [comment]
For a while, I think they tracked each other to some degree.  Sorry, I
can't state any dates.
