### ISSUE TITLE
Notes from "Hackers - Wizards of the Electronic Age"

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#1724]
26-minute TV feature from 1984: https://www.youtube.com/watch?v=zOP1LNr70aU

**Comment by larsbrinkhoff** [comment]
- 7:08 - hacker with coke.  340 display in background.
- 7:09 - hacker at teletype.  PDP-6 console in background.

**Comment by larsbrinkhoff** [comment]
25:58 - "Additional footage & photographs provided by Mark Beeler"  Mike?

**Comment by larsbrinkhoff** [comment]
@aap spotted Spacewar consoles at 7:09, so it must be the MIT's AI lab PDP-6.

**Comment by larsbrinkhoff** [comment]
7:08 is Donald Eastlake.

7:09 is Richard Fateman.

**Comment by larsbrinkhoff** [comment]
7:09
![Fateman](https://user-images.githubusercontent.com/775050/64682525-e5a24f00-d481-11e9-8f11-741d8e062835.png)

**Comment by larsbrinkhoff** [comment]
7:12-7:20 - Richard Shroeppel (?) playing chess on behalf of Machack VI.

**Comment by larsbrinkhoff** [comment]
Michel Beeler doesn't know about any Mark Beeler.

**Comment by larsbrinkhoff** [comment]
Schroeppel confirms it's him.  Also notes:

- 8:55 Seymor Papert.
- 8:58 Eugene Charniak.
- 9:00 Joseph Weizenbaum.

**Comment by Alexey-Slyusar** [comment]
Brian Harvey appears twice on the tape:
- 3:00
- 5:39 

And if I am not mistaken, this is RMS states "My project is to make all software free" at 2:58.

**Comment by larsbrinkhoff** [comment]
Other footage from same event?
https://www.youtube.com/watch?v=SE_tlrfDVS0

**Comment by larsbrinkhoff** [comment]
Article from Tech Insider:  
https://tech-insider.org/personal-computers/research/acrobat/8505-a.pdf
