### ISSUE TITLE
ITS with extended addressing?

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#1739]
@eswenson1 proposes to update ITS to use extended addressing.  Let's discuss that.

**Comment by larsbrinkhoff** [comment]
I'm worried this would need large invasive changes.  First, imagine all places in ITS that need to keep track of a job PC.  Traditionally, a single word can hold flags and an 18-bit PC address.  This no longer holds true with extended addressing.

Second, consider all system calls that assumes 18-bit addresses.  You either have to make a whole new set of system calls, or proclaim that system calls are limited to work inside a single section.

Etc...

Finally, applications.  Maybe just making Lisp use extended addressing would have the biggest impact.  And next possibly TECO/EMACS.  Updating just those two would go a long way.

**Comment by eswenson1** [comment]
I wasn’t actually serious about making ITS use extended addressing. I agree, 18-bit addresses are way too pervasive.

**Comment by rcornwell** [comment]
Extended addressing is a collection of 256k spaces. Currently 32 are implemented on the KL10. Although there is nothing preventing the full 11 bit space from being implemented. Currently I throw the section number in the bits over 18 of the PTE entry. This can cause a bit of thrashing for PTE entries if to sections are addressed at the same page.

What would be interesting is to study Tops10 and Tops20 to see how they used extended addressing. Extended address pretty much requires that Tops 20 style page tables be used. Which would be the most major change to ITS.

**Comment by larsbrinkhoff** [comment]
It could be a branch off the traditional ITS... NITS or XITS?  I think we can close this for now.
