### ISSUE TITLE
Output from BUG DDT,[SHUTDOWN COMPLETE]

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#1740]
When KA10 or KS10 ITS is shut down, we'll see this:

```
KA ITS 1648 NOT IN OPERATION 07:07:00
SHUTDOWN COMPLETE
PI LEVEL 7 BUGDDT.  TYPE <ALTMODE>P TO CONTINUE.
YOU ARE NOW IN DDT.
BUGPC/   CAI COFFI4+1   $Q-2/   JRST COFFI7
```

However, on the KL10 we just see this:

```
MX ITS 1648 NOT IN OPERATION AT 07:11:26
SHUTDOWN COMPLETE
```

@eswenson1 pointed out the latter is what he remembers from shutting down MIT-MC.

Is there a bug on the KA10 and KS10 versions, or is this the expected output?  I'm labeling this "question" rather than "bug" for now.

**Comment by larsbrinkhoff** [comment]
The SHUTDOWN COMPLETE message is from here:

```
;SYSTEM FULLY DOWN; GO TO DDT.
COFFI4: BUG DDT,[SHUTDOWN COMPLETE]

**Comment by larsbrinkhoff** [comment]
The BUG DDT macro is defined to do a `PUSHJ P,BUGDDT`.

BUGDDT is in SYSJOB:

```
BUGDDT: PUSH P,TT
        PUSHJ P,SYSMS0          ;COPY MESSAGE INTO SYSTEM JOB BUFFER
        JSP TT,BUGDD0           ;PRINT MESSAGE AND GO TO DDT
            ASCIZ/DDT.  TYPE <ALTMODE>P TO CONTINUE./

**Comment by larsbrinkhoff** [comment]
BUGDD0 ends up in BUGDD2 which does this:

```
BUGDD2: MOVE A-1,BUGPI          ;CHECK FOR PI IN PROGRESS
        ANDI A-1,77400
        LSH A-1,20.
        JFFO A-1,[ MOVEI I,[ASCIZ/PI LEVEL /]
                   PUSHJ P,SYSSP
                   PUSHJ P,SYSDPT
                   PUSHJ P,STYOS
                   JRST .+1 ]
        MOVEI I,[ASCIZ/BUG/]
        PUSHJ P,SYSSP
        POP P,I                 ;PAUSE OR HALT MESSAGE
        SKIPN SYSDBG            ;PUNT LONG-WINDED MESSAGE IF DEBUGGING
         PUSHJ P,SYSSP
        MOVEI I,[ASCIZ/
YOU ARE NOW IN DDT./]
        PUSHJ P,SYSSP
        MOVEI TT,[ASCIZ|BUGPC/$Q-2/|]

**Comment by larsbrinkhoff** [comment]
So I can see that the "PI LEVEL" message may not come up.

But I do not understand why the KL10 doesn't print "BUGDDT.  TYPE \<ALTMODE>P" and "YOU ARE NOW IN DDT" etc.

**Comment by eswenson1** [comment]
I must be remembering wrong. I think it must be that something in pdp10-kL that is preventing the return to DDT and the message to that effect. Shutting down MC did return you to DDT and we’re not getting there.

**Comment by eswenson1** [comment]
Yes, my recollection was that the SHUTDOWN COMPLETE message was displayed, followed by a message saying YOU ARE NOW IN DDT.  What I didn't remember ever seeing was the PI LEVEL message, which seems more of an error-sounding message.

**Comment by eswenson1** [comment]
If you patch support for the DTE 3400 command in the console interface to return 0 in DTEF11 if there is no input available, this fixes this issue.

**Comment by larsbrinkhoff** [comment]
The latest updates on the `kl10` branch have fixed this.  However, we can't use it yet because the build breaks.

The same goes for #1745.
