### ISSUE TITLE
Push SALV higher for "KA" ITS

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#1744]
We have run out of memory to add more things to "KA" ITS.  There is a soft limit because SALV is assembled to sit at address 200000 so ITS need to stay below that.  Lifting this limit should be no harder than editing SALV and ITS to agree on a new address.

**Comment by techfury90** [comment]
After a few missteps (didn't rebuild SALV properly the first few times), I managed to generate KA ITS with the higher SALV address used on KL ITS. It seems to work, but I haven't extensively tested it yet.

**Comment by larsbrinkhoff** [comment]
Thanks for testing this.  Since there are a few more things pending to go into KA ITS it's great that you're testing the higher SALV address.

I think the address should probably be moved from SYSTEM; ITS > to CONFIG.  It could default to 200000.  Or maybe to some place that can be shared between ITS and SALV?

**Comment by larsbrinkhoff** [comment]
Is there something unclear about NITS.md that made it hard to get SALV right?

**Comment by techfury90** [comment]
I think moving it to CONFIG would be wise for ITS >, but that still leaves SALV to worry about. Maybe some sort of common place (common header?) would be a good idea.

As far as NITS.md goes, it omitted the BIN in SALV BIN- a documentation error that tripped up this newbie for a few hours. I was therefore merging in just SALV (aka @ SALV), which was the old version of SALV.

Actually, what _is_ the difference between these two files? My existing @ SALV seems to be 1 block larger than the SALV BIN I generated from MIDAS. But yet SALV BIN seems to work fine? Am I perhaps missing a step here?

**Comment by techfury90** [comment]
Okay, reviewed the build scripts to see how they're doing things... (see snippet at the bottom)

Looks like @ SALV is made by DSKDMP, loading in SALV BIN and saving it out. Looking further down, we see that SALV BIN is merged in with NITS BIN to make the new ITS. It would therefore seem that we may want to include this step within the instructions in NITS.md...

https://github.com/PDP-10/its/blob/7a20b68181f17f36fc9a1d0087d24c6ab704fed2/build/ka10/include.tcl#L101-L133

**Comment by larsbrinkhoff** [comment]
The (supposed) difference between @ SALV and SALV BIN should be that
@ SALV has DDT merged into the core image.  Whereas SALV BIN is just
the binary file from assembling SALV.  This means that if you run
@ SALV from DSKDMP by typing "SALV CR" you end up in DDT and are able
to run SALV subroutines.  This is the user interface for SALV.

**Comment by larsbrinkhoff** [comment]
I needed to move SALV in #937.  It seems to work.  I also tested it locally, with no discernible ill effects.

**Comment by larsbrinkhoff** [comment]
Pushed to 212000 like MC.

**Comment by larsbrinkhoff** [comment]
The idea to have this parameter in a file shared between ITS and SALV makes sense.  But it's not in line with tradition, which has SALV using a completely separate set of parallel parameters which must be maintained to match ITS.

**Comment by eswenson1** [comment]
What’s to say we can’t improve things? I’d say we have learned a few things about software engineering since ITS was conceived!

**Comment by larsbrinkhoff** [comment]
I have written about this before, the tension between staying close to the historical experience versus the desire to make improvements.  I'm torn myself, and I don't have an answer to fit every situation.

**Comment by eswenson1** [comment]
I don’t see why introducing an include file in SALV/NSALV and ITS for this purpose isn’t just the right thing to do to prevent future issues as these values are adjusted. I’m sure the originators of ITS would agree — after having issues keeping them in sync plagued them enough times. 

I don’t think this is violating the spirit of ITS at all. The implementors didn’t intentionally try to do things badly—they were trying, usually, to use the absolute minimum amount of cpu/mem resources. And this sometimes led to less-than-ideal practices. And the audience for their changes was very small. Now, our audience has grown as there are many more ITS systems and owners than we had in the old days.

**Comment by dabridgham** [comment]
On the issue of historical ITS vs making improvements, I'd like to see two tracks.  I'd like a historical track that researches, recovers, and preserves ITS as it was.  Perhaps small fixes as they're found and needed but not much else.

Then another track that's "modern" ITS where we're free to play.  Obviously I want, eventually, to port ITS to the processor I'm building which is much like a KA but not entirely.  And the I/O devices will be all different.  Then I have a handful of ideas for modifications and extensions that would interest me.  I bet others have their own ideas for changes too.

**Comment by larsbrinkhoff** [comment]
I have been thinking on and off about this two-track arrangement.  The
problem I see is if effort is divided and duplicated between the tracks.
As long as there's only a tiny number of people, I think it's important
to cooperate as much as possible.

It has been my intent that this repository should lean towards
"historical, but with small fixes".  Yet I want to include those who
want to make improvements like running on new hardware, because I think
it's better to have a single canonical place for ITS development.  This
has worked so far, but it could become more challenging in the future.

I have a third on the side: a ~1972 ITS image, which is only available
from telnet.  Actually I'd like this to expand to historically close
snapshots from several points in time, like every two years or so.
Since these are frozen in time, they don't need much in the way of
active development.
