### ISSUE TITLE
Exec DDT in KL ITS does not support ^F

### ISSUE THREAD

**Issue by eswenson1** [PDP-10/its#1745]
I cannot list directories from KL Exec DDT.  Nothing happens when I do.

**Comment by eswenson1** [comment]
If you patch the code for processing DTE command 3400 in the DTE console interface in pdp10-kl to return 0 for DTEF11 when there is no input, ^F works fine.

**Comment by larsbrinkhoff** [comment]
The latest updates on the `kl10` branch have fixed this.  However, we can't use it yet because the build breaks.
