### ISSUE TITLE
Get Chaosnet working in KL ITS

### ISSUE THREAD

**Issue by eswenson1** [PDP-10/its#1747]
Currently, Chaosnet, when enabled in ITS, doesn't work.  While ITS comes up, you see messages like this periodically on the system console:

CHAOS NET ATTEMPTING TO USE TOO MUCH CORE  16:43:01

and no Chaosnet programs work (finger, chtn, etc.)  

This is with the following defined in the SIMH script for pdp10-kl:

set ch enable
set ch peer=54.174.143.211:42044
set ch node=5461
at ch 42043

And ITS configured with 5461 as the chaos net address.

The same configuration works fine in pdp10-ka.

**Comment by larsbrinkhoff** [comment]
The message comes from CHABG4, which is only called from CHABGI which is used to allocate a buffer for Chaosnet packets.  Apparently it can't get one from a free buffer list, so next tries a fresh 1K page.  There is a limit set to 50 pages which is overrun.

CHABGI is called from a lot of places, so it's hard to work backwards from this.

**Comment by eswenson1** [comment]
It seems that ITS, when assembled for chaosnet, gets a bunch of undefined symbols.  This is very likely the cause of the issues with chaosnet:

```
KL:CHAOS 289 SYSTEM;
CHAXM0+7        66433    2.    14-041   DLCSS1  Undefined
DLCWK1+2        67551    2.    26-015   DLCRS1  Undefined
DLCWK1+6        67555    2.    26-019   DLCRS1  Undefined
DLCWK2+1        67564    2.    26-028   DLCSS1  Undefined
DLCWK3+7        67574    2.    26-036   DLCSS1  Undefined
DLCWK4+1        67577    2.    26-040   DLCSS1  Undefined
DLCIBG+1        67615    2.    27-005   DLCRS1  Undefined
DLCIB1+3        67621    2.    27-010   DLCRS1  Undefined in literal
DLCIB1+12       67630    2.    27-018   DLCRP1  Undefined
DLCIB1+13       67631    2.    27-019   DLCRP1  Undefined
DLCIB1+16       67634    2.    27-023   DLCRS1  Undefined
DLCIB1+17       67635    2.    27-024   DLC     Undefined
DLCXMT+3        67642    2.    27-032   DLCSP1  Undefined
DLCXMT+4        67643    2.    27-033   DLCSP1  Undefined
DLCXMT+7        67646    2.    27-037   DLCSS1  Undefined
DLCXMT+10       67647    2.    27-038   DLC     Undefined
    ==> INSERTED:  CHAOS 289
```

I traced the code that is allocated chaosnet buffers, and ran into this, from correlating the cpu trace with a listing:
```
067620   777743173567  067737     777743173567  777744173570   304000  260640067737  PUSHJ 15,67737
```

```
                         ;THIS ROUTINE SUPPLIES AN INPUT BUFFER TO THE 11 ON ALL BUFFERS THAT NEED IT
                         ;CALL WITH INTERRUPTS OFF OR IN PROGRESS
067614  201440 000001   DLCIBG: MOVEI J,1
                            SKIPE DLCRS1(

DLCIBG+1    67615    2.    27-005   DLCRS1  Undefined
067615  332011 000000   J)
067616  365440 067615   DLCIB1:  SOJGE J,.-1
067617  321440 012005       JUMPL J,CPOPJ
067620  260640 067737       PUSHJ P,CHABGI      ;GET A BUFFER
```

Note, we have a MIDAS error there, in the LISTING.  I suspect the KL build doesn't include all the right chaosnet code, or that the code has bit-rotted.  We'll have to investigate this.

**Comment by eswenson1** [comment]
Ahhh.   One of the undefined symbols is DLCSS1.  We need DL10P==1 in order to get this symbol defined.  I defined DL10P==1 (we’re using it for chaosnet) and now I don’t get the buffer allocation issues any more.

I still can’t connect, but at least we’re not using up all the chaosnet buffers.

**Comment by larsbrinkhoff** [comment]
We know CH10P works on KA10 without DL10P.  Since on a KL10 DK10P seems to be required, this points to some kind of error in the conditionals.

**Comment by eswenson1** [comment]
Ok. I’ll have a closer look. But first, I want to debug why an RFC doesn’t work.

**Comment by eswenson1** [comment]
Well, on KA, we used CH10P==1.  So the code that used DLCSS1 was not used.  But on KL, we have CH10P==0.  The chaosnet goes through the DL10.  So it seems we need DL10P==1 to get DLCSS1 defined.

**Comment by larsbrinkhoff** [comment]
This is news to me.  I don't see any DL10 Chaosnet in the emulator.  If there is, but all means set DL10P==1.

**Comment by eswenson1** [comment]
Don’t assume I know what I’m doing. I thought MC used the IOELEV for Chaosnet. When Rich told me that pdp10-kl had support for Chaosnet, he agreed with me that I should set DLCP==1 — just as MC had in its config. So I updated KL’s config to have it too. But assembling ITS with Chaosnet enabled and DLCP==1 gets unresolved symbols — all referencing the shared memory of the PDP11 used to talk to the Chaosnet. Setting DL10P==1 makes the errors go away.

**Comment by rcornwell** [comment]
I said DLCP should be set to 0 since I don't support DL10 on the KL10. If you want to add DL10 support to the existing Chaos10 driver, feel free.

**Comment by eswenson1** [comment]
So how do you support Chaosnet on KL10? ITS has three choices: DL10, Unibus, or on the PDP-10 I/o bus. That last setting is CH10P==1.

**Comment by rcornwell** [comment]
Unibus is not an option on the KL10. So either CH10 (i/o bus), or DL10. DL10 is also technically I/O bus, since it was not part of channel. Another option would be to add support to the FE to do Chaosnet.

**Comment by eswenson1** [comment]
MC did chaosnet via frontend.  I tried CH10P==0 and got a HALT.  I tried CH10P==1 and connections time out.  (And I previously tried DL10P==1 and you said you didn't support DL10).

I'm pretty sure we had this discussion before -- via IRC, perhaps.  I told you MC did it via the frontend with DL10P==1 and you said you'd add it.  I thought when you told me to try Chaosnet on pdp10-kl, that you had. I must have misunderstood and that you didn't mean that you added it to the FE via DL10, like MC had, but via some other means.

**Comment by rcornwell** [comment]
I mean that there is support in Ioeleven to enable Chaosnet, however it is currently not implemented. This would be over a DTE20 rather then a DL10. DL10 is a different beast. After I finish Extended KL10B and get NIA driver on it I might consider adding it. But it will have to wait.

Adding support under the FE (via DTE20) will require changes to ITS. Sounds like CH10 will also require changes to ITS.

**Comment by rcornwell** [comment]
Please do add DL10 support. I don't know what MC had. I would assume a DTE10 and a DL10 or perhaps more. DTE10/DTE20 is required for the FE on a KL10. KL10 can support up to four DTE20's. Not sure about KL10A.

I would assume that ITS could be configured to use the CH10 interface, there is no reason it should work out of the box. It did not use MPX device so there should be no need to add the IRQ vector support to it.

**Comment by eswenson1** [comment]
Are you saying that pdp10-kl should support chaosnet with CH10P==1?  ITS builds and boots fine with this setting.  Chaosnet connection attempts with this setting time out, but no crashes.  Should I debug tihis?  Or is there no support in pdp10-kl for it.  When you told me earlier to "try chaosnet" and see if it works, I assumed you had support for it already in pdp10-kl. Please confirm where chaosnet is implemented in pdp10-kl.

**Comment by rcornwell** [comment]
I added CH10 to the pdp10-kl build. Whether it works or not I don't know.

If you want DL10 support for Chaosnet, please add it. It will be a couple months before I can get to it.

**Comment by larsbrinkhoff** [comment]
Note IOELEV can be built for three different front ends: AI CHAOS-11, MC
DTE20 (CONS-11?) and MC DL10.

If I read IOELEV right:

- AI's CHAOS-11 just does Chaosnet.
- MC's console FE runs KLDCP in one half of core, and IOELEV in the
  other.  IOELEV does terminals.
- MC's DL10 FE (originally a plain DC76?) does terminals, T300 disks,
  and Chaosnet.

**Comment by larsbrinkhoff** [comment]
Eric, I'm pretty sure the only viable option for KL Chaosnet is CH10P.
I'm also pretty sure it will not work out of the but due to assumptions
in ITS that KL Chaosnet is DL10P only.  But it should be fixable.

**Comment by eswenson1** [comment]
Ok, I'll proceed with investigating when CH10P==1.  This config boots fine -- chaosnet just doesn't do anything.  I'll try to track down what is or is not happening.

I thought we wanted pdp10-kl to support MC's configuratiom?  If so, then we'll need DL10 for MC's chaosnet support.

**Comment by larsbrinkhoff** [comment]
As far as I'm concerned, the end goal is to be able to run MC unchanged.
But we're not there yet, and probably will not be for some time.

**Comment by larsbrinkhoff** [comment]
Make sure CHAOSP==1 and CH10P==1, but DL10P==0 and DLCP==0.

**Comment by eswenson1** [comment]
So I've built a KL ITS with DLCP==0, DL10P==0, and CH10P==1 and CHAOSP==1.  It assembles and boots fine.  When I do a :finger @es, the connection times out.  The CH device in pdp10-kl logs a bunch of CONO 470, 435 instructions, and this appears to correspond to ITS's code here:

```
IFN CH10P,[
;FOR NOW, JUST ALWAYS SHIP IT OUT THE CH10
	HRRZ B,CHXXMQ		;ADD TO END OF TRANSMIT QUEUE
	JUMPE B,[ HRLZM A,CHXXMQ ? JRST .+2 ]
	 HRLM A,-2(B)
	HRRM A,CHXXMQ
	HRRZS -2(A)		;PUT END-LIST INDICATOR IN LH
	MOVEI B,CHXTEN		;ENABLE TRANSMIT-DONE INTERRUPT
	IORM B,CHXCNO
	CONO CHX,@CHXCNO
	CONO PI,PICON(E)	;RESTORE PI
	POPJ P,
];CH10P
```
Apart from transmit queue reference, the other flags in the EA of the CONO instruction are CHXCHN+CHXREN+CHXTEN (5 + 20 + 10).  This means we've enabled transmit and receive and specified channel 5 (chaosnet). 

I don't see any KL10P conditionalization outside of the DL10 support in system;chaos 289, so I have no reason to believe that CH10 support for chaosnet won't work on the KL10.  

So what is supposed to happen when the monitor does a CONO 470, 435?  What does pdp10-kl do with this?  

How can I enable all the cool tracing that appears to be supported, but that I haven't been able to figure out.  I see these debug options, but I haven't figured out how to get any of them to work:  

```
Debug output enabled to "dbg1"
Device: CH     Debug=TRC;REG;PKT;DAT;INT;ERR;XMT;RCV;RET;MODEM;CONNECT;ASYNC;TRACE;XMTPKT;RCVPKT;EXPECT;SEND
```
In my "dbg1" log file, I only see messages like this:

```
DBG(1837076453171)> CH REG: CONO 000000000435 000000000435
DBG(1838290624956)> same as above (6 times)
DBG(1838533275429)> CH REG: CONO 000000000435 000000000435
DBG(1839745738245)> same as above (5 times)
DBG(1839987543152)> CH REG: CONO 000000000435 000000000435
DBG(1841199417051)> same as above (5 times)
```
I'm hoping someone can tell me how to use the ch debug options.  Otherwise, I'll have to resort to gdb debugging of ka10_ch10.c.  I hate gdb.

**Comment by larsbrinkhoff** [comment]
We know the "CH10P" Chaosnet works fine with KA10, so it's a bit of a mystery why it wouldn't on KL10.  The simulated hardware is the same.  Interrupts are (almost?) the same.

There are a few KL10P conditionals in SYSTEM; CHAOS 289 but as far as I can see they are all inside DLCP.

`CONO 470, 435` does this:

1. Talks to device 740 which indeed is CH10.
2. Assigns PI channel 5.  CHXCHN==5, so this is fine.
3. Enables RX and TX interrupts.
4. Sets halfword mode.

I *don't* see that this should generate an interrupt.  I'd expect bit 1000 to do this.

**Comment by larsbrinkhoff** [comment]
All output is done with DATAO below CHXBK7 which is the CH10 interrupt handler.  I think this is how we are supposed to go there:

```
CHXBK5: CONSO CHX,CHXXMT        ;TRANSMIT DONE?
```

CHXXMT is 1000.

I think this bit is supposed to be *ON* when CH10 is reset.  So at the first moment the TX interrupt is enabled, we should get an interrupt.  So contrary to what I wrote in the previous comment, the CONO *should* generate an interrupt.

Setting `set ch debug=int` should write to the log when an interrupt is triggered:

```
    sim_debug (DBG_INT, &ch10_dev, "%s %s Interrupt\n",
               ch10_status & RXD ? "RX" : "",
               ch10_status & TXD ? "TX" : "");
```

**Comment by eswenson1** [comment]
It is working fine in pdp10-kl and KL ITS.  The first issue (resolved earlier) was that we needed to configure CH10P==1 rather than DLCP==1 and DL10P==1.  The second issue was operator error -- that the ch device was not attached in the SIMH script.
