### ISSUE TITLE
^N in TS DDT over ILDB instructions doesn't step in pdp10-kl

### ISSUE THREAD

**Issue by eswenson1** [PDP-10/its#1751]
Doing a ^N in TS DDT at an ILDB instruction doesn’t move to the next instruction on pdp10-kl.  It does on klh10:

Pdp10-kl:

JCLGT5+1>>ILDB A,B   A/   74000,,0   B/   440700,,JCLBUF      ↑N
JCLGT5+1>>ILDB A,B   A/   74000,,0   B/   350700,,JCLBUF      ↑N
JCLGT5+1>>ILDB A,B   A/   74000,,0   B/   350700,,JCLBUF      ↑N
JCLGT5+1>>ILDB A,B   A/   74000,,0   B/   350700,,JCLBUF      ↑N
JCLGT5+1>>ILDB A,B   A/   74000,,0   B/   350700,,JCLBUF

Klh10:

JCLGT5+1>>ILDB A,B   A/   74000,,0   B/   440700,,JCLBUF      ↑N
JCLGT5+2>>JUMPN A,JCLGT5   A/   0,,PAT

**Comment by eswenson1** [comment]
DPB instructions also cannot be 1-proceeded over.

**Comment by larsbrinkhoff** [comment]
I think it would be worthwhile to have an automated test for one-proceed.  It's also an instructive piece of code since it involves getting the one-proceed PC flag from ITS, creating an inferior job, adding code to its core image, starting it, and handling interrupts.

**Comment by larsbrinkhoff** [comment]
I made a pull request for the test program: #1753

**Comment by eswenson1** [comment]
What about IBP and IDBP?  Do they work now?

I also noticed that when single-stepping in SIMH, you have to do a "step 2" or "step 3" for some MUUOS.  Is that "right"?  I know this is a separate issue from ^N in TS DDT, but I wonder if there are other related/similar cases that could make ^N not work in TS DDT?

**Comment by larsbrinkhoff** [comment]
Has this been fixed now?  My test program works across ILDB.

**Comment by larsbrinkhoff** [comment]
Ping @eswenson1.

**Comment by eswenson1** [comment]
Yes, this appears to work fine for me in latest pdp10-kl.  Thanks.
