### ISSUE TITLE
Have DSKDMP auto boot ITS?

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#1805]
DSKDMP has this feature:

```
TYI:    ILDB C,MEMSIZ-1         ;CHECK FOR COMMANDS FROM MEMORY
```

So it would be possible to inject some memory contents to automatically start ITS.

**Comment by larsbrinkhoff** [comment]
I'm thinking it would be especially useful for the @PiDP -10 to have an unattended boot.

Possibly `./start auto`.

**Comment by PiDP** [comment]
The simh command script can just type the ITS-esc-G sequence when is sees
DSKDUMP come up. That keeps all the flexibility.

**Comment by larsbrinkhoff** [comment]
Good point.  And booting DSKDMP seems to clear MEMSIZ-1 so it will ignore any stored commands.
