### ISSUE TITLE
KLH10 builds are prone to hang

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#1808]
On some machines.  It usually happens when Emacs is built.

As per `expect -d` the build script is sending input, but it's not echoed.

**Comment by larsbrinkhoff** [comment]
Here's a previous change to KLH10 console input:  
https://github.com/PDP-10/klh10/issues/9  
https://github.com/PDP-10/klh10/pull/24

**Comment by techfury90** [comment]
It seems that I can get a successful build on Ubuntu 16.04.6, but not 18.04.3, 19.04.x, or 19.10.x (all amd64) releases under VMware Workstation on the same hardware. (Ryzen 1600X 3.6 GHz) 
Raspbian Buster on an RPi 4 B/4GB doesn't succeed either. I don't think macOS Mojave succeeded when I last tried, but that was a few months ago.

**Comment by larsbrinkhoff** [comment]
We found a workaround: set `KLH10_CTYIO_INT` to 0 when building KLH10.

```
# This is a known problem on some Linux systems with high performance
# hardware.  As far as I know, Ken has not found a fix for it.
#
# The workaround is to rebuild klh10 with a special configuration that
# avoids the esoteric real-time-interrupt mechanisms.
#
# You should only do this on a system which has this problem.  It will run
# on other systems, but will eat up CPU unnecessarily.

**Comment by larsbrinkhoff** [comment]
I let my build go on, and it hung in the Macsyma part now.

**Comment by larsbrinkhoff** [comment]
But a second time it ran to completion.

@techfury90, any luck with networking?

**Comment by techfury90** [comment]
Yeah, I have networking working fine. Interestingly, with a simulator built with KLH10_CTYIO_INT set to 0, I no longer experience the strange halts we talked about last night/morning. 

Guessing that the CTYIO_INT issue results in some sort of condition in which the klh10 execution flow blocks on waiting for character input. Very interesting.

**Comment by larsbrinkhoff** [comment]
Thanks.  I'll move my KLH10 ITS to the fixed (workarounded) emulator.

**Comment by larsbrinkhoff** [comment]
This workaround didn't work on Circle CI.
