### ISSUE TITLE
Is the tape assembly and install step necessary to run on end-user machines?

### ISSUE THREAD

**Issue by mseddon** [PDP-10/its#1814]
I may be naive in suggesting- if there were seperate makefiles for the emulator binaries and the ITS tape/install process for those champing at the bit to get started, that would be great.

I would *hate* to lose that expect build system in general though (watching it botch around issues building maclisp was hypnotic!).

Can this (tape assembly/install) step be done offline and distributed to end users that way? That way we only have to worry about building our emulator, and we can e.g. `curl XYZZY && tar -zxf` the rest. After all, I would at least hope that the bits emulated on my distribution on initial boot are the same as anyone else's.  However I am new to ITS and the PDP-10 in general, not to mention the hairy, undocumented heroism that is involved in getting this stuff to run at all, so I may be totally off target here.

Again, *obviously* the building steps are vital and deeply insightful, and I would always want a way to run the full process when I need to understand a particular artefact.

**Comment by jwbrase** [comment]
Unfortunately, as I understand it, many things that would be configured at runtime on a modern system with an edit to a config file and a daemon reload are configured at assembly-time on ITS, including such things as the system's hostname and IP address, and I get the impression there are other host-specific special cases in the code. Bear in mind that the total historical install base was on the order of 10 machines, and even on systems of the period that historically had greater install bases and thus more need to be friendly to install, I've seen some really dumb things configured at compile time: The people we now consider giants of computing history were forging new ground back then, and they had to make all the dumb mistakes before they could write the best-practice guides that tell new students today what dumb mistakes not to make.

Still, it might be good to have an example turnkey system.

**Comment by larsbrinkhoff** [comment]
What you suggest may be possible.  We do use online continuous integration services, so sparkly new disk images could be made available every time a new change has been merged.  The main roadblocks are 1. somewhere to host the fies, and 2. a way to securely transfer the files from the CI servers to the hosting service.

**Comment by jwbrase** [comment]
Lars's reply crossed with mine, he's the one in more of a position to say what's feasible.

**Comment by larsbrinkhoff** [comment]
@jwbrase, you have a point.  But I think the system build as is without any configuration tweaks is good enough for most situations.  People who want to do tweaks will have to go through the build, or make incremental updates on top of the baseline system.

**Comment by larsbrinkhoff** [comment]
This should be solved by #2004.  Please give it a try.
