### ISSUE TITLE
KL-10 segfaulted when attempting to save state

### ISSUE THREAD

**Issue by jwbrase** [PDP-10/its#1815]
Due to a graphics stack crash, I had to reboot the host machine for a KL-10 instance running ITS. I attempted to drop to the sim> prompt and use the "save" command to save the machine state to restore after the reboot, but simh segfaulted and dumped me back to my shell session. I was able to reproduce the issue on a fresh boot of ITS. The file I saved to exists and is 1814528 bytes in size. Running "start", and then attempting to use the "restore" command to load the file results in the error message "I/O Error", and then, when I exit simh:

"Improper thread context for operation on TTY1 in scp.c line 10992                                                     
Aborted: (core dumped)"

I get similar results if I run tools/sims/BIN/pdp10-kl directly without the start script.

I understand that tools/sims/BIN/pdp10-kl is a modification of the standard simh pdp10 simulator, so I'm filing my bug report here rather than with upstream simh.

I built the simulator and ITS using the procedure listed in Readme.md, the only change was to conf/network.

**Comment by larsbrinkhoff** [comment]
Sorry, saving emulator state is mostly unsupported as far as ITS is concerned.  It's an area where we would appreciate some help.  In any case, it's an emulator issue, not ITS issue.

There has been some updates to the KL10 emulator on the "kl10" branch, so maybe try that. http://github.com/rcornwell/sims

**Comment by larsbrinkhoff** [comment]
You should also know that KL10 is the least stable emulator.  If you want to test it, that's great.  But if you want to have a stable experience I recommend KA10 or KLH10 in KS10 mode.

**Comment by rcornwell** [comment]
I am not sure I got all the bits into registered needed. KL10 is still in development stage.

**Comment by larsbrinkhoff** [comment]
I'm closing this.  Please open issues in "sims" for KL10 emulator problems.
