### ISSUE TITLE
Add "echo" equivalent to DDT cheatsheet for Unix users

### ISSUE THREAD

**Issue by jwbrase** [PDP-10/its#1816]
I'm trying to figure out how to print text to the console from an xfile without side effects, and there's nothing especially clear in the ITS documentation about how to do this. Of course, :print will print the entire contents of a named file (a la cat), but I'm looking for a command that will print its argument. About the closest thing I've found is more.

**Comment by larsbrinkhoff** [comment]
This can be done with DDT commands, but it's really is not especially clear.

One way is to use a comment: `:◊Text here.◊`  I use `◊` for altmode here.

If you want just the text without the command characters, you can turn off printing for those with `^W` and `^V`:

```
^W:◊^VText here.^W◊^V
```

**Comment by larsbrinkhoff** [comment]
I don't think there's a colon command or program to do this.  It wouldn't be hard to make a program that just printed its JCL, but I believe `:◊` is the preferred way to do this.

**Comment by jwbrase** [comment]
OK, I'd figured out that :◊Hello World!◊, with appropriate printing suppression, had the effect of printing "Hello World!", but I wasn't certain that :◊ or :◊H wasn't a command that had side effects but didn't print anything to the screen. It's good to know that that construction is officially a comment.

So that would be good to include as the equivalent of "echo" and of the "#" comment construct in Unix. There are a few corner cases: when typed interactively :◊ doesn't retype the argument, which makes it somewhat more like a comment (at least in those Unix shells that don't give # a special meaning in interactive sessions. sh and bash treat everything after a # in an interactive command as a noop, but zsh gives # a special meaning interactively, while treating it as a comment in a script), but, on the other hand, the argument to :◊ is typed in a script, which is more like echo.

> I don't think there's a colon command or program to do this. It wouldn't be hard to make a program that just printed its JCL, but I believe `:◊` is the preferred way to do this.

Well, effectively :◊ is a colon command that means "treat everything up until the next ◊ as a comment".

**Comment by larsbrinkhoff** [comment]
I intended the DDT.md file as an intruction to the basics for new users.  I'm not sure adding :◊ there is helpful.  On the other hand, it wouldn't do any harm.  On the third hand, maybe there could be another guide for DDT scripting.

In any case, I encourage your to submit a pull request.

**Comment by larsbrinkhoff** [comment]
Fixed by #1818.
