### ISSUE TITLE
pdp6 submodule should be updated

### ISSUE THREAD

**Issue by tvrusso** [PDP-10/its#1824]
The PDP6 submodule is currently at commit 99a2eb7, which meant that I had to patch it a little to get it to compile under FreeBSD.  Looking at the master branch of PDP6, I find that the changes I had made are already present in the latest commit (including "<sys/socket.h>" and "<netinet/in.h>" in emu/utils.c).

It's no big deal to patch these by hand to get the entire ITS package to build on FreeBSD, since I also have to patch the Makefile to take out gcc-specific CFLAGS anyway (FreeBSD's default compiler is clang), but if the submodule were updated it would be one fewer thing to tweak.

**Comment by larsbrinkhoff** [comment]
Absolutely.  I added it to #1823.
