### ISSUE TITLE
On This Day

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#1828]
Noteworthy events by date.

- 1982-02-16 AI PDP-6 demolished.
- 1979-02-19 Magic swich removed.  #1232 
- 1969-03-01 DEFUN added to Maclisp.  #1661 
- 1967-03-09 PDP-10 first powered on.
- 1978-05-01 First spam, about DEC-2020.
- 1982-05-02 AI PDP-10 flushed.
- 1967-07-?? ITS operational.
- 1964-10-06 AI PDP-6 delivered.
- 1983-11-02 DM PDP-10 shut down.

**Comment by atsampson** [comment]
BAN.AI has an almanac file of significant dates for Multics in `>am>almanac>lib>Multics.Events` which are shown on login. You could do the same for ITS events...

**Comment by larsbrinkhoff** [comment]
Yes, but I have a hard time finding much more than this short list.  Maybe it will grow over time.

**Comment by larsbrinkhoff** [comment]
```
Welcome to alt.sys.pdp10

Post by Magnus Olss » Wed, 24 Aug 1994 02:21:43


Welcome to the new newsgroup alt.sys.pdp10!

This is a newgroup for the discussion of DEC's PDP-10 and DEC-20
computers and clones by other manufacturers, their hardware and
architecture, their software and operating systems, and emulators
running on other machines.

Also it's a place for telling your "war stories" involving these
machines, anecdotes about the '10-based hacker culture (including the
ITS community); a place for old hackers to reminisce about the old
days, and for younger hackers to learn about these legendary things.

And, finally, it's a place for the priests of the 36-bit creed to
combat the modern heresy that a machine must have a word length
that's a multiple of 8 :-).

P.S. If your site isn't receiving alt.sys.pdp10 within a week or so,
talk to your news admin. If he/she hasn't received any newgroup
message, please contact me.

**Comment by larsbrinkhoff** [comment]
Not ITS, but cousin Twenex:

```
Date: 21 March 1982 03:09-EST
From: Xxxxxx Xxxxx Xxxxxx <XXXX at MIT-AI>
Subject:  (current-state-of-OZ?)
To: BUG-OZ at MIT-AI

[...]

As many people have noticed, OZ has arrived. The configuration is as
follows:

 8  RP06 disk drives, 176 megabytes per drive.
 2  TU77 tape drives. 1600 bpi maximum density.
    (We hope to get a 6250 bpi tape drive, because backing up our disks
     would require too much tape otherwise)
 1  DecSystem 2060. Comes in 4 cabinets; I/O, Front End, CPU, and
    External Memory Cabinet.
 1 DN20 for terminal interface.
 1 AN20 for Arpanet interace.

The electricians should be done about next Tuesday; DEC could probably
come next Wednesday and begin installation. I would suspect that the
machine could be up for use by Lab members who want to test it out in
2 or 3 weeks.

**Comment by larsbrinkhoff** [comment]
Another interesting date from http://www.bitsavers.org/pdf/dec/pdp10/memos/720829_KL10_Technology_Goals.pdf:

> On the 27th of October, 1971, the DECsystem-10 Product Line proposed a Phase I study to determine an Engineering Specification, Software Specification, Marketing and business plan for the KL10.

**Comment by larsbrinkhoff** [comment]
@rmaldersoniii pointed out that the PDP-6 was announced in Business Week on March 14.  I didn't find a copy of that particular issue, but I found it in the 1964 index: https://archive.org/details/sim_business-week_1964_index_0/

![business-week-pdp6](https://github.com/PDP-10/its/assets/775050/cdc002db-7ea4-4866-87f4-e4874624f630)
