### ISSUE TITLE
Add Chaosnet bridge

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#1840]
Add @bictorv's Chaosnet bridge as a submodule.

(Dream scenario: it builds and auto configures and connects to The Chaosnet automagically.)

**Comment by bictorv** [comment]
We need some kind of DHCP for automagic connection. I gave it some thoughts maybe two years ago (there are some old protocols), and have more indirect experience of setting it up now. But I lack time at least until the summer.

**Comment by larsbrinkhoff** [comment]
Fixed by #2211.
