### ISSUE TITLE
AI films

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#1866]
Films found when CSAIL moved to a new building.  Includes commentary by Richard Greenblatt.

https://projects.csail.mit.edu/films/aifilms/AIFilms.html  
http://projects.csail.mit.edu/video/history/aifilms/  
https://projects.csail.mit.edu/films/aifilms/Podcasts/  
https://projects.csail.mit.edu/films/aifilms/FilmList.php

Notes below cover both films and comments.  Information in parentheses from "FilmList".

**Comment by larsbrinkhoff** [comment]
### 01-robot

Greenblatt points out the black and white parts are from the 340 display.

### 02-robot

Greenblatt says first display hack is from Michael Speciner.  [But it looks to me more like Pornism.]  Second part is Speciner's gas simulation.  Third part is "contour".  Bongo board.  Short clip of Greenblatt.  Minsky and Gosper.  AMF arm.  Minsky/Bennett arm.  Waltz finger.  SHRDLU.

### 03-gas

Speciner's gas.

### 04-cubechess

AMF arm doing copy demo, Gosper's programming.  Second part is SHRDLU.  Third part starts with model 35 teletype.  340 displaying chess, Alan Baisley.  Different angle with PDP-6 console.  Moby memory visible.

**Comment by larsbrinkhoff** [comment]
### 05-life

Roger Banks' cellular automaton.

### 06-robot

Stanford arm.

### 07-arm

PDP-6, different arrangement than 04-cubechess.  AMF arm.  Gosper from behind.  340 displaying input from vidissector.  Hand-eye coordination.  Minsky/Bennett arm with Bennett operating it, then Minsky.  Margaret Minsky.

### 08-turtle

**Comment by larsbrinkhoff** [comment]
### 11-robot

Japanese robot?

### 12-robot

Unknown robot tracking a line.

### 13-cubechess

AMF arm picking blocks.  Carl Engelman? with 340 and chess.  Closeup of 340 chess board.

### 14-cube

AMF arm.  Gosper.  Arm grippers projected onto 340 display when calibrating.

### 15-robot

Older Ernst arm for TX-0.  Grenblatt talks a lot about the TX-0.

**Comment by larsbrinkhoff** [comment]
### 16-solar

Solar Corona my Michael Beeler.  Greenblatt's room mate.  DEC made two color displays as an experiment.  They were really humongous.  Regular television CRT.  Point plotting display.  Problems with converging.  Low resolution.  Sat around at DEC for many years.  One given to MIT.  KA10 out of commision for running timesharing for quite a while when pager was added.

### 17-turtle

Color scope, first unknown effect, then OCEAN.  Big yellow turtle.

### 18-bongo

Bongo board.

### 19-cube

AMF arm stacking blocks.

### 20-cube

AMF arm stacking blocks.

**Comment by larsbrinkhoff** [comment]
### 21-bongo

Cynthia Solomon pushing someone on bongo board.

### 22-tutle

Big yellow turtle.

### 23-worm

Very briefly, possibly MACDMP displaying a file listing on the 340.  Then a worm, probably GROW WORM or GROAN WORM from the listing.

### 24-worm

Pornism.  Speciner's gas simulation.  Color scope WORM, OCEAN

### 25-logo

Logo on model 35 teletype.  "TEACHING CHILDREN THINKING" on color scope.  Pornism.  Color scope again.

**Comment by larsbrinkhoff** [comment]
### 26-robot

SHRDLU.

### 27-solar

Solar Corona with Sushine Superman music.  Greenblatt talks about Peter Samson's PDP-1 music program.

### 28-logo

Logo on model 35 teletype.  TEACHING CHILDREN THINKING.  Pornism.  Color scope: SPIRAL? something else, OCEAN.  Bongo board

### 29-solar

Solar Corona.  Greenblatt talks about NASA in Tech Square.

### 30-gas

Speciner's gas.  Pornism?  3D rotation.  Countour.

**Comment by larsbrinkhoff** [comment]
### 31-robot

### 32-mathlab

### 33-cube

### 34-robot

### 35-screen

**Comment by larsbrinkhoff** [comment]
### 36-wireforks

### 37-robot

### 38-robot

### 39-worm

### 40-logo

**Comment by larsbrinkhoff** [comment]
### 41-radial

### 42-radial

### 43-arm

### 44-logo

### 45-mac

**Comment by larsbrinkhoff** [comment]
### 46-robot

### 47-robot

### 48-worm

### 49-worm

### 50-logo

**Comment by larsbrinkhoff** [comment]
### 51-cube

### 52-robot

### 53-robot

### 54-bongo

### 55-worm

**Comment by larsbrinkhoff** [comment]
### 56-life

### 57-screen

### 58-logo

### 59-bongo

### 60-bongo

**Comment by larsbrinkhoff** [comment]
### 61-arm

### 62-logo

### 63-chess

### 64-robot

### 65-worm

**Comment by larsbrinkhoff** [comment]
### 66-worm

### 67-life

### 68-gas

### 69-gas

### 70-gas

**Comment by larsbrinkhoff** [comment]
### 71-robot (80, A Brief Introduction to the Robots at ETL)

Unknown robot arm and blocks.  Two displays.  Robot drumming.

### 72-gas (81, Gas 4 scraps (& losing tacky and chess)

Double pendulum.  GAS.

### 73-gas (82, Gas 5 scraps "pretty good")

GAS.

### 74-bongo (83, Bongo - SP on Bongo Board)

Bongo boarding.

### 75-logo (84, Logo Turtle Pen)

Yellow floor turtle.

"Children learn by doing and by thinking about what they are doing." possibly TECO on 340.

Logo on teletype.

**Comment by larsbrinkhoff** [comment]
### 76-robot (85 Vision Line Finding)

Mahavalo(?) vision.  Vidisector TVB.  340 display.

### 77-life (86 "Life" Mike Beeler)

Banks' cellular atomaton.  Life on color scope, but B/W unlike 56-life.

### 78-cube (87 Asst Robot Shots print)

Visidsector on 340.  AMF arm manipulating blocks.  Gosper.

### 79-logo (88 Random Logo Shots)

Display turtle.  TEACHING CHILDREN THINKING.

### 80-cube (89 Robot (NO 340) CBS)

Visidsector TVB.  AMF arm.  Background: HP display in rack, slaved to 340.  Donald Eastlake.

**Comment by larsbrinkhoff** [comment]
### 81-mathlab (90 Math Lab)

1860 math textbook.  Equations on the 340 display.  William A. Martin's thesis.  Woman at PDP-6 console, using light pen.  7090 kludge display mentioned by Greenblatt.  MATHLAB(68).

Girl with AMF arm.

Engelman playing chess at PDP-6.  Moby memory and DEC memoriy.  Greenblatt explains details of the Moby memory.  To the right is DEC Type 163 16K memory, with parity option.

GE consoles, "bought quite early".  The AI lab made an interface for it, supporting four consoles.  Display was a TV, keyboard from a model 33 teletype.  "Pretty kludgey."

Physics textbook.  Formula on 340 display.

**Comment by larsbrinkhoff** [comment]
### 86-bongo (95 Boy Bongo Boarding)

Boy jumping on a bongo board.

### 87-cube (96 Robot)

Vidisector scanning.  Robot picking up cube displaying on 340.  Gosper.

### 88-eye (97 "The Eye of the Robot" - "Studies in Machine Vision at MIT")

TVC vidisector.  David Waltz narrating.  Berthold Horn typing on teletype.  Marvin Minsky holding a lecture.

Visual feedback filling a container with liquid, program by Bob Woodham.

### 89-logo (98 #1 Day 1 Book", logo arrow display)

340 display.  Eye tracking, says Greenblatt.

### 90-logo (99 Logo, Stars, Worm

340 display?  Logo squiral.

**Comment by larsbrinkhoff** [comment]
### 91-turtle (101 Logo Polyspi)

Yellow floor turtle.

### 92-turtle (102 Log turtle pen)

Yellow floor turtle.

### 93-cube (103 Overexposed cube stack & Krakauer Hand Picture)

AMF arm.  Countour.

### 94-solar

Beeler's heart cell simulation.  Greenblatt comments about the similar looking Solar Corona.

### 95-turtle

Yellow floor turtle, B/W.  Greenblatt comments on Logo and turtles.

**Comment by larsbrinkhoff** [comment]
### 96-worm

340? display hack.  File listing on the display.  Worm.  Greenblatt comments on seaworm, Paterson's worm.

### 103-consort

No Greenblatt comments from here on.

"CONSORT"  someone light penning a vector display.  VT52.  Robot balancing.

### 104-mac

340 displaying "WORK REPORTED HEREIN..."  Girl using eye tracking device.

THE MAC ROBOT PROJECT.  AMF arm, vidisector.

Alan Baisley.  Minsky arm.  Chess.  Chess tournament trophy, April 1967.  Macsyma? equations, 340 by the looks of the font.

### 105-museum

Boston computer museum. TX-2, or 0?  Tic-tac-toe, mouse in maze.

### 106-twinkle

Random dots.

**Comment by larsbrinkhoff** [comment]
### x01-eye

Eye of the Robot.

### x02-run

Robotics from 1980s.

### x03-walking

Robotics from 1980s.

### x04-donuts

Donuts demonstration.

### x05-graphics

GRAPHICS, bkph.  Hacks for Knight TV display.  PEEK nine minutes in.

### x06-orienting

IC ORIENTING, bkph.

**Comment by atsampson** [comment]
Serial numbers punched into the film leaders. Note that in several cases we have the same number on several (similar) films, so maybe batch numbers rather than individual reels.

### 18-bongo, 21-bongo, 44-logo - 724110802

![leader-18](https://user-images.githubusercontent.com/436317/151605655-a64ad924-ba72-43a3-a6db-62c1b9e752d3.png)
![leader-21](https://user-images.githubusercontent.com/436317/151605657-2068565d-da48-4a90-a3c5-f6497147b4ae.png)
![leader-44](https://user-images.githubusercontent.com/436317/151605669-81a641cb-2e2a-4657-924b-40d61be12088.png)

### 22-turtle, 49-worm, 62-logo, 65-worm - 724242521

![leader-22](https://user-images.githubusercontent.com/436317/151605661-27c214fd-4625-44f0-bd6a-20491140dc57.png)
![leader-49](https://user-images.githubusercontent.com/436317/151605671-ae11f5fa-e5ae-47ef-a04d-79c7797bb7d3.png)
![leader-62](https://user-images.githubusercontent.com/436317/151605674-c69b7dc1-65db-46f5-8bc0-01b320266d41.png)
![leader-65](https://user-images.githubusercontent.com/436317/151605676-d417ed51-cb1d-4789-9d62-34c03a58a646.png)

### 25-logo, 28-logo - 727800802

![leader-25](https://user-images.githubusercontent.com/436317/151605663-a3f4987e-df97-45b5-8a47-7edcebecd9d7.png)
![leader-28](https://user-images.githubusercontent.com/436317/151605664-b97bf0d8-e04e-4068-a29e-1750551c3e9a.png)

### 43-arm - 727887205

![leader-43](https://user-images.githubusercontent.com/436317/151605666-d698acd6-38d0-4bd7-863b-f8cd37f72380.png)

### 93-cube - 727890412

![leader-93](https://user-images.githubusercontent.com/436317/151605679-04c51232-e7ca-4973-8ee4-aeec223d28d3.png)

### Subway films - 727890736

From https://github.com/PDP-10/its/issues/2107#issuecomment-1024157119 - two different clips.

![leader-subway1](https://user-images.githubusercontent.com/436317/151605681-f49678be-27ca-433b-bac0-c51c9402d566.png)
![leader-subway2](https://user-images.githubusercontent.com/436317/151605690-a5cb73ef-4520-42ce-8a0f-7db1df1cd27b.png)

**Comment by larsbrinkhoff** [comment]
Thanks a lot for the numbers, @atsampson!

Pointer to the Greenblatt transcriptions you made:  
http://stuff.offog.org/private/greenblatt.html
