### ISSUE TITLE
Datacomputer notes

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#1904]
See #812 (DFTP), #811 (DCSTAT).

http://www.dtic.mil/dtic/tr/fulltext/u2/a015125.pdf

The Datacomputer was a TENEX machine with a terabit memory.

![datacomputer](https://user-images.githubusercontent.com/775050/87145623-e24a4080-c2a9-11ea-90e2-42cd217b2374.png)

**Comment by larsbrinkhoff** [comment]
Email conversations about the Datacomputer:  
https://www.saildart.org/FTP.MSG[1,LES]2  
https://www.saildart.org/FTP.MSG[1,LES]

**Comment by larsbrinkhoff** [comment]
"The datacomputer-A network data utility"

[datacomputer.pdf](https://github.com/PDP-10/its/files/4902616/datacomputer.pdf)

**Comment by BobKerns** [comment]
What a blast from the past.
It combined the capacity of a mid-range SD card with the retrieval times of AWS Glacier and the data transfer speeds of a slow typist. And was unavailable a lot.

**Comment by eswenson1** [comment]
Based on that non-endorsement, I take it you wouldn't recommend it to perform cloud-based backups my home network machines?

**Comment by larsbrinkhoff** [comment]
Some interesting data stored on the Datacomputer.  Basically the history of the CLU programming language up until 1978.  Where did it go?

```
The following files exist on the Datacomputer in the RWS directory.
The DMS directory is one of RWS, CLUCMP, CLUSYS, or CLU.

DMS file(s)                     DC file

ARC CLU-V2                      CLU-VERSION-2.ARCHIVE
AR1 -CLU-                       CLU-SYSTEM-VERSION-2.ARCHIVE
AR2 -TEST-                      CLU-TEST.ARCHIVE
AR5 CLUX&N                      CLUX-AND-NCLU.ARCHIVE
AR1 INLINE                      INLINE.ARCHIVE
AR1 PARS23                      PARSER-VERSION-2-AND-3.ARCHIVE
AR4 -PSW-                       PSW.ARCHIVE
AR3 V2NBIN                      NBINS-VERSION-2.ARCHIVE
AR6 X&NBIN                      NBINS-CLUX-AND-NCLU.ARCHIVE
AR7 NCLUMU                      NCLUMUD.ARCHIVE
AR9 TRANS                       TRANS.ARCHIVE
various FBINS                   FBINS.ARCHIVE
CLUSAV 2.16                     CLU-VERSION-2-16.SAVE
CLUMUD 2.0                      CLU-SYSTEM-VERSION-2-0.SAVE
CLUSAV 3.0X                     CLU-VERSION-3-0X.SAVE
AR1 BASE                        CLU-VERSION-3-BASE.ARCHIVE
AR2 PARSE                       CLU-VERSION-3-PARSE.ARCHIVE
AR3 CHECK                       CLU-VERSION-3-CHECK.ARCHIVE
AR4 CODER                       CLU-VERSION-4-CODER.ARCHIVE
```

CC @brfid

**Comment by larsbrinkhoff** [comment]
Terabit Memory file format, by @nsdecicco.  
https://ncar.github.io/TBMconv/files/tbm.pdf

**Comment by larsbrinkhoff** [comment]
@macrakis, I saw your Wikipedia article about the Datacomputer.  Maybe there's something here you can use.

**Comment by macrakis** [comment]
> @macrakis, I saw your Wikipedia article about the Datacomputer. Maybe there's something here you can use.

Thanks for the ping! I created that article for two reasons:

- To serve as a canonical target for mentions of the Datacomputer elsewhere in Wikipedia.
- As a seed which might grow into a fuller article with the contributions of interested people, whether historians of computing, or people who actually worked with it or on it in the day.

So please feel free to contribute to that article!

             -s
