### ISSUE TITLE
Muddle version history

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#1911]
Trying to find dates for Muddle versions.

**Comment by larsbrinkhoff** [comment]
| Version | Date | Source
| --- | --- | ---
| 50 | 1975-09-17 | MAPS3: SYS1; TS MUD50
| 51 | 1975-10-14 | MAPS3: SYS1; TS MUD51
| 52 | 1975-12-12 | MAPS3: SYS1; TS MUD52
| 53 | 1976-04-24 | MAPS3: SYS1; TS MUD53
| 54 | 1977-07-01 | MAPS3: MUDSAV; TS MUD54
| 55 | 1979-04-06 | MAPS3: MUDSAV; TS MUD55

**Comment by larsbrinkhoff** [comment]
The ".TAPE" data is from .TAPE*n* files from DM, which records all backed up file names and timestamps.

**Comment by larsbrinkhoff** [comment]
The 1990 snapshot from KS10 AI has an earlier Muddle 54 date in the MAPS3 directory.

**Comment by larsbrinkhoff** [comment]
@36bit, do you have any input to this?

**Comment by 36bit** [comment]
> do you have any input to this?

Not really. The dates you have for 54 (ITS version) and 104 (Tenex and Tops-20 versions) and 55 (ITS version) and 105 (Tenex and Tops-20 versions) seems consistent with the multiple versions of TR-293 that I have.

**Comment by larsbrinkhoff** [comment]
Added version 42 from a Project MAC progress report.

**Comment by larsbrinkhoff** [comment]
There are two files from AI called MUDDLE; TS MUDDLE, from June and December 1972.  But the newer says `MUDDLE ^?^?^?^?^?^?^?^?^?^?^?^?^?^?^?^?^?^? IN OPERATION.` and the other doesn't have a starting address.

**Comment by larsbrinkhoff** [comment]
Information about Muddle 56 from @taa01776:

```
To:            (FEATURE MUDDLE) at MIT-DMS
From:          TAA at MIT-DMS (Timothy A. Anderson)
Subject:       FEATURE MUDDLE
Message id:    <[MIT-DMS].99684>

Originated:    4 Feb 79 at 0013 EST
Received:      4 Feb 79 at 0015 EST

In preparation for (choke) muddle 56, and as further additions to  muddle
105, I changed MAIN, MUDITS, and MUDEX as follows:
1) VALRET will take a fix:  10X/20X does a HALTF; ITS does a .BREAK 16,
   with the fix as the effective address.
2) On 10x/20x, VALRET does appropriate RSCANs (will this work on 10x?)
   such that the string returned will really be read by the superior.
3) New SUBRs XUNAME and XJNAME, similar to UNAME and JNAME (on 10x/20x
   there's no distinction).
4) UNAME and JNAME will 'work' on 10X/20X:  UNAME returns the name of
   the logged-in directory; JNAME returns the GETNM name of the process
   (which is set by the EXEC or somebody at startup).
        -taa

**Comment by larsbrinkhoff** [comment]
Muddle 31 added.

**Comment by larsbrinkhoff** [comment]
Added TS MUDDLE with unknown versions from ToTS tapes 3100150, 3100151, and 3100015.

**Comment by atsampson** [comment]
If you find an ITS Muddle executable from version 54 or earlier, it's likely that it won't work in a modern emulator (or a real PDP-10!) because it assumes that `POP TP,TP` means `MOVE TP,(TP)` - this seems to have been an MIT CPU modification. The misbehaviour is pretty obvious:

```
MUDDLE 54 IN OPERATION.
LISTENING-AT-LEVEL 1 PROCESS 1
<QUIT>$
9265
<+ 3 4>$
9305
```

(that is, any bracketed expression is read as a `FIX` - it's because `GOBBLE` in the `READ` code pushes a load of temporary `FIX`es followed by the original `TP` onto the `TP` stack, and `FINID` expects `POP TP,TP` to remove them all).

This was fixed somewhere between 54 and 56 by substituting `MOVE TP,(TP)`; you can do the same as a binary patch.

**Comment by atsampson** [comment]
There are four instances of POP TP,TP in Muddle 54 - GLOSEG-3, FINID, CBYST+4 and CARIT1+10. In the [1973 TS OMUDDL](https://github.com/PDP-10/muddle/blob/master/MUDDLE/ts.omuddl), there's just GLOSEG-3 and FINID. I found these by searching dis10's output, but DDT's `$w` search also works:

```
*:omuddl
MUDDLE IN OPERATION.
LISTENING-AT-LEVEL 1 PROCESS 1
<+ 3 4>$
10469
^Z
:kill

*:job omuddl
*:load ts omuddl
*pop tp,tp$w
DOT1+11/   POP TP,TP
FINID/   POP TP,TP
*dot1+11/   POP TP,TP   move tp,(tp)
findid/   POP TP,TP   move tp,(tp)
pop tp,tp$w
*:pdump ts omfix
*:kill

*:omfix
MUDDLE IN OPERATION.
LISTENING-AT-LEVEL 1 PROCESS 1
<+ 3 4>$
7
```

**Comment by eswenson1** [comment]
Thanks, @atsampson

**Comment by larsbrinkhoff** [comment]
TENEX Muddle from June 1975: https://github.com/PDP-10/muddle/blob/master/sumex/muddle.source-list.750610.2.txt
