### ISSUE TITLE
SYSENG; DIRDEV 86 should really use version number of 87

### ISSUE THREAD

**Issue by eswenson1** [PDP-10/its#1944]
The original version of SYSENG; DIRDEV 86 on MC is different than what we have in our source tree. Our version includes a Y2K fix that the original didn't have. However, we didn't bump the version number. This ticket is to update the version number to 87.

**Comment by larsbrinkhoff** [comment]
The same commit also clobbered PEEK 639.

Might as well check if anything else was updated around that time.

**Comment by eswenson1** [comment]
I guess we can't really do anything about PEEK, since we're advanced  beyond the one you clobbered. Also, I assume you mean PEEK 629, since we're at PEEK 631 now.  Or did you mean something different?

**Comment by larsbrinkhoff** [comment]
You're right, I meant 629.
