### ISSUE TITLE
Current master (3eb08a071c469a2237ee8f41a212d0734b79f113) don't build no more

### ISSUE THREAD

**Issue by athornton** [PDP-10/its#1954]
....stuff stuff stuff

```
*:job midas
!
*:load sysbin; midas 324bin
*purify$g
:$Purified$pdump$
DSK: SYS; TS MIDAS    midas;ts 324
*:kill
*:job midas
!
*:load sysbin; midas 77bin
*tsymgt+5/   P   10
purify$g
:$PURIFIED$
*:pdump midas; ts 77
*:kill
*:midas;77
MIDAS.77
MIDAS; TS 73_MIDAS; MIDAS 73
DSK:MIDAS 73 MIDAS;
FILE NOT FOUND
```

(`Makefile:114: recipe for target 'out/klh10/rp0.dsk' failed`)

**Comment by larsbrinkhoff** [comment]
Thanks.  We do run a CI build with KLH10, but it has reduced scope.  I'm testing a full build now.

Which platform do you use?  It seems KLH10 may be less stable on MacOS.  And there is a problem running on Linux in a virtual machine.

**Comment by larsbrinkhoff** [comment]
The error message means the file MIDAS; MIDAS 73 is missing.  If that's the case, it's strange why that would be.  Did you make a clean build?  "make clean all ..." should ensure any previous build artifacts are removed.

If you build in a previous checked out repository, make sure to update all subrepositories.

**Comment by larsbrinkhoff** [comment]
I cloned out a fresh clean repository and built it with "make clean all EMULATOR=klh10", on a Ubuntu 16 machine.  I got past the point above:

```
:$PURIFIED$
*:pdump midas; ts 77
*:kill
*:midas;77
MIDAS.77
MIDAS; TS 73_MIDAS; MIDAS 73

MIDAS 6
2101 WORDS INITIALIZATION CODING.
MIDAS 6
CONSTANTS AREA INCLUSIVE
FROM   TO
14343   14773
15717   15721
:KILL 
```

**Comment by athornton** [comment]
I'll try a reclone.  I'm on a Pi so I have to bump timeouts up in places, but other than that I should be able to do a clean build

**Comment by larsbrinkhoff** [comment]
Any update on this?

**Comment by athornton** [comment]
I totally forgot.  Um, I'll give it a shot this weekend?

**Comment by larsbrinkhoff** [comment]
That's perfect.  Thanks!

I think it's a random fluke, or maybe related to the lower speed of the Pi.  I have a Pi 4 with the file system on a USB stick, and it's fine for building ITS.  A 2 would probably be difficult.

**Comment by athornton** [comment]
Timeout.  Don't know if I got farther.  I'll bump up the timeouts and try again.

**Comment by athornton** [comment]
Completed successfully with no timeout less than 1000.  Closing as nonreproducible.

**Comment by larsbrinkhoff** [comment]
Thanks for checking!  I wonder if this is a use case to be supported,
or if would be better to provide ready built disk images for download.
(Or both.)

**Comment by athornton** [comment]
I don't actually have all that much interest in generating a new image every time the ITS folks add another piece of the system, but if you were to provide prebuilt images, you almost certainly want to do it with git-lfs or somesuch rather than having multiple revisions of images pile up in the regular repo.  That will make pulling and cloning super-painful if you do (see also: https://github.com/A2osX/A2osX/issues/159 ).  

Certainly, for just running stuff at mvsevm.fsf.net I'd rather just pull a new prebuilt image every so often.  

I don't think there's a good portable way to ask "how long should that delay timeout be?"--for instance /proc/cpuinfo is Linux-specific and it's not like summing bogomips across processors is at all reliable, and anyway if you happen to be running in a container, although /proc may well be bind-mounted it's going to show you the host numbers, not your container's available CPU....

**Comment by drboone** [comment]
Github will block pushes once the repo reaches some preset size.  2 GB maybe?  I've hit it a few times.
