### ISSUE TITLE
MacOS+SIMH build stops in lisp.tcl.

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#1955]
@erkyrath reports a SIMH build problem on MacOS I have never seen before.  It times out in lisp.tcl when it's deleting UNFASL files:

```
@delete * unfasl
Delete? (Y or N): yes.
   %PRINT UNFASL
   6BIT   UNFASL
   APROPO UNFASL
   ARITH  UNFASL
   ARYFIL UNFASL
   ATAN   UNFASL
   AUTODF UNFASL
   BBOOLE UNFASL
   BENCH  UNFASL
   BINPRT UNFASL
   BREAK  UNFASL
   BS     UNFASL
   CARCDR UNFASL
   CHAR   UNFASL
   COMRD  UNFASL
   COMRED UNFASL
   DBG    UNFASL
   DEBUG* UNFASL
   DEFSTA UNFASL
   DOCTOR UNFASL
   DOW    UNFASL
   DPRINT UNFASL
   DRIBBL UNFASL
   DUMPGC UNFASL
   FAKE-S UNFASL
   FASDMP UNFASL
   FFORMA UNFASL
   FILBIT UNFASL
   FLOAD  UNFASL
   FONTRD UNFASL
   FOR    UNFASL
   GENFNS UNFASL
   GPRINT UNFASL
   GRAPH$ UNFASL
   GRAPHA UNFASL
   GRAPHM UNFASL
   GRAPHS UNFASL
   GRAPHT UNFASL
   IMPDEF UNFASL
   IOTA   UNFASL
   LAUGH  UNFASL
   LETFEX UNFASL
   LETS   UNFASL
   LINERE UNFASL
   LISPM  UNFASL
   LISPT  UNFASL
   LOOP   UNFASL
   LSPMAC UNFASL
   LUSETS UNFASL
   MORE   UNFASL
   NSHARE UNFASL
   OCTAL  UNFASL
   OD     UNFASL
   OPTDEF UNFASL
   PHSPRT UNFASL
   PRIVOB UNFASL
   PROMPT UNF
The last command timed out.
make: *** [out/simh/rp0.dsk] Error 1
```

**Comment by larsbrinkhoff** [comment]
A second run times out in virtually the same place:

```
   OD     UNFASL
   OPTDEF UNFASL
   PHSPRT UNFASL
   PRIVOB UNFASL
   PROMPT UN
The last command timed out.
make: *** [out/simh/rp0.dsk] Error 1

**Comment by larsbrinkhoff** [comment]
A succesful build looks like this:

```
   OD     UNFASL
   OPTDEF UNFASL
   PHSPRT UNFASL
   PRIVOB UNFASL
   PROMPT UNFASL
   QTRACE UNFASL
   READS  UNFASL
   REDO   UNFASL
   SAVE   UNFASL
   SETS   UNFASL
   SHARAB UNFASL
   SHARE  UNFASL
   SIXBIT UNFASL
   SMURF  UNFASL
   SPLIT  UNFASL
   STACK  UNFASL
   STATTY UNFASL
   STEPMM UNFASL
   STEPR  UNFASL
   STRING UNFASL
   SUN    UNFASL
   TIME   UNFASL
   TRAP   UNFASL
   TTY    UNFASL
   TTYHAK UNFASL
   WIFS   UNFASL
   WINDOW UNFASL
@q

:KILL

**Comment by larsbrinkhoff** [comment]
@erkyrath, if you want to try some quick workarounds, I have some suggestions:

- Comment out the call to lisp.tcl *and* also macsyma.tcl, scheme.tcl from the script build/build.tcl.  The intent is that the other scripts shouldn't depend on lisp.tcl, but this has not been tested.
- Try SIMH KA10 and/or KLH10: `make clean all EMULATOR=pdp10-ka` or `EMULATOR=klh10`

**Comment by erkyrath** [comment]
First test: commented out lisp.tcl and macsyma.tcl.

    #source $build/lisp.tcl
    #if {$env(MACSYMA)=="yes"} {
	#source $build/macsyma.tcl
    #}

Result was that it timed out somewhere else.

```
ENTERING BUILD SCRIPT: SCHEME
Wed Sep 16 11:47:04 EDT 2020

 
*complr^KSYS: SYS3; TS COMPLR - FILE NOT FOUND

The last command timed out.
make: *** [out/simh/rp0.dsk] Error 1
```

**Comment by larsbrinkhoff** [comment]
Comment out scheme.tcl too.  COMPLR is the Maclisp compiler, which is built by lisp.tcl.

**Comment by erkyrath** [comment]
Second test: `make all EMULATOR=pdp10-ka`

This failed with a C compiler error:

```
cc -O3   -c -o ka11.o ka11.c
ka11.c:258:6: error: expected ';' after expression
        uint by;
            ^
            ;
ka11.c:258:2: error: use of undeclared identifier 'uint'
        uint by;
        ^
ka11.c:258:7: error: use of undeclared identifier 'by'
        uint by;
             ^
```

(looks like `uint` is not defined)

**Comment by erkyrath** [comment]
(As you see I am trying things one at a time! I will catch up, don't worry.)

**Comment by larsbrinkhoff** [comment]
The `unit` seems like a problem in the TV-11 emulator.  I don't see it defined anywhere, so maybe you uncovered a GCC-ism in the code which clang doesn't support.  In any case, tv11 isn't needed to just build ITS, so you can either skip it or add a `typedef unsigned int unit;` somewhere.

**Comment by erkyrath** [comment]
Now trying `EMULATOR=simh` with lisp.tcl, macsyma.tcl, scheme.tcl commented out.

I found that the build does a 

    make -C tools/vt05 vt52

...which required SDL2 to be installed. (Despite the readme claiming it wouldn't be.)

I've installed that; restarting build.

**Comment by erkyrath** [comment]
Success!

Hopefully the notes above are helpful.

**Comment by larsbrinkhoff** [comment]
Thank you.  I'm glad you could make it work.

The underlying problem remains unsolved, but I don't have a Mac so I can't reproduce it.  There is a Tavis CI build on MacOS, but it's not a full build due to time restrictions.  It would be good if a CI build could be arraged which accepts build times in excess of 60 minutes.  (Or maybe if the build could be rearranged to run in several steps?)
