### ISSUE TITLE
Make fails trying to remove tools/tek4010/tek4010

### ISSUE THREAD

**Issue by pgalbraith** [PDP-10/its#1970]
```
MAIN BUILD SCRIPT DONE
Tue 24 Nov 2020 06:03:49 AM EST
touch out/pdp10-kl/stamp
rm tools/tek4010/tek4010
rm: cannot remove 'tools/tek4010/tek4010': No such file or directory
make: *** [Makefile:290: tek-hack] Error 1
```

**Comment by larsbrinkhoff** [comment]
The tek4010 comes with a binary checked in.  In order to build it from source, the "its" Makefile first removes the binary.  Of course, `rm` fails if there is no binary file.  Just ignoring the error should fix the build.  I posted #1971 to do this.

**Comment by rcornwell** [comment]
There is an option to rm that does not warn about file not existing,
