### ISSUE TITLE
build timeout

### ISSUE THREAD

**Issue by pgalbraith** [PDP-10/its#1973]
tail of console output from my last build ... any idea where the timeout setting is for this?

```
:KILL
*:job maint
!
*:load maint; part a
*:start
$L PART B MAINT;
*$G
$L PART C
*$G
$L PART E
*$G
$L PART F
*$G
$L PART G
*$G
$L PART I
*$G
$L PART J
*$G
$L PART K
*$G
$L PART L
*$G
$L PART M
*$G
$L PARt a
*$G
$L PART B MAINT;
*$G
^Z
6512)   JUMP 6513   :kill
*:midas dsk0:maint;_tst342
TST342 - Type 342 character set test.
TST342 - Type 342 character set test.
Constants area inclusive
From    To
146     146
Run time = 0.00
1442 Symbols including initial ones (53% used)

:KILL
*:midas maint;ts 1proc_1proc test
ONE-PROCEED TEST
ONE-PROCEED TEST
Constants area inclusive
From    To
137     171
205     206
Run time = 0.00
1439 Symbols including initial ones (53% used)

:KILL
*:maint;1proc
:$TEST FAILED$
*:KILL
*
The last command timed out.
make: *** [Makefile:120: out/pdp10-kl/rp04.1] Error 1

```

**Comment by larsbrinkhoff** [comment]
Yes, it's the "1proc" part of misc.tcl.  It's not a matter of time; the script is looking for the string "SUCCESSFUL", but the test outputs "TEST FAILED".

It appears the CPU "one-proceed" (single step) feature isn't working in your build.  I see you are using the pdp10-kl emulator, which is not as well tested as the others.  However, it *should* work and it does in the CircleCI build.

Does this happen every time you build, or just sometimes?  What host machine and operating system do you use?

**Comment by larsbrinkhoff** [comment]
By the way, I don't want to discourage use of the KL10 emulator.  If that's what you want to use, that's great and I'd like to help out with any problems.

**Comment by pgalbraith** [comment]
No it doesn't happen every time, the build ran to completion on the next try.

**Comment by larsbrinkhoff** [comment]
I'll copy @rcornwell, but I maybe there isn't much we can do if the problem is not reproducible.

**Comment by pgalbraith** [comment]
Likely something to do with the fact that I'm building in fairly slow virtual machine.

**Comment by larsbrinkhoff** [comment]
Any luck?

**Comment by pgalbraith** [comment]
Gah sorry I left this open, I'm not even near a Windows machine at the moment but I'll assume it's fine :-)
