### ISSUE TITLE
M.F.D full

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#1997]
I'm dumping a lot of experimental files onto my TT ITS, and now I finally reached the limit on the number of directories in the M.F.D.

Let's consider raising the limit.

**Comment by larsbrinkhoff** [comment]
I think it's messy to increase the number of directories on an existing system, because the number is built into ITS, SALV, and DSKDMP.  Do update KA ITS etc, we will have to make new bootstrapping binaries.

**Comment by larsbrinkhoff** [comment]
I'm considering adding one more round of rebooting and formatting disks. So the bootstrap ITS and target ITS can have different disk parameters.  This would probably add a bit to the build time, sigh.

**Comment by eswenson1** [comment]
Isn't this a similar operation as when you want to increase the number of disk packs on a system? You update dakdmp, (n)salv, and ITS and reboot? If so, I think this is only really needed for systems like yours and mime. Maybe we should just document the procedure?

Or is disk pack reformatting necessary in order to increase the MFD size? If the latter, then, of course it would be better to do when the system is first built.

**Comment by larsbrinkhoff** [comment]
The number of free directory slots is maybe around 10, so I think it's best to address this now even for the generic GitHub build.

I was assuming the worst: that increasing the MFD size would make the disk format incompatible.  But I haven't checked.

I took a closer look at the bootstrap procedure, and I don't think reformatting the disks will add much time to the build.

Current procedure:
1. Run SALV to format disks.
2. Load a minimal system from tape, including ITS, DDT, and MIDAS.
3. Boot old ITS.
4. Load a few sources from tape.
5. Build a new ITS and supporting tools.
6. Reboot new ITS.
7. Etc.

New procedure:
1. Run SALV to format disks.
2. Load a minimal system from tape, including ITS, DDT, and MIDAS.
3. Boot old ITS.
4. Load a few sources from tape.
5. Build a new ITS and supporting tools.
6. Save new binaries to tape.
7. Reboot into SALV to reformat disks.
8. Load binaries from 6.
9. Reboot new ITS.
10. Etc.

**Comment by eswenson1** [comment]
I didn't realize that the MFD resulting from DB build had only room for 10 additional directories. If that is the case, I completely agree that the build should increase the size of the MFD. But are you sure about the fact that only 10 directories can be created? On my ES system, I must have 30 or so directories that I've created.

**Comment by larsbrinkhoff** [comment]
I forgot to mention this is for "KA" ITS, i.e. running the KA10 emulator.  The NUDSL parameter is only 250.  All others has it set to 500 which is much more comfortable.  So it makes sense to solve this for the KA10 build and not mess with the others.

I made a fresh build and counted the number of directories.  They are 218, so the number is actually closer to 30, not 10.

**Comment by eswenson1** [comment]
Ahhh.  I don't "do" KA-10 (being an MC user, I still have disdain for them!). That's why I have much more room in my MFD.

**Comment by larsbrinkhoff** [comment]
Will soon be fixed by #2052.
