### ISSUE TITLE
Weird integer math in :lisp

### ISSUE THREAD

**Issue by owainkenwayucl** [PDP-10/its#2000]
I'm not sure what's going on here.

I'm running ITS as built by the makefiles in this repo and lisp running on ITS seems to be unable to do integer math properly.

It's not obvious stuff (e.g. very big numbers) but some serious problems at small numbers e.g.:

```
*:lisp

LISP 2154
Alloc? n


* 
(* 3 7)
25 

```

It's fine with floats e.g.

```
(*$ 3.0 7.0)
21.0 
```

I'm running on simh-ka built by this repo's build systems, on a raspberry pi3 (if the latter matters which it shouldn't...)

**Comment by larsbrinkhoff** [comment]
The default is octal notation for fixnums.

**Comment by owainkenwayucl** [comment]
Ah hah!

I was confused because the value of `base` is 10.

**Comment by owainkenwayucl** [comment]
Just for anyone who reads this and is as confused in future.

`base` is 10 because in octal 8 is 10.

If you want decimal, set base to 12.

**Comment by larsbrinkhoff** [comment]
The usual way to force decimal is to add a period after the number.  If there is no fractional part, it parses as a fixnum.  This is also true for MIDAS.

Hey, yours is issue number 2000! :tada:
