### ISSUE TITLE
OD runs into GC problems

### ISSUE THREAD

**Issue by heasm66** [PDP-10/its#2012]
If I inspect a file with OD it always stops at about the adress 4300 (octal) with a GC error:

`:od madman; madadv dec12`

    004354:  777551055347     -227,,55347    0L9S9M  _]I%KG  ^?vHZs
    004355:  466031342532  -311747,,342532   RZ0LAX  FP9<5:  MAKE-
    004356:  406072444636  -371706,,-333142  7 LVY$  @PZDF>  ACTIO
    004357:  470000000000  -310000,,0        UHAOZV  G       N....
    004360:  440015000000  -337763,,0         0C8ZV  D -     H.h..
    004361:  000010777777       10,,-1         ZXLE    (___  ..G^?^?
    004362:  000000000000        0,,0                        .....
    004363:  000000000000        0,,0                        .....
    004364:  777551055347
    ;BKPT GC-OVERFLOW

**Comment by larsbrinkhoff** [comment]
It's an early attempt at Maclisp programming by me, and it may well be deficient.  I don't see any obvious consing going on.

If you want to dissect the SAVE files, maybe my PDP-10 disassembler may be more useful or robust.  It's here: https://github.com/larsbrinkhoff/pdp10-its-disassembler.  You would typically use it with the `-r` option to disassemble a file without regard to the file format.

**Comment by heasm66** [comment]
I just wanted to extract the text to the "US News & Dungeon Report" from the Zork-files that crashes. For that task it worked by using PRINT.

Is the LISP code available somewhere. I could make a crack at it in MDL...

**Comment by larsbrinkhoff** [comment]
Sure, it's here: https://github.com/PDP-10/its/blob/master/src/libdoc/od.3

**Comment by heasm66** [comment]
I'm a bit of a newbie on LISP, but I experimented a little running OD interactive.

Default program stops with an gc-overflow error at about line 3500:

     003533:  002334777777     2334,,-1       26IJU%   3<___  .Mg^?^?
     003534:  000034000000       34,,0         1XQJV    <     ..`..
     003535:  773446025307    -4332,,25307    Z4QI$M
     ;BKPT GC-OVERFLOW

Rewriting a function, PRINT-ASCII, to use less variables using bitwise operations instead:

    (defun clean-ascii (ch)
      (if (< ch 32.) (setq ch "."))
      ch)

    (defun print-ascii (word)
      (setq word (quotient word 2))
      (let ((result nil))
        (push (clean-ascii (logand word 177)) result)
        (push (clean-ascii (logand (lsh word -7.) 177)) result)
        (push (clean-ascii (logand (lsh word -14.) 177)) result)
        (push (clean-ascii (logand (lsh word -21.) 177)) result)
        (push (clean-ascii (logand (lsh word -28.) 177)) result)
        (format t "~A  " (implode result))))

    004425:  000034000000       34,,0         1XQJV    <     ..`..
    004426:  772326024167    -5452,,24167    XO1PBM  _36"AW  ~M0(;
    004427:  777551055347     -227,,55347    0L9S9M  _]I%KG  ^?vHZs
    004430:
    ;BKPT GC-OVERFLOW

This one runs a little longer, but not much.

Then I found this in the [PitManual](http://www.maclisp.info/pitmanual/system.html):

    (SETQ GC-OVERFLOW '(LAMBDA (X) T)) ;Suppress GC-OVERFLOW breaks

And then it runs much longer and and exits with another error:

    125244:  000052125244       52,,125244    3BRMB    J*JD  ..Q*R
    125245:  777774075240       -4,,75240    0.B$VV  __\'J@  ^?^?`zP
    125246:  777774074230       -4,,74230    0.B$IV  __\'B8
    ;FIXNUM STORAGE CAPACITY EXCEEDED

I then tried  to make an explicit call to GC to force garbage collection at intervals. But that didn't help much:

    (defun print-binary (file)
      (with-open-file (input file '(single fixnum in))
      (eoffn input #'goodbye)
      (format t "~&         ~12A  ~16A  SQUOZE  SIXBIT  ASCII~%"
          "OCTAL" "HALF-WORDS")
      (loop for i from 0 while t do 
        (print-file-offset i)
          (if (= (remainder i 1000.) 0) (gc))
          (read-word input))))
	  
    125731:  777774075470       -4,,75470    0.B$ZN  __\'LX  ^?^?`{.
    125732:  000023000000       23,,0         0.V$F    3     .....
    125733:  777775126002       -3,,126002   0.G9LH  __]*P"  SYMBOL BLOCKSTORAGE CAPACITY EXCEEDED BEYOND RECUPERATION
    ;MAJOR RESTART UNDERTAKEN

I'm open for suggestions from anyone with battling GC in MacLisp... and I'm still tempted to rewrite it in MDL to see if MDL will handle it differently (better)...

**Comment by heasm66** [comment]
One rewrite to try would be to do everything in the same function and thereby reusing the same variables (word, ch, ...) repeatadly. This could maybe stop the program from allocating new variable space. The cost being that one would lose much of the nice modularity...

**Comment by heasm66** [comment]
Allocation more space for SYMBOL and FIXNUM witth:

    (comment SYMBOL 12000 FIXNUM 28000)

Didn't help. It still runs out of resource space at around line 125000.

**Comment by larsbrinkhoff** [comment]
I seem to recall that fixnums in Maclisp are allocated, rather than just
a special kind of tagged pointer.  If so, it makes sense that computing
a large number of fixnums would run out of memory.  Then the question
is, how do you free up a fixnum when you are done with it?

**Comment by eswenson1** [comment]
The same way you free up a CONS or anything else? Don't have any live references to it and perform a GC?

I wonder if FIXNUM space is perhaps not GC'able? Maybe ask some MacLISP guru?

As already suggested maybe try to rewrite code so that you don't have so many distinct fixnum variables, but reuse them?

**Comment by larsbrinkhoff** [comment]
Maybe I'm misunderstanding, but is it really the case that fewer
*variables* will reduce consing?  I thought it was the number of
*values* that need reducing.  Not that I see that there should be many
live fixnum values.

As for symbols, they probably run out of space due to the use of
IMPLODE.  I understand some Lisp implementations don't even GC symbols.
Maybe there's a way to implode an uninterned symbol?  Or make a string
some other way.

**Comment by larsbrinkhoff** [comment]
@heasm66, can you keep the call to `(gc)` but replace `intern` with `maknam` (see http://www.maclisp.info/pitmanual/symbol.html#10.10.2)?

**Comment by eswenson1** [comment]
You are right that it I would be fewer values, since all variable referencing the same fixnum would share the same memory.

**Comment by heasm66** [comment]
@larsbrinkhoff You're right. It's the `implode` that is the culprit. If I replace `implode` with `maknam` (three instances), the program runs all the way through (even without any explicit call to `(gc)`.

The file `MADMAN;MADADV DEC12` (128 838 36-bit words, 543 771 bytes) take about 20 minutes, interactivly, on my machine.

    354003:  000000000000        0,,0                        .....
    354004:  000000000000        0,,0                        .....
    354005:  000000000000        0,,0                        .....
    354006:  000000000001        0,,1             0       !  .....
    354007:  END OF FILE

I also made a conversion of the program into MDL. It's over [here](https://github.com/heasm66/ITS-MDL-MISC/blob/main/MDL-OD/MDL-OD.1). The same file runs a little slower and it takes about 37  minutes for the MDL version.

One other thing a noticed is that in the ASCII-part it prints the char 127 (DEL) and the SIXBIT-part print chars lower than 32 + char 127. These unprintable characters maybe should be cleaned from the output?

**Comment by larsbrinkhoff** [comment]
Thanks!  Would you do the honors of sending a pull request?

Yes, I think DEL should be replaced with . like the control characters.

**Comment by larsbrinkhoff** [comment]
I suppose for a fair comparison both implementations should be compiled.  But for now only the Lisp compiler is available.

**Comment by heasm66** [comment]
@larsbrinkhoff I need to be a part of this group to be able to create branches. Could you add me?

Would you like me to increase the version number on the file (od.3 --> od.4) as the convention seems to be?

I ran both the Lisp and MDL versions interctivly, so the time difference is there... but there is quite a lot of crude format calculations going on in the MDL version that leave pleanty of room for optimization.

**Comment by larsbrinkhoff** [comment]
You have been invited!  Feel free to make branches in this repository if you like.  Use a branch name prefix like "heasm/".

Yes, please increase the version number.

**Comment by larsbrinkhoff** [comment]
Fixed by #2013.
