### ISSUE TITLE
More information on image processing on the PDP-6?

### ISSUE THREAD

**Issue by stephencwelch** [PDP-10/its#2025]
Apologies in advance if this question is too off topic for this repo, please feel free to remove if so.

I’m working on a project for my YouTube channel [Welch Labs](https://www.youtube.com/channel/UConVfxXodg78Tzh5nNu85Ew), and am trying to learn more about how images would have been stored and manipulated on DEC PDP computers in the 1960s. I’m specifically interested in the [MIT Summer Vision Project](https://dspace.mit.edu/handle/1721.1/6125), which based on my research thus far, appears to have used PDP-6 and an image dissector. I’m hoping to get a better sense for what it was really like to work with images on these machines, this will help me tell a better story about the origins of computer vision, and allow me to make deeper and clearer connections to today’s technology. Here's what I'm trying to learn:

- How exactly would the output of the image dissector be stored?  I know that the PDP-6 used 36 bit words, would the dissector record each pixel value as a word?  Or perhaps a word held more pixels values with less bit depth?
- How could/would a machine like the PDP-6 handle the 2-D component of the image data (e.g. unravel the columns into a long vector?) I’m guessing there were no image format standards at the time?
- What media would images have generally been stored on in the 1960s on a PDP machine, paper tape?
- I guess there was probably some time of “data acquisition” program that was run with the image dissector to store the image data? Would this have been written in assembly, something else? Would this routine have been provided by the image dissector manufacturer?
- Shifting to how the image would have been processed, what would implementing an image processing algorithm like [Robert’s Cross](https://en.wikipedia.org/wiki/Roberts_cross) have consisted of? What language would a program like this likely have been written in? What were the mechanics of writing a program like this? Was there a good way to visualize the output? Was it possible to print the processed image? 

Any answers or connection to folks who may have answers is greatly appreciated - thank you!

**Comment by larsbrinkhoff** [comment]
Hello,

I think your question is appropriate and interesting!  First off, take a look at the information here: https://github.com/PDP-10/its/issues/1487

**Comment by stephencwelch** [comment]
Woah, thanks @larsbrinkhoff, this #1487 is awesome! I'm going to review the documents you cited [here](https://github.com/PDP-10/its/issues/1487#issuecomment-465448996) and [here](https://github.com/PDP-10/its/issues/1487#issuecomment-465455450) first and see how many of my questions I can answer.

**Comment by larsbrinkhoff** [comment]
I can answer some questions:

- The storage medium available in 1966 would have been DECtape (aka Microtape).  Note that it only stores 576 blocks of 128 36-bits words, so it would not be able to store much image data.

- Any code was probably written at the AI lab.  Much of the hardware was made there too.  The main language would have been  MIDAS assembly language.  Some AI memos hints at Lisp programs too.

- Visualisation was done on a Type 340 display.  It was a random scan, point plotting CRT (vector display).  There were 1024x1024 addressable points, and points could have seven different intensity levels.

**Comment by stephencwelch** [comment]
Great, thanks @larsbrinkhoff! I'm digging deeper into [AIM-75](https://github.com/larsbrinkhoff/its-archives/blob/master/ailab/AIM-075.pdf), and [AIM-90](http://www.bitsavers.org/pdf/mit/ai/aim/AIM-090.pdf). 

[AIM-75](https://github.com/larsbrinkhoff/its-archives/blob/master/ailab/AIM-075.pdf) looks like it might hold some more of the information I'm looking for. Looks like the images from the Vidisector would have been dumped right into core memory:

<img width="1002" alt="Screen Shot 2021-04-15 at 8 04 40 AM" src="https://user-images.githubusercontent.com/5165996/114866589-c38d5300-9dc1-11eb-8e8d-cc7a4a59de0f.png">

I'm wondering how much core memory would have been available and type of physical memory this actually was (excuse my dumb question - flip flops or something?). I can dig more into this next. 

After seeing this diagram in [AIM-75](https://github.com/larsbrinkhoff/its-archives/blob/master/ailab/AIM-075.pdf), and [AIM-90](http://www.bitsavers.org/pdf/mit/ai/aim/AIM-090.pdf): 

<img width="1027" alt="Screen Shot 2021-04-15 at 8 11 09 AM" src="https://user-images.githubusercontent.com/5165996/114866949-33034280-9dc2-11eb-8d62-2e5007b70b0c.png">

I was hopeful that Minsky would describe the encoding mechanism for the image data ifself, but if I understand correctly what Minsky is describing here is the control protocol for the vidisector. I'm going to have a close look at the memo to see if I can glean anything else.

**Comment by larsbrinkhoff** [comment]
> I'm wondering how much core memory would have been available and type of physical memory this actually was

We know from other AI memos that in 1966 the PDP-6 had 16K memory (36-bit words).  A 256K memory was being installed but didn't work fully until summer 1967.  The type was core memory, see https://en.wikipedia.org/wiki/Magnetic-core_memory

I was hoping to find some information about the image storage format in https://dspace.mit.edu/bitstream/handle/1721.1/6152/AIM-146.pdf, but it only vaguely mentions floating-point and fixed-point numbers.  And maybe those are only what are presented to application programs, rather than files stored on tape.

There is a full list of AI memo titles and abstracts here: http://www.bitsavers.org/pdf/mit/ai/aim_index.txt  
Maybe you can search there for keywords.

**Comment by larsbrinkhoff** [comment]
https://dspace.mit.edu/bitstream/handle/1721.1/5882/AIM-113.pdf seems to say intensity values read from TV-B was 8 bits.
![tvb](https://user-images.githubusercontent.com/775050/114870374-64970080-9df8-11eb-8fee-fe7db3922f38.png)

**Comment by larsbrinkhoff** [comment]
The author of AI memo 113, Larry Krakauer, seems to have a very good memory for technical details although it was more than 50 years ago.  If you want to ask him, there is contact information here: http://ljkrakauer.com/

**Comment by swelchm** [comment]
Thanks @larsbrinkhoff  - lots of interesting threads here. 

1. I'm not familiar with the notation in your reference to [AIM-113](https://dspace.mit.edu/bitstream/handle/1721.1/5882/AIM-113.pdf), does 376<sub>8</sub>, mean octal? So, 254 in decimal?
2. Just reached out Larry Krakauer :crossed_fingers:
3. I took your advice and poked around the [full list of AI memos](http://www.bitsavers.org/pdf/mit/ai/aim_index.txt), I found [AIM-119](ftp://publications.ai.mit.edu/ai-publications/pdf/AIM-119.pdf), which has a really interesting reference list: 

<img width="905" alt="Screen Shot 2021-04-16 at 8 32 03 AM" src="https://user-images.githubusercontent.com/55189642/115024549-3d8b0e00-9e8e-11eb-87ae-ab432a1e4f5b.png">

2, 3, 4, and 5 look interesting, but I notice that these are largely internal memos, and googling around didn't turn much up in terms on the original documents - @larsbrinkhoff do you know if internal memos like this are generally available?

**Comment by stephencwelch** [comment]
Thanks @larsbrinkhoff  - lots of interesting threads here!

1. I'm not familiar with the notation in your reference to [AIM-113](https://dspace.mit.edu/bitstream/handle/1721.1/5882/AIM-113.pdf), does 376<sub>8</sub>, mean octal? So, 254 in decimal?
2. Just reached out Larry Krakauer :crossed_fingers:
3. I took your advice and poked around the [full list of AI memos](http://www.bitsavers.org/pdf/mit/ai/aim_index.txt), I found [AIM-119](ftp://publications.ai.mit.edu/ai-publications/pdf/AIM-119.pdf), which has a really interesting reference list: 

<img width="905" alt="Screen Shot 2021-04-16 at 8 32 03 AM" src="https://user-images.githubusercontent.com/55189642/115024549-3d8b0e00-9e8e-11eb-87ae-ab432a1e4f5b.png">

2, 3, 4, and 5 look interesting, but I notice that these are largely internal memos, and googling around didn't turn much up in terms on the original documents - @larsbrinkhoff do you know if internal memos like this are generally available?

**Comment by larsbrinkhoff** [comment]
Yes, it's octal.  Note 377 was also mentioned, so the full range is 0-255, i.e. 8 bits.

Try a search like `site:dspace.mit.edu "quick look"`.  I found these:  
https://dspace.mit.edu/bitstream/handle/1721.1/6127/AIM-102.pdf  
https://dspace.mit.edu/bitstream/handle/1721.1/6128/AIM-103.pdf  
https://dspace.mit.edu/bitstream/handle/1721.1/5898/AIM-110.pdf  
https://dspace.mit.edu/bitstream/handle/1721.1/5897/AIM-111.pdf

**Comment by stephencwelch** [comment]
Thanks @larsbrinkhoff, very helpful. 

I think I found some helpful information in [AIM-120](ftp://publications.ai.mit.edu/ai-publications/pdf/AIM-120.pdf), potentially relevant to my questions: 

> How exactly would the output of the image dissector be stored? I know that the PDP-6 used 36 bit words, would the dissector record each pixel value as a word? Or perhaps a word held more pixels values with less bit depth?
> How could/would a machine like the PDP-6 handle the 2-D component of the image data (e.g. unravel the columns into a long vector?) I’m guessing there were no image format standards at the time?

I believe that [AIM-120](ftp://publications.ai.mit.edu/ai-publications/pdf/AIM-120.pdf) basically describes Minsky's proposed image storage & access protocol (I'm wondering how much of this design made it into code in [AIM-146](https://dspace.mit.edu/bitstream/handle/1721.1/6152/AIM-146.pdf)). 

### AIM-120 Excerpt 1
<img width="885" alt="Screen Shot 2021-04-19 at 8 15 11 AM" src="https://user-images.githubusercontent.com/5165996/115234924-94d7eb00-a0e7-11eb-9e0d-46e796cf4896.png">
- I believe Minsky appears to be suggesting a bit depth of 10? My hunch here is that he's talking about using the 10 most significant bits form the 36 bit shift register of the vidisector (excerpt below)
- I'm curious what Minsky's comment about later systems being projective - is he perhaps referring to the projective geometry that would be used to map image coordinates to world coordinates for robotics applications?

### AIM-075 Excerpt 1
<img width="966" alt="Screen Shot 2021-04-19 at 8 24 57 AM" src="https://user-images.githubusercontent.com/5165996/115236004-d3ba7080-a0e8-11eb-9cd6-cb28f379d6f9.png">


### AIM-120 Excerpt 2
<img width="844" alt="Screen Shot 2021-04-19 at 8 15 21 AM" src="https://user-images.githubusercontent.com/5165996/115235362-17f94100-a0e8-11eb-9958-1f1808ebe7e2.png">
- Unless I'm mistaken this may be one of the earliest image storage formats? Pretty cool!
- I'm trying to make sense of the formula Minsky shows, I believe that this is the mapping between the coordinate of a given point in image space and an address in memory? 


### AIM-120 Excerpt 3
<img width="912" alt="Screen Shot 2021-04-19 at 8 17 17 AM" src="https://user-images.githubusercontent.com/5165996/115235450-33fce280-a0e8-11eb-8785-521893134fb7.png">
-  A little more evidence for a bit depth of 10

**Comment by larsbrinkhoff** [comment]
> Coordinates normally occur as a dotted pair (x . y) in half words.  For display purposes, normally the 10<sub>10</sub> most significant bits are used

Here Minsky talks about the X,Y spatial coordinates.  Each coordinate "normally" fit in 18 bits (a half word).  But apparently 10 bits is assumed to be enough for a display, i.e. of 1024x1024 resolution.

I'm not sure what projective systems Minsky mean.  Yes, it's possible they are related to robotics.  Some memos talk about transforming coordinates related to robot arms.  And there is film footage that shows the movements of a robot arm being programmatically projected onto a display.

> All pictures are composed of 36-bit groups of single-level digitized video.

I take this to mean the storage format is only 1 bit per pixel, and grouped together in one word i.e. 36 bits.

**Comment by stephencwelch** [comment]
- @larsbrinkhoff good point on **AIM-075 Excerpt 1**,  I misinterpreted the 10 bits there, Minsky is clearly referring to the x,y coordinates, not the intensity value of the image at that location.  
- Given this correction, I'm really confused about **AIM-075 Excerpt 3**: "P2 is a format word that specifies what part of the TVC's goes into which byte of the array block. Zero means right 10 bits". Is Minsky saying that the (x,y) location of each point in the image is stored? This seems really inefficient if this is the case, I'm wondering why not use a raster?
- "All pictures are composed of 36-bit groups of single-level digitized video" - I had the same initial reaction when I saw this, that Minsky might mean that image intensity values are binary, seems pretty restrictive, but perhaps  there was some limiting factors that made binary intensity values make more sense here.

**Comment by stephencwelch** [comment]
Found some interesting evidence of 8-bit image intensity values in [AIM-101](ftp://publications.ai.mit.edu/ai-publications/pdf/AIM-101.pdf): 
<img width="872" alt="Screen Shot 2021-04-20 at 9 52 07 PM" src="https://user-images.githubusercontent.com/5165996/115485463-cbfee700-a222-11eb-8e3a-068b4a5f2c2d.png">

<img width="852" alt="Screen Shot 2021-04-20 at 9 52 17 PM" src="https://user-images.githubusercontent.com/5165996/115485467-cf926e00-a222-11eb-82ca-4d35f996adce.png">

**Comment by larsbrinkhoff** [comment]
> P2 is a format word that specifies what part of the TVC's output goes into which byte of the array block. Zero means right 10 bits.

There are many uncertainties as to what this would mean exactly.  First, what is the "TVC output"?  Normally PDP-6 devices deliver quantities of 36 bits.  So presumably "zero" indicates the "right 10 bits" of out those should be stored.  "Right" here means the least significant part.  But what is that output?  Intensity?  And what are the 26 bits that are ignored?  We know from AIM 113 that TVB output 8 bits of intensity, but is that also true for the TVC?  We can't say for sure.

AIM 101 doesn't say which vidisector is used, but given the date I'd say likely TVB.  This is also consistent with AIM 113.

[AIM 160](http://bitsavers.org/pdf/mit/ai/aim/AIM-160.pdf) from May 1968 seems to introduce TVC as the "new vidisector".  Appendix 1 is interesting.  It says input coordinates to the "old vidisector" (TVB) are 10 bits, and the output is 8 bits of intensity.

**Comment by larsbrinkhoff** [comment]
ITS code to get data from the vidisector still exists, but going back only as far as 1971. From what I can see, it's for the "new vidisector" TVC.

**Comment by larsbrinkhoff** [comment]
I'm closing this.  But feel free to keep adding comments!

**Comment by stephencwelch** [comment]
Sounds good, thank you, this has been very helpful.

**Comment by larsbrinkhoff** [comment]
For some vidissector action shots, search here for e.g. "vidi": https://github.com/PDP-10/its/issues/1866

**Comment by stephencwelch** [comment]
Interesting - thanks for the update!
