### ISSUE TITLE
MIDAS vs MACRO-6?

### ISSUE THREAD

**Issue by stephencwelch** [PDP-10/its#2032]
I have a small question on the history of the MIDAS assembler. I noticed that the DEC PDP-6 appears to have shipped with [the Macro-6](http://www.bitsavers.org/pdf/dec/pdp6/DEC-6-0-TP-MAC-LM-FP-ACT01_MACRO-6_Assembly_Language_Feb65.pdf) assembler. 

I'm wondering why project MAC folks at MIT implemented their own assembler (MIDAS) rather than using the assembler from the manufacturer?

I noticed that the MIDAS assembler appears to have a [longer history](http://www.bitsavers.org/pdf/mit/rle_pdp1/memos/PDP-1_MIDAS.pdf), going back to the TX0 and PDP-1 machines. Perhaps MIDAS was used on the PDP-6 instead of DEC's assembler for forward compatibility reasons? Or maybe it just offered more features? I poked around the aim index a bit and haven't seen any memos yet that mention MACRO-6. Pointers to any relevant documents would be appreciated, thanks!

**Comment by larsbrinkhoff** [comment]
Both MACRO and MIDAS stem from the TX-0 days at MIT:  
http://www.bitsavers.org/bits/MIT/tx-0/

I don't know why, but apparently the people who would go on to found DEC took MACRO along.  But the hackers at MIT preferred MIDAS.

**Comment by aap** [comment]
And then there's the whole question of how it was bootstrapped.
DEC had a PDP-6 assembler running on a PDP-4. Did it use the later MACRO syntax or was it more primitive? How was PDP-6 MIDAS assembled?

**Comment by larsbrinkhoff** [comment]
I haven't heard or seen any clues how the PDP-6 software was bootstrapped.  That would be a question for people like Greenblatt, Samson, Knight.

**Comment by larsbrinkhoff** [comment]
Page 9 here says how TECO was ported from the PDP-1 to the 6.  But it say nothing of the assemblers.  
https://archive.computerhistory.org/resources/access/text/2012/12/102657935-05-01-acc.pdf

**Comment by stephencwelch** [comment]
Thanks - @larsbrinkhoff and @aap. The [Oral History of Richard Greenblatt ](https://archive.computerhistory.org/resources/access/text/2012/12/102657935-05-01-acc.pdf) is interesting, I noticed on page 10 that he mentions writing TECO in "PDP-6 assembly language": 

<img width="866" alt="Screen Shot 2021-04-29 at 8 53 32 PM" src="https://user-images.githubusercontent.com/5165996/116635622-428b9b00-a92d-11eb-9a82-b926e9773e9d.png">

This is kinda confusing to me, maybe I'm missing something - do you think Greenblatt is referring to MACRO-6 here? If so, I guess TECO would have been written in a version of MACRO or MIDAS compatible with the PDP-1, and the porting consisted of rewriting it (or writing from scratch as Greenblatt says) in MACRO-6? Something like that?

**Comment by larsbrinkhoff** [comment]
I don't know which assembler TECO 6 was first written in.  What we do know is that there is a ["PDP-6 memo 2"](https://github.com/larsbrinkhoff/its-archives/blob/master/ailab/pdp6-memo-2.pdf) which describes it and is dated October 29, 1964.  And that is only a few weeks after the PDP-6 was installed, see http://ljkrakauer.com/LJK/essays/pdp6plaque.jpg

So the question is: did they have a MIDAS 6 already at that point?  Or did they use MACRO supplied by DEC?  Or a cross assembler on the PDP-1 or some other computer?  I can't say.  But I think there's a good chance Richard Greenblatt and Peter Samson would remember.

The earliest AI memo to mention MIDAS 6 seems to be this one from July 1, 1965: https://github.com/larsbrinkhoff/its-archives/blob/master/ailab/AIM-82.pdf

**Comment by larsbrinkhoff** [comment]
Here is a table with information about preserved PDP-6 programs:  
https://github.com/PDP-10/pdp6-programs/wiki

**Comment by stephencwelch** [comment]
Thanks @larsbrinkhoff, this is very helpful. Seems like there's not an obvious answer to my initial question, I definitely didn't come across anything definitive in my reading so far. I also wanted to ask this question to see if there was some big gap in my understanding, so in that way your response and these documents are very helpful. Please feel free to close this issue.

**Comment by stephencwelch** [comment]
Just on more note on this, I did find a little tidbit in page 89 of "Hackers: Heroes of the Computer Revolution" by Steven Levy: 

> "The assembler that Margaret Hamilton used with her Vortex program was not the hacker-written MIDAS assembler, but the DEC-supplied DECAL system that the hackers consider absolutely horrid."

**Comment by larsbrinkhoff** [comment]
Interesting.  Note, that's about the PDP-1.  Thanks @stephencwelch!

**Comment by larsbrinkhoff** [comment]
It says here that the TX-0 version of the MIDAS assembler was "translated" to produce the PDP-1 version.

> &nbsp; This memorandum describes an assembler which has been in use on the TX-0 computer at MIT for a year, and has recently been translated for use on the PDP-1.  Since the MIDIAS language includes most of MACRO, it is hoped that MACRO users will easily be able to switch over to this more powerful assembler.
> &nbsp; The MACRO language had been used on the TX-0 for some three years previous to the writing of MIDAS.  Hence, MIDAS incorporates most of the features which have been requested by users of MACRO, such as more flexible macro Instructions, six character symbols and relocation.
> &nbsp; The original MIDAS Assembler was written for MIT primarily by Robert A. Saunders.  The PDP-1 translation was done by R. Saunders, now of III; A. Kotok, DEC, W. F. Mann, BBN; D. Gross, MIT; and S. D. Piner, DEC. 

http://www.bitsavers.org/pdf/mit/rle_pdp1/memos/PDP-1_MIDAS.pdf
