### ISSUE TITLE
Clean build fails: expect not found

### ISSUE THREAD

**Issue by bictorv** [PDP-10/its#2041]
At the end of "make EMULATOR=klh10":
/bin/sh: 1: expect: not found

is the message I get. (I think I remember discussing this previously.)

It seems build/dependencies.sh is not used by the standard build, but only by travis and cirrus and gitlab etc. I don't know how to make it be used in the best way.

**Comment by larsbrinkhoff** [comment]
There is no provision for detecting or installing dependencies automatically.  The they are documented in the toplevel README.md, see https://github.com/PDP-10/its/#building

**Comment by bictorv** [comment]
Well there is: build/dependencies.sh does it, and is called by travis and whatnot. Couldn't the standard ("user") build also do that?

**Comment by larsbrinkhoff** [comment]
That was not the intent.  There is a small number of CI servers and the dependencies script caters only to those.  I was not planning to add support for a wide variety operating systems or Linux distributions.

**Comment by bictorv** [comment]
Ah, no, sure, it is a can of worms.
