### ISSUE TITLE
H3MAKE tries to send mail to SRA,Alan,JTW,cent,MAP

### ISSUE THREAD

**Issue by bictorv** [PDP-10/its#2063]
See KVTUSR in SYSHST;H3MAKE. 

It would be better to send to some alias, but which? BUG-HOSTS3? HOSTMASTER? Or just no one, these days?

This is related to the issue about MAIL;NAMES, #2058, since the mail address should be there and be localized.

**Comment by eswenson1** [comment]
Duplicate of #2123.
