### ISSUE TITLE
An Emacs-centric family tree of editors.

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#2067]
In reference to @e-n-f's ![vi-centric family tree of editors](http://web.mit.edu/kolya/misc/txt/editors).

**Comment by larsbrinkhoff** [comment]
Predecessors:

- PDP-1 TECO by Dan Murphy.
- PDP-6 TECO by AI lab hackers.
- ITS TECO.
- TECO macro packages: ^R mode (cmm, rms), TECMAC, TMACS, Rmode, ZED/DOC.
- E by Fred Wright, Brian Harvey, et al.

**Comment by larsbrinkhoff** [comment]
- EINE/ZWEI/Zmacs.
- SINE
- Multics Emacs.
- Montgomery.
- Zimmeman/CCA.
- Gosling/UniPress Emacs.
- GNU Emacs.
- Epoch
- Lucid
- Xemacs

**Comment by larsbrinkhoff** [comment]
Special mention?  Applications branching off TECO/EMACS: RD, RMAIL, INFO.

**Comment by ericfischer** [comment]
The sources that I collected 20+ years ago are mostly scanned and posted to https://archive.org/search.php?query=enf-editors

**Comment by larsbrinkhoff** [comment]
It's so pleasant to see a message longer than 280 characters!

**Comment by larsbrinkhoff** [comment]
@ats found a message where Bob Clements says he brought PDP-6 TECO to SAIL and ported it to the DEC monitor:  
http://stuff.offog.org/its/news/1990-clements-sail-teco

**Comment by larsbrinkhoff** [comment]
The earliest evidence of ZWEI I can find is this message.

```
DLW@MIT-AI 11/14/78 19:18:50
To: EAK at MIT-MC
ZWEI is the second version of EINE, of course.  It stands for
Zwei Was Eine Initially.  It is a complete rewrite for about
six reasons which I will type in one of these days.  It wan't
announced in mail because everyone here heard about it by word
of mouth.
```
