### ISSUE TITLE
PROBE - Probe around in a job

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#207]
SYS; TS PROBE  
SYSBIN; PROBE BIN  
BAWDEN; PROBE 258

From source code, maybe create PROBE ORDER?

    Usage is:
    :~S <uname> <jname>
    or
    :~S <job number>
    or
    :~S T<console number>
    or
    :~S <jname>
    or
    :~S <uname>
    
    With no JCL under DDT, operates on previously selected job.

**Comment by eswenson1** [comment]
Created new ticket #217 regarding adding documentation for probe. This ticket should be about getting existing code installed. Also, I'm not convinced the documentation mentioned here is "quite right".  For example, the command would be ":pb \<uname\> \<jname\>", not :~S \<uname\> \<jname\>.

**Comment by eswenson1** [comment]
Also, the link sys;ts pb should point to sys; ts probe.

Note: this program automatically purifies itself and pdumps to sys;ts probe when run with debug/0.

**Comment by larsbrinkhoff** [comment]
Thanks, it's better to have a separate issue.

The ~S should be replaced with the JNAME.  It's a call to the FORMAT function.  I suppose in the documentation, we should use either PROBE or PB.
