### ISSUE TITLE
Unable to change Timezone

### ISSUE THREAD

**Issue by oilcan-productions** [PDP-10/its#2117]
I am trying to change the TZ from EDT to PDT 
I changed the SYSTEM;CONFIG to contain
```
DEFINE TZONE==-420
```

But I might be holding it wrong or interpreting the explanation wrong.

Mike

**Comment by larsbrinkhoff** [comment]
I believe the TZONE feature was added by @bictorv.  Do you have any thoughts?

**Comment by larsbrinkhoff** [comment]
I kind of consider ITS to be native to Cambridge; what happens in Massachusetts stays in Massachusetts.

**Comment by bictorv** [comment]
The TZONE is the number of hours from GMT, where e.g. 5 is Eastern, -1 is Central Europe. I guess it should be better documented, and maybe even configurable in the build config?

**Comment by larsbrinkhoff** [comment]
@oilcan-productions, I guess you should try `DEFINE TZONE==7` instead?

**Comment by bictorv** [comment]
Or even better, ```DEFOPT TZONE==7```.

**Comment by larsbrinkhoff** [comment]
It seems like the issue should be resolved.

**Comment by oilcan-productions** [comment]
@larsbrinkhoff  @bictorv I tried both options in the config.203 file but the Timezone is not changing. Maybe I am putting it into the wrong spot?

**Comment by larsbrinkhoff** [comment]
@oilcan-productions, should put it inside the `IFE MCOND` conditional for the machine you are running.

After that, the usual procedure as mentioned here: https://github.com/PDP-10/its/blob/master/doc/NITS.md

You can check that the new ITS BIN you built has the right timezone in DDT.  Something like
```
its$j
$l its bin
tzone=
```
The `=` command should print the value of the `TZONE` symol.  (Modify as needed depending on which directory and file name your ITS BIN has.)

When you have your new @ ITS you can double check that too, the same way.

**Comment by oilcan-productions** [comment]
Thanks that was it :) Rebuilt and works as expected
