### ISSUE TITLE
build with EMULATOR=pdp10-ka timing out on LISP compiler

### ISSUE THREAD

**Issue by tuklusan** [PDP-10/its#2125]
*:complr

LISP COMPILER 2000 [in LISP 2156]

_teach;macro
MPV; 13664>>MOVE 7,1030(3)
The last command timed out.
make: *** [Makefile:162: out/pdp10-ka/rp03.2] Error 1

**Comment by larsbrinkhoff** [comment]
There are two possible causes:
- If you're using a slow computer such as a Raspberry Pi, the timeout values are a bit too tight.
- Or else, a random failure that has not been tracked down.  Try again a few times.

**Comment by 13spacemen** [comment]
@larsbrinkhoff I'm also getting the exact same error. I compiled KLH10 just fine before, but I want PDP10-KA so I can play Maze War

```:KILL
*midas lisp;_lspsrc;sort
***** MACLISP ****** SORT FUNCTIONS **************************
    ==> INSERTED:  .FASL DEFS
***** MACLISP ****** SORT FUNCTIONS **************************
Constants area inclusive
From    To
376     401
Run time = 0.06
1784 Symbols including initial ones (65% used)

:KILL
*:link lisp;subloa lsp,nilcom;subloa >
*complr^K!

LISP COMPILER 1999 [in LISP 2156]

_liblsp;_libdoc;loop

_^Z
50107)   XCT 11   :kill
*complr^K!
ILOPR; 0>>0
The last command timed out.
make: *** [Makefile:162: out/pdp10-ka/rp03.2] Error 1```

Compiling on Ubuntu 20.04 LTS on WSL2 on Windows 10 x64

**Comment by larsbrinkhoff** [comment]
If retrying a few times doesn't work, then try this:

```
make -k clean all EMULATOR=pdp10-ka
make download EMULATOR=pdp10-ka
```

This should get everything built locally, and then download disk images from hactrn.org.

**Comment by rcornwell** [comment]
I've been telling you about this error for a while.

**Comment by eswenson1** [comment]
> If retrying a few times doesn't work, then try this:
> 
> ```
> make -k clean all EMULATOR=pdp10-ka
> make download EMULATOR=pdp10-ka
> ```
> 
> This should get everything built locally, and then download disk images from hactrn.org.

@larsbrinkhoff I tried that, since i'd never tried "make download" before, but it didn't do what I expected.  The "all" target caused the build to, after building the simulator, then build up the disk images like it has always done before.  What use is this?  I would expected that you'd want to simply build the simulator, and then DOWNLOAD the disk images, right?

**Comment by 13spacemen** [comment]
@larsbrinkhoff Unfortunately that does not work, the firsr command starts building disk images anyway
And for some reason I cannot build KLH10 either anymore, keep getting timeout errors

**Comment by larsbrinkhoff** [comment]
@13spacemen, that's right.  It should start building.  Let it do its thing, and when it's done do the "make download".

**Comment by 13spacemen** [comment]
@larsbrinkhoff Thanks got it working, I had to do chmod 777 -R inside the its folder first though before ./start would work
But I can play Adventure now 👍 
I still can't get Maze War to work, I do ./start imlac but there is no extra window or anything
If I do :maze I can load the Maze War game but it's unplayable since it's a graphical game not a text game like Adventure or Zork
Could you perhaps help with this? I'm interested in Maze War since it's the first FPS game

**Comment by rcornwell** [comment]
I'm still having problems. Note this is fresh git clone followed by switch to latest emulator level.

**Comment by larsbrinkhoff** [comment]
@13spacemen, "imlac" needs manual installation of the C# based emulator.  There is also "simh_imlac" which I _hope_ should work out of the box.  It starts with blank memory though, so the first thing is to get it loaded with the "firmware".  Did you see this?  https://www.youtube.com/watch?v=jYRFDLYPeTU

**Comment by eswenson1** [comment]
But Lars, I thought the whole point of the "download" option was to make it so users wouldn't have to spend an hour or so building the disk image, that will just get replaced by the downloaded one.  Why can't we make a make target that will build the simulator and tools, and then NOT start it, but rather download the disk images?

**Comment by tuklusan** [comment]
> > If retrying a few times doesn't work, then try this:
> > make -k clean all EMULATOR=pdp10-ka
> > make download EMULATOR=pdp10-ka

This worked for me. I am able to use "start" and login, and see an emulator instance running with command line "tools/sims/BIN/pdp10-ka out/pdp10-ka/run"

thank you.

**Comment by larsbrinkhoff** [comment]
@eswenson1, that's a good point, and that was the intention.  But I botched something, so just typing "make download" doesn't quite work.  So the workaround for now is to do a "make -k all" first.
