### ISSUE TITLE
TOPS-20 machines at MIT

### ISSUE THREAD

**Issue by gregbo** [PDP-10/its#2127]
MIT-EECS may have come online in 1980.  I remember in the spring of 1980 while taking the [SICP](https://en.wikipedia.org/wiki/Structure_and_Interpretation_of_Computer_Programs) class, some problem sets could be implemented on it.  This was part of a transition from running the class on a PDP-11/45 to the KL10.

**Comment by eswenson1** [comment]
This machine was more frequently referred to MIT-EE or simply EE. I remember having an account there and getting to it primarily through MC via chaosnet.

**Comment by gregbo** [comment]
OK.  As I recall, the machine was known by various names at various times.  For example, in [a post I made to the human-nets list in the fall of 1982](https://usenet.trashworldnews.com/?thread=108377), the address presented to the list was <Uc.Gds at MIT-EECS at MIT-MC>.  (If this looks funny, it's because this was pre-DNS.)  Also, sometime in 1981, the people running the EECS computing facility decided to adopt the Hitchhikers Guide to the Galaxy theme.  Many of the systems were renamed or aliased, including MIT-EE, which went by the name MIT-DEEP-THOUGHT for awhile also.

**Comment by larsbrinkhoff** [comment]
Thank you.  Sometimes the multitude of aliases can be confusing.  Another one is the BLT (Brave Little Toaster) DEC-2020 which I believe was also named LSD.  Further away, SU-AI was the official name for the Stanford AI PDP-10, but SAIL was common.
