### ISSUE TITLE
PDP10-KA MAC Address conflict

### ISSUE THREAD

**Issue by oilcan-productions** [PDP-10/its#2153]
I just rebuilt from scratch and used KA instead of KLH.
Everything seems to work but when running 
```
sudo ./start tv11 tvcon
```
I get the following error when the network comes up

```/home/pi/its/out/pdp10-ka/run-40> set imp ip=192.168.2.101/24

%SIM-INFO: IMP DHCP disabled

/home/pi/its/out/pdp10-ka/run-43> at imp tap:tap0

%SIM-INFO: Eth: opened OS device tap0

Thu Feb 23 10:24:15 2023

Sockets: _eth_write(tap):  error 5 - Input/output error

%SIM-ERROR: IMP: Eth: Error Transmitting packet: Input/output error

You may need to run as root.

Thu Feb 23 10:24:16 2023

Sockets: _eth_write(tap):  error 5 - Input/output error

%SIM-ERROR: IMP: Eth: Error Transmitting packet: Input/output error

You may need to run as root.

%SIM-INFO: Eth: closed tap0

%SIM-ERROR: IMP: MAC Address Conflict on LAN for address E2:6C:84:1D:34:F6
```
I changed the MAC address in '~/its/out/pdp10-ka/run' to make sure it does not interfere with any of the other SIMH instances on my network but no change.

Not sure what to check next.
I can access the system locally just fine

**Comment by larsbrinkhoff** [comment]
Getting SIMH to do networking can be tricky.  There's no ready made recipe for how to make this work.  I have all but given up myself.  @rcornwell or @eswenson1, do you have any advice here?

**Comment by eswenson1** [comment]
I have managed to get pdp10-ka (and pdp10-kl) to do both chaosnet and internet networking.

Here is my script for a working pdp10-ka system:

```
![image](https://user-images.githubusercontent.com/867939/221017324-7ae96d64-5312-4998-aaf1-da56ccb386db.png)

```

**Comment by eswenson1** [comment]
I think the only significant lines, above, are the "set imp" and "at imp" lines (for internet) and the "set ch" and "at ch" lines (for chaosnet).

**Comment by oilcan-productions** [comment]
Thanks I will give this a try

**Comment by oilcan-productions** [comment]
@eswenson1 I assume the 172.xxx.xxx.xxx addresses match your home network and 172.16.0.4 is the IP address of an ethernet adapter on the host, correct?
Also mpx=4 is the interrupt of the adapter in ITS. Is that always 4?

**Comment by eswenson1** [comment]
No.  That 172.16.0.4 address is purely internal to the SIMH/imp stack.  I don't really understand how this works, but I think the 172.16.0.4/24 defines a virtual network, of which the 172.16.0.2 ip acts as the gateway, and where 172.16.0.4 is the IP of the endpoint that is bound to the guest os (e.g. ITS).  @rcornwell is the expert here and perhaps he can weigh in and explain how this works. He can also answer your mpx question.  This is all black magic to me -- I used values he gave me at one point.

**Comment by oilcan-productions** [comment]
Ah OK that makes more sense now.

**Comment by eswenson1** [comment]
Nice thing about this config is that it doesn’t really matter what your ITS IP address is configured as. Note I’m napping local ports 2021 and 2023. I run all three of KA, KL, and KS on this host, and I use different local port numbers (eg 3021, 3023, 4041, 4043) for the KL and KS systems.

**Comment by rcornwell** [comment]
@oilcan-productions You should have no problems setting the MAC address to whatever you want.

set imp enabled
set imp mac=e2:6c:84:1d:34:a3
set imp DHCP
set imp host=10.3.0.6
set imp mpx=4        ; Only on PDP10-KA.
at imp tap:tap0

Address in the ITS is set to 10.3.0.6. This will use your local DHCP to set up an address. "set imp IP=#/mask" will set the IP address that you connect to ITS from the outside. "set imp GW=#" will set the gateway ITS talks to. @eswenson1 uses a different form to connect since he uses a WiFi connection. He uses the NAT format. With this you connect to your host at given ports.

**Comment by eswenson1** [comment]
Thanks, @rcornwell.

**Comment by rcornwell** [comment]
@eswenson1 Here is sort of a diagram of how networking for IMP works.

   ITS (10.3.0.6) -> tap (##.##.##.##/##) 

 The stack translates all ##.##.##.## to 10.3.0.6 and translates all ITS traffic to ##.##.##.##

For NAT connection you have.
    ITS(10.3.0.6) -> SimH/Slirp (176.16.0.4) -> Slirp Gw (176.16.0.2)-> localhost.

 This maps the ports into localhost ports. Note you have to define gateway=172.16.0.2,network=172.16.0.0/24 since ITS does not appear to like talking to 10.0.0.2 addresses that are the default Slirp gateway/network.

**Comment by oilcan-productions** [comment]
Thanks @rcornwell, if I set it up like above I get this again
```
%SIM-INFO: Eth: opened OS device tap0

Thu Feb 23 14:28:05 2023

Sockets: _eth_write(tap):  error 5 - Input/output error

%SIM-ERROR: IMP: Eth: Error Transmitting packet: Input/output error

You may need to run as root.

Thu Feb 23 14:28:06 2023

Sockets: _eth_write(tap):  error 5 - Input/output error

%SIM-ERROR: IMP: Eth: Error Transmitting packet: Input/output error

You may need to run as root.

%SIM-INFO: Eth: closed tap0

%SIM-ERROR: IMP: MAC Address Conflict on LAN for address E2:6C:84:1D:34:A3
```

I am launching as root 'sudo ./start vt52'

**Comment by rcornwell** [comment]
You can set the ownership of the tap device to yourself and don't need to use root. However I wonder if your tap bridge is set up correctly, it does not appear that you are actually connecting to anything.

**Comment by oilcan-productions** [comment]
I used the steps here https://github.com/simh/simh/blob/master/0readme_ethernet.txt to setup the tap device. Should I use something else?

Mike

**Comment by oilcan-productions** [comment]
I redid the steps and now I have the tap setup and the error is gone. Now I need to figure out how to connect from remote.

**Comment by larsbrinkhoff** [comment]
@oilcan-productions, if you got everything working, could you please write it up and post a pull request?  It would be so nice to have a clear step by step guide for this.

**Comment by oilcan-productions** [comment]
@larsbrinkhoff  sure I will re-open this for now because I need a few more bits of info to write it up.

**Comment by oilcan-productions** [comment]
@rcornwell I see the SIMH adapter got an IP address from DHCP, 192.168.0.85.

When I try to FTP to that address I see this message but the connection is stuck. Client says 'Connectred to 192.168.0,85' and hangs indefinitely. 
```
TOP LEVEL INTERRUPT 200 DETACHED JOB # 22, USR:___022 TCP    10:27:57
```
Telnet works though. 
I checked if port 21 would be in use elsewhere and it is not. Anything specific I need to do to get FTP to work?

Mike

**Comment by rcornwell** [comment]
First of all make sure you are using FTP and not SFTP. You can also try telneting to port 21 to make sure that the FTP daemon is working. @larsbrinkhoff Any idea on making sure FTPD is running correctly?

**Comment by oilcan-productions** [comment]
One last question. I have no idea how to see which IP address the SIMH adapter is getting I had to log into my router and search for the MAC address. What is the best way to look it up?

**Comment by oilcan-productions** [comment]
> First of all make sure you are using FTP and not SFTP. You can also try telneting to port 21 to make sure that the FTP daemon is working. @larsbrinkhoff Any idea on making sure FTPD is running correctly?

Yeah I am using FTP and it shows connected but nothing else happens. So I assume it gets to SIMH but the port is not forwarded.

**Comment by oilcan-productions** [comment]
Created PR https://github.com/PDP-10/its/pull/2155 let me know if you want me to change anything

**Comment by rcornwell** [comment]
The command "show imp" will show the DHCP address that the imp is set to. You can also in your router assign the MAC address to a fixed IP address, this is what I do.

PDP10 IMP device does not map ports per say. What it does is IP address translation. It translates all packets from ITS into the address of the NIC, and all inbound packets to the same IP address to ITS. It takes care of handling ARP requests and management of DHCP if you want. Not it is possible to configure ITS to a local address and totally disable the address translation functions. The IMP device also modifies packets for FTP Data by translating the address and tracking sequestering and other functions.

**Comment by larsbrinkhoff** [comment]
@rcornwell, first of all, check that DEVICE; TCP SYN025 is there and is the FTP server (FTPS), or a link to it.  But the build script makes sure it is, so it should be.

Second... there isn't much of a second step.  It's difficult to debug this from ITS.  Like you said, try telnetting directly to port 21 and type FTP commands manually.

**Comment by oilcan-productions** [comment]
@larsbrinkhoff yes DEVICE; TCP SYN025 is there 
```L TCP SYN025 SYSBIN FTPS BIN```
I did telnet into port 21, it connects just like FTP does and I can type commands but do not get anything back

**Comment by rcornwell** [comment]
@larsbrinkhoff I tried a build and FTP does not appear to start.

**Comment by eswenson1** [comment]
@rcornwell What do you mean?  FTP doesn't "start" until you connect to port 21 (025).  There is a TCP handler for port 025 that "starts" the FTPS (ftp server) when a connection comes in over that port.

**Comment by rcornwell** [comment]
I did some more testing and under current build FTP does not start when I try to externally connect to FTP. The process does start, however nothing happens. Commit 4b8dfa2 works. Commit de1bd31 does not work. I tried my version of pdp10-ka and the one in tools. On the older build it works, on newer it just hangs.

**Comment by larsbrinkhoff** [comment]
I opened a new issue about the FTPS problem: #2158

**Comment by oilcan-productions** [comment]
Closing this one and tracking the FTPS problem in #2158
