### ISSUE TITLE
make download EMULATOR=pdp10-ka fails because image is no longer at hactrn.org

### ISSUE THREAD

**Issue by gwright83** [PDP-10/its#2156]
The approach to fixing the KA build given in #2125 no longer works because the images/ directory at [http://hactrn.org/images/](http://hactrn.org/images/) seems to no longer exist.

While building ITS for pdp10-ka I got:
<
wget http://hactrn.org/images//pdp10-ka.tgz
--2023-02-24 17:21:55--  http://hactrn.org/images//pdp10-ka.tgz
Resolving hactrn.org (hactrn.org)... 205.166.94.7
Connecting to hactrn.org (hactrn.org)|205.166.94.7|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-02-24 17:21:56 ERROR 404: Not Found.
gmake: *** [Makefile:106: download] Error 8
>

**Comment by larsbrinkhoff** [comment]
The hactrn.org machine was out of disk space and is being updated.  We'll have to wait for a while, not sure how long.

**Comment by gwright83** [comment]
Thanks, Lars.  I guess the issue should stay open until hactrn.org is fully available again, lest someone else notice and report it again.

**Comment by oilcan-productions** [comment]
Looks like it is still down.

**Comment by oilcan-productions** [comment]
Would it help to get a mirror up for the images? How much disk space do you need?

**Comment by larsbrinkhoff** [comment]
Yes, it would be helpful with a second place to store images.  A couple GB is needed.  Say, 1G per target to be on the safe side, and... how many emulators now... times five.  And a stable host name, with scp access and a web server.

**Comment by oilcan-productions** [comment]
Sure, I can get you that minus the SCP access. I only have FTP available on my VPS at GoDaddy.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by oilcan-productions** [comment]
Made a change to the deploy to FTP script #2168

**Comment by oilcan-productions** [comment]
I see the emulator images have deployed successfully to the new location.

**Comment by larsbrinkhoff** [comment]
Thanks for your help resolving this!  Maybe hactrn.org will be back some time, but for now let's close this.
