### ISSUE TITLE
COMBAT or NCOMBA?

### ISSUE THREAD

**Issue by eswenson1** [PDP-10/its#2175]
DB currently includes SYS3;TS COMBAT, which is compiled from SYSEN3;COMBAT 151.  As far as I know, this is an older version of COMBAT than what was used near the end of DM's time.  As far as I know, SYS3;TS NCOMBA, compiled form COMBAT;NCOMBA 472 is the one that was in active use.  

I'm planning on adding NCOMBA to DB in a PR soon, but the question is, should we keep COMBAT as well as NCOMBA?  Should we replace COMBAT with NCOMBA (perhaps having a link from TS COMBAT to TS NCOMBA?

I've tried both COMBAT and NCOMBA with COMBAT ZONE, and they both appear to work.  I'm not sure what the differences are.  However, the version number difference (151 versus 472) is extreme.

**Comment by eswenson1** [comment]
I notice that the source for COMBAT, in SYSEN3;COMBAT 151 includes a `TITLE NCOMBAT`, so it does appear to be a version of NCOMBAT.  However, its version number is well-behind that in COMBAT;NCOMBA 472.

**Comment by eswenson1** [comment]
It actually looks to me like SYSEN3;COMBAT 151 is *better* than COMBAT;NCOMBA 472.  So I may want to simply not install the latter....  SYSEN3;COMBAT 151 has conditionalizations for non-ITS systems as well.

It seems like COMBAT 151 came from MIT-XX, whereas NCOMBA 472 came from ITS, with the MIT-XX version more advanced than the ITS.

Based on this, I suggest we not install NCOMBA.  It seems like COMBAT (151) works fine.

**Comment by larsbrinkhoff** [comment]
COMBAT 151 was added here: https://github.com/PDP-10/its/pull/1392.  Yes, it's a TOPS-20 (presumably XX) file.  Maybe the version number was reset when moved from ITS.

If COMBAT 151 is the better version, and NCOMBA 472 doesn't offer any features the former doesn't have, I'd say drop the latter.  We do have some programs in multiple versions, but it's only when there's some special reason to do so.

**Comment by eswenson1** [comment]
Agreed. Comparing the sources, it does appear that COMBAT 151 is later than NCOMBA 472. The few deletions appear to be inconsequential.

**Comment by eswenson1** [comment]
Closing this issue as the COMBAT 151 that we currently have in DB is the "best" one to have. Not installing NCOMBA.
