### ISSUE TITLE
New daemon (dragon?) to kick off idle users who haven't logged in by name

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#2196]
I get a lot of connections to my public ITS system which manage to ^Z but never log in.  After that they sit idle and hog a job slot forever.

I need a program which runs in the background, detects these users, and kicks them off the system.

**Comment by eswenson1** [comment]
Seem to recall there was such a program.  I wonder if GUNNER (the DM daemon) does it?  In any case, there was something else that we ran back on MC to do just that -- kill idle not-logged-in jobs.

**Comment by larsbrinkhoff** [comment]
The DM GUNNER seems to have code to do that.  I did some grepping, but I couldn't find anything else so far.

**Comment by larsbrinkhoff** [comment]
That sounds like exactly what I want.  I got a copy off ES and tested it.  We also need KSC; TIMRTS to assemble it.  I crossed my fingers and ran it even if there are no idle users - there was no carnage.  Now I'm waiting 20 minutes to test the gunnage.

**Comment by larsbrinkhoff** [comment]
It gunned down the idle job perfectly.  I'll make a pull request for this soon.

**Comment by larsbrinkhoff** [comment]
I haven't been able to get an exact copy of GUNNER 6 due to Chaosnet problems.  Can you send me one?  (The one I have is captured ^R output.)

**Comment by eswenson1** [comment]
I sent you gunner 6 and timrts 42 via email.

**Comment by larsbrinkhoff** [comment]
Resolved by #2202.
