### ISSUE TITLE
Unable to mount tape from instructions.

### ISSUE THREAD

**Issue by bilegeek** [PDP-10/its#2197]
Tried to follow the instructions at https://github.com/PDP-10/its/blob/master/doc/DUMP-itstar.md , but was halted at the "Mount the tape image in the emulator." section.

First I made a tape image containing https://www.saildart.org/RSKINI.FAI[P,SYS]_octal ; I renamed the file to rskini.fai, moved it to a new "waits" directory in /tools/itstar/, and ran " ./itstar -cf waits.tape waits". Moved the resulting waits.tape to the base ITS directory.

TU0 doesn't exist, and trying to enable it at the emulator prompt gives me "%SIM-ERROR: Non-existent device: TU0"; I tried re-enabling TUA in the "out/pdp10-ka/run" config then mounting the tape on TUA ("%SIM-INFO: TUA0: Tape Image 'waits.tape' scanned as SIMH format"), but I get the error " 16717   6MT0: MACRO  IN     MASTER; DEVICE NOT READY" after typing load at the "_" prompt.

**Comment by larsbrinkhoff** [comment]
Those instructions were written before the KA10 and KL10 emulators were added to SIMH.  It's a good thing you checked this, they should be updated soon!

You don't say which emulator you're using, but I'm guessing KA10 or KL10.  The tape device for both of them is called `MTA`, so the attach command should be `attach mta0 waits.tape`.

**Comment by larsbrinkhoff** [comment]
Did you convert RSKINI.FAI from octal format to ITS evacuate format.  You can do this with `cat36 -Woct -Xits < input > output`.  The cat36 program is found in the `tools/dasm` directory.

**Comment by bilegeek** [comment]
Alright, got it going. Converted the file with cat36 and did "load crdir" like you said. Thanks!

**Comment by larsbrinkhoff** [comment]
By the way, the same directory also has a `dart` program which can write tape for WAITS to read.  In that case, the files should have the CR LF line ending format: `cat 36 -Woct -Xascii`.

**Comment by larsbrinkhoff** [comment]
#2198 should make it more clear how to handle tapes on the newer emulators.
