### ISSUE TITLE
INIT

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#22]
I'm not sure what INIT is, but it looks interesting.  Is it built into DDT, or else where is the source code?

Info in INFO; INIT >.

**Comment by larsbrinkhoff** [comment]
Maybe SYSEN2; INIT 230

**Comment by eswenson1** [comment]
INIT appears to be a "helper" program that can be used in init files (e.g. EJS;EJS LOGIN). It seems to let you do some things more easily than using DDT commands.  And yes, SYSEN2;INIT 230 is the source for it.

**Comment by larsbrinkhoff** [comment]
Thanks, it's on the TODO list then.
