### ISSUE TITLE
CHANNA; TS CNAVRL link missing

### ISSUE THREAD

**Issue by eswenson1** [PDP-10/its#221]
PI distribution includes a link to the mailer (COMSAT) in the CHANNA directory as "TS CNAVRL". This is missing in the DB build.

**Comment by larsbrinkhoff** [comment]
Does anything use the link?

**Comment by larsbrinkhoff** [comment]
Ken has an interesting file: KLH; XLINKS 1.  It seems to be a script to create all links in the PI distribution.

**Comment by eswenson1** [comment]
It is a way for system maintainers to run the mailer as an inferior.
