### ISSUE TITLE
DUMP remote tape code uses DMOVE

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#2216]
The magtape DUMP program has DMOVE instructions in the remote tape code.  That doesn't work on the KA10.

**Comment by eswenson1** [comment]
I assume you mean only when trying to dump over the network? Because normal file-to-tape dumping works just fine.

**Comment by larsbrinkhoff** [comment]
Yes, it's only in the remote tape code.

**Comment by larsbrinkhoff** [comment]
Fixed by #2218.
