### ISSUE TITLE
RIPDEV

### ISSUE THREAD

**Issue by eswenson1** [PDP-10/its#222]
PI distribution includes:  

DEVICE; ATSIGN R.I.P. build from SYSEN2;RIPDEV 3

**Comment by eswenson1** [comment]
RIPDEV replaces MLDEV for machines that have passed away. I wonder whether we need it.  I guess we could use it for AI, MC etc. so that anyone trying to access these machines will get some friendly message.  Thoughts?

**Comment by larsbrinkhoff** [comment]
I suppose they have all passed away.  On the other hand, I don't expect 
anyone would try to acces them by mistake.
