### ISSUE TITLE
MIT network maps

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#2227]
A growing number of MIT network maps in picture form is turning up.  I'll collect them here.

**Comment by larsbrinkhoff** [comment]
![mit-network-map-1987](https://github.com/PDP-10/its/assets/775050/b3942aa0-efd8-499d-a97b-0883a93ae373)

Source: http://www.domain-logic.com/images/1987-network-map.gif
https://github.com/PDP-10/its/issues/181#issuecomment-385512311

**Comment by larsbrinkhoff** [comment]
@jonathangray pointed to this.
![mit-network-map](https://github.com/PDP-10/its/assets/775050/c91d76a2-5e67-4ab4-94b7-0ed49f6c3b9e)
Source: https://archive.org/details/DTIC_ADA138905/page/n19/mode/2up  
http://publications.csail.mit.edu/lcs/pubs/pdf/MIT-LCS-TM-254.pdf#page=18

**Comment by ams** [comment]
No CADR in sight ... downvote.
