### ISSUE TITLE
Re-enable publishing to hactrn.kostersitz.com

### ISSUE THREAD

**Issue by oilcan-productions** [PDP-10/its#2264]
Adding an issue to re-enable hactrn.kostersitz.com for publishing artifacts

**Comment by larsbrinkhoff** [comment]
It seems to be a success:
```
Run sh build/deploy-ftp.sh
  sh build/deploy-ftp.sh
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    SECRET: ***
    FTP_SECRET: ***
    EMULATOR: simhv3
Deploying as if0_35726802 at ftpupload.net
Passive mode: on; fallback to active mode: off.
Local directory now: /home/runner/work/its/its/out
```

**Comment by oilcan-productions** [comment]
I’ll take a look tomorrow.
Sent from my iPhone

On Jan 6, 2024, at 05:08, Lars Brinkhoff ***@***.***> wrote:

﻿

However, getting the files don't work yet:

wget http://hactrn.kostersitz.com/images/pdp10-ka.tgz
--2024-01-06 14:03:14--  http://hactrn.kostersitz.com/images/pdp10-ka.tgz
Resolving hactrn.kostersitz.com (hactrn.kostersitz.com)... 185.27.134.113
Connecting to hactrn.kostersitz.com (hactrn.kostersitz.com)|185.27.134.113|:80... connected.
HTTP request sent, awaiting response... No data received.


And checking http://hactrn.kostersitz.com/images/ gets me a 404.

**Comment by larsbrinkhoff** [comment]
Deployment of https://github.com/PDP-10/its/pull/2266 seemingly went fine.  But when I visit http://hactrn.kostersitz.com/ I just see this:

> File List
> 
> No Files Found.

**Comment by larsbrinkhoff** [comment]
The Makefiles expect tarballs here: `IMAGES=http://hactrn.kostersitz.com/images`

Is that the right place, or should the directory be dropped?

Can you put some test files where the tarballs should go, so we can see them in a web browser?

**Comment by oilcan-productions** [comment]
The place is correct. The ISP I am using has changed their directory security and I have an open support ticket to get directory listing back

**Comment by larsbrinkhoff** [comment]
I can't get any data using `wget` from these places:
- http://hactrn.kostersitz.com/pdp10-ka.tgz
- http://hactrn.kostersitz.com/images/pdp10-ka.tgz
- http://hactrn.kostersitz.com/htdocs/images/pdp10-ka.tgz

**Comment by larsbrinkhoff** [comment]
> Is the FTP upload working?

The log doesn't indicate any errors: https://github.com/PDP-10/its/actions/runs/7485323655/job/20373594335#step:5:2
> Run sh build/deploy-ftp.sh
>  sh build/deploy-ftp.sh
>  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
>  env:
>    SECRET: ***
>  
>    FTP_SECRET: ***
>    EMULATOR: simh
> Deploying as if0_35726802 at ftpupload.net
> Passive mode: on; fallback to active mode: off.
> Local directory now: /home/runner/work/its/its/out

**Comment by larsbrinkhoff** [comment]
Do you have a Linux (or other Unix) machine to test the deploy-ftp.sh script?

**Comment by oilcan-productions** [comment]
I do have an environment to try it out

**Comment by oilcan-productions** [comment]
I'll do a git fetch and test it out

**Comment by oilcan-productions** [comment]
Images are published now and download works now

**Comment by oilcan-productions** [comment]
@larsbrinkhoff I think we can close this now

**Comment by larsbrinkhoff** [comment]
Yes, looks great now.  Thanks!
