### ISSUE TITLE
Build successfully completed for simh emulator but emulator halts immediately on start

### ISSUE THREAD

**Issue by jordanhubbard** [PDP-10/its#2278]
jkh@ubuntu-> ./start vt52
VT52 started, pid 3100

PDP-10 simulator Open SIMH V4.1-0 Current        git commit id: 348f5f29
/home/jkh/Src/its/out/simh/boot-10> at -u dz0 10004
%SIM-INFO: Listening on port 10004
/home/jkh/Src/its/out/simh/boot-12> at -u dz0 line=7,10018
%SIM-INFO: Line 7 Listening on port 10018
/home/jkh/Src/its/out/simh/boot-14> at -u dz0 line=6,10019
%SIM-INFO: Line 6 Listening on port 10019
/home/jkh/Src/its/out/simh/boot-16> at rp0 out/simh/rp0.dsk
%SIM-INFO: RP0: Unit is read only

HALT instruction, PC: 777721 (HALT 777721)
sim> 

Ubuntu 22.04 on x86_64 architecture

**Comment by larsbrinkhoff** [comment]
> /home/jkh/Src/its/out/simh/boot-16> at rp0 out/simh/rp0.dsk
> %SIM-INFO: RP0: Unit is read only

This shouldn't happen.  Why is the rp0.dsk file not writable?

**Comment by larsbrinkhoff** [comment]
I will speculate there might be a file permission or ownership problem.
