### ISSUE TITLE
fatal error: SDL_net.h: No such file or directory

### ISSUE THREAD

**Issue by billb2050** [PDP-10/its#2296]
After  "make clean all EMULATOR=pdp10-ka". I get...

ENTERING MAIN BUILD SCRIPT Tue Apr 2 07:11:13 AM EDT 2024

------- 2 hrs later ------

MAIN BUILD SCRIPT DONE Tue Apr 2 09:20:20 AM EDT 2024

cc -O3 `sdl2-config --cflags` -o tvcon tvcon.c `sdl2-config --libs` -lSDL2_net
tvcon.c:12:10: **fatal error: SDL_net.h: No such file or directory**
   12 | #include <SDL_net.h>
      |          ^~~~~~~~~~~
compilation terminated.
make[1]: *** [Makefile:4: tvcon] Error 1
make[1]: Leaving directory '/home/bill/Downloads/Computers/Emulation/simh/PDP-10/ITS/its/tools/tv11/tvcon'
make: *** [Makefile:388: tools/tv11/tv11] Error 2
bill@bill-MS-7B79:~/Downloads/Computers/Emulation/simh/PDP-10/ITS/its$

**Comment by eswenson1** [comment]
I think you're missing a dependency.  That file comes from the libsdl2-net-dev package (on Ubuntu) and probably some similarly-named package on other distributions.  See the README.md and search for "sdl2".  That is a required dependency.

**Comment by billb2050** [comment]
Thank you I'm on a Ubuntu based distro. That worked and your "You don't have to start over" saved me 2 hrs.
