### ISSUE TITLE
Image upload to hactrn.kostersitz.com is corrupted

### ISSUE THREAD

**Issue by oilcan-productions** [PDP-10/its#2299]
@oilcan-productions, I often get this now.  If I rerun the build 1-2 times it will usually work.  Any idea why?
![Screenshot from 2024-04-12 07-02-06](https://github.com/PDP-10/its/assets/775050/7480a815-23bc-4c27-84ed-38b40e0f0154)

_Originally posted by @larsbrinkhoff in https://github.com/PDP-10/its/issues/2294#issuecomment-2050980976_

**Comment by oilcan-productions** [comment]
Checked the server side logs, show Client disconnected, nothing more. 
I opened a support ticket to see if there is throttling happening in the background somewhere

**Comment by oilcan-productions** [comment]
They fixed an error in the quota settings file (should be unlimited and was set to 250MB and 4 concurrent connections) of the home path of the account we use to upload. Now it should be unlimited around. @larsbrinkhoff  can you kick off a build and see if that resolved the issue?

**Comment by larsbrinkhoff** [comment]
The restarted build failed for three out of six targets, due to the FTP check.  It's a good thing you added that verification!  Still, the upload goes wrong sometimes, apparently.

(Since we need "make download" to work, I reran the builds until they passed, so now everything is green again.)

**Comment by oilcan-productions** [comment]
@larsbrinkhoff  I am seeing the build right now not deploying at all to the FTP server, as well as the Ubuntu build failing before it gets to the deploy stage.

**Comment by larsbrinkhoff** [comment]
Only commits on master will run the deploy script.  I have merged the pull request now; here's the build to watch: https://github.com/PDP-10/its/actions/runs/8905672868

**Comment by larsbrinkhoff** [comment]
And then the next build went perfectly fine.  No retries needed.  
https://github.com/PDP-10/its/actions/runs/8953189776

**Comment by oilcan-productions** [comment]
Added to the retry logic to recreate the tarball upon retry to ensure it is actually correct.

**Comment by oilcan-productions** [comment]
This should be resolved now. I have been spot testing the uploads for the last month and they always worked

**Comment by larsbrinkhoff** [comment]
It usually works, but sometimes there are still issues.  E.g. right now I have this:

https://github.com/PDP-10/its/actions/runs/10484147466/job/29094427098

The log show five failed attempts at verifying the tar file.  I suspect downloading isn't the problem, but that the uploaded copy was corrupted in the first place.

```
gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
Error unpacking simh.tgz: 
gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
File integrity verification failed, retrying... (5/5)
```

**Comment by ams** [comment]
Wasn't this an issue a year ago as well?  Can't we just stuff this somewhere more stable, and update that periodically?
