### ISSUE TITLE
Compilation issues

### ISSUE THREAD

**Issue by stevefalco** [PDP-10/its#2304]
I am using Fedora 40, and have hit two compilation issues in the pdp6 and chaos bridge submodules.

The first is in tools/pdp6/emu/joy.c where I had to add:

`#include <unistd.h>`

This was needed because close() was undefined and the compiler treated it as an error.

The second is in tools/cbridge/chtls.c where I had to change line 1439, because the second argument to `is_in_mux_list()` was of the wrong type and the compiler wouldn't accept it.  Originally, that line was:

`is_in_mux_list(dchad, &tlsdest[i].tls_muxed)`

and I changed it to:

`is_in_mux_list(dchad, tlsdest[i].tls_muxed)`

i.e. just remove the &, because `tlsdest[i].tls_muxed` is already a pointer, so it seems wrong to take its address in this line of code.

**Comment by larsbrinkhoff** [comment]
Please post your information here:  
https://github.com/aap/pdp6  
https://github.com/bictorv/chaosnet-bridge

**Comment by stevefalco** [comment]
Done.  Here are links to the issues for completeness.

https://github.com/bictorv/chaosnet-bridge/issues/45
https://github.com/aap/pdp6/issues/31
