### ISSUE TITLE
COMSAT should get GATHST, TCPGAT, DOMGAT from NAMES.

### ISSUE THREAD

**Issue by bictorv** [PDP-10/its#2332]
When changing addresses of e.g. your host system, patching in any updates of the addresses of TCPGAT and DOMGAT in COMSAT is easy to forget. It would be good if COMSAT would parse special host names (not every time they are used) and use their addresses instead.

I would imagine a good place for such host names would be .MAIL.;NAMES, where most of the COMSAT configuration is done anyway. Special entries such as

`(*COMSAT-TCP-GATEWAY (R-NAME my-tcp-gateway.com))`
`(*COMSAT-DOMAIN-GATEWAY (R-NAME my.domain.gateway.org))`

could perhaps be used (with or without the `*` - just to minimize the risk of collisions), and the OWNHST routine in COMSAT could check for them (using RCPEQV) and save them in TCPGAT/DOMGAT etc (if they are defined).

The advantage would be that if `my-tcp-gateway.com` changes address (in HOSTS3), COMSAT automatically picks it up (at its next restart).

Thoughts?

**Comment by eswenson1** [comment]
This is a great idea. I was thinking along the same lines, but simply requiring entries in the host table for magic names for gateways. But I prefer your idea of the host names being specified in names >.

It seems you understand the names > parsing logic. I found it very confusing and never really grokked it.

**Comment by bictorv** [comment]
> It seems you understand the names > parsing logic. I found it very confusing and never really grokked it.

Me too! But with some testing it should be doable.

**Comment by bictorv** [comment]
I have a working fix now. The syntax will be

`(*COMSAT-BUGHOST (EQV-LIST @host))`

where `host` is a host name or address (e.g. 3131 or 192.160.1.1). And same for `*COMSAT-TCP-GATEWAY*`, `-DOMAIN-GATEWAY*` and `-GATEWAY-HOST*`. Might not commit until Monday.
