### ISSUE TITLE
logo.md has to be updated

### ISSUE THREAD

**Issue by Alexey-Slyusar** [PDP-10/its#2333]
@eswenson1 noticed that logo.md is not up to date in 11LOGO section and has wrong procedure to get 11LOGO up and running.

Here is correct procedure to run 11LOGO on KA ITS with the Type 340 display active:
````
*:cwd 11logo
*:pdp45
1145.428
CORE = 8.K
!56.:core
CORE = 56.K
!;a pk
!;a df
!;l l bin
!;a ngdis
!400;g
11LOGO 1007
?STARTDISPLAY
````
And here is 11LOGO recursive picture as a tribute to the tradition in logo labeled issues:
![изображение](https://github.com/user-attachments/assets/25a5c162-f9e5-4844-8861-6a92a0735102)

@larsbrinkhoff In order to update the 11LOGO section in logo.md @eswenson1 or @Alexey-Slyusar will make a pull request soon.

**Comment by larsbrinkhoff** [comment]
Thank you, and good to hear from you @Alexey-Slyusar.
