### ISSUE TITLE
User name for built binaries

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#239]
Currently, the entire build runs without loggin in.  That works fine, but it makes the binary assembly info looks bad.  Some programs require a logged-in user to work.

My lars/xfile branch logs in `BUILD`, but I'm open to suggestions.  `GITHUB` would fit the six-character limit, but I don't like that name.

I don't think it's worth the trouble to replicate the user for every binary as found in PI.

**Comment by eswenson1** [comment]
Could use ADMIN or BUILD.

Or we could use EJS, a legendary ITS hacker!

**Comment by larsbrinkhoff** [comment]
Modest, aren't we? ;-)

Or how about DB, since that implies the DistriBution ITS?

**Comment by eswenson1** [comment]
Perfect!

-- Eric

**Comment by larsbrinkhoff** [comment]
Fixed by #253.
