### ISSUE TITLE
ITSDEV - Chaosnet miscellaneous ITS services

### ISSUE THREAD

**Issue by eswenson1** [PDP-10/its#246]
DEVICE; TCP SYN723 => DEVICE; CHAOS ITSDEV
DEVICE; CHAOS ITSDEV
SYSTEM; ITSDEV 974

**Comment by eswenson1** [comment]
SYSTEM; ITSDEV 974 is not correct.  The real source is ML: BAWDEN; ITSDEV 102.

**Comment by larsbrinkhoff** [comment]
ML: or MC:?

**Comment by eswenson1** [comment]
Well, ML: is where the binary was assembled from in the PI distribution. The file actually can be found in AI:BAWDEN; and MC:BAWDEN;.  I got it from AI:BAWDEN;

**Comment by larsbrinkhoff** [comment]
Interesting, I haven't seen any other reference to the ML machine.
