### ISSUE TITLE
DRAGON; HOURLY UPTIME

### ISSUE THREAD

**Issue by eswenson1** [PDP-10/its#249]
There should be a link from DRAGON; HOURLY UPTIME to BAWDEN; UPTIME BIN (or perhaps SYSBIN; UPTIME BIN).  Source for UPTIME is in SYSEN1;UPTIME 4.

**Comment by larsbrinkhoff** [comment]
I think maybe BAWDEN; UPTIME BIN isn't from SYSEN1; UPTIME 4

There's a BAWDEN; UPTIME DATA which is one page.  The data is SIXBIT with three words per host:

    ML
    900114
    073056
    MC
    900420
    110839
    MX
    880916
    233607
    AI
    900420
    110839
    MD
    881125
    184819

I believe it's likely that this file was updated by UPTIME BIN, but the SYSEN1 program doesn't do that.

There's also ALAN; ALAN (CMDS) which among other thing does this:

    uptime$J$0Ldsk:bawden;uptime data
    $'^V0$N^W
    $^X.

This prints the data file as SIXBIT.

**Comment by larsbrinkhoff** [comment]
Fixed by #1343.
