### ISSUE TITLE
LISP packages

### ISSUE THREAD

**Issue by eswenson1** [PDP-10/its#251]
There are a bunch of missing LISP packages from the LISP; directory.  Here is a list:

- [x] BITS FASL
- [x] BS FASL
- [x] CGPRIN FASL
- [x] DEBUG FASL
- [x] DRAMMP FASL
- [x] FUNCEL FASL
- [x] LCHNSP FASL
- [x] LDBHLP FASL
- [x] LEXPRF FASL
- [x] LSETS FASL
- [x] NILAID FASL
- [x] PUREP FASL
- [x] REAP FASL
- [x] SHARAB LISP
- [x] SHARAB FASL
- [x] SHARPA FASL
- [x] SHARPC FASL
- [x] STRUCT FASL
- [x] THREAD FASL
- [x] TTY FASL

**Comment by eswenson1** [comment]
I'm working on this. For all the packages for which I can find source, I've been able to build the FASL files -- except STRUCT/NSTRUCT (DEFSTRUCT).  I'm having issues with this one. I've asked Alan Bawden about it -- it seems the file ALAN; STRUCT INITIA is damaged (in AI/MC/SV) and this file is actually needed at compile time to compile STRUCT.

**Comment by larsbrinkhoff** [comment]
If Alan doesn't have it, we'll have to hope for that TOTS project to come through.

**Comment by eswenson1** [comment]
I could look in a current Multics release to see if the file is there.  However, the Multics pathnames I've seen in the ITS sources are not to files in the "system" directories, but, similar to ITS, to files in user directories (which were not included in the Multics public domain release).

**Comment by eswenson1** [comment]
I looked in the Multics source tree and while the defstruct.lisp looks like it was derived from ALAN; NSTRUCT >, and I see lots of virtually identical code, the preamble (which loads ALAN; STRUCT INITIA) is very different.  I do see all the various dependencies that DEFSTRUCT has (sharpsign, defmacro, other_other, defstruct). I'm confused by defstruct's having a dependency on defstruct (circular), but this may be due to the fact that defstruct's current implementation uses defstruct, and you have to bootstrap from a previous version of defstruct (thus, we'd need STRUCT FASL in order to build STRUCT FASL).  I'm checking with Alan Bawden on this.

**Comment by eswenson1** [comment]
Well, I managed to build STRUCT FASL -- but I don't know if it is correct yet.  When you load my compiled STRUCT FASL into LISP, it claims it is DEFSTRUCT 280.  When you LISP; STRUCT FASL (binary from PI) you also get the same herald, so we may well be "good" here.  

I was unable to build STRUCT without having some FASL files (that are loaded by LSPENV INIT).  I believe I can build all those FASL files too, but I need them there as a bootstrap.  This isn't unprecedented. We used the binary COMPLR to build the LISP compiler and then replace it with the one built.  I believe we should be able to do the same bootstrapping of STRUCT and any of its dependent libraries.

**Comment by eswenson1** [comment]
While I *think* I'm able to build a STRUCT FASL from NSTRUC 280, the size of the resulting FASL is a little different from that in the PI distribution (8 +959 versus 8 +993).  I realized that earlier on, I had created an empty ALAN; STRUCT BOOT file (because compiling NSTRUC 280 requires this file, but I can find no such file in any of our virtual tapes).  Creating the empty file allows the compilation to succeed, and, as I said, the resulting FASL loads into lisp, and seems to provide DEFSTRUCT functionality, but since I don't know what was in STRUCT BOOT and since the sizes are slightly different, it is conceivable that we haven't reconstructed the identical FASL file.

**Comment by eswenson1** [comment]
Ahhh, it appears that ALAN; STRUCT BOOT is supposed to be a link to ALAN; NSTRUC FASL.
Replacing my empty STRUCT BOOT with NSTRUC FASL doesn't make the sizes match either.  Now, the compiled NSTRUC FASL is 8 +962, whereas the version in LISP; STRUCT FASL (which is a link to LIBLSP; STRUCT FASL) is 8 +993.  So a little closer, but not exactly.  I suspect, however, that this is all fine.  When ALAN (or whoever) last built STRUCT (NSTRUC), I suspect the PREVIOUS version of STRUCT FASL was different (earlier/older).  This might account for the differences.

**Comment by larsbrinkhoff** [comment]
Are there anything in Multics beoynd what we have in ITS?

**Comment by larsbrinkhoff** [comment]
Good job building STRUCT.  You can certainly add some FASL files.  I had to install a few :EJ files to build EMACS.

**Comment by eswenson1** [comment]
I doubt if there was anything in Multics beyond what we have in ITS. The several sources I looked at appeared to be older than what is in ITS (defstruct certainly was) -- but you could tell that the Multics version was created from the ITS version because much of it was identical.

**Comment by eswenson1** [comment]
In #380, the following lisp libraries are added:  BITS, BS, DEBUG, DRAMMP, FUNCEL, LCHNSP, LDHLP, LSETS, NILAID, PUREP, REAP, SHARAB, SHARPA, SHARPC, STRUCT, THREAD, and TTY.  

I haven't updated the checkboxes in the ticket description, as this PR hasn't been merged.

**Comment by larsbrinkhoff** [comment]
I listed the files in LISP now, and checked the boxes in the issue description.

I suppose the MACYMA build will check even more?

**Comment by eswenson1** [comment]
Yes

**Comment by eswenson1** [comment]
I'm going to split up the macsyma build a little -- and will include a commit that adds more Lisp library FASL files and the corresponding compilation to get the FASL files.  But I do have a bunch more that are needed to support the Macsyma build (which I'm getting very close to committing also).

**Comment by larsbrinkhoff** [comment]
Sounds like a good plan!

**Comment by eswenson1** [comment]
I was wrong -- there are no new FASL files, nor recompiled FASL files in the LISP directory as part of the Macsyma build. There are, however, updates the LIBLSP directory.  We don't have a similar checklist for that directory. I'll create another ticket for LIBLSP so that we can track those files remaining to be added/recompiled.

**Comment by larsbrinkhoff** [comment]
Is this list still useful?

**Comment by eswenson1** [comment]
Yes. Unless we want to enter tickets for the still-missing one.

**Comment by larsbrinkhoff** [comment]
Ok great, just checking.

**Comment by eswenson1** [comment]
Removing NADEFV, NALOOP, and NALET from this list because ticket #1089 covers them.

**Comment by eswenson1** [comment]
Removing @ FASL from this list because #1081 covers this file.

**Comment by eswenson1** [comment]
Removed FLRMAT FASL from this list because #735 covers this file.

**Comment by eswenson1** [comment]
Removing LODBYT from this list since #739 covers this file.

**Comment by eswenson1** [comment]
Removed MACLIS LISP, MACLIS FASL, and MACLIS SHARAB this list since #1090 covers these files.

**Comment by eswenson1** [comment]
Marking this issue resolved now that all files are either recovered and part or DB, or there are separate tickets on the original outstanding files.
