### ISSUE TITLE
Y2K problem

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#26]
The year 2016 in file listings is printed as 116.  This applies to both :LISTF and :FIND.

**Comment by bictorv** [comment]
Check http://up.update.uu.se/patch; for many Y2K fixes, including this (I think LISTF is fixed by recompiling after fixing DATIME.)

**Comment by larsbrinkhoff** [comment]
Thank you, @bictorv.  I'll look closely at all those patches.

**Comment by eswenson1** [comment]
It almost seems that there were several binary patches made by KLH in the PI distribution. We should look closely to see whether we should change some sources or patch some binaries.

-- Eric

**Comment by larsbrinkhoff** [comment]
@eswenson1 Why would it be preferable to patch binaries instead of sources?

**Comment by eswenson1** [comment]
Only If we didn't have sources for something.

-- Eric

**Comment by larsbrinkhoff** [comment]
Ah, of course!

**Comment by larsbrinkhoff** [comment]
@bictorv I tried your DAYTIME patch, then I downloaded  the whole file. In both cases I still saw the bug.

**Comment by larsbrinkhoff** [comment]
LISTF fixed in ITS"UQL5A.

FIND fixed in FIND"DATPRT.
