### ISSUE TITLE
EMACS display broken with VT100 height > 24

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#263]
If I run CRTSTY VT100, and then, say, TCTYP HEIGHT 50, EMACS display doesn't work well.  HEIGHT 24, which I suppose is the default, works fine.  Maybe that's hardcoded somewhere?

**Comment by larsbrinkhoff** [comment]
TCTYP VT52 works fine.

**Comment by atsampson** [comment]
Have you tried CRTSTY ANSI? That's what I'm using; it seems to be friendlier to modern terminals than CRTSTY VT100.

**Comment by larsbrinkhoff** [comment]
No I haven't, but  I will now.  Thanks!
