### ISSUE TITLE
MACRO-10 - DEC assembler

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#272]
DECSYS; MACRO SHR
SYS2; TS MACRO (says it's assembled from SYSEN1; LOADP 11)

Needed to build DEC software like FORTRAN, etc.

**Comment by larsbrinkhoff** [comment]
@36bit This, and also #170 FORTRAN (hey @budd), should fall under the "DEC 36-bit hobbyist license", see http://pdp-10.trailing-edge.com/.  Have fun!

**Comment by philbudne** [comment]
ISTR the versions of FORTRAN-10 (and perhaps its predicessor F40) in
ITS DECSYS; were ANCIENT (perhaps V1 of F10? I worked on versions 7
(FORTRAN-77) & 10 (octal, dontcha know! -- Extended Addressing))

I have a hard time ingaining anything in DECSYS would have been built
from source, or if it had, that the sources were hanging around.  It
was pretty much, by definition, "dusty stuff from DEC"

phil

**Comment by larsbrinkhoff** [comment]
> Needed to build DEC software

Note: we now have FAIL which, I believe, is compatible with MACRO-10.

**Comment by larsbrinkhoff** [comment]
With DECSYS; MACRO SHR installed, running `:dec sys:macro` gets to the * prompt.

**Comment by larsbrinkhoff** [comment]
Fixed by #1235.
