### ISSUE TITLE
MACSYMA

### ISSUE THREAD

**Issue by eswenson1** [PDP-10/its#284]
May not have everything we need to run. Most likely don't have sources to build it.

sys; ts a => maxdmp;maxima >
maxdmp; maxima 305

**Comment by larsbrinkhoff** [comment]
I read about Macsyma, and it seems the free version Maxima is based on a 1982 version of Macsyma from MIT.  It could be that the Maxima people still have the original version.

**Comment by eswenson1** [comment]
Do you have any contacts with the Maxima folks?  I worked for Rich Zippel and Barry Trager (both at MIT Project Mac) and they are both fraternity brothers of mine. We all three (and many, many more) worked on Macsyma at LCS.  I wonder if they know anything?

**Comment by larsbrinkhoff** [comment]
There's an active mailing list at sourceforge.net.  I'll try that.

There's a git repository, but the history only goes back to 2000.

**Comment by eswenson1** [comment]
I did just send email to both Rich Zippel and Barry Trager.  We'll see if either responds to me.

**Comment by larsbrinkhoff** [comment]
Good.  I sent a email to Joel Moses.

**Comment by eswenson1** [comment]
That was a good idea.  I'd also be keen on getting Multics Macsyma sources.

**Comment by larsbrinkhoff** [comment]
Also to Richard Fateman.

**Comment by ams** [comment]
I had a odd ball version of Macsyma for the Lisp Machine.   Absolutely no idea if it works, how far away from MACLISP it is, if this version ran on ITS, etc.

**Comment by eswenson1** [comment]
Can you pass it to us and i’ll try to build on ITS? Chances are pretty good that it is a fork of MC’s version and probably maintains it’s conditionalizations.

**Comment by ams** [comment]
Of course! I don’t have direct access to my machine until Sunday (January 21st, 2018), but will dump it somewhere then.

**Comment by larsbrinkhoff** [comment]
Some tidbits:  
http://bitsavers.org/pdf/mit/macsyma/

**Comment by larsbrinkhoff** [comment]
I haven't heard from Moses or Fateman yet.

**Comment by eswenson1** [comment]
I heard back from Rich Zippel, but didn’t learn anything new. I’m waiting to hear back after a follow-up message. He seemed to think all the sources would be in MC tapes. But I thought we’ve looked for them and not found them. 

-- Eric

**Comment by larsbrinkhoff** [comment]
Plenty of `#+MACLISP`, `#+ITS`, and `#+PDP10` in your dump, @ams.

Also `#+MULTICS` and `#+H6180`, @eswenson1.

**Comment by larsbrinkhoff** [comment]
List of conditionals used:
- fixcons
- franz
- gc
- h6180
- its
- jpg
- lispm
- maclisp
- maxii
- mit
- multics
- nil
- pdp10
- tops-20
- unix

**Comment by larsbrinkhoff** [comment]
@ams The file timestamps are from 2017.  Do you have the original timestamps somewhere else?  I'm just curious what age the oldest and newest files are.

**Comment by larsbrinkhoff** [comment]
Also, what do you mean by "oddball version"?

**Comment by larsbrinkhoff** [comment]
Is there a manual?  Is there a tutorial?

Make links from doc/DDT.md.

**Comment by ams** [comment]
@larsbrinkhoff By odd ball I mean I don’t know how much it might have been modified from any original dump.  There is no version information that makes sense (e.g., patch files say that this is Macsyma 1).  You can check when the patch files were generated for a hint in from when they are.

I’ll dig up the file time stamps for this later today.

**Comment by eswenson1** [comment]
It is pretty likely no one removed conditionals—however, as time marched on, it is unlikely people kept old conditionalizations up-to-date. Still, it should give us some hope.

-- Eric

**Comment by ams** [comment]
I created an issue with the original time stamps: https://github.com/PDP-10/macsyma/issues/1

**Comment by larsbrinkhoff** [comment]
Thanks!

**Comment by eswenson1** [comment]
I have managed to find and compile a lot of macsyma, by the way.  Don't have anything near working yet, but at least I'm able to make some progress.  There are some sources that I haven't been able to find, but I don't (yet) know how critical they are.

**Comment by ams** [comment]
Do you have a list of the missing ones? I can do some digging on my side.

**Comment by larsbrinkhoff** [comment]
Excellent!

**Comment by eswenson1** [comment]
Here are the ones I haven't been able to locate.  The ones with 
<missing> and a filename are those for which the source is missing but 
where we have a FASL file.


CFFK; APLOT2 >            <missing>
CFFK; TEKPLT >            <missing>
ELLEN; PRIMER >            <missing>
JPG; MEDIT >            <missing>
LIBMAX; LMMAC >            <missing>
LIBMAX; OPSHIN >        <missing> ./ai/libmax/opshin.fasl
MAXSRC; AR >              <missing>
MAXSRC; ARDS >            <missing> ./ai/macsym/ards.fasl
MAXSRC; ARRAY >            <missing>
MAXSRC; CHAR >            <missing>
MAXSRC; DESCRI >        <missing>
MAXSRC; ERMSGM >        <missing> ./ai/maxdmp/ermsgm.fasl
MAXSRC; H19 >              <missing> ./ai/macsym/h19.fasl
MAXSRC; MTRACE >        <missing> ./ai/macsym/mtrace.fasl
MAXSRC; MTREE >            <missing> ./ai/macsym/mtrace.fasl
MAXSRC; OUTEX >            <missing> ./ai/macsym/outex.fasl
MAXSRC; VT100 >            <missing> ./ai/macsym/vt100.fasl
PAULW; EEZ >              <missing> ./ai/macsym/eez.fasl
PAULW; NEWFAC >            <missing> ./ai/macsym/newfac.fasl
RAT; EZGCD >            <missing> ./ai/macsym/ezgcd.fasl
RAT; POIS2 >            <missing> ./ai/macsym/pois2.fasl
RAT; POIS3 >            <missing> ./ai/macsym/pois2.fasl
RAT; RATLAP >            <missing> ./ai/maxdmp/ratlap.fasl
RAT; RATPOI >            <missing> ./ai/macsym/ratpoi.fasl
TENSOR; ITENSR >        <missing> ./ai/macsym/itensr.fasl
TEST; XBATCH >             <missing>
TRANSL; LJOB >            <missing> ./ai/alan/ljob.74
TRANSL; MCOMPI >        <missing> ./ai/macsym/mcompi.fasl
TRANSL; MTAGS >            <missing> ./ai/macsym/mtags.fasl
TRANSL; TRDEBG >        <missing> ./ai/macsym/trdebg.fasl
WGD; MPRINT >              <missing>
ZZ; APROPO >            <missing>

 From looking at the maxerr; directory in the ai tapes, I can see that 
ITS had later versions of most of the files that were on Alfred's 
macsyma tape (from Symbolics).  This is interesting -- I would have 
thought that the Symbolics versions would have had greater version numbers.

In any case, I'm going to have a mixture of source/fasl files between 
those files on the Symbolics (I'm assuming this is where that tape came 
from, Alfred) tape and those files from the ai/mc tapes.

Still not at all clear that we have enough to get a macsyma working....

-- Eric

**Comment by eswenson1** [comment]
One of the missing files: libmax; lmmac > causes tons of stuff to not 
load or compile. I need to find that one.

It appears to define the following:

(DEFVAR LMMAC-FERROR-USE ±708
(DEFVAR LMMAC-CHECK-ARG-USE ²072
(DEFMACRO CHECK-ARG ²121
(DEFMACRO FIRST ²618
(DEFMACRO SECOND ²659
(DEFMACRO THIRD ²700
(DEFMACRO FOURTH ²744
(DEFMACRO FIFTH ²786
(DEFMACRO SIXTH ²835
(DEFMACRO SEVENTH ²887
(DEFMACRO REST1 ²938
(DEFMACRO REST2 ²976
(DEFMACRO REST3 ³015
(DEFMACRO REST4 ³055
(DEFMACRO / ³097
(DEFMACRO / ³161
(DEFMACRO NEQ ³228
(DEFMACRO / ³268
(DEFMACRO MAKE-LIST ³325
(DEFMACRO AREF ³411
(DEFMACRO ASET ³484
(DEFMACRO MAKE-ARRAY ³586
(DEFSETF AREF ³655
(DEFMACRO EVERY ´220
(DEFMACRO SOME ´579
(DEFMACRO FSYMEVAL µ099
(DEFMACRO FMAKUNBOUND µ279
(DEFMACRO FBOUNDP µ594
(DEFMACRO FSET µ638
(DEFMACRO FSYMEVAL µ712
(DEFMACRO FMAKUNBOUND µ763
(DEFMACRO MAKE-STRING-FROM-SYMBOL ¶283
(defmacro make-string-from-symbol ¶394
(DEFMACRO MAKE-STRING-FROM-CHARS ¶525
(defmacro array-dimension-n ¶907
(DEFMACRO INTERNEDP ·776
(DEFMACRO STRINGP ·907
(DEFMACRO STRING-LENGTH ¸161
(DEFMACRO STRING-EQUAL ¸214
(DEFMACRO READ-FROM-STRING ¸278
(DEFMACRO STRING-UPCASE ¸346
(DEFMACRO STRING-DOWNCASE ¸456
(DEFMACRO STRING-REVERSE ¸567
(DEFMACRO STRING-NREVERSE ¸665
(DEFMACRO MAKE-SYMBOL ¹140
(DEFMACRO GET-PNAME ¹345

Some of these, of course, are pretty easy to implement. Others, I'm not 
sure about. -- Eric

**Comment by larsbrinkhoff** [comment]
@b4, please keep an eye out for PDP-10 MACSYMA files.  Especially from MIT.

**Comment by eswenson1** [comment]
It turns out that this might be ok (but not great) because we do have 
lmmac.fasl.  So this isn't the show-stopper I thought it was.

-- Eric

**Comment by ams** [comment]
@ewswenson1 could you please not quote the whole previous thread? :-) It makes it suuuper hard to read on small devices.

**Comment by larsbrinkhoff** [comment]
@ams stop tinkering with your phone and get yourself to a real computer. :-)

**Comment by b4** [comment]
As best I can tell, I have one or two.

**Comment by ams** [comment]
I wasn't able to find any of those file in my stash.   But rewriting the `libmax; lmmac` file shouldn't be to complicated.

**Comment by eswenson1** [comment]
Yeah, I can guess what most of those macros do. In the mean time, I’m using the FASL. We’ll probably find we need to reconstruct a bunch of source from FASL files.

**Comment by eswenson1** [comment]
@b4  Were you able to locate any of the missing Macsyma files I referenced earlier in this thread?

**Comment by eswenson1** [comment]
Well, I've made a lot of progress, but may have hit a brick wall.  I need to find MAXSRC; ERMSGM > and JPG; MEDIT >.  There are other missing files, but these have blocked me so far.

By the way, I found that ALJABR; COMPLR > is the LISP source that provides the steps for building Macsyma.  Simply start COMPLR, load it, and run (MSCOMP).  Unfortunately, that bombs due to missing sources (two above are examples). You can $P to continue, but, of course, you won't get a working Macsyma.  

Also, you won't succeed just doing the above unless you have a bunch of files in the right places and some of them compiled already.  

I'll keep hacking, but it may be that we'll be stuck if we don't either fine the missing sources or reconstruct them. Some of these have FASL files, so we can just put the FASL files in the right places and if we have enough sources and FASL files, we might be able to run Macsyma -- that is my current effort.  I'll let you know how it goes.

**Comment by ams** [comment]
Can we backport the code from DOE Macsyma?

**Comment by eswenson1** [comment]
That will be my tact of last resort. I have the first commit to the sourceforge repo of MAXIMA, which shows many filenames matching those from ITS Macsyma.  Of course, the contents have been converted to Common Lisp, but one could, in theory, backport to MacLisp.

It would sure be nice if we could uncover the original ITS Macsyma that DOE started with....

**Comment by larsbrinkhoff** [comment]
Maybe the CSAIL tape archive people can dig up something?

**Comment by eswenson1** [comment]
Where is that?

**Comment by larsbrinkhoff** [comment]
Well, there's this: http://people.csail.mit.edu/devon/archive/

And I know Pandora Berman and Hal Abelson are more or less involved.  Also Brad Parker has been able to extract file files from MIT in the past.

But we have been in touch with all of the above, and it's not clear how much there is or how to get at it.

**Comment by eswenson1** [comment]
I've managed to compile all the Macsyma sources I can find.  I edited the "ALJABR;COMPLR >" lisp file to comment out those modules for which we don't (yet?) have source.  The process completes (and the FASL and UNFASL files are created.

I'm now trying to get the loader to load the FASL files and create a dumpable image.  This is currently failing.  It appears that one or more of the compiled FASL files are not "good" (loading them gives unresolved references to functions/defsets/macros).  I'm steadily working through each of those, recompiling manually and trying to produce FASL files that load without error.  Some of the previously-compiled files just needed to get recompiled after required macro files were recompiled and placed in the right places.  I'm currently stuck on one file (MAXDMP; COMPAR FASL), that I haven't managed to get compiled such that it loads without unresolved references.  Still working on it.

**Comment by larsbrinkhoff** [comment]
Thanks Eric.  I'm following this with interest!

**Comment by larsbrinkhoff** [comment]
Eric is away from hit GitHub password at the moment, so I'll pass on the word that he has now managed to build MACSYMA and has it running in ITS!

**Comment by ams** [comment]
Nice!!!

**Comment by eswenson1** [comment]
There, are, however, some decisions to make. What I did was to compile all the sources I could find and use FASLs for the few missing sources. I used sources from various sources, including that Symbolics tape from @ams. Many of the sources from that tape were older than FASLs I could find on ITS tapes. So one question to resolve is this: should we include in our DB ITS, the latest FASLs (which means very few sources) or the mixture (older version of Macsyma)?

**Comment by eswenson1** [comment]
When I dumped Macsyma (to get TS MACSYM), i used the INCORE (binary) file from the AI dump. This file is an input file used by the loader in ALJABR; LOADER >. I haven’t explored, yet, how this file is produced. I’d like to resolve that before committing changes.

**Comment by eswenson1** [comment]
Apparently, in order to build Macsyma, you need a bunch of FASL files, but also the UNFASL files and the files (whatever they are) from the MAXERR; and MAXER1; directories. These are all outputs of the Macsyma compilation process. Since we don’t have all the sources, I had to grab UNFASL and those MAXERR/MAXER1 files from AI tapes — which didn’t necessarily match in version. So, while the load and dump of Macsyma worked, and I get the appropriate prompt when I start it up, and the few simple expressions I’ve tried so far result in correct answers, I have no clue what will misbehave as a result of the mix-and-match compromise.

**Comment by larsbrinkhoff** [comment]
Generally, I'd like to favour sources over binaries where possible.  If no one is missing a crucial feature due to outdated sources, I don't think much harm is done.

If you want to add a binary file, build the program with that, but include the older source file too if there is one.

**Comment by eswenson1** [comment]
I haven’t really looked at the code to understand the purpose of MAXDMP; INCORE >, not of the MAXERR and MAXER1 output files. I think they have something do do with strings/messages and whether these are maintained in memory or not. I would like to understand all this before I commit changes to our build for Macsyma. 

So I might take a bit more time before you see a PR.

**Comment by eswenson1** [comment]
My inclination, too, is to use sources. Perhaps I’ll do that and if we find a bug in the resulting Macsyma that is resolved by replacing the compiled FASL with a later version FASL for which we have no source, we can make a conscious decision to use the FASL or try to fix the source ourselves.

**Comment by ams** [comment]
I think using sources where possible is better, even if we might have to use a older one.  As long as things get documented we can always update the code with either new versions or bug fixes (much harder for FASL)

**Comment by eswenson1** [comment]
Ok, that is the tact I've taken so far -- use sources where we have them, fasls where we don't.

**Comment by eswenson1** [comment]
A little preview:  https://pastebin.com/M4eNzQsK

As you can see, there are some issues to iron out, but a bunch of the stuff works.

**Comment by larsbrinkhoff** [comment]
Nice!  Was there ever some kind of graphical rendering of equations?

**Comment by eswenson1** [comment]
I don't know about that. I stopped working on Macsyma in 1980 and don't remember any when I was there (doesn't mean there wasn't one -- I just never used it).

**Comment by eswenson1** [comment]
If you type the "help();" command, you get an error that the file DSK:MAXOUT;DESCR FASL doesn't exist. I haven't been able to find the source for this file (but we do have the FASL file).

**Comment by eswenson1** [comment]
Installing MAXOUT; DESCR FASL as well as MAXOUT; MACSYM BINDEX and MAXOUT; MACSYM DOC does provide a working help system.

**Comment by eswenson1** [comment]
Seems you need the file MACSYM; MANUAL DEMO in order to run commands like:

example(delta);

I see lots of Macsyma-related demo files in AI: DEMO; * DEMO, but I don't (yet?) know how to combine them into a MANUAL DEMO file.

**Comment by eswenson1** [comment]
The PRIME() function appears to want to use the prime table on MC: It gets an error trying to access MC: MAXDMP; PTABLE >.  We'll have to find the source for the PRIME function and configure it to use the DSK: device.

**Comment by eswenson1** [comment]
When running more complicated Macsyma commands, I get errors like:

FXPDL storage capacity exceeded

I used the value of the fixnum PDL as specified in ALJABR;LOADER > -- so would have thought this should have been sufficient. Not sure why it isn't.  I'll try again (at some point) to rebuild Macsyma with a bigger FXPDL and see if it ameliorates the issue. We might have some other issue that is causing this error regardless of the FXPDL setting.

**Comment by kossow** [comment]
Did you ever get access to ToTS from Hal?

**Comment by eswenson1** [comment]
ToTS? Not to my knowledge. Lars?

**Comment by larsbrinkhoff** [comment]
@kossow, no we don't have access.  The MIT pepole are somewhat tight-lipped about it.

Hal wrote he contacted the MIT archivists in November 2016 about delivery of backup files from ITS.

**Comment by larsbrinkhoff** [comment]
I inquried about DOE Macsyma to the maxima mailing list.  I got this:

> https://sourceforge.net/projects/maxima/files/Maxima/historical/ has a list of some old tarballs. Note that the files in the tarballs are actually older than the tarballs themselves. The files in maxima-5.0.tar.gz date to the late 80's and early 90's. The most recent timestamps in the 5.0 tarball date to 1994. Note that's before Bill Schelter obtained permission (1998) from DOE to distribute Macsyma under terms of the GPL.
> 
> Maxima 5.0 presumably contains DOE Macsyma plus changes that were made by Schelter. I don't know for sure if I've ever encountered DOE Macsyma itself. But I have a vague recollection that at some point it was actually listed on a DOE website as a software download. Is that possible? Wishful thinking perhaps?

**Comment by larsbrinkhoff** [comment]
Maxima 5.0 does have #+ITS, #+Maclisp, and #+PDP10 conditionals.

**Comment by eswenson1** [comment]
So it is still MacLisp-based and ported to CL?

**Comment by eswenson1** [comment]
I downloaddd the earliest version I could find and checked the contents. Although it was clearly based on ITS Macsyma and did still have ITS (and Multics) conditionals, it has been ported to CL. And I looked for one of the missing files (ERMSGM) and it wasn’t there.

**Comment by eswenson1** [comment]
While I can still update the source tree to build a version of Macsyma, I can't correctly handle the message files and the updating of MAXDMP;INCORE >.  This file is generated using tools in the MAXTUL directory.  They rely on the FASL reading logic in RLB;FASLRO 71.  I cannot compile that file, and can't find a FASL for it, because it requires RLB; BITMAC, which I can't find anywhere.

Now, there may be other impediments for building an updated message system, but for now, I'm going to just use the binary INCORE > file that we have -- that is what I did in building, dumping, and running the Macsyma that I have.  However, it means that a) it doesn't match the actual source/FASL files we have for Macsyma (since it was built from different versions of many of the sources) and b) we can't update it in the future, if we ever update other sources.

**Comment by eswenson1** [comment]
Brad Parker found me BITMAC, so now I can compile FASLRE and FASLRO.  That's great.  I'll see what else I need to get INCORE created.

**Comment by eswenson1** [comment]
I've managed to build macsyma and the resulting executable runs.  I'll create a PR soon.
