### ISSUE TITLE
FED - font editor

### ISSUE THREAD

**Issue by eswenson1** [PDP-10/its#289]
SYS; TS FED
SYSEN2; FED 134
.INFO.;FED ORDER

**Comment by eswenson1** [comment]
Also needs SYSENG;FNR 10

**Comment by larsbrinkhoff** [comment]
https://dspace.mit.edu/bitstream/handle/1721.1/41113/AI_WP_078.pdf

**Comment by ams** [comment]
Is this the same/similar to the FED on CADR?  I am thinking if the original, not the Symbolics variant which was a total rewrite AFAIU.

**Comment by larsbrinkhoff** [comment]
I don't know what the CADR FED is like.  The ITS one isn't really an editor.  It converts between a text format and one or two binary formats (don't remember).

**Comment by ams** [comment]
The CADR FED takes a ASCII file (KST suffix) and spits out a QFASL.  There is a graphical editor as well to edit KST or QFASL fonts directly.

**Comment by larsbrinkhoff** [comment]
Ok, it certainly must be closely related, but the ITS program is written in MIDAS.  The text input is called AST, and the binary output is called KST.

It should also be possible to display the font on a 340 or Knight TV display.
