### ISSUE TITLE
CHARFC/CHARFS - CHAOS RFC

### ISSUE THREAD

**Issue by eswenson1** [PDP-10/its#296]
SYS1; TS CHARFC
MOON; CHARFC.3
SYS1; TS CHARFS => SYS1; TS CHARFC

**Comment by larsbrinkhoff** [comment]
What is RFC?  There's also something called NETRFC, I'm guessing it's something related?

**Comment by eswenson1** [comment]
Request for Comments? :-). I just copied what was in the header. Was going to look into what RFC they were implementing if/when ticket got assigned to me!

**Comment by larsbrinkhoff** [comment]
There's a .CALL called NETRFC - Get pending Request For Connection.

**Comment by larsbrinkhoff** [comment]
Usage is: :CHARFC HOST <space> CONTACT NAME

From Wikipedia:

"*Initial establishment of the connection was made using "contact names." These names identified the network service and higher-level protocol. For example, "STATUS" was the contact name which requested basic network statistics from a host. "TELNET" was a contact name for the Arpanet TELNET protocol. "FILE" was a contact name for the Lisp Machine network file service. Other contact names included "SUPDUP", "MAIL", "NAME" for the Arpanet Finger protocol, "TIME", "SEND" for interactive messaging, "ARPA" for a gateway service to Arpanet. "DOVER" was the contact name for sending print jobs to Chaosnet hosts with a Xerox Dover printer attached (an early laser printer). Developers could easily experiment with new protocols by inventing new contact names. In ITS, a new server for that protocol could be installed by creating a link to the program in the location DSK:DEVICE;CHAOS <cname> where <cname> was up to six letters of the contact name.*"

**Comment by larsbrinkhoff** [comment]
From INFO; NETWRK 1:

> For contacting a host at an arbitary contact name, use
>            :MOON;CHARFC host contact
