### ISSUE TITLE
TTY - display TTYs and UNAME/JNAME/CORE and other info

### ISSUE THREAD

**Issue by eswenson1** [PDP-10/its#302]
SYS1; TS TTY
SYSEN1; TTY 8

**Comment by atsampson** [comment]
It's a bit hard to see what this program is actually doing on a fast terminal...

Mark Crispin in news:Pine.OSX.4.64.0601081045290.9510@pangtzu.panda.com:

> > What was the difference between tty <CTRL/F> and tty <CTRL/K>?
>
> Both commands showed a "systat" or "who" type display of who else was on 
> the system, what they were running, etc.
> 
> tty <CTRL/F> showed the directory of the TTY: device, that is 
> the contents of TTY:.FILE. (DIR)
> 
> tty <CTRL/K> ran the TTY program, which showed the same directory, only it 
> output each character in a random order (albeit at the correct screen 
> position).  It was quite the neat thing to watch.

**Comment by larsbrinkhoff** [comment]
I logged the output.  Indeed there's a lot of cursor motion going on.  But why?!?
