### ISSUE TITLE
CHATST - Chaos Test

### ISSUE THREAD

**Issue by eswenson1** [PDP-10/its#308]
SYS2; TS CHATST
AI: MOON; CHATST 56

**Comment by eswenson1** [comment]
When you run this, you get a "ILLEGAL SYSTEM CALL NAME" referencing CHAOS0.  It may well be that this is old and no longer supported by ITS.

**Comment by larsbrinkhoff** [comment]
I sometimes see references to DM being somewhat special, and doing things the other ITS systems didn't.  But I wouldn't guess Chaosnet testing would be one of thsoe.

**Comment by eswenson1** [comment]
Yes, DM had daemons, INIT, and a file system that could hide directories from prying eyes.
