### ISSUE TITLE
MIDAS mode for GNU Emacs

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#337]
I get this when I open a MIDAS file in GNU Emacs:

    File local-variables error: (void-function midas-mode)

**Comment by eswenson1** [comment]
Seems we are missing midas-mode. Must be an :EJ for it.

**Comment by larsbrinkhoff** [comment]
ITS EMACS seems to do fine with -\*- MIDAS -*- files.

**Comment by larsbrinkhoff** [comment]
MIDAS Mode is part of USRCOM.

**Comment by larsbrinkhoff** [comment]
USRCOM handles these modes:

- LISP
- PALX (same as MIDAS)
- MIDAS
- TECO (loads PURIFY)
- TEX (loads TEX)
- Scribe (loads SCRIBE)
- Text
- Fundamental
- Macsyma
- MUDDLE (loads MUDDLE)
- PL1 (loads PL1)
- Debug (loads TDEBUG for debugging TECO)
- Auto Fill
- Atom Word
- Overwrite
- Indent Tabs
- SAIL Character
- Word Abbrev (loads WORDAB)
-

**Comment by larsbrinkhoff** [comment]
I started a MIDAS mode for GNU Emacs: http://github.com/larsbrinkhoff/midas-mode

**Comment by larsbrinkhoff** [comment]
There's one feature that would be really useful: Jumping to a line specified by a MIDAS error; i.e. page number and line number within page.
