### ISSUE TITLE
Need MacLISP

### ISSUE THREAD

**Issue by eswenson1** [PDP-10/its#35]

**Comment by larsbrinkhoff** [comment]
I believe INQUIR is written  in Lisp, right?  Is there anything else?

**Comment by eswenson1** [comment]
Yes. I have INQUIR building fine.  But it assumes LISP is built.

**Comment by eswenson1** [comment]
I think there are other apps built in lisp too.  Will have to check to come up with a list.

**Comment by larsbrinkhoff** [comment]
Is there anything of interest here?  
ftp://ftp.ultimate.com/pdp10/maclisp/

I'm not sure what versions 804 or 861 are, or what version we have.

**Comment by eswenson1** [comment]
We appear to have a much later version of *lisp.154 than the midas source for MacLisp in the 861 tarball.  The copyright on 861 is 1979.  The copyright on *lisp.154 is 1981.  Our Maclisp claims to be version 2154 (this might be because we built it, but that suggests that the sources we got were originally for 2153 (or thereabouts).  I suspect 861 is really version 861 -- quite a bit older than 2153.

**Comment by eswenson1** [comment]
There do appear to be some lisp sources in the lisp and lisp2 tarballs that we don't have. Not sure how old they are. However, if we find we're missing something important, these two tarballs might be a way of getting at least *some* version of them.  One example -- apropos. I don't think we have the source for this -- but it is in the lisp.tar.gz tarball.

**Comment by larsbrinkhoff** [comment]
Hello @philbudne, 

Do you remember where (or when) these tarballs came from?  
 ftp://ftp.ultimate.com/pdp10/maclisp/

**Comment by philbudne** [comment]
The maclsp* tarballs probably came from files from Stevens Tech,
possibly sent via tape by JONL.

I think the lisp* tarballs are of files FTP'ed from a public access
XKL Toad system system (possibly Paul Allen's PDP Planet, which
predated LCM).

phil
