### ISSUE TITLE
MAIL dates don't handle 21st century very well

### ISSUE THREAD

**Issue by eswenson1** [PDP-10/its#353]
Mail received on ITS displays Date headers similar to this:

Date: Tue, 20 Dec ;6 15:18:33 EST

Note the ";6", which should be "16" or "2016".

**Comment by larsbrinkhoff** [comment]
@Pul-Ess and @bictorv both have some changes to adress Y2K problems.  I tried them lightly, but so far didn't make any progress.

**Comment by larsbrinkhoff** [comment]
I saw this too.  (Except it's been a while, so it was ;9.)

**Comment by bictorv** [comment]
I fixed that in KSC;OUT around 2005, see http://up.update.uu.se/patch; for a description and patch.

**Comment by larsbrinkhoff** [comment]
Thanks.  I chose to conservatively stay with RFC 822 and make the two-digit years work, and I see you updated them to RFC 2822.  That's something to consider.

**Comment by bictorv** [comment]
Hmm, why not follow the current standard when it's so easy to do?

**Comment by larsbrinkhoff** [comment]
In this case I saw the comment `; Year as 2-digit number.` so I stayed with that in order not to risk break any code.  I didn't check anything further, so I didn't notice it's actually for output of RFC 822 date & time.

**Comment by larsbrinkhoff** [comment]
@eswenson1, have ES received any mail lately?  Was the Y2K bug fixed now?

**Comment by eswenson1** [comment]
I just sent some mail from ES to ES and got this:

```You have mail from COMSAT:
Date: Mon,  5 Oct 20 09:36:32 EDT
From: COMSAT@ES-ITS.SWENSON.ORG
Subject: Msg of Monday, 5 October 2020 09:36-EDT
To: EJS@ES-ITS.SWENSON.ORG
Message-ID: <1214.201005@ES-ITS.SWENSON.ORG>

Queued: (FILE [EJS;EJS MAIL]) at ES-ITS.SWENSON.ORG```

Not really sure why it was queued, but all the dates look ok.  Does that answer your question?

**Comment by eswenson1** [comment]
Seems my directory was full -- reason for the above. Just deleted some files and then sent another message.  Received it fine as:

```Date: Mon,  5 Oct 20 09:41:57 EDT
From: Eric J. Swenson <EJS at ES-ITS.SWENSON.ORG>
To:   EJS at ES-ITS.SWENSON.ORG

test```

**Comment by larsbrinkhoff** [comment]
> I just sent some mail from ES to ES and got this:
>
> Date: Mon,  5 Oct 20 09:36:32 EDT
> Subject: Msg of Monday, 5 October 2020 09:36-EDT

Thanks.  These two dates look fine.

> and then sent another message. Received it fine as:
>
> From: Eric J. Swenson <EJS at ES-ITS.SWENSON.ORG>
> To:   EJS at ES-ITS.SWENSON.ORG
>
> test```

No date there though.

**Comment by eswenson1** [comment]
Actually there was.  Here it is again:

```
Date: Mon,  5 Oct 20 09:41:57 EDT
From: Eric J. Swenson <EJS at ES-ITS.SWENSON.ORG>
To:   EJS at ES-ITS.SWENSON.ORG

test
```

**Comment by larsbrinkhoff** [comment]
Looks god too.  I guess we can close this then.
