### ISSUE TITLE
LSPEED gets a .VAL 0

### ISSUE THREAD

**Issue by eswenson1** [PDP-10/its#365]
When you attempt to execute LSPEED without parameters, and even if you supply JCL (perhaps only incorrect JCL), LSPEED gives you a .VAL 0.

**Comment by larsbrinkhoff** [comment]
Due to .EVAL not finding one of these symbols: NFDLTY, NDLTYS, DL10PL, DL10PR, DL10PS, NFETY, NETYS, DTELSP, DTELPR.

MIT-MC only?
