### ISSUE TITLE
ITS on KA10 and/or KL10

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#376]
@rcornwell is working on a KA10 emulator.

AI Lab WP 227 descibes how to boot ITS on a KA and KL.

**Comment by larsbrinkhoff** [comment]
@alanmimms, how is that KL10 simulator coming along?  We can send you the ITS microcode for testing.

**Comment by alanmimms** [comment]
I have set it aside. To much work for my job right now and the worth approach I was taking didn't seem like it would be successful. Maybe in a few months I can go back to it.

**Comment by larsbrinkhoff** [comment]
@rcornwell says his KA10 emulator is ready for initial testing with standalone utilities.  I guess MAGDMP would be a good first test.

**Comment by larsbrinkhoff** [comment]
I'll close this for now.
