### ISSUE TITLE
TEACH; LISP

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#377]
There's TEACH; TS LISP that says it's assembled from SYS: SYS; PURQIO 2149.  So Lisp, I guess?

TEACH; TEACH 159 looks promising.

@BobKerns, do you want to look into this?

**Comment by larsbrinkhoff** [comment]
It loads:
- BACKQ
- TEACH; MACRO
- LIBLSP; IOTA FASL
- LIBLSP; TIME
- LIBLSP; GPRINT
- APROPOS
- DATABASE
- ERRHEL
- ERRHAN
- EXLIST
- COMPLAIN
- IO
- LESSN
- MORE
- RECORD
- TREEPR
- INIT

I think we have everything covered.

**Comment by eswenson1** [comment]
Wow! RWK! Didn't know he came onboard.

**Comment by eswenson1** [comment]
Or I can, once I finish the rest of the lisp packages.

**Comment by larsbrinkhoff** [comment]
I suppose all of TEACH; LESSON * are part of this.

**Comment by larsbrinkhoff** [comment]
TEACH; TS MACSYM - teach Macsyma?  
TEACH; TDUMP 2 - xfile for dumping a new TEACH; LISP  
TEACH; TEACH DUMP - Lisp file for dumping  
TEACH; TEACH MIDAS

**Comment by larsbrinkhoff** [comment]
It seems proper that RWK should have dibs on this. :-)

**Comment by BobKerns** [comment]
I  imagine TS MACSYM is probably a link?

LESSON * would be the content,, written by me and KMP.

No idea about TEACH MIDAS. Where would I find all this good stuff? I poked around a bit earlier but I am on my phone, so I didn't clone.

Maybe I should get ITS up on this phone.. I think SIMH should work. Maybe even KLH10?

Can I get it up on my watch?

**Comment by larsbrinkhoff** [comment]
Yes, both SIMH and KLH10 works.  I suggest you run CROCK on your watch!

**Comment by eswenson1** [comment]
Indeed. But I doubt he'll be able to get it up on his watch!  :-)  @bobkerns let me know if you want to take this on or if you'd like me to.

**Comment by larsbrinkhoff** [comment]
Looks like it's all yours, @eswenson1!

**Comment by eswenson1** [comment]
Did @bobkerns say he did't want to do it?

**Comment by larsbrinkhoff** [comment]
No, he didn't say either way.

**Comment by larsbrinkhoff** [comment]
Ping.

**Comment by larsbrinkhoff** [comment]
I think we can safely say this is up for grabs.  I'm looking at it now, but I'll defer to you @eswenson1.

**Comment by larsbrinkhoff** [comment]
- TDUMP starts Lisp and loads TEACH DUMP.
- TEACH DUMP loads TEACH INIT.
- We don't have a TEACH INIT!  But maybe it was a link to TEACH; INIT >.
- TEACH DUMP calls `DUMP`.
- DUMP is defined in TEACH; TEACH >.  How is that file loaded?
- TEACH; START > reads TEACH; GLOBAL > to intern a list of symbols.
- It also loads TEACH; TEACH >.
- Maybe TEACH INIT should be a link to TEACH; START >?

**Comment by BobKerns** [comment]
Sorry to be AWOL. I've had a lot going on w/ health (mine and family), and haven't been able to get up to speed to really say or do anything useful.

In particular, I don't know where the files you're referencing are? I can't find them in master and there doesn't seem to be an obvious branch.

Does TEACH DUMP load TEACH INIT from TEACH;, or from the current dir? It might be found in RWK;...

Or it might be one of the two links you hypothesize.

Anyway, if you can point me to the files, I'll see if I can offer any insight.

**Comment by larsbrinkhoff** [comment]
Hello @BobKerns,

Thanks for getting back in touch.  The files are here:  
https://github.com/PDP-10/its-vault/tree/master/files/teach

**Comment by BobKerns** [comment]
Thanks!

Observations:

- It looks like TEACH DUMP and START > are alternatives for deployment & dev, respectively.
- I didn't know it had been ported to TOPS-20!  KMP's work, I'm sure!
- I don't know if it was ever on AI: (per the commit message). I was only aware of it on MC. Do you know if it was actually there, or just a commit message artifact?
- There's MIDAS code there to respond to interactive requests for help from students, in the AR3 MIDAS archive.
- I think INIT > had to be loaded at runtime, to set up the interrupt handlers, etc. I bet TEACH INIT was a link to INIT > as you suggest. That was a pretty common convention for complex init files.

**Comment by eswenson1** [comment]
If you do the following:
  :link teach;teach init,teach;init >
  teach$$^S
  teach$^S
  complr^K
  teach;teach
  ^Z
  :KILL
  lisp^K
  (load '((teach) teach)
  (load '((teach) init)
 
You get a GC OVERFLOW.  If, at this point, you simply do:

  $p<space>

TEACH starts up and prompts with a "$".

If you then type:

  (lesson)

A lesson starts.

**Comment by eswenson1** [comment]
The above steps seem to result in a working TEACH.  I typed:
```
(lesson info)
```
and went through some of the intro, typing ^N when told to move to the next section.

I ran into this section:

```
Getting a normal Lisp
------- - ------ ----

To get a Lisp, one normally types LISP^K or just L^K (or one of several
variations on this.....) However, for the purposes of this course there
has been created a special version of Lisp (one of the neatest things
about Lisp is that it makes such things surprisingly easy.). To run it,
just say :RWK;LISP
```

This suggests that we'll need an RWK;TS LISP -- probably a link to SYS; TS LISP.

**Comment by eswenson1** [comment]
I went through the following lessons without any issues:  INTRO, EVAL, OBJECT, DOT, SETQ, COND, FIB, MEMQ, ASSQ, LAMBDA, DEFUN, OUTPUT, INPUT, PROG, and DO. After DO, came TRACE. I didn't actually do any work in this lesson, just typed ^N at each step. At the end, TEACH asked me whether I wanted to restart TRACE. It didn't offer to move onto any other lesson.  Perhaps there aren't any.

**Comment by eswenson1** [comment]
The above error occurs because there is no saved-obarray property on the 'obarray symbol. I'll look for a source file that saves the old obarray and try to load it before running TEACH DUMP.

**Comment by eswenson1** [comment]
Looks like one shouldn't load teach;teach fasl, but rather teach;start >.

**Comment by eswenson1** [comment]
Well, that doesn't work.  While a saved-obarray property is placed on 'obarray, I still get .val errors trying to dump.  

While I haven't managed to figure out how to dump a TEACH using TEACH; TEACH DUMP, I have managed to dump a TEACH (defaults to TEACH; TS XLISP) by manually running (DUMP) after forcing the OBARRAY to be the one that is the one saved on the 'obarray symbol.  

I did this:
```
(setq obarray (get 'obarray 'saved-obarray)
(dump)
```

in a lisp where I had loaded teach; start >.  But I don't understand (yet) why TEACH DUMP doesn't work.  It just binds obarray to the saved obarray and funcalls the function on the DUMP symbol (which is put there by TEACH; TEACH FASL).  That should have worked as far as I know.

**Comment by eswenson1** [comment]
If I do this:

```
teach$$^S
lisp^K
n
(load '((teach) start)
(let ((obarray (get 'obarray 'saved-obarray))) (funcall (intern "DUMP")))
```

I can successfully create a TEACH; TS XLISP that is a TEACH lisp.   And it appears to work.
Why TEACH; TEACH DUMP doesn't work is still a mystery to me.  @larsbrinkhoff we've seen a .VAL recently from LISP and proceeding from that PC gave an ILOPR, I think.  Do you remember what that was, and what the solution was?

Regardless, we can create a TEACH using the steps I mentioned above, so we can proceed with including TEACH in DB if we like.  Thoughts?

**Comment by eswenson1** [comment]
For me, at least, loading teach;init > (or teach;teach init, as a link to teach;init >) results in the .VAL error.  The approach to dumping a TEACH xlisp in my previous post seems to work -- it does result in INIT > being loaded.  TEACH > has a "(load-module init)" which loads INIT.  So I don't really know what TEACH; TEACH INIT is supposed to be -- not a link to TEACH; INIT >.

**Comment by eswenson1** [comment]
So I created a dummy file called TEACH; TEACH INIT, which contained just ().  And then, I can do this successfully:

teach$$^S
lisp^K
n
(load '((teach) start))
(load '((teach) teach dump))
```

And this successfully dumps out a TEACH; TS XLISP that works.

**Comment by eswenson1** [comment]
Note; I used all the FASL files from 1982-1984 for the above experiment except for TEACH >, which I had recompiled.  I'm going to retry the whole experiment when compiling all the LISP files to FASL files first.  If this works, shall I commit this to DB build?

**Comment by eswenson1** [comment]
I deleted all the FASL files (from 1982-1984) and recompiled them (first compiling MACRO in one COMPLR, and then all the rest in another).  I then redumped a new XLISP, and it worked fine.  So I think we are "good" here.  I'll commit unless I hear from Lars that I shouldn't for some reason.

**Comment by larsbrinkhoff** [comment]
Good work!  Can you make a pull request as usual?

**Comment by eswenson1** [comment]
I'm going to commit everything necessary to build TEACH; TS XLISP, as well as the all the LESSON files that we have in the its-vault.  I'll also commit the -read- -this-, to-do >, no >, yes >, tdump >, teach bugs, and teach midas.  I'm not going to build no or yes (in this commit) or do anything with those auxilliary files. In another commit, I can see about building yes and no to see if these actually work, as well as figuring out what to do with the extra files.  Ok?

**Comment by larsbrinkhoff** [comment]
Ok.
