### ISSUE TITLE
Source for LIBLSP;DPRINT.FASL damaged

### ISSUE THREAD

**Issue by eswenson1** [PDP-10/its#379]
DPRINT.FASL is compiled from ALAN; DPRINT 142. This file, however, is damaged. It has garbage at the beginning of the file, then the actual DPRINT 142 begins, but then ends in the middle of the INSPECT function.

We should see if we can find this source somewhere else. If not, we could remove the INSPECT function, which is documented as an "additional" feature (see LIBDOC; DPRINT ALAN), and then it will compile. However, it won't include the INSPECT capability for DEFSTRUCTS.  Perhaps it is best to leave the DPRINT FASL un-recompiled until we can recover the pristine source.

**Comment by larsbrinkhoff** [comment]
Or, if we're really lucky, the missing data may be in another file.

**Comment by eswenson1** [comment]
Good point. Most likely at the start of the next file in the dump tape.

**Comment by larsbrinkhoff** [comment]
SailDart may be another source of file replacements.  Did a quick search for dprint, but didn't find anything obvious.

**Comment by eswenson1** [comment]
I also checked in the Multics lisp library and didn't find it.

**Comment by eswenson1** [comment]
I noticed that the next file in the directory where DPRINT 142 lives (according to DIR.LIST) is a link, and the file after that appears undamaged. And the file after that (DZ11.6) is damaged, and while there is some lisp code at the head of that file (before the ;-*- Lisp line, it doesn't appear to be the "correct" code for the missing part (at the bottom) of DPRINT 142.

**Comment by larsbrinkhoff** [comment]
Source no longer missing.

**Comment by larsbrinkhoff** [comment]
@eswenson1, did you forget about this one?

**Comment by eswenson1** [comment]
It looks like it is done. We’re compiling it in lisp.tcl. Right?

**Comment by larsbrinkhoff** [comment]
Right.  Thanks!
