### ISSUE TITLE
Build LISP compiler

### ISSUE THREAD

**Issue by eswenson1** [PDP-10/its#383]
Currently, we're dumping out a new lisp compiler from the pre-built FASL files. We need to build these FASL files from source.

**Comment by larsbrinkhoff** [comment]
Right, it's much like EMACS.  I had it dumped from a few pre-built :EJ files, which are later rebuilt.  But I should dump a new EMACS from the rebuilt files.

**Comment by aap** [comment]
I couldn't find the lisp source files anywhere. Do they still exist?

**Comment by ams** [comment]
Do you have a list of the files you are looking for?

**Comment by aap** [comment]
I wonder where the fasl files in LISP come from. Unfortunately I don't know too much about ITS.

**Comment by larsbrinkhoff** [comment]
Sorry, those source files are not in here yet.  I suppose Eric will be working on that.

**Comment by eswenson1** [comment]
Yes, I'm working on it.

-- Eric
