### ISSUE TITLE
CHASE - game

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#391]
BMT1; CHASE INFO  
BMT1; CHASE (INIT)  
BMT1; CHASE FASL

Lisp source mising.

**Comment by larsbrinkhoff** [comment]
BAK; CHASE 78

**Comment by larsbrinkhoff** [comment]
The info file states this game is copyrighted.  We can ask Kornfeld's permisson on linkedin or facebook.

**Comment by larsbrinkhoff** [comment]
I wrote him through facebook.

**Comment by eswenson1** [comment]
Great.  Thanks.

**Comment by larsbrinkhoff** [comment]
Hello @bill-kornfeld,

There are a few of us involved with preserving software from the Incompatible Timesharing System and restoring it to working condition.  We have found your game CHASE for VT52 terminals.  The info file clearly states it's copyrighted by you.  We would like to ask permission to publish your game on GitHub.  May we do so?

Best regards,
Lars Brinkhoff

**Comment by larsbrinkhoff** [comment]
Eric got this message from Bill:

> Absolutely.  You have my permission to use the material in any way you see fit.

**Comment by eswenson1** [comment]
The binary, info, etc. are installed in GAMES as part of #907.  Still need to build from source.

**Comment by eswenson1** [comment]
I can't figure out how to compile BAK; CHASE 78. It makes references to NEWCOPY and MAKESYM. While I can guess what MAKESYM is supposed to do and can write a function that does what I think it is supposed to do, I can't figure out NEWCOPY.

**Comment by eswenson1** [comment]
I have CHASE compiling now. I defined MAKESYM and NEWCOPY and fixed some missing parentheses and now it appears to compile and load when run.  I don't think my SUPDUP client is emulating a VT52 so I'm unable to play successfully, though.

**Comment by larsbrinkhoff** [comment]
No, it won't work very well through a SUPDUP session.  It could be an interesting exercise to make a VT52 emulator that uses P-codes.  (I have an idea to make a microcode level VT52 *simulator*, so maybe I'll do just that.)

I'll test this in an xterm, which supports VT52 emulation.

**Comment by atsampson** [comment]
> It could be an interesting exercise to make a VT52 emulator that uses P-codes.

CRTSTY should be able to do that, with something like ":crtsty soft simulate vt52". (No idea whether it actually works, but the code is definitely there!)

**Comment by eswenson1** [comment]
I think CHASE actually does work — as long as you type only uppercase ascii characters as commands. And the doc says that you are supposed to use these uppercase commands.

**Comment by larsbrinkhoff** [comment]
Thanks @atsampson, I didn't know CRTSTY could do that too.
