### ISSUE TITLE
Assembler Guide from Columbia University

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#394]
Maybe this would be a nice addition to the INFO directories?

http://www.columbia.edu/kermit/ftp/dec20/assembler-guide.txt

**Comment by eswenson1** [comment]
Well, it is a DEC-20 assembler manual -- isn't the instruction set sufficiently different from that of a KS-10 that it might be confusing?

**Comment by larsbrinkhoff** [comment]
I think the user instruction set is almost identical.  There are probably differences between MACRO-10/20 and MIDAS.

**Comment by larsbrinkhoff** [comment]
It's part of SV: DOC; (#420), so this can be closed.

**Comment by atsampson** [comment]
Chapter 2 of this, which says it was "written by Ralph E. Gorin at Stanford University and modified slightly at Columbia", is nearly the same as INFO; PDP-10 >. I can't see it on SAILDART, but perhaps it's in REG's non-public directory...

**Comment by larsbrinkhoff** [comment]
We can try asking Ralph.  What is the question, exactly?  If we can get a copy of the original SAIL file?

Maybe it evolved into this?  https://github.com/PDP-10/documents/blob/master/asm-intro-dec10.pdf

**Comment by atsampson** [comment]
Yes, that looks like a descendent of the same text -- e.g. chapter 6.1.1 on MOVE is an extended version of the text from the other two documents.

I'm not sure it's worth bothering him about at the moment, but if we get PUB/Scribe (and some kind of ersatz XGP-to-PDF process) up and running in the future then the sources for books like this would be nice to have.
