### ISSUE TITLE
PIC file format

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#395]
What is the file format for the PIC files, e.g. in the -PICS- directory?

INFO; DIR says there should be a file VIS; IMAGES, but there is no such directory.

**Comment by ams** [comment]
Contact Bjorn Victor; he will know.  UP has some hacks for rendering PIC files as SVG.

**Comment by larsbrinkhoff** [comment]
Thanks, done.

**Comment by larsbrinkhoff** [comment]
.INFO.; ARDS INFO

**Comment by larsbrinkhoff** [comment]
ARDS = Advanced Remote Display System.  Developed in-house at Project MAC.
