### ISSUE TITLE
DEC Hobbyist License

### ISSUE THREAD

**Issue by 36bit** [PDP-10/its#398]
Relevant for #170 and #272

I have made contact with Nissa Strottman, Associate General Counsel, Software, Cloud and Open Source at HP Enterprise about changing the DEC 36-bit hobbyist license into a proper [free software](https://www.gnu.org/philosophy/free-sw.html) license. This would affect not just those programs but everything that DEC's non-free 36-bit hobbyist license applies to like TOPS-10 and TOPS-20 and OS/8.

I've also asked about freeing up the documentation for those things. My understanding is that DEC had given permission for people to make copies of the documentation they no longer sold. See http://web.archive.org/web/20030422082524/http://www.decdocs.org/ for a copy.

The current wording is problematic in that it's not clear if it allows for giving copies of that documentation to others. It also doesn't seem to cover modification though so it's non-free regardless. So I've also asked about expanding it to cover documentation for that stuff too.

Seems positive so far. She replied saying "Thanks. We'll take a look at this and get back to you." I shall hold out hope for a positive outcome.

**Comment by larsbrinkhoff** [comment]
Any news on this?

**Comment by 36bit** [comment]
Despite the initial positive response she has since not replied to any further prodding from me.

**Comment by larsbrinkhoff** [comment]
Let's reopen this if there's any news.
