### ISSUE TITLE
Dump a new ITS

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#4]
The ITS monitor builds, but is not yet dumped and installed in `.`.  We also have EDDT and NSALV, so everything is in place.

Question: Is it possible to use timesharing DDT to dump?  Just $L and $$L the components, and then $Y.

**Comment by larsbrinkhoff** [comment]
> Is it possible to use timesharing DDT to dump? Just $L and $$L the components, and then $Y.

Well, I tried to $L ITS BIN, $$L NSALV BIN, and $Y .;@ NITS.  DSKDMP couldn't even load the result.

**Comment by larsbrinkhoff** [comment]
Fixed by #10.

**Comment by larsbrinkhoff** [comment]
Maybe the DDT $0Y command writes the right format for DSKDMP to load?

Let's see if @cstacy  or @eak knows?

**Comment by eak** [comment]
Sorry, I never worked on ITS itself, just a few user commands. ITS 
hacking was mostly done by RMS and Moon in my day. I suppose you could 
ask one of them.

**Comment by larsbrinkhoff** [comment]
Tried: `$L .;its bin` `$$1L .;nsalv bin`, and then both

- `$Y .;@ its2` - loads, but freaks out with continuous error messages:

    MUUO IN EXEC MODE, PC= 700000,,774001  
    BUGHALT.  FIND A WIZARD OR CONSIDER TAKING A CRASH DUMP.
    THE SYSTEM HAS CRASHED AND CANNOT BE REVIVED WITHOUT EXPERT ATTENTION.
    IF YOU CAN'T FIND HELP, RELOAD THE SYSTEM.
    YOU ARE NOW IN DDT.


- `$0Y .;@ its2` - when loading, DSKDMP never prints LF.

**Comment by larsbrinkhoff** [comment]
Success.  Loading ITS last did the trick.

    $1L .;@ ddt
    $$1L .;nsalv bin
    $$L .;its bin
    $Y .;@ nits
