### ISSUE TITLE
MIDAS and STINK version of REL file format

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#410]
The REL file format as used by MIDAS and STINK is not documented.  Presumably it could be reverse engineered by looking inside MIDAS and STINK, but it's not very ovbious where to look.

**Comment by larsbrinkhoff** [comment]
I took a look at SAIL; JOBDAT REL:

It begins with

    002002,,000000

Next comes a symbol table.  Every symbol is described by five words.  Here's an example:

    457573,,601127  ;Symbol name in SQUOZE: "JOBSVM"
    000000,,000075  ;Symbol value
    314201,,176553
    004003,,000000
    000000,,000000

The first symbol seems to be the symbol table block name or file name.

The table is terminated by a symbol entry that starts with 0.  After that comes four words.  The first looks like two negative half words.  The third is the block name or file name again.

**Comment by larsbrinkhoff** [comment]
Assembling a simple file titled BARFOO which just defines `FOOBAR=1234567`.

FAIL produces this REL file:

    OCTAL         SQUOZE
    002004000000  1O9QJV
    051301670001  BARFOO
    000000000001       0
    014544243324  FOOBAR
    000001234567    4C%U
    707725407662  9D%33H
    000602000000   %K18N
    000000000000        
    000000000000        
    777176777777   $6VBU
    001001000000  0BK8ZV
    051301670001  BARFOO
    725476107776  RCI6%$

MIDAS produces this REL file:

    OCTAL         SQUOZE
    000600000000   %BXLF
    777200777777   $E%%%
    000600000000   %BXLF
    777200777777   $E%%%
    000600000000   %BXLF
    777200777777   $E%%%
    000202000001   CBI70
    000000000000        
    000000000000        
    777576777776  0NFEDD
    002004000000  1O9QJV
    051301670001  BARFOO
    000000000000        
    014544243324  FOOBAR
    000001234567    4C%U
    707725407663  9D%33I
    001001000000  0BK8ZV
    051301670001  BARFOO
    725476107776  RCI6%$

**Comment by larsbrinkhoff** [comment]
There is now a DMCG document describing the format:  
https://github.com/larsbrinkhoff/its-archives/blob/master/dmcg/SYS.03.02.pdf

**Comment by larsbrinkhoff** [comment]
The format is a sequence of blocks.  Each block has a header word, data, and a checksum word.

The header word bits:
- 4.9 EOF.  If set, ignore block.
- 4.8-4.6 LCB, loader contitional bits.
- 4.5-3.8 Block type.
- 3.7-3.1 Number of data words.
- 2-1-1.1 Address.

The checksum is a one's complement sum of the header word and the data.

Block types:
- 1 - Loader command
- 2 - Code to be loaded at address (not relocated)
- 3 - Code to be loaded at address (relocated)
- 4 - Program name.
- 5 - Library search.
- 6 - COMMON (Fortran).
- 7 - Global parameter assignment.
- 10 - Local symbols.
- 11 - Load time conditional.
- 12 - End load time conditional.
- 13 - Local symbols to be half-kiled.
- 14 - End of program, for libraries.
- 15 - Entries.
- 16 - External references.
- 17 - Load if needed.
- 20 - Global symbols.
- 21 - Fixups.
- 22 - Polish fixups.

**Comment by larsbrinkhoff** [comment]
MIDAS doesn't seem to know about block types 13-21.

**Comment by larsbrinkhoff** [comment]
STINK knows all SYS.03.02 block types, plus 22-30.  But 23-30 are not supported.

**Comment by atsampson** [comment]
I've found at least one feature that MIDAS and STINK know about that's not in that document: extend code 2 in a standard data block can also be used to rename or expunge symbols, depending on the value you pass. See the code in LOCGLO in STINK.

**Comment by larsbrinkhoff** [comment]
This is documented in [DMCG memo SYS.03.02 "STINKING-DYNAL Relocatable Format"](https://github.com/larsbrinkhoff/its-archives/blob/master/dmcg/SYS.03.02.pdf).
