### ISSUE TITLE
CHEOPS - Chess processor

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#413]
There are references in ITS to something called CHEOPS.  After some searching, I found out it's a chess processor.

> Chess-Oriented Processing System with a dedicated chess processor, developed end of the 70s at MIT by John Moussouris, Jack Holloway and Richard Greenblatt, derived from the original conception and design of a 8x8 hardware chess array instrumented by Edward Fredkin. CHEOPS was used by Baisley's Tech 2 and a brute force version of Greenblatt's Mac Hack, but unfortunately have never competed in computer chess tournaments with this approach. According to Joe Condon and Ken Thompson, already working on a chess hardware for Belle, the problem with CHEOPS was the lack of positional evaluation support.

https://chessprogramming.wikispaces.com/CHEOPS

**Comment by larsbrinkhoff** [comment]
There seems to be SUDS schematics.  Something called CHEOPS LOAD could be microcode or something.

**Comment by larsbrinkhoff** [comment]
AGB; CHEOPS GAME1  
AGB; CHEOPS LOAD
AGB; CHEOPS NLOAD
AGB; CHESS2 CHEOPS
CHESS; CHEOPS TXT
CHESS; CRAZY CHEOPS
CHPROG; CCHEOP 484  
CHPROG; CHEOPS DMP
CHPROG; CHEOPS DMP2
CHPROG; CHEOPS DRW
CHPROG; CHEOPS LOAD
CHPROG; CHEOPS LOCK
CHPROG; CHEOPS NLOAD
CHPROG; CHEOPS OLOAD
CHPROG; CHEOPS PS
RG; CHEOPS 111
RG; CHEOPS 17
RG; CHEOPS DIAG
LCHESS; LCHEOP 124

**Comment by atsampson** [comment]
We've got several sets of SUDS schematics now (10-11 x2, CADR and various devices, CHEOPS, ADVENT). Should we have an expect script to print them?

**Comment by larsbrinkhoff** [comment]
Since they are not expected to be update, I think it doesn't need to be part of the main build script.  There could be a separate one.

**Comment by larsbrinkhoff** [comment]
CCHEOP is the "CHEOPS console program".  It's not a standalone program.  Both OCM and CHESS2 .INSRTs it.

Some obvervations:

- It uses the T11MP system call to map in PDP-11 memory.
- CHEOPS DMP is control memory.  Microcode?
- It mentions the CONS, maybe copy-pasted code.  CC @ams.
- CHEOPS LOAD is also written to CHEOPS, not sure what it is.

**Comment by larsbrinkhoff** [comment]
This is the file CHEOPS DRW.

![cheops](https://user-images.githubusercontent.com/775050/43258074-d3c35bac-90d1-11e8-9309-f5181b08f0a1.png)

**Comment by atsampson** [comment]
AGB; CHUCOD 83 looks like CHEOPS microcode source.

**Comment by larsbrinkhoff** [comment]
It certainly is!  Thanks.  I made #840 to look at those files, but never got around to it.

CHPROG; CHASM5 94 seems to be the assembler.  And CHADMP 13 is for dumping out contents from CHEOPS memories.

**Comment by larsbrinkhoff** [comment]
The microcode explains some more things about the hardware:

- There is an 4K word memory on the Unibus.  It's used for communication between the PDP-10 and CHEOPS.

**Comment by larsbrinkhoff** [comment]
More files that probably make up the assembler:

RG; CHASM 34  
RG; CHASM1 10  
RG; CHASM2 42  
RG; CHASM3 74  
RG; CHASM4 104
RG; CHASMS 3  

CHPROG; CHASM TAGS says WHITE-TO-PLAY is in CHASMS.

**Comment by larsbrinkhoff** [comment]
There's also RG; CHUCOD 390, presumably newer that verison 83 we have.

**Comment by larsbrinkhoff** [comment]
CHARM DRW
![charm](https://user-images.githubusercontent.com/775050/43356018-ff56bf00-9268-11e8-8a03-f5d725f6b498.png)

**Comment by larsbrinkhoff** [comment]
CHARM1 DRW
![charm1](https://user-images.githubusercontent.com/775050/43356021-09887018-9269-11e8-9427-687e059daa06.png)

**Comment by ams** [comment]
Could it be something similar like on the CADR, that it was only used for interfacing/debugging?

**Comment by kervinck** [comment]
FYI: Wikispaces has stopped, and the chess programming wiki migrated to its own domain. The CHEOPS article is now at https://www.chessprogramming.org/CHEOPS

**Comment by larsbrinkhoff** [comment]
Thanks @kervinck.  I have been in touch with Gerd Isenberg from time to time.
