### ISSUE TITLE
QMAIL - user interface to COMSAT

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#42]
KSC; QMAIL 614  
.INFO.; QMAIL INFO

>  Qmail sends messages to people over the network or locally; the "Q" is for "queue" as it always operates by queueing mail to a special independent program which does the actual sending.

**Comment by eswenson1** [comment]
Isn't QMAIL in the COMSAT commit?  As far as I can see, KSC; QMAIL 614 is in that commit, and so is .INFO.;QMAIL INFO.

**Comment by larsbrinkhoff** [comment]
Sorry!  Missed that.
