### ISSUE TITLE
XGP - Xerox graphics printer

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#427]
SYSEN2; XGPDEV - device handler  
SYSEN2; XGPSPL - unspooler  
SYSDOC; XGP WRITUP  
INFO; XGP 24
.INFO.; XGP WRITES

**Comment by larsbrinkhoff** [comment]
Will accept text files, plot files (vector graphics), or scan files (bitmaps).

**Comment by atsampson** [comment]
(Relevant for #863 too.)

I've experimented with this a bit on the [ats/xgpglp](https://github.com/PDP-10/its/commits/ats/xgpglp) branch. XGP/GLP (XQUEUE) and XGPDEV/GLPDEV work with a bit of tweaking, and XGPSPL at least builds, although none of this is directly useful at the moment.

I was hoping GLP would work with VERSA, but while they use the same spool directory, GLP doesn't produce filenames that VERSA likes...

**Comment by larsbrinkhoff** [comment]
Maybe se should ask DCP som questions.
- What's the status of VERSA?  Should se expert all Venables features to Erik?
- VERSA Verdis GLP filenames.

...anything Else?

**Comment by atsampson** [comment]
After comparing VERSA 211 and INFO; XGP, there are a number of XGP commands that VERSA either doesn't implement fully (e.g. line spacing, underlining) or doesn't implement at all (margins, vector drawing). I've tried adding support for margins and correct line feed behaviour, which makes TJ6 output look much better.

Do we have any high-quality (ideally 600 DPI) scans of real XGP output? @larsbrinkhoff, you mentioned you had scans of an XGP listing of Dazzle Dart recently... but it would also be nice to have something that uses underlining and multiple font sizes, to compare spacing against.

**Comment by 36bit** [comment]
> Do we have any high-quality (ideally 600 DPI) scans of real XGP output?

The book about the Muddle programming language says:

> This document was prepared using the PUB system (originally from the Stanford Artificial Intelligence Laboratory) and printed on the Xerox Graphics Printer of the M.I.T. Artificial Intelligence Laboratory.

**Comment by eswenson1** [comment]
I have real XGP output -- the zork sources printed out from circa 1980. One could scan them in at any resolution.  But what good are scans of XGP output?

**Comment by larsbrinkhoff** [comment]
Right, the Dazzle Dart scan is on the lars/dazzle branch.  Maybe it's output from "@"?

Probably many AI memos were printed on the XGP.

I beleve the XGP had a resolution of about 200 DPI.

**Comment by larsbrinkhoff** [comment]
Split off XGP to #1077.

**Comment by larsbrinkhoff** [comment]
Some pictures of the CMU XGP I got from Clem Cole.

![xpg1](https://user-images.githubusercontent.com/775050/49465213-4b7bef00-f7fd-11e8-9ab0-c02ecb558913.png)

**Comment by larsbrinkhoff** [comment]
![xpg2](https://user-images.githubusercontent.com/775050/49465226-5d5d9200-f7fd-11e8-9f90-2e0d71330672.png)

**Comment by larsbrinkhoff** [comment]
![xpg3](https://user-images.githubusercontent.com/775050/49465238-65b5cd00-f7fd-11e8-9003-db45ff62ba0b.png)

**Comment by larsbrinkhoff** [comment]
- XGPDEV, XGPSPL, and INFO; XGP 24 added in #926.
- XGP WRITUP, and XGP WRITES added in #1436.

All done.

**Comment by larsbrinkhoff** [comment]
In 2001, Mark Crispin wrote to ITS-LOVERS:

```
> 4. There were features of ITS designed to support high quality output.  The
> XGP (Xerox Graphics Printer) was in place by the time I arrived, and I
> believe initial support for ITS was written by Marc Crispin.
                                                 ^^^^ Mark

The program to do font compilation, rendering, and printing on the XGP was
already in place when I arrived.  However, the only way that you chould print
something was link to the mod 35 TTY that had the XGP and give a command to
it.

I wrote the XGP spooler; instead of waiting for the XGP to be free, you just
queued the file to the spooler and waiting for it to print.  To the dismay of
many in the ITS community, it prioritized requests, first by file size and
then by giving AI members (as recorded in INQUIR) a priority boost over others
(LCS, tourists,...).  Rumors to the contrary notwithstanding, I was following
orders from AI management; it was not my decision.  It was about that time
that RMS decided to create his elitist "$" INQUIR classification to indicate
his independence from AI (but "$" also got a priority boost).

It had a few options, including the THESIS option to block printing of the
request until someone gave a command on the XGP mod 35 to indicate that thesis
quality paper was installed in the XGP (at which point requests which didn't
have the THESIS option were blocked until another command was given to say
that ordinary paper was back.

I also wrote a job device called XGP so you could see the status of the queue
and XGP hardware with XGP CTRL/F.

**Comment by larsbrinkhoff** [comment]
Picture from SAIL.  XGP to the far right.   We can see the customary trash bin.

![sail-xgp](https://user-images.githubusercontent.com/775050/54308792-07a03f00-45cf-11e9-817c-22cd5e8e2c71.png)

**Comment by larsbrinkhoff** [comment]
The SAIL XGP is hiding in the background.

![xgp](https://user-images.githubusercontent.com/775050/56711999-344a8900-672d-11e9-920c-87ed9210c825.jpg)

**Comment by larsbrinkhoff** [comment]
The SSV4 software for the Imlac PDS-4 supports an "XGP graphics mode".

```
SUBTTL XGP SIMULATOR

**Comment by larsbrinkhoff** [comment]
From page 62 here: https://www.isi.edu/publications/trpublic/pdfs/sr-75-3.pdf

![xgp](https://user-images.githubusercontent.com/775050/109118499-ae8e2f00-7743-11eb-8936-c05c90665a6a.png)

**Comment by larsbrinkhoff** [comment]
According to https://www.historyofinformation.com/detail.php?id=970:
> by 1972 they were in use at Carnegie-Mellon, Stanford, MIT, Caltech, and the University of Toronto

**Comment by larsbrinkhoff** [comment]
From https://www.tug.org/interviews/interview-files/morris/morris-render.pdf
![xgp3](https://user-images.githubusercontent.com/775050/131787537-0460971f-d42c-425d-9c92-5e4a9ba10b72.png)

**Comment by larsbrinkhoff** [comment]
The LDX was a fax.  The printer side was adapted to make the XGP.
Source: http://digitalprinting.blogs.xerox.com/wp-content/uploads/sites/3/2012/08/Xerox-LDX-Image.jpg
![Xerox-LDX-Image](https://github.com/PDP-10/its/assets/775050/ba07548c-930a-4800-a6db-67bfb420d634)

**Comment by larsbrinkhoff** [comment]
An XGP emulator is in development and various bits and pieces to use it is noted here: #2271

**Comment by larsbrinkhoff** [comment]
Tweets from Geoff Goodfellow:

https://twitter.com/keyboardofGeoff/status/1753083975046922637
> you "forgot" the (D)ARPA office at 1600 Wilson Blvd in Arlington, VA & Lincoln Labs in Lexington, MA... IIRC the Lincoln Labs LDXR was connected to the TX-2 and must have been situated before they made an XGP placard cuz it said LDXR

https://twitter.com/keyboardofGeoff/status/1753213478427677174
> sorry no, don't have any further information or references you could dig into.. other than yours truly's recollection here... btw, not having an XGP at SRI where SRI-ARC & SRI-AI's computer rooms K2079 abutted one another was A Sore Issue (luckily yours truly had access at SU-AI)

https://twitter.com/keyboardofGeoff/status/1753216297364828306
> IRC, at SU-AI/SAIL Les Earnest (yours truly believes) "published" a font catalog called Find A Font (as well as a restaurant guide called YUMYUM) and in Those Days pretty much everything XGP'd was done with/in the "document compiler" PUB markup language that Larry Tesler wrote

**Comment by larsbrinkhoff** [comment]
A color photo of MIT's XGP.  Source: https://www.computerhistory.org/collections/catalog/102803907
![mit-xgp](https://github.com/PDP-10/its/assets/775050/d43f596e-942c-4973-901f-ea1d02d13794)

**Comment by larsbrinkhoff** [comment]
Hello @Rick-Shiffman,

Please add your recollections of the ISI XGP to this issue.  Thanks!

**Comment by Rick-Shiffman** [comment]
Hi Lars, I remember looking at the insides of ISI's XGP. It had a one
line, page wide, bright green CRT that write one line of the image as
the pre -charged paper rolled by the CRT.

also if the XGP's PDP-11 crashed while the XGP was moving paper, then the XGP would dump its large roll of paper on the computer room floor!

**Comment by larsbrinkhoff** [comment]
Thanks Rick!

**Comment by larsbrinkhoff** [comment]
A better photo from ISI.  Source: https://twitter.com/Rrs86595671/status/1754564516669714755
<img width="281" alt="rrs-xgp" src="https://github.com/PDP-10/its/assets/775050/62aa5fe0-5869-4ced-9d84-ebfb82615f7f">
