### ISSUE TITLE
I/O PDP-11

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#439]
Collecting notes on the I/O PDP-11.

It was a PDP-11 dedicated to do I/O for the PDP-10.  On AI, it was connected through a "Rubin 10-11" interface.  On MC (KL), two were connected through DTE20 and DL10.

**Comment by larsbrinkhoff** [comment]
SYSTEM; CONFIG > says:

    ; The following AI-KA stuff is broken since the 10-11 interface doesn't work,
    ; but is retained in case it gets fixed.
    DEFOPT TEN11P==0        ; Rubin 10-11 interface
    IFN TEN11P,[
      DEFOPT XGP==1         ; Has XGP
      DEFOPT CHAOSP==1      ; Has CHAOS net
      DEFOPT MYCHAD==2026   ; CHAOS net address
      DEFOPT NINDX==50.     ; Number of Chaosnet indices
      DEFOPT T11CHP==1      ; CHAOS net goes through TEN-11 interface
      DEFOPT CH11NM==7      ; # of 10-11 PDP11 handling CHAOS net.
      DEFOPT TT11NM==0      ; # of 10-11 PDP11 that handles TV TTYs.
      DEFOPT N11TYS==16.    ; # PDP11 TV TTYS
      DEFOPT MXVBN==40      ; Max video bfr # for assignment purposes.
    ] ;TEN11P               ; These actually correspond to video switch inputs.

**Comment by larsbrinkhoff** [comment]
SYSTEM; IOELEV 432 is the source for the code running in the PDP-11.

**Comment by aap** [comment]
Oh cool. This looks promising. I wonder how all of tech square's 11s were mapped into the 10's address space. The ITS pager only seems to be able to address 512kw physical memory....but Greenblatt said it looked like a memory to the 10...hm...

**Comment by larsbrinkhoff** [comment]
SYSENG; 11BOOT 23

    TITLE 11BOOT - BOOT I/O 11 ON KL10
    ;LOADS DSK:KLRUG BIN AND DSK:IOELEV BIN, GIVES SYMBOLS TO RUG, AND
    ;MAKES DSK:@ BOOT11 WHICH IS TO BE PUT ON THE MAGDMP TAPE.

**Comment by larsbrinkhoff** [comment]
The Knight TV PDP-11 was loaded from ITS by running the STUFF program, according to AI WP 227.

**Comment by larsbrinkhoff** [comment]
@aap The pager used with AI should have supported 1024 Kwords, according to this:
> The paging box built for the KA10 had the PDP-6's memory space as one of its 4 'mobys' (the other three being 2 for AI's memory, and one for the Rubin 10-11 interface).

SYSTEM; CONFIG > says for AIKA:
> DEFOPT TSYSM==768. ;TOTAL PDP10 1K MEM BLOCKS
> DEFSYM PMRCM=1777 ;CORE ADR FIELD IN PAGE MAP (AI-KA HAS 10 BITS)

The KA ML and DM pagers supported 512K.  KL MC supported 2048K.

**Comment by larsbrinkhoff** [comment]
There were three flavours of IO-11:

- AI - Rubin 10-11, Chaosnet, Ethernet.
- MC - DTE20, console, DH11.
- MC-DL - DL10, terminals, DH11, Chaosnet.

**Comment by aap** [comment]
Notably the Knight TV only used the 10-11 interface. The other devices are only used by IOELEV it seems, which has nothing to do with the Knight TV as far as I can tell.

**Comment by larsbrinkhoff** [comment]
Right, the TV system was MIT-AI only.

**Comment by larsbrinkhoff** [comment]
I edited the description at the top.  I wrote it was a 11/40, but I see no source for this.  Rather, IOELEV says 11/10 and 11/20 were used.

**Comment by larsbrinkhoff** [comment]
- AI IO-11 doesn't have any DDT.  Use CARPET, says the code.
- MC DTE IO-11 has "DDT".  11DDT or RUG?  The source mentions RUG.
- MC DL10 IO-11 has "DDT".

Instuctions say to use 11STNK to link IOELEV with 11DDT, but which IO-11?

There's 11BOOT which merges IOELEV with KLRUG for booting, but which IO-11?

**Comment by larsbrinkhoff** [comment]
AI and MX IOELEV assembled in #974.  MX-DL would need IOELEV 431 or a fix for 432.
