### ISSUE TITLE
Running ITS in the KA10 SIMH

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#445]
I suggest we move the discussion from #376 and #440 to here.

https://github.com/rcornwell/sims

**Comment by larsbrinkhoff** [comment]
CC @rcornwell.

**Comment by larsbrinkhoff** [comment]
The plan of attack would be something like:

1. Use MAGDMP and MAGFRM to get a file system on magtape.  Try to run a few standalone programs.
2. Try to build the old SALV to make a file structure on a disk.  Expect to debug the disk emulation and/or controller code.
3. Build KA version of DSKDMP and exec DDT to be able to load and run a monitor.
4. Build a KA monitor.
5. Profit!

**Comment by rcornwell** [comment]
Sounds like a good plan of attack. If you find bugs in my simulator post an issue on my sim. If I have time tonight I will try and fix the bug I introduced last night adding TLB and starting to add ITS pager support. Otherwise it will probably have to wait until the weekend. Biggest problem I can see is getting all the patches to support the 1 proceed and other ITS specific changes to the KA. The paging is not much different then than the KI paging.

**Comment by larsbrinkhoff** [comment]
This is a good read:  
https://github.com/larsbrinkhoff/its-archives/blob/master/ailab/AI_WP_227.pdf

Thank you @cstacy.

**Comment by larsbrinkhoff** [comment]
I ran MAGFRM and created a tape with a MAGDMP on it.  ka10 attempts to boot from it, but the hardware readin deposits the loader in memory locations 0-17.  This doesn't work, because the KA10 fetches instructions from the ACs.

**Comment by larsbrinkhoff** [comment]
I tried to fix this in two ways:
- Deposit into fast memory.
- Make KA10 fetch from main memory.

The result was the same: the loader starts running, but loops endlessly waiting for CONSO 344,1 to signal that the TM10 is ready to go.

**Comment by larsbrinkhoff** [comment]
@rcornwell I believe there's a bug in the implementation of CONSO.

    dev_tab[d](CONI|(d<<2), &AR);

The CONSI should probably be CONSO, right?

**Comment by rcornwell** [comment]
I don't believe there is any bug in CONSO. The TMA controller passes Dec diags, except for some parity issues which can't be simulated on the sim. I will re-test it this weekend. 

   dev_tab[d](CONI|(d<<2), &AR); 

  this is correct, CONSZ and CONSO are both CONI as far as the hardware is concerned. Both do a mask of the CONI word, CONSZ skips if all bits are zero, CONSO skips if any bits are one.

  The PDP10 hardware only implements DATAI, DATAO, CONI, CONO. 

   Please enable MT debugging I suggest (CONI;CONO;DATAIO;CMD;DETAIL) and see what that shows. CONSO 344,1 is checking for a data request. Perhaps the boot chunk is not in it's own record. If this is the case, I will have to make changes to the sim to support it.

**Comment by larsbrinkhoff** [comment]
Oh, you're right.  I'm a bit rusty on the I/O instructions.

**Comment by larsbrinkhoff** [comment]
How to prepare programs for running a KA ITS:
- Make DSKDMP: Assemble SYSTEM; DSKDMP.  Say "ask", and then "no" to everything else, except number of dirs which should be 250.  Put the binary in .; @ DSKDMP.
- Make SALV: Assemble SYSTEM; SALV.  Not time-sharing version.  ML machine.
- Make MAGDMP paper tape: Assemble MAGDMP and say yes to the paper tape question.  Get the file onto Unix and convert it to a paper tape binary; use tools/dasm/its2rim.
- Make MAGDMP magtape: First assemble MAGDMP for use with ML.  Put the binary in .; MAGDMP BIN.ML. Then run MAGFRM.  Use the "W" command to put .; @ DSKDMP and .; @ SALV on there.

**Comment by larsbrinkhoff** [comment]
- Boot from MAGDMP paper tape: Start SIMH and enter "load -r magdmp.rim", then "go".
- You should now be able to access the magtape formateted with MAGDMP.  "F <ALTMODE>" should display a file listing.  "filename <CR>" should load and start a standalone program.

**Comment by larsbrinkhoff** [comment]
@rcornwell I will try to add information here about how to build KA10 standalone programs, paper tapes, magtape images, etc.

**Comment by larsbrinkhoff** [comment]
- Make exec DDT: Assemble SYSTEM; DDT.  Answer "0" to cpusw to build for a KA10.  One disk and RH-10 I suppose?

**Comment by larsbrinkhoff** [comment]
@jeffpar  
The tape images mentioned in this issue may also be useful to you for testing your JavaScript KA10 simulator.

**Comment by larsbrinkhoff** [comment]
Fixes needed so far:
- NMTAPE doesn't space to EOT correctly, makes MAGFRM fail.
- Wrote a Unix magfrm to make MAGDMP tapes.
- SALV (old KA/KL salvager) doesn't understand the DUMP tape format.
- Exec DDT needs to be build without disk support for $U to work.

**Comment by larsbrinkhoff** [comment]
Update.  KA ITS is now running!  Albeit limpingly in some areas.

**Comment by larsbrinkhoff** [comment]
Installation goes like this:

- Mount a MAGDMP magtape with DDT and SALV.
- Boot MAGDMP off paper tape.
- Load DDT and SALV.
- MARK two packs on unit 0 and 1, make them number 2 and 3.
- Mount the minsys tape on tape unit 5 and TRAN it.

Start ITS using the DSKDMP paper tape.

**Comment by eswenson1** [comment]
Any networking support?

**Comment by larsbrinkhoff** [comment]
No.  For now, I think there's just the console, paper tape, magtape, and RP03 disk.

Wanted:

- Terminal scanner.  @rcornwell wants to do the DC76.
- Networking.  IMP or Chaosnet?
- DeCoriolis real-time clock.
- 340 display.
- Knight TV system.

**Comment by larsbrinkhoff** [comment]
Optional:

- DC10, Systems Concepts disk controller
- TK10, terminal scanner
- Morton box, terminal scanner
- Knight kludge, terminal scanner
- Datapoint kludge, terminal scanner
- DECtape
- NCP through IMP

Very very optional (I don't even know what all of these are):

- Morse code output device
- XGP printer
- Sylvania tablet
- Robot console
- Holloway clock
- OMX output multiplexor
- IMX input multiplexor
- VIDI
- Chess tournament clock
- D/A converter

**Comment by larsbrinkhoff** [comment]
ITS does boot and work reasonably well.  Some things are not working yet, but there should be specific issues for those problems.
