### ISSUE TITLE
MACDMP

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#449]
You are in a maze of twisty little programs, all alike:

SYSENG; MACDMP 10D256  
SYSENG; MACDMP 10U256  
SYSENG; MACDMP 6U256  
SYSENG; MACDMP 6U32  
SYSENG; MACDMP 6U64  
SYSENG; MACDMP MOBY  
SYSENG; MACDMP MOBY1  
SYSENG; MACDMP RIM10  

SYSEN1; 10DMP 13 - full moby  
SYSEN1; 10D16K 1 - 16K memory  

SYSEN2; TENDMP 2 - both microtape and TD10  
SYSENG; TENDMP 12 - same as version 2 except microtape is default  
SYSENG; TENDMP MAC - original DEC version  

SYSEN2; MACTAP F71 - library routines

Standalone tool for loading/dumping files on DECtape.

**Comment by aap** [comment]
Have you come across any code for formatting DECtapes? Formatting is one thing in my emulation that I haven't implemented yet and I have some trouble imagining how a program would even do it, having some code would certainly help me.

**Comment by larsbrinkhoff** [comment]
I have now made an extensive search for "dectape", and nothing obvious turned up.  Maybe it's in a MACDMP subroutine.

**Comment by larsbrinkhoff** [comment]
By the way, do you mean some low-level formatting, or initializing a tape with a MACDMP format?

**Comment by larsbrinkhoff** [comment]
10D16K is just 10DMP with one line changed.

TENDMP is 10DMP with many edits and additions.

**Comment by aap** [comment]
I mean the low level formatting; writing the timing and marking tracks. I talked to Greenblatt and he said they didn't have anything of that sort...maybe programs supplied by DEC, but I'm not too familiar with DEC software. One other thing that I find strange is that both @rcornwell and Greenblatt said DECtape formats for different architectures were rather compatible. I can't imagine how that would work as the 36 bit format has an additional mark code (25, Block Space) that the 18 bit and 12 bit formats (which are otherwise identical) don't. And this code is quite important for reading too...not only used to extend the block number to 36 bits.

**Comment by larsbrinkhoff** [comment]
Over all, I don't see a lot of references to DECtape at all in ITS material.

**Comment by larsbrinkhoff** [comment]
@aap @rcornwell 
I think it would be interesting to test MACDMP (and/or TENDMP, 10DMP) soon.  I suppose there's only PDP-10 DECtape device support for now?  And currently no way to create a bootable DECtape, so start from paper tape.

**Comment by aap** [comment]
My emulator only has PDP-6 DECtape support (551), but it's not tested to well. So I agree it would probably be a good idea to test this.

**Comment by larsbrinkhoff** [comment]
Tried to assemble MACDMP 6U32, but there were errors.  I think we first need an old version of MIDAS, but that in itself needs an old MIDAS to build.

**Comment by larsbrinkhoff** [comment]
I built it with MIDAS 108, but it still complained about missing brackets.  I added them, and it was fine.

There's a DUMP tape image and a paper tape image in http://lars.nocrew.org/its/

**Comment by larsbrinkhoff** [comment]
Looks like the lineage is MACDMP -> 10DMP -> TENDMP.

**Comment by larsbrinkhoff** [comment]
Copy from #610:

We have these versions of MACDMP

- MACDMP 6U32
- MACDMP 6U64
- MACDMP 6U256
- MACDMP 10U256
- MACDMP 10D256
- MACDMP MOBY
- MACDMP MOBY1
- MACDMP RIM10

The 6/10 U 32/64/256 versions only differ in the definitions of RLC and PDP10.  10D256 sets TD10 and fixes unterminated `[` literals.  They all have the RIM2 loader for PDP-6.

The MOBY/MOBY1/RIM10 versions remove the RIM2 and shadow loader.  The TD10 switch is gone.  340 display code is added to the MOBY versions.

MOBY has some garbage at the end which MOBY1 lacks.  RIM10 removes the use of RLC and has some other edits.

**Comment by larsbrinkhoff** [comment]
Also check if ITS will read a DECtape in MACDMP format, so e.g. `:listf ut1:` works.

**Comment by larsbrinkhoff** [comment]
@aap we talked about a mystery 32K configuration.  HW memo # 3 talks about three memories: a moby memory, a DEC 16K, and an Ampex 16K.

**Comment by larsbrinkhoff** [comment]
BIG (#901) can be assembled for 16 or 32 K.

**Comment by larsbrinkhoff** [comment]
Tried to assemble MACDMP 6U32 with .MLLIT=-1, but still there were errors.

**Comment by larsbrinkhoff** [comment]
Should try to assemble with MIDAS 77 or 73 which are now part of the repository.

**Comment by larsbrinkhoff** [comment]
MIDAS 77 works fine!

**Comment by larsbrinkhoff** [comment]
| File | Timestamp
| --- | ---
| MACDMP RIM10 | ≤1971
| MACDMP MOBY | ≤1971
| MACDMP MOBY1 | 1971-07-31
| MACDMP 6U64 | 1971-10-14
| MACDMP 6U64 | 1971-10-14
| MACDMP 6U64 | 1971-10-14
| MACDMP 6U96 | 1971-10-14
| MACDMP 6U144 | 1971-10-14
| MACDMP 6U32 | 1973-01-02
| MACDMP 6U256 | 1973-01-17
| MACDMP 10U256 | 1973-01-17
| MACDMP 10D256 | 1973-05-08

**Comment by larsbrinkhoff** [comment]
See http://pdp-6.net/loader.html#ut for @aap's description of the DECtape bootstrap.

**Comment by larsbrinkhoff** [comment]
MACDMP MOBY1 and 6U32 added in #1930.

**Comment by larsbrinkhoff** [comment]
MACDMP commands, from [AI memo 118](http://bitsavers.org/pdf/mit/ai/aim/AIM-118.pdf)

```
n$	Sets the current tape to n if n is in the interval 0 to 7.
	If n is greater than 7 the current starting addres is set to
	n.

G$	Transfer control to the current starting address.

fn1 fn2<cr>	Clear core, load progrm fn1 fn1, and go to its
	starting address.

L$fn1 fn2<cr>	Clear core, load, set starting address, but stay in
	MACDMP.

M$fn1 fn2<cr>	Load (Merge) and set starting address staying in
	MACDMP.

I$fn1 fn2<cr>	Verify core against program fn1 fn2.

T$fn1 fn2<cr>	This command assumes that DDT has been loaded and
	that fn1 fn2 is a file with symbols.  It clears core
        below DDT, loads fn1 fn2, adds the symbols for fn1 fn1
        to DDT's symbol table and goes to DDT.

N$fn1 fn2<cr>	The same as T$ but does not clear core below DDT.

D$fn1 fn2<cr>	Dumps the contents of core on the current tape as a
	file called fn1 fn2 with the current starting address
        and write out the updated file directory of the current
        tape.  A previous file of that name will be deleted.

K$fn1 fn2<cr>	Eliminate the file fn1 fn2 from the file directory
	of the current tape.  Does not write out its file directory.

D$n$	Dump out the durrent file directory on tape n.

I$n$    Verify the current file directory against that for tape n.

**Comment by larsbrinkhoff** [comment]
From http://www.bitsavers.org/pdf/dec/pdp10/1970_PDP-10_Ref/1970PDP10Ref_Part6.pdf

![tendmp](https://user-images.githubusercontent.com/775050/111264226-6cac2680-8627-11eb-9a9a-49ef82e42cc9.png)
