### ISSUE TITLE
Boot KA off disk?

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#455]
Supposedly, a KA ITS was always cold booted from a DSKDMP paper tape.  Using a MAGDMP tape with DSKDMP on it would also be possilbe.

It should be possible to use hardware readin with a disk.  It looks like there is DSKDMP boot code for the KA disk contollers.  AI had a Systems Concepts DC10; ML and DM had a RP10.  There is also code for RH10, but it was probably never used with a KA, only the KL MC.

**Comment by larsbrinkhoff** [comment]
I think there's very little need for this.

**Comment by rcornwell** [comment]
I disagree, this would be very nice to have. And requires zero mods to simulator. All you need to is write a utility to copy DSKDMP to sectors 4-7 of any RP10 drive that is online. Boot will read first word as Word Count/Address and load rest of the sector into this location and then transfer to the address in the last word.

**Comment by larsbrinkhoff** [comment]
Ok, I'll reopen this.

I suggest this should be a nice exercise for someone to get into ITS programming.

**Comment by rcornwell** [comment]
Possibly, requires writing to raw device, and making sure those sectors are not used by ITS file system.

**Comment by larsbrinkhoff** [comment]
Yes, told you it was a nice exercise! :-)

**Comment by rcornwell** [comment]
Probably need to do it yourself. I do not know the structure of the ITS file system, nor how to do raw writes. At the moment I also don't have time to do this. All this requires is that the dskdmp be put in as a .rel file into sectors 4-7 of any of the disks in a pack. KA10 will use the first word as an address and word count. It will then execute the last instruction read.

**Comment by larsbrinkhoff** [comment]
I don't really want this.  So I'll close.  If or when someone is ready to implement disk booting, feel free to reopen.
