### ISSUE TITLE
How to scan print sets?

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#457]
If someone were to be in possession of, say, the master print set for the AI  KA10, what would be the best way to digitize it?

@david-moon @kossow

**Comment by kossow** [comment]
I have a set scanned. The scan is quite large (around 12gb)

**Comment by kossow** [comment]
I misunderstood what you were asking.

You are going to have to find someplace with a blueprint scanner.
Hopefully, the drawings haven't faded

**Comment by larsbrinkhoff** [comment]
Thanks, I think that answers the question.
