### ISSUE TITLE
HTTP server

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#460]
Get permission from @bictorv or @Pul-Ess to add their HTTP server(s) to this repo.

**Comment by Pul-Ess** [comment]
On Thu, 26 Jan 2017, Lars Brinkhoff wrote:

>Get permission from @bictorv or @Pul-Ess would to add their HTTP server to this repo.

Sure, no problem.
If you could put a link to its.svensson.org somewhere that would be even greater.
Yes, SV is on the net again -- supdup only, no telnet.

 	/Paul

**Comment by larsbrinkhoff** [comment]
I made a link here for starters:  
https://github.com/PDP-10/its/issues/181

*Someone* should submit a pull request to update [machines.md](https://github.com/PDP-10/its/blob/master/doc/machines.md).
