### ISSUE TITLE
In the news

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#470]
https://news.ycombinator.com/item?id=13514918

https://www.theregister.co.uk/2017/01/30/pdp10_enthusiasts_resurrect_ancient_mit_operating_system/

**Comment by maantje** [comment]
here as well https://tweakers.net/geek/120653/github-project-herbouwt-mit-besturingssysteem-uit-jaren-zestig.html

**Comment by larsbrinkhoff** [comment]
More from Europe:

http://www.silicon.es/proyecto-github-recupera-antiguo-sistema-operativo-its-del-mit-2328137
