### ISSUE TITLE
Chaosnet interfaces

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#476]
- KA AI Chaosnet went through the 10-11 interface.
- KA ML Chaosnet went through the PDP-10 I/O bus, aka CH10.
- KA DM: no record.
- KL Chaosnet went through DL10.
- KS Chaosnet went through Unibus, aka CH11.  This is what KLH10 does.

**Comment by larsbrinkhoff** [comment]
@jaoswald and @rmaldersoniii chatted about this:

https://jaoswald.wordpress.com/2010/02/10/chaosnet-implementations-for-pdp-10/

**Comment by jaoswald** [comment]
https://jaoswald.blogspot.com/2010/02/chaosnet-implementations-for-pdp-10.html
is a more live copy of that discussion. I'm working on recovering my
credentials for the Wordpress hosted version.

**Comment by larsbrinkhoff** [comment]
@aap, here are some notes about Chaosnet interfaces.
