### ISSUE TITLE
Reference dates are off on some files

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#486]
Some files have reference dates set to e.g. year 1917.  Reading a file sets a correct year, so I think they are files written by DUMP.  There could be a bug in DUMP, or in itstar.

**Comment by larsbrinkhoff** [comment]
I made a new tape with itstar, and extracted it with DUMP.  The reference date was fine.

**Comment by eswenson1** [comment]
Do you mean files that we've loaded onto the DB system from the build?

**Comment by larsbrinkhoff** [comment]
Yes, use :LF to look at INFO; for example.

**Comment by larsbrinkhoff** [comment]
I don't see this any more using :LF to list INFO.
