### ISSUE TITLE
BINPRT - Print assembly information

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#50]
SYSEN1; BINPRT 117  
INFO; BINPRT 5

**Comment by eswenson1** [comment]
Oh good. I've been LOADing this onto my ITS builds and using it all the time. Kept telling myself that I should do this one next!  Thanks for entering a ticket.

**Comment by larsbrinkhoff** [comment]
@eswenson1 Sure, you can have this one.
