### ISSUE TITLE
UNMIDAS - disassembler

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#518]
AR3: GREN; UNMIDA 55

No installed binary.

**Comment by eswenson1** [comment]
Does this work?

**Comment by larsbrinkhoff** [comment]
I'm not sure.  It could be a work in progress.  I see code for writing out the symbol table, but nothing for disassembling instructions.

I could ask GREN.

**Comment by larsbrinkhoff** [comment]
Right, it mostly just writes the symbol table in MIDAS source syntax.
