### ISSUE TITLE
Need the full multimedia experience!

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#545]
I asked for photos in #425.  Now I'll get on my bare knees and plead for more media.  Can someone *please please please* make 3D scans of PDP-10 models?  And record sounds?

Also noted in aap/pdp6#4.

**Comment by larsbrinkhoff** [comment]
Video of running KA10.

http://youtu.be/Hm3UY1o7Bdo

**Comment by larsbrinkhoff** [comment]
3D model of PDP-11/20:  
http://youtu.be/LQaXkHY20HA

**Comment by ams** [comment]
I am happy that there are crazy hackers like you around, makes my craziness look normal! :-)

**Comment by larsbrinkhoff** [comment]
IBM 370:  
http://youtu.be/Lr_m8IhKzbo

**Comment by rcornwell** [comment]
Not bad, but he got some things wrong. Tape drives don't flash unless there is a tape in them! Also a 370 would never be running z/OS! Also keyboards don't flash! Also there never was that many people in any machine room I was ever in. At the end the Emergency pull does not flash :-)

**Comment by larsbrinkhoff** [comment]
@atsampson, join the cause for a KS10 scale model here!

**Comment by larsbrinkhoff** [comment]
@davidnunez I'd totally buy 3D printed PDP-10 models!

**Comment by larsbrinkhoff** [comment]
3D printing in progress...
![3d-pdp10-1](https://user-images.githubusercontent.com/775050/51964405-c57bcd80-2466-11e9-9c4c-333e655103ee.jpg)

**Comment by larsbrinkhoff** [comment]
Some parts are a challenge to get right.  Real versus model.
![3d-pdp10-2](https://user-images.githubusercontent.com/775050/51964507-1ab7df00-2467-11e9-8264-b9d2a5adb3b0.jpg)

![under](https://user-images.githubusercontent.com/775050/51964488-ffe56a80-2466-11e9-95c7-7b047c493137.png)

**Comment by larsbrinkhoff** [comment]
Sound of KA10 starting!

https://www.youtube.com/watch?v=lC7cl5qqbeA
