### ISSUE TITLE
Routing tables

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#549]
:PEEK has this to say about routing tables:

    Internet routing table
    Network                      Gateway                    Interface   Idle
    128.52.0.0                   10.3.0.6    ML.MIT.EDU           IMP
    18.0.0.0      MIT            10.0.0.77   10.0.0.77            IMP   5

    Chaosnet Routing Table
    Subnet  Cost    Gateway
      6             (direct)

I'm guessing these are hard-wired into the monitor.  I wonder if there's a way to change these tables, other than editing the source files?

**Comment by larsbrinkhoff** [comment]
Looks like 128.52.0.0/16 and 18.0.0.0/16 still belong to MIT, so the routing information is not entirely obsolete.  However, I believe the gateways will be hard to reach at those IP numbers!

**Comment by larsbrinkhoff** [comment]
We grabbed MIT's Chaos subnet 6 for some ITS machines.

@b4's SJ is at 7100, which is node 0 in subnet 16.  I don't know how Chaos routing is supposed to work, but :UP SJ works from my 3150 node in subnet 6.

**Comment by b4** [comment]
ATM it's P2P - is it routable at all using ITS?

**Comment by larsbrinkhoff** [comment]
IP routing is hardcoded in SYSTEM; INET 139.  See GWDEF and the IPGW tables.

ITS seems to accept some kind of Chaosnet RUT packet with routing information.  There's also some support for routing in @bictorv's CH11 device emulator.
