### ISSUE TITLE
Allow using more than one disk

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#588]
According to Rich Alderson, you just have to increase NQS in SYSTEM; CONFIG > to use more disk drive units.  @Pul-Ess is running SV with NQS==3.

Add to configuration, build, documentation, etc.

**Comment by rmaldersoniii** [comment]
Building an 8-disk ITS runs into a snag under KLH10: Specifying 8 disk image files in the DSKDMP.INI file causes the message at the end of the following to appear:

**
KLH10# ; Define basic KS10 device config - two RH11s each on its own Unibus
KLH10#
KLH10# devdef rh0  ub1   rh11   addr=776700 br=6 vec=254
KLH10# devdef rh1  ub3   rh11   addr=772440 br=6 vec=224
KLH10#
KLH10# ; Provide one disk, one tape in config ITS expects
KLH10#
KLH10# devdef dsk0 rh0.0 rp     type=rp06 format=dlw8 path=../../out/its.0.rp06 iodly=0
KLH10# devdef dsk1 rh0.1 rp     type=rp06 format=dlw8 path=../../out/its.1.rp06 iodly=0
KLH10# devdef dsk2 rh0.2 rp     type=rp06 format=dlw8 path=../../out/its.2.rp06 iodly=0
KLH10# devdef dsk3 rh0.3 rp     type=rp06 format=dlw8 path=../../out/its.3.rp06 iodly=0
KLH10# devdef dsk4 rh0.4 rp     type=rp06 format=dlw8 path=../../out/its.4.rp06 iodly=0
KLH10# devdef dsk5 rh0.5 rp     type=rp06 format=dlw8 path=../../out/its.5.rp06 iodly=0
KLH10# devdef dsk6 rh0.6 rp     type=rp06 format=dlw8 path=../../out/its.6.rp06 iodly=0
KLH10# devdef dsk7 rh0.7 rp     type=rp06 format=dlw8 path=../../out/its.7.rp06 iodly=0
KLH10#
KLH10# devdef mta0 rh1.0 tm02   fmtr=tm03 type=tu45
KLH10#
KLH10# ; ITS wants a 60Hz clock, allow it.  Need this until defaults OK.
KLH10# set clk_ithzfix=60
   clk_ithzfix: 60.  =>  60.
KLH10#
KLH10# ; Define IMP for PI on ITS.JOSS.COM
KLH10# devdef imp  ub3   lhdh   addr=767600 br=6 vec=250 ipaddr=172.16.36.247 gwaddr=172.16.36.1
Out of room for more device defs
KLH10#
**

I have increased KLH10_DEVMAX from 20 to 31, then to 63, in kn10dev.c, with no change in the occurrence of the error message.

Ideas, anyone?

**Comment by Rhialto** [comment]
I mentioned it in the other issue: The Makefile system contains an override -DKLH10_DEVMAX=12. Could that be the problem?

**Comment by larsbrinkhoff** [comment]
Fixed by PDP-10/klh10#28.

**Comment by larsbrinkhoff** [comment]
I had to do a little bit more to go from two to four RP03 on a KA10.  See #1035.
