### ISSUE TITLE
Almost but not completely builds

### ISSUE THREAD

**Issue by raywjewhurst** [PDP-10/its#591]
I get to this point it pauses for a few minutes and then I get the error:

DB ITS 1633 IN OPERATION
DB ITS 1633 SYSTEM JOB USING THIS CONSOLE.THE KS-10 CLOCK HAS BEEN RESET, IF THE TIME CANNOT
BE DETERMINED FROM THE NETWORK, YOU MAY HAVE TO :PDSET
YEAR, PDTIME OFFSET, NOT ON DISK.
PLEASE SETLOC APPROPRIATELY.
 LOGOUT ___003 0 

DB ITS 1633 SYSTEM JOB USING THIS CONSOLE. 

The last command timed out.
Makefile:31: recipe for target 'out/rp0.dsk' failed
make: *** [out/rp0.dsk] Error 1

I checked out lines 30 and 31 of the Makefile and 31 references simh and I am using KLH10, btw I do have Expect, Autoconf, and Curses installed per the prerequisites.  I have built this before so I'm not sure what is going on.

**Comment by larsbrinkhoff** [comment]
The interaction between the build script and the PDP-10 console isn't 100% solid.  Sometimes the build will get stuck at some point.  If you restart the build, does it work?

**Comment by raywjewhurst** [comment]
No it does not. I have tried both Simh and KLH10 as well and it doesn't
make a difference. Also of note, I am using the new Xubuntu 17.10.

**Comment by larsbrinkhoff** [comment]
I think you may have forgotten to include `EMULATOR=klh10` when running make.

The message `THE KS-10 CLOCK HAS BEEN RESET` should only apprear when using SIMH.

**Comment by raywjewhurst** [comment]
I got it to work by doing a complete from scratch build so you can close
it.

Thanks

Ray

**Comment by larsbrinkhoff** [comment]
Great!
