### ISSUE TITLE
Chaosnet packet dump 

### ISSUE THREAD

**Issue by ams** [PDP-10/its#593]
Couldn’t think of a better place to ask this, I need a Chaosnet packet dump, if any random traffic for debugging purposes.  It can be anything really, a TIME request and the traffic that ensues, or copying a file over FILE.

Anyone got something like that around, or has a setup where things talk chaos and could do dump the traffic?

**Comment by larsbrinkhoff** [comment]
Would a tcpdump of all UDP packets be ok?

**Comment by ams** [comment]
More than ok!

**Comment by larsbrinkhoff** [comment]
Result from running `:UP UP`.  @bictorv there's nothing secret in here, is there?

There's probably some chatter going on unrelated to the STATUS request.

[up.txt](https://github.com/PDP-10/its/files/1479677/up.txt)

**Comment by larsbrinkhoff** [comment]
Reading a file, probably using the MLDEV service.

**Comment by bictorv** [comment]
It just looks like an old STATUS ANS the new RFC from the :UP command, and some replies to that.

What do you need the Chaos pkt dumps for? (You can find some Chaosnet traffic on Update's Ethernet...) And by the way the chaosnet-bridge now supports TIME and UPTIME in addition to STATUS and DUMP-ROUTING-TABLE.

**Comment by larsbrinkhoff** [comment]
The chatter I was referring to is that there are some packets sent even if I'm not doing anything on the network.  Most look like this and are sent to UP:

    0x0000:  4500 005c 03d2 4000 4011 f276 ac1f 0164  E..\..@.@..v...d
    0x0010:  82ee 13d7 a43a a43a 0048 44a2 0101 0000  .....:.:.HD.....
    0x0020:  0900 0025 0663 b01d 0668 901f 0002 0005  ...%.c...h......
    0x0030:  6f43 6e6e 6365 6974 6e6f 6420 656f 2073  oCnnceitnod.eo.s
    0x0040:  6f6e 2074 7865 7369 2074 7461 7420 6968  on.txesi.ttat.ih
    0x0050:  2073 6e65 c164 0663 0668 5bb5            .sne.d.c.h[.

Translated: "Connection.does.not.exist.at.this.end".

**Comment by ams** [comment]
Perfect! Thank you! Debug purposes (I don't have a decent setup for ITS currently), writing a plugin for Wireshark and fixing this horrible Linux Chaos driver.

**Comment by ams** [comment]
Argh, wireshark doesn't handle text tcpdump sensible.  Is a pcap dump possible?  Otherwise, I'll write something.

**Comment by ams** [comment]
Sorted! These can be converted using the text2pcap program, maybe adding an IP header or UDP header in the process.

[file-converted.txt](https://github.com/PDP-10/its/files/1479824/file-converted.txt)
[up-converted.txt](https://github.com/PDP-10/its/files/1479826/up-converted.txt)
