### ISSUE TITLE
KA10 AI master print set

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#600]
@david-moon has the master print set for the AI lab KA-10 with all the changes for ITS marked in red.  But no way to digitize it.

**Comment by larsbrinkhoff** [comment]
Some options people have suggested:

- Check if Tom Knight has equipment for scanning.
- Send them to @kossow.
- Go to OfficeMax and make reduces copies at 11x17 inches.  Noel Chiappa says he can scan those.

**Comment by b4** [comment]
I know someone up in Seattle with likely resources for scanning if the backlog is too long.

I recall the most recent project for said person was archiving Bell System docs.

**Comment by larsbrinkhoff** [comment]
So these prints are now in the posession of Bob Cassels.  Right @aap?

**Comment by aap** [comment]
Not possession, but he has them for scanning the, yes.

**Comment by larsbrinkhoff** [comment]
Tried to ping Bob the other day.  Didn't work.

**Comment by ams** [comment]
How many pages are we talking about? It is entirely possible to setup a quick small rig using a DLSR and process several hundreds of pages with very good quality and very fast.

**Comment by aap** [comment]
A normal KA print set has about 80 pages of block schematics and 20 pages of flow diagrams. Some more for wiring and assembly. Let's just have some more patience.

**Comment by atsampson** [comment]
This has been done now: http://lars.nocrew.org/its/MIT-AI-Lab-KA10-modified.pdf
