### ISSUE TITLE
Screencasts

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#604]
There should be screencasts showcasing ITS.

**Comment by larsbrinkhoff** [comment]
Some random ideas.

- How to build, run, login, shut down.
- Run EMACS.
- Run Maclisp.
- Connect with supdup.
- Connect to @Pul-Ess SV, @bictorv UP.
- Use cool-retro-term.
- Use real terminals.  I have a VT220 and a VT420.  VT52 would be nice.
- Booting KA ITS, when @rcornwell has it working.
- Ask @rmaldersoniii to record something at LCM.
- @Devon7 had an idea to "record old timer video interviews overlaid with emulated login sessions to jog their memories".

**Comment by larsbrinkhoff** [comment]
Prior art:
- [Compiling and running Adventure](https://www.youtube.com/watch?v=IXCb_6HpbYc)
- [Using the C compiler](https://www.youtube.com/watch?v=zF-vy8b4r-Y)
- [Running Maclisp](https://www.youtube.com/watch?v=r3jaer8lSwA)

Honourable mentions:
- [Connecting to WAITS](https://www.youtube.com/watch?v=4iCDcdJvgM8)
- [Last running KA10](https://www.youtube.com/watch?v=Hm3UY1o7Bdo)

**Comment by larsbrinkhoff** [comment]
I did a test run, capturing an xterm and uploaded it to YouTube.  It works, so everything is in place.

**Comment by larsbrinkhoff** [comment]
Script for first screencast:

- Start with a prebuilt ITS image.
- Start an emulator.
- Start ITS from DSKDMP.
- ^Z and login.
- List user directory with :LISTF.
- List all directories.
- List some other directory.  Use ^F.
- Print out a file.
- Run PEEK to see jobs.
- Shut down with LOCK.
- Exit emulator.

**Comment by larsbrinkhoff** [comment]
First shot: http://youtu.be/MwhsdO0avuU

**Comment by eswenson1** [comment]
What? No demonstration of emacs?  Foo!

**Comment by larsbrinkhoff** [comment]
Don't worry, there will be!  There's a checklist of things to demo near the top of this issue.  But I won't do them all in a single session.

**Comment by larsbrinkhoff** [comment]
Hello @macrakis,

I read you suggested there should be a video demoing ITS made before the KL10 MIT-MC died.  Was such a video made?

Regards,
Lars

**Comment by macrakis** [comment]
​I'm not aware of one, sorry.​

**Comment by larsbrinkhoff** [comment]
MIT videos:

- [Graphics, Knight TV?](http://projects.csail.mit.edu/video/history/aifilms/x05-graphics.mp4)
- [Chess](http://projects.csail.mit.edu/video/history/aifilms/63-chess.mp4)
- [SHRDLU](http://projects.csail.mit.edu/video/history/aifilms/26-robot.mp4)

**Comment by larsbrinkhoff** [comment]
Suggested next screencast: Hello world MIDAS and some DDT debugging.

**Comment by larsbrinkhoff** [comment]
Continued in #2057.
