### ISSUE TITLE
LOGO

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#620]
According to the LOGO family tree, there was an MIT PDP-10 LOGO:  
http://pavel.it.fmi.uni-sofia.bg/logotree/logo.html?187

Maybe it's the same as LLOGO?  
https://dspace.mit.edu/handle/1721.1/6221

Here's a copy from @SimHacker.
> Here is the source code to LLogo in MACLISP, which I stashed from the MIT-AI ITS system. It's a fascinating historical document, 12,480 lines of beautiful practical lisp code, defining where the rubber meets the road, with drivers for hardware like pots, plotters, robotic turtles, TV turtles, graphical displays, XGP laser printers, music devices, and lots of other interesting code and comments.

http://donhopkins.com/home/archive/lisp/llogo.lisp

**Comment by larsbrinkhoff** [comment]
Game by @SimHacker written in LOGO:  
http://donhopkins.com/home/archive/logo/adventure.logo

**Comment by larsbrinkhoff** [comment]
Maybe not the same, here's LLOGO:  
http://pavel.it.fmi.uni-sofia.bg/logotree/logo.html?123

**Comment by larsbrinkhoff** [comment]
@leighklotz wrote here about the PDP-11 and Maclisp versions of LOGO done at MIT:

https://groups.google.com/forum/#!topic/comp.lang.logo/UqOvEkZsJEQ

**Comment by aap** [comment]
I still wonder how that's supposed to work. 16x512x512 would need 512kb for the buffers alone. That's more than the Unibus can handle.

**Comment by SimHacker** [comment]
On 23 Jan 2018, at 10:52, Lars Brinkhoff <notifications@github.com> wrote:
>Game by @SimHacker <https://github.com/simhacker> written in LOGO:
>http://donhopkins.com/home/archive/logo/adventure.logo <http://donhopkins.com/home/archive/logo/adventure.logo>That was my first commercially distributed program, on the C64 Terrapin Logo demo disk! It’s a simple adventure game that uses the Logo top level interpreter as a parser, and is meant to demonstrate some simple data modeling and list processing techniques. 

On another note, here’s an intertwingled PseudoScientific Visualization of the ARPANET circa 1986, from a data file that Mike Brescia sent me. (Sorry the image maps don’t work, but the text links do work). 

Main index of all ARPA IMPs:
http://www.art.net/~hopkins/Don/arpanet/index-large.html <http://www.art.net/~hopkins/Don/arpanet/index-large.html>

MIT-77 IMP:
http://www.art.net/~hopkins/Don/arpanet/mit77-large.html <http://www.art.net/~hopkins/Don/arpanet/mit77-large.html>

NSA2 IMP:
http://www.art.net/~hopkins/Don/arpanet/nsa2-large.html <http://www.art.net/~hopkins/Don/arpanet/nsa2-large.html>

-Don

**Comment by larsbrinkhoff** [comment]
@SimHacker,  
Cool stuff!  It's like those early ARPANET maps, only a zillion nodes instead of seven.

But isn't it a bit reduntant to display that an IMP is a neighbour of its own neighbour?

**Comment by larsbrinkhoff** [comment]
At MIT, there were:

- 11LOGO - PDP-11
- APLOGO - Apple II
- ATLOGO - Atari
- TILOGO - Texas Instruments
- LLOGO - Lisp
- PLOGO - Pascal

**Comment by larsbrinkhoff** [comment]
LLOGO  
http://bitsavers.org/pdf/mit/ai/aim/AIM-307.pdf  
http://bitsavers.org/pdf/mit/ai/aim/AIM-307a.pdf

**Comment by larsbrinkhoff** [comment]
11LOGO  
http://bitsavers.org/pdf/mit/ai/aim/AIM-313.pdf  
http://bitsavers.org/pdf/mit/ai/aim/AIM-315.pdf  
http://bitsavers.org/pdf/mit/ai/aim/AIM-313a.pdf

**Comment by larsbrinkhoff** [comment]
Atari Logo: https://www.youtube.com/watch?v=nisFUjnO87g

**Comment by larsbrinkhoff** [comment]
This is about the MIT Logo group:  
https://logothings.wikispaces.com/The70s

Maybe the Tom Knight display?  
![](https://logothings.wikispaces.com/file/view/room.jpg/30480899/room.jpg)

**Comment by larsbrinkhoff** [comment]
@leighklotz message to comp.lang.logo is requried reading:  
https://groups.google.com/forum/#!topic/comp.lang.logo/UqOvEkZsJEQ

**Comment by larsbrinkhoff** [comment]
AIM-307 says there was a PDP-10 CLOGO.  Maybe this?

BACKUP; TS CLOGO  
HQM; CLOGO BIN  
SYSBIN; CLOGO BIN  
SYS; TS CLOGO

No source code?  At least not named CLOGO.

**Comment by larsbrinkhoff** [comment]
@Paul-Svensson, I see that the file SV: PAUL; LOGO MAC is a BBN Logo from 1970.  Do you remember where that file came from?

**Comment by Alexey-Slyusar** [comment]
BBN Logo documentation:

* Bolt Beranek and Newman, Inc., Report no. 2165 vol. 4 "The Logo Processor: A Gide for System 
   Programmers",
   pub date 30 June 1971
[https://archive.org/details/ERIC_ED057582](url)

* Bolt Beranek and Newman, Inc., Report no.1889 "Programming-Languages as a Coceptual Framework 
  for Teaching Mathematics" (Feurzeig, Papert at al., 1969) has Appendix  "A Description of the Logo 
  Language and System".
[https://files.eric.ed.gov/fulltext/ED038034.pdf](url)

**Comment by larsbrinkhoff** [comment]
Thank you @Alexey-Slyusar!

Have you heard anything about CLOGO for the PDP-10?

**Comment by Alexey-Slyusar** [comment]
LOGO family tree says that CLOGO is direct descendant of BBN Logo. So it is possible that they are similar not only syntactically (e.g. both  BBN Logo and  CLOGO allow use "noise words". Most of the "noise words" have been eliminated in LISP LOGO) but also have similar internal design. 
So it is possible that the BBN Report no. 2165 vol. 4 that described BBN PDP-10 LOGO system may be relevant to CLOGO implementation also.

**Comment by larsbrinkhoff** [comment]
You're welcome.  I want to put ITS in the hands of everyone who's interested.  It's good to hear you're up and running with TECO and Scheme.

If you or any other Logo fan wants to dig into the Logo aspect of ITS, I'm happy to help.  I'd like that aspect to be explored more fully, but I don't have much time myself.

I have a few binary files from CLOGO, but no source code.  We could install the binary in ITS so people can try it out.  There's also some kind of BBN Logo for the PDP-10, but it's not for ITS: https://github.com/PDP-10/bbn-logo

We do have source code for the PDP-11 Logo that was developed at MIT, but I haven't been able to assemble it.  There's also a very early version of Apple II Logo from MIT, but I'm not yet sure it can be put online.

**Comment by larsbrinkhoff** [comment]
I checked CLOGO disassembly against the "BBN Logo" (if it indeed is that), but they're not similar.

**Comment by Alexey-Slyusar** [comment]
Thank you @larsbrinkhoff!

Could you please include the CLOGO binary in current ITS git repository. I want to try it out (with my big pleasure I must say). I think that I will be able to  write some kind of Introduction and Primer for CLOGO after I play with the system for a while.

**Comment by larsbrinkhoff** [comment]
I will add a CLOGO binary in #1018.

**Comment by larsbrinkhoff** [comment]
The Logothings wiki moved here:  
https://logothings.github.io/logothings/The80s.html

**Comment by larsbrinkhoff** [comment]
I think we can close this now.

See #889, #1233,  #884, #934, etc.

**Comment by Alexey-Slyusar** [comment]
Mostly yes, but I ask to keep #884 still opened for a while.
Thank you!

чт, 27 сент. 2018 г. в 17:49, Lars Brinkhoff <notifications@github.com>:

**Comment by larsbrinkhoff** [comment]
@Alexey-Slyusar, do you know about the Logo Tree Project, and who runs it?  I think we can make some updates.

**Comment by Alexey-Slyusar** [comment]
Hi Lars! Yes I know. The Logo Tree Project leaded by Dr. Pavel Boytchev. He
is an associated professor and researcher at the Faculty of Mathematics and
Informatics, Sofia University. And he is notable logo developer - there are
at least two very interesting logo realisations he authored: ELICA Logo
(OpenGL graphics oriented environment goes far beyond elementary turtle
graphics) and lhogho (a logo compiler, compiler sic!).
I think that it is great idea to contact with Pavel and contribute some
updates to the Logo Tree Project.
I think that is possible to find Pavel's contact from researchgate.net or
something similar resource or directly from Sofia University web site. I'll
try to find Pavel's email and provide you with the actual email address
 soon.

чт, 4 окт. 2018 г. в 8:43, Lars Brinkhoff <notifications@github.com>:

**Comment by Alexey-Slyusar** [comment]
Great! Thank you.

чт, 4 окт. 2018 г. в 11:26, Lars Brinkhoff <notifications@github.com>:

**Comment by larsbrinkhoff** [comment]
We have this information in the LogoTreeProject PDF:

| Name | Years | Platform | Inspirer | Main Creator(s) |
| --- | --- | --- | --- | ---
| 11LOGO | 1973-1974 | PDP-11 | Logo (Ghost) |
| BBN PDP-10 Logo | 1967-1968 | PDP-10 | BBN PDP-1 Logo
| CLLOGO | <1975 | PDP-10 | LLOGO, CLOGO |
| CLOGO | <1975 | PDP-10 | Logo (Ghost)
| LLOGO (LISP LOGO) | 1970-1975 | PDP-11| Logo (Ghost) | Henry Lieberman, Daniel Bobrow,<br>Kenneth Kahn(?)
| MIT Apple Logo | | Apple | Pascal Logo |
| MIT Logo for the Apple II | 1981 | Apple II | TI Logo | Steven Hain, Patrick Sobalvarro, Leigh Klotz (MIT)
| MIT PDP-10 Logo | 1969(?) | | BBN PDP-1/10 Logo | (MIT)
| MIT PDP-11 Logo | 1970-1975 | PDP-11 | MIT PDP-10 Logo | Ron Lebel, Wade Williams,<br>Joe Cohen, Nat  Goodman,<br>Hal Abelson, Roger Hale,<br>Radia Perlman, Tom Knight,<br>Ira Goldstein, Henry Lieberman,<br>Richard Greenblatt, Seymour Papert,<br>Cynthia Solomon (MIT)
| NLLOGO | ?-1974-? | PDP-10 ? | LLOGO
| Pascal Logo (PLOGO) | 1977-1978 | TI-9900 | MIT PDP-11 Logo | Gary Drescher
| TI Logo | 1981-1984 | TI-99 | Pascal Logo | Edward Hardebeck
| TI Logo II | 1983 | TI-99 | TI Logo

I think this can be revised substantially.

CC @leighklotz, @lieber, @ToonTalk, @hqm, @natgoodman, @lhogho

**Comment by larsbrinkhoff** [comment]
My suggested updates:

- 11LOGO and MIT PDP-11 Logo are the same.  I think I see evidence it was updated up until 1979.
- BBN PDP-10 Logo: We have source file with a copyright from 1970.
- CLLOGO, LLOGO, and NLLOGO are the same.  I see timestamps up to 1977.  Platform is both PDP-10 and Multics, not PDP-11.
- CLOGO and MIT PDP-10 Logo are the same.  I see timestamps up to 1977.  It seems to be a direct port of BBN PDP-10 Logo to ITS.
- MIT Apple Logo and MIT Logo for the Apple II are the same.  1980-1981.

**Comment by larsbrinkhoff** [comment]
- PLOGO: Updated in 1979.
- TI Logo: What I see suggests 1979-1980.

**Comment by larsbrinkhoff** [comment]
- Inspiration for Apple II Logo should be PLOGO.
- Platform for PLOGO and TI Logo should be TI 99/4.

**Comment by Alexey-Slyusar** [comment]
Thank you Lars for such compact and informative summary. I have only one
LLOGO related clarification.
Strictly speaking, CLLOGO, LLOGO, and NLLOGO are not the same. All of these
are LISP LOGO variants as it described on AIM-307a page 13.

чт, 4 окт. 2018 г. в 12:16, Lars Brinkhoff <notifications@github.com>:

**Comment by larsbrinkhoff** [comment]
What I mean is that for the purpose of the Logo Tree Project, this is just one implementation.  There is a compile-time option to build CLLOGO or LLOGO from one set of source files.  And NLLOGO is just a newer version, not a distinct implementation.

**Comment by Alexey-Slyusar** [comment]
For the purpose of the Logo Tree Project, this is just one implementation.
You're absolutely right, thank you.

чт, 4 окт. 2018 г. в 13:05, Lars Brinkhoff <notifications@github.com>:

**Comment by lhogho** [comment]
Thanks everyone -

I'm now processing the suggested changes in the Logo tree data. Some 
modifications will require merging of records. When I'm ready, I will 
let you know, so you can check whether everything is OK.

Meanwhile, I have the impression that you have not seen the full record 
of each Logo. For example, the data shown below (name, years, platform, 
inspirer, creators) is the default view.

The top of the page, under the caption "Visible columns" there are 
buttons to toggle the visibility of additional data (URL, version, status)

- Pavel

**Comment by Alexey-Slyusar** [comment]
Hi Pavel!
Thank you!

I'll check the columns and fill the additional data (URL, version, status)
soon.
Thanks again!

Alexey


сб, 13 окт. 2018 г. в 15:35, lhogho <notifications@github.com>:

**Comment by larsbrinkhoff** [comment]
I have been in touch with Guy Montpetit, formerly of the General Turtle company.

He called the smaller display part the *Turtle Terminal* 2500.  The larger computer part would be the 3500, and maybe it used an LSI-11.  Maybe it ran a version of "NLOGO" (#1737) on top of LSITS, the "Little SITS emulator".  My theory is that the LSI-11 is too small to host a full SITS (#1730), so maybe LSITS is a layer to pretend there's an operating system for 11LOGO to run on.
