### ISSUE TITLE
Rubin 10-11 interface

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#621]
Make notes here.

**Comment by larsbrinkhoff** [comment]
ITS subtitle DEFINE EXEC PAGES.

There's a fixed mapping for some 10-11 pages in the monitor virtual address space:
- T11CP is a control page.
- XGP has three pages.
- Knight TV has six pages for the ttys, plus 11 pages for the video buffer.

**Comment by larsbrinkhoff** [comment]
PDP-11 assignment

- 0 - Knight TVs
- 1 - XGP
- 7 - Chaosnet

**Comment by larsbrinkhoff** [comment]
David Moon:
> MIT-AI also had a device, which was heavily used for many years although it never worked reliably, that mapped portions of the pdp10's address space into eight pdp-11 Unibuses.  The pdp-11's in question (they weren't all real pdp-11's; one was a Lisp machine and one was a Chess machine) were scattered around the lab; some were I/O controllers for the pdp-10, while others were independent machines that just used this device as a high-speed link to the timesharing system.  The effect of this hardware was to make pdp-11 memory look like extremely slow pdp-10 memory with the right-hand 4 bits of each word missing.  A user program in the timesharing system could issue a system call to map an arbitrary portion of an arbitrary pdp-11's memory into its virtual address space and could then do whatever it wanted to it.  These references were mapped through the usual virtual-to-physical page map and then again through a pdp-10-physical to pdp-11-physical page map located inside the 10/11 interface device.

**Comment by larsbrinkhoff** [comment]
From SYSEN2; STUFF 92

```
;5/29/73 PROGRAMMING THE PDP-10 TO PDP-11 INTERFACE

;THE INTERFACE LETS THE PDP-10 PROGRAMMER DIRECTLY ACCESS THE MEMORIES
;OF UP TO EIGHT PDP-11'S.  PDP-10 PAGES ARE MAPPED INTO SEGMENTS OF
;VARIABLE SIZE IN THE PDP-11'S MEMORY.  THE PDP-10 PAGE MAP IS ALSO
;DIRECTLY ADDRESSABLE IN MEMORY (IT CURRENTLY LIVES IN LOCATIONS
;776000-776777)**.  THERE IS ONE ENTRY IN THE MAP FOR EACH PDP-10 PAGE.
;** SEE ALSO BELOW

;PAGE TABLE ENTRY:
;       4.9     VALID
;       4.8     WRITE ENABLE
;       4.3-4.7 (5 BITS) NOT USED (0)
;       3.9-4.2 (3 BITS) PDP-11 NUMBER
;       2.2-3.8 (16 BITS) RELOCATION
;               ORIGIN OF SEGMENT OF IN PDP-11 ADDRESS SPACE
;               PDP-11 ADDRESS=4*RELOCATION
;       1.1-2.1 (10 BITS) PROTECTION (PDP-11 PROTECTION=4*PROTECTION
;               IF PROTECTION=0 THEN ONLY ONE 16 BIT WORD IS ACCESSIBLE)

;WRITE REFERENCE FORMAT
;       3.3-4.9 (16 BITS) WORD 0, LOW ORDER WORD
;       1.5-3.2 (16 BITS) WORD 1, HIGH ORDER WORD
;       1.4     DON'T WRITE WORD 0
;       1.3     DON'T WRITE WORD 1
;       1.1-1.2 (2 BITS) NOT USED

;READ REFERENCE FORMAT
;       3.3-4.9 (16 BITS) WORD 0, LOW ORDER WORD
;       1.5-3.2 (16 BITS) WORD 1, HIGH ORDER WORD
;       1.1-1.4 (4 BITS) 0

;NOTE -- SPLIT CYCLES WILL DO THE RIGHT THING; HENCE, ILDB AND IDPB WORK.

;CAUTION -- WHEN USING BYTE INSTRUCTIONS, A 16 BIT BYTE SIZE IS
;RECCOMMENDED.  SUCCESSIVE INCREMENTS OF BYTE POINTERS WITH AN 8 BIT BYTE
;SIZE DO NOT ADDRESS CONSECUTIVE BYTES IN THE PDP-11!

**Comment by larsbrinkhoff** [comment]
By David Moon:
> MIT-AI also had a device, which was heavily used for many years although it never worked reliably, that mapped portions of the pdp10's address space into eight pdp-11 Unibuses. The pdp-11's in question (they weren't all real pdp-11's; one was a Lisp machine and one was a Chess machine) were scattered around the lab; some were I/O controllers for the pdp-10, while others were independent machines that just used this device as a high-speed link to the timesharing system. The effect of this hardware was to make pdp-11 memory look like extremely slow pdp-10 memory with the right-hand 4 bits of each word missing. A user program in the timesharing system could issue a system call to map an arbitrary portion of an arbitrary pdp-11's memory into its virtual address space and could then do whatever it wanted to it. These references were mapped through the usual virtual-to-physical page map and then again through a pdp-10-physical to pdp-11-physical page map located inside the 10/11 interface device.

**Comment by larsbrinkhoff** [comment]
Schematics: #805.

**Comment by larsbrinkhoff** [comment]
I looked at the schematics: https://stuff.offog.org/its/ten11/

Except for the ADRACK sheet, I don't see any complicated logic.  There are a few 74xx ICs here and there.

**Comment by larsbrinkhoff** [comment]
PALX code for small hello world test:

```
.title hello world

.=100
r0=%0

start:  mov     #hello,r0
loop:   tstb    @#%tps
        bpl     loop
        movb    (r0)+,@#%tpb
        bne     loop
        halt

hello:  .asciz /hello world/

.end start

**Comment by larsbrinkhoff** [comment]
When you start a PDP-11 running, you're supposed to put a `BR .` at 0.  You simply deposit 777 in the first word.

When using SIMH, executing a HALT will drop you into the console command line mode.  In this mode, no external memory references will be accepted.  Restart as per above.

**Comment by larsbrinkhoff** [comment]
But I think that page might be wrong.  From reading the microcode I get the impression there was no PDP-11.  There was an 8K octet core memory on the bus, and the PDP-10 could also access the control 1K x 64 control store directly.

**Comment by atsampson** [comment]
I've just converted some more SUDS files.

* TEN11; https://stuff.offog.org/its/suds/ten11/
* TEN11N; https://stuff.offog.org/its/suds/ten11n/

(If any SUDS experts know how to fix the (??) after each pin name, please let me know! I assume I need to load DIP definitions or something...)
