### ISSUE TITLE
KL-UDGE board

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#622]
The KL-UDGE board incorporates a DeCoriolis clock, a 60 Hz clock interrupt, and console lights.

Quoth John Francis at alt.sys.folklore:

> When DEC introduced the third version of the PDP-10/DECSystem-10, the KL-10, it had practically no blinky lights on the outside (and only a PDP-11/35 console display inside if you opened up the cabinet doors).
> 
> Somebody (MIT, I believe, although it could have been BB&N) cobbled up a display using an empty CPU cabinet from an earlier model of PDP-10, which still had all the light panels installed.  THey even labelled it with a semi-official looking DEC part number:  KL-UDGE

**Comment by larsbrinkhoff** [comment]
@eswenson1 Do you remember this board?  Did you see the console lights?

**Comment by larsbrinkhoff** [comment]
There's a picture of MIT-MC here:  
https://github.com/PDP-10/its/issues/425#issuecomment-276038046

The PDP-11 front end is visible of course.  But the KL-UDGE lights?

**Comment by larsbrinkhoff** [comment]
Photos.
![kl-udge-2](https://user-images.githubusercontent.com/775050/57760774-8f541800-76fc-11e9-971b-5487e693f92d.jpg)
![kl-udge-1](https://user-images.githubusercontent.com/775050/57760785-92e79f00-76fc-11e9-9ff1-dfbe19b8127b.jpg)

**Comment by larsbrinkhoff** [comment]
The file IMPTER; KLUDGE TXT says "IMP interface, calendar clock, and TTL I/O Buss adapter."

**Comment by larsbrinkhoff** [comment]
Another photo.  KL-UDGE is the box to the left.  Source: https://www.computerhistory.org/collections/catalog/102803897
![mit-mc-kludge](https://github.com/PDP-10/its/assets/775050/1cb30ed3-30c4-4658-a800-1256e3432782)

**Comment by aap** [comment]
The website seems to be having issues right now. I guess they'll fix it soon

**Comment by larsbrinkhoff** [comment]
www.computerhistory.org seems to be back online now.

**Comment by eswenson1** [comment]
Yes, thanks.
