### ISSUE TITLE
Tape databases

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#637]
SYSENG; MACRO TAPES  
SYSENG; MACRO MLTAPE  
.TAPE0;   
.TAPE1;   
.TAPE2;   
MAPS;  
MAPS2;  
MAPS3;

**Comment by larsbrinkhoff** [comment]
DUMP commands that deal with tape the database:

- TAPE
- TAPES
- TLIST
- FIND

**Comment by larsbrinkhoff** [comment]
Seems the files in MAPS are just a small selection of the data in .TAPE.

The .TAPE files aren't that complex.  Some header, a little data for each directory, and then three words per file: name and presumably timestamp.

**Comment by larsbrinkhoff** [comment]
SYSENG; MACRO TAPES has a ten-word record for each tape.  The information includes tape number, date, who made it.  As far as I can see, it doesn't cover the full history of backups.  Far from it.

**Comment by larsbrinkhoff** [comment]
The .TAPE files go back to 1985.  So it looks like the backup tape database was remade from scratch when the KS10 machines replaced the older ones.

I made Unix tools to print out the contents of MACRO TAPES and TAPE nnn files.

**Comment by larsbrinkhoff** [comment]
I got some sample .TAPE files.  Some are an older format.  I made some guesses and updated my tape-dir tool for this format.

Sample output:

```
Tape: 2
Reel: 1
Date: 730418
Type: Full (1)
 CHESS   C       NBIN   1901-04-10 20:09:25
 CHESS   ENDGME  102    1901-03-25 16:28:38
 CHESS   TECH    BIN    1901-04-16 20:06:52
 CHESS   TECH    DUMP   1901-04-16 20:06:10
 CHESS   TECH    GAME   1901-04-09 22:04:50
 CHESS   TECH    LOSES  1901-04-11 00:24:23
 CHESS   TECH    WINS   1901-04-10 01:21:06
```

```
Tape: 0
Reel: 0
Date: 720915
Type: Full (1)
 .       @       DDT    2411-15-31 [WARNING: overflowed year field] 36:24:31
 .       @       ITS    2411-15-31 [WARNING: overflowed year field] 36:24:31
 .       @       MSALV  2411-15-31 [WARNING: overflowed year field] 36:24:31
 .       @       NITS   2411-15-31 [WARNING: overflowed year field] 36:24:31
 .       @       OITS   1900-08-10 19:26:27
 .       @       OMSALV 2411-15-31 [WARNING: overflowed year field] 36:24:31
 .       @       OOITS  2411-15-31 [WARNING: overflowed year field] 36:24:31
 .       @       PT     2411-15-31 [WARNING: overflowed year field] 36:24:31
 .       DECDSK  BIN    1900-08-09 01:12:56
 .       ITS     BIN    1900-09-15 16:17:14
 .       MSALV   BIN    1900-08-09 08:29:00
 .       MSALV   DMP    2411-15-31 [WARNING: overflowed year field] 36:24:31
 .       TENDMP  BIN    1900-07-03 17:21:17
 .       _MSGS_  .      1900-07-26 16:24:47

**Comment by larsbrinkhoff** [comment]
Obviously the date isn't decoded correctly.  Vague idea is that the month and day is right, but the year should be added to 1972 instead of 1900.  Maybe some files in . are older than 1972 so there's a negative number.

**Comment by rmaldersoniii** [comment]
Didn't ITS use the DEC date format to begin with?
    (((YEAR - 1964) * 12) + MONTH) * 31) + DAY

**Comment by larsbrinkhoff** [comment]
I never saw anything about early ITS date formats.  Did you?

I will certainly try that DEC format when I get a chance!

**Comment by larsbrinkhoff** [comment]
When I print the dates using the DEC format, I get lots of dates from 1964 which would be too early.  Maybe another epoch was used.

But I also see a September 31th, and timestamps after the tape was made.

**Comment by larsbrinkhoff** [comment]
It seems the day and month field use the ITS format, but the year field is different somehow.

Most files dumped in 1972 has this 9-bit field set to 000, but for some files it's 001.  A tape made in 1971 has most files set to 001, but a few have 000.  It's unclear if the field encodes a year, or if so how.

Ah, SYSENG; PRUFD 10 was dumped several times with both the new and old formats.  This could be a Rosetta stone.

**Comment by larsbrinkhoff** [comment]
DUMP has some code to convert "old .TAPEn; TAPEnnn file format to new (1975?)".  It's not immediately obvious what it does, but I'll examine it closely.

**Comment by larsbrinkhoff** [comment]
Most old timestamps has the 9-bit year field set to either 000 or 001.  I'm not sure if this is a year at all.

Some interesting timestamps:

- DDTINI; MGW .DDT. - 1903-01-02
- GJC; A HACK - 1903-03-03

These have the field set to 003.  I see no files with 002 or 004-011.

**Comment by larsbrinkhoff** [comment]
Found this in ITS 785:

```
YEAR==73.       ;BASE YEAR LOW BIT ONLY STORED IN FILE
YEARPH==-1      ;1 OR -1 AS FOLLOWS
;IF LBT (YEAR) .NE. LBT (STORED YEAR) THEN COMPLETE STORED YEAR = YEAR+YEARPH
```

**Comment by larsbrinkhoff** [comment]
More details:

```
        LDB I,[UNYRB+@DIRPT(A)]
        MOVEI TT,YEAR
IFE YEAR&1,     SKIPE I
IFN YEAR&1,     SKIPN I
IFG YEARPH,     AOS TT
IFL YEARPH,     SOS TT
```

and

```
        UNDATE==3       ;DATE ETC.
                UNTIM==2200,,   ;COMPACTED TIME OF CREATION
                UNYMD==221200,, ;Y,M,D OF CREATION
                UNREFT==341000,,        ;DAYS AFTER CREATION LAST REFERENCED
                UNMON==270400,, ;MONTH
                UNDAY==220500,, ;DAY
                UNYRB==330100,, ;YEAR BIT

**Comment by larsbrinkhoff** [comment]
I wrote earlier: 

> Most files dumped in 1972 has this 9-bit field set to 000, but for some files it's 001. A tape made in 1971 has most files set to 001, but a few have 000.

This makes perfect sense now.  The 1972 tape has most files dated 1972, but a few from 1971.  The 1971 tape should have a few files from 1970!

**Comment by larsbrinkhoff** [comment]
I updated the tape-dir tool in pdp10-its-disassembler.  It can now read the old and new file formats, and will handle 1-bit years.  We have a few old _TAPEn fles, which I processed and put in a GitHub repository.  We can now see a bit of ITS prehistory.

**Comment by larsbrinkhoff** [comment]
@eswenson1, I made some notes about the _TAPE databases here.

**Comment by larsbrinkhoff** [comment]
Unique file timestamps from _TAPE records, 1970-1990.
![timestamps](https://user-images.githubusercontent.com/775050/91426544-f1d31800-e85c-11ea-9e6b-3423829878b3.png)
