### ISSUE TITLE
Merge KA ITS build

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#657]
There's a `ka10` branch for building KA ITS.  The build script isn't quite ready yet, and the KA10 simulator isn't either.  But it's getting close.

Currently, it's a bit of a hack on top of the stock SIMH build.

**Comment by larsbrinkhoff** [comment]
Things to consider:

- The KA10 simulator is currently a separate repository, but will (most likely) be merged into stock SIMH.
- One more build dimension: Which processor.
   - Other bootstrap binaries (ITS monitor, DUMP, etc).
   - Other cold start tools (MAGDMP, paper tapes.)
   - No need to make the KS front end filesystem.
   - No need to make bootable KS tapes.

**Comment by rcornwell** [comment]
The KA10 is about 6 months to 1 year from merging into the main SIMH tree. However it will be merged into the PDP10 tree so will be in the same location as Bob's KS10 simulator. This also depends on the number of devices that we decide to add.

To consider how to select KA10 vs Bob's KS10 simulator. Perhaps use name PDP10 to select Bob's and KA10 to select mine, rather then SIMH.

**Comment by aap** [comment]
Why not ks10, ka10, and klh10?

**Comment by larsbrinkhoff** [comment]
Maybe because the names of the SIMH executables would be `pdp10` and `ka10`.  But then, the name of the KLH10 executable is `kn10-ks-its`.

**Comment by rcornwell** [comment]
How about pdp10, ka10, klh10?

Does the klh10 run in KL10 mode or only in KS10 mode?

**Comment by aap** [comment]
Maybe the simh KS10 executable should be renamed then. Wasn't the KA10 the only 10 that was actually called PDP? Would be strange to have `pdp10` refer to a KS and have something else for the KA and KI.

**Comment by larsbrinkhoff** [comment]
You have a point, but I'm not sure the SIMH team would want to change the name.

**Comment by rcornwell** [comment]
I doubt that they would change the name. This would break way to many things. This is why I did not call my simulator pdp10.

**Comment by larsbrinkhoff** [comment]
@rcornwell I have now pushed changes to build KA ITS in Travis:  
https://travis-ci.org/PDP-10/its/builds/343740267

I'm not sure it'll pass the 50-minute build time limit.

**Comment by larsbrinkhoff** [comment]
Note, you'll now have to type

    make clean all EMULATOR=sims

**Comment by larsbrinkhoff** [comment]
All three simulator targes build now.

Need to fix the EMACS and COMPLR bugs, and change the KA10 machine name from ML to DB.

**Comment by larsbrinkhoff** [comment]
Will be fixed by #685.
