### ISSUE TITLE
CONS Lisp Machine

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#658]
According to SYSEN2; STUFF 92, the CONS Lisp Machine was connected to the Rubin interface, slot 2.  Its software was loaded from CONS; CCONS BIN.

**Comment by larsbrinkhoff** [comment]
@ams, are LispM hackers interested in the CONS, or is it all about the CADR?

**Comment by ams** [comment]
If I understood it correctly the CONS was a (note the singular) prototype which was repurposed for what then quickly became the CADR.  Which is what everyone then used at the MIT AI lab.  

The CONS paper is also just a very early draft of what became the CADR.  There are some differences in architecture, but they are minor.

All bits are interesting, but if it is just binaries I don’t think we have much use for them in any CADR related work.

**Comment by larsbrinkhoff** [comment]
LISPM1; LMI 845 - Loads a CONS through 10-11.  Also does many other things.  Simulator?

**Comment by larsbrinkhoff** [comment]
LISPM1; CONSLP 251 - Microcode assembler.

**Comment by larsbrinkhoff** [comment]
LMCONS; LISMP 10.  Loads CC and some other files into Maclisp and/or dumps out a TS CC.  Also TS CADR for that other Lisp machine.

**Comment by ams** [comment]
I assume that `CC (INIT)` would be for CONS, and `CCD (INIT)` for CADR.

This seems to be stuff to get CC (for CONS and CADR) working on a 10.

**Comment by larsbrinkhoff** [comment]
From LMIO; CHSTBL LISP:

```
                       (434 . "907 [Son of CONS] Lisp Machine 1  x6765"));LM1
```

Lisp Machine 1 in room 907 was the son of CONS.

**Comment by larsbrinkhoff** [comment]
We now have CC (INIT), so may be able to make a TS CC.

**Comment by larsbrinkhoff** [comment]
LMCONS; LISP 10, when run, needs LISPM; UTIL FASL which isn't there.

**Comment by larsbrinkhoff** [comment]
From https://www.computerhistory.org/collections/catalog/102647223  
"CONS Machine main board"
![cons](https://user-images.githubusercontent.com/775050/77066867-3ae88b80-69e4-11ea-9d94-fa1b51c30f02.jpg)

**Comment by larsbrinkhoff** [comment]
Looks like the CONS potentially could have been in use until October 1978.  Well, possibly longer too but not very pleasantly without a keyboard.

LMDOC; BUG OLISPM (ToTS 7007802, timestamp1978-10-31)
```
MOON@MIT-AI 10/29/78 19:17:40
To: (BUG LISPM) at MIT-AI
I ripped off the keyboard from the CONS machine.
````

**Comment by larsbrinkhoff** [comment]
It's easier to put a lower bound on the start of the CONS.  -READ- -THIS- timestamps for LISPM and CONS are 1974-09-14 and 1975-10-16, respectively.  Roughly, LISPM is software and CONS is hardware.  It appears software was initially developed using the LMI emulator which appeared in fall 1974.
