### ISSUE TITLE
STUGA - Swedish adventure game

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#659]
From http://microheaven.com/svenska/stuga.shtml
> Stugan torde ha varit ett av de mest spridda spelen för PC i Sverige under 80-talet. Eftersom det är en viktig bit av Sveriges datorhistoria, och för att det är ett spel med många roliga och överraskande scener, ville jag översätta spelet till en plattform som gör det lätt att spela för vem som helst, idag och i framtiden. Jag kontaktade författarna, men de meddelade att källkoden tyvärr var borta för gott, både för stordatorversionen Stuga och den kommersiella PC-versionen Stugan. En tid senare fick jag ändå syn på källkoden till Stuga på Kimmos hemsida. Det visade sig att de plötsligt fått ett tips om en kille som tagit över en del av stordatorprylarna som Stuga skrevs på, och efter kontakt med honom fick de fram vad som troligen var den sista versionen av källkoden! Jag fick författarnas välsignelse att översätta Stuga till programmeringsspråket Inform, för att sedan släppa spelet som freeware.

The source code was thought to be lost.  But then someone appeared who was in posession of (parts of) the old mainframe used to write the game.  Maybe the same machine as in #412.

Source code:  
http://microheaven.com/svenska/stuga.txt

**Comment by larsbrinkhoff** [comment]
The source code contains åäö characters, so it's not accepted as input to itstar.

**Comment by atsampson-abertay** [comment]
I guess the authors would have been using terminals with the ISO 646 Swedish variant characters, so feeding it through `tr '\304\305\326\344\345\366' '[]\\{}|'` should be period-appropriate.

Author Kimmo Eriksson's site has a version with that character set (but also with line-wrapping damage): http://kimmoeriksson.se/stugan/STUGA.txt

I suppose it'd be possible to backport Johan Ottosson's English translation of the Inform 6 port of this game to the BASIC code...

**Comment by atsampson** [comment]
I guess the authors would have been using terminals with the ISO 646 Swedish variant characters, so feeding it through `tr '\304\305\326\344\345\366' '[]\\{}|'` should be period-appropriate.

Author Kimmo Eriksson's site has a version with that character set (but also with line-wrapping damage): http://kimmoeriksson.se/stugan/STUGA.txt

I suppose it'd be possible to backport Johan Ottosson's English translation of the Inform 6 port of this game to the BASIC code...
