### ISSUE TITLE
EMACS1 directory full

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#66]
A fully populated EMACS1 directory with the latest files from both AI and MC has 172 files.  Apparently, this is over the limit, because DUMP fails with `ERROR: OPEN:  DSK: EMACS1; _DUMP_ OUTPUT - DIRECTORY FULL`

In the snapshots, AI: EMACS1; has 128 files, and MC: EMACS1; has 169 files.

**Comment by eswenson1** [comment]
Sounds like EMACS2 is in order! 

-- Eric

**Comment by larsbrinkhoff** [comment]
> Sounds like EMACS2 is in order!

So there's no (reasonable) way to increase the limit for a directory?

**Comment by eswenson1** [comment]
I don’t think so. I think there is a 2 page limit on them, and that limit is burned into many programs, as well as ITS.

**Comment by larsbrinkhoff** [comment]
Ok, thanks.  In that case, there's no bug, just a known limitation to which we'll have to adapt.
