### ISSUE TITLE
Do something with DECtape images

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#694]
We just got DECtape images from Al Kossow and Peter Samson.

**Comment by aap** [comment]
http://www.bitsavers.org/bits/DEC/pdp6/X3411.2006_Peter_Samson_DECtapes/

D95A_perr has a MACDMP in the first sectors that should be bootable from a PDP-10. Sadly no PDP-6 boot blocks :(

**Comment by larsbrinkhoff** [comment]
Happily, we found SYSENG; SYSTEM GEN!

**Comment by eswenson1** [comment]
There seems to be garbage at the end of that file, though.  Might want to clean it up.

**Comment by larsbrinkhoff** [comment]
That's probably because it's a copy from MACDMP, which doesn't store information about file length beoynd the number of blocks.

**Comment by eswenson1** [comment]
But when we commit the file to Git, we should get rid of the garbage at the end.

**Comment by larsbrinkhoff** [comment]
That's a separate repository.  One for storing untouched and unsorted files.

**Comment by larsbrinkhoff** [comment]
I added a macdmp tool to my suite in pdp10-its-disassembler.  It can extract files from a MACDMP tape image.

**Comment by larsbrinkhoff** [comment]
The files are here:

http://lars.nocrew.org/dectapes/
