### ISSUE TITLE
KA IMP

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#700]
Build ITS with KA IMP enabled.

Add IMP support to @rcornwell's KA10 simulator.  Probably needs PI multiplexing to share channel 1 with TM10.

![](http://i.dailymail.co.uk/i/pix/2014/03/06/article-0-1C16DE7600000578-182_634x372.jpg)

**Comment by aap** [comment]
But do we have an IMP yet?

**Comment by larsbrinkhoff** [comment]
We just need a working interface.  We can emulate the IMP functionality.  This is what KLH10 does.

**Comment by larsbrinkhoff** [comment]
Documentation helps.

- Host/IMP protocol: https://tools.ietf.org/html/rfc704

**Comment by larsbrinkhoff** [comment]
Link to the sims issue: rcornwell/sims#16.

**Comment by larsbrinkhoff** [comment]
Setting KAIMP==1 builds ITS with IMPOLD WTHNCP. I enabled TCP/IP, but not NCP.

Booting this crashes. But if I also set C1MXP it runs, which is encouraging.

**Comment by larsbrinkhoff** [comment]
I have added a small amount of channel 1 multiplexing to the simulator, and made TM10 use it.  Seems to work.

Also some stubs for a KAIMP device.  It's there, but it's not doing anything.

**Comment by larsbrinkhoff** [comment]
The transmitting from PDP-10 seems to work ok now.  ITS starts off by sending four 1822 NOP packets to the IMP.  They go through the KA IMP interface, to the IMP 1822 interface, and are processed by an emulated NCP software which drops them as per spec.

Next I tried to make an FTP connection.  But I got a BUGHALT.

**Comment by larsbrinkhoff** [comment]
In SYSTEM; INET 139, the call to IMPCTS isn't very successful, because that symbol is undefined.

**Comment by larsbrinkhoff** [comment]
If I NOP out the call and the following JRST, it seems to work.

My emulated IMP sends an ICMP echo request to ITS, and gets a response back, so basic IP networking works.

I have started interfacing with a TUN device.  I should use the SIMH built in Ethernet code, but it seems so complex.

**Comment by larsbrinkhoff** [comment]
I can now telnet from my Linux host to KA ITS.

**Comment by larsbrinkhoff** [comment]
@rcornwell is working on a KA IMP simulation.

**Comment by oilcan-productions** [comment]
I think this can be closed. KA has IMP support for both NAT and TAP at least.

**Comment by larsbrinkhoff** [comment]
Thanks!
