### ISSUE TITLE
Multiplexing

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#701]
There are many separate things called multiplexers in ITS.

- I/O Buss Multiplexer.  Documented in https://github.com/PDP-10/its/blob/master/doc/ITS_Hardware_Memo_1.pdf

   Makes it possible to share devices between a PDP-6 and a PDP-10 connected to the same I/O bus.

   This is implemented as the deselection device, DSDEV.  It's enabled by the DSDP switch.

- Channel 1 multiplexing feature.  Called C1MXP in the source code.

   Makes it possilble for multiple devices to share PI level 1.  The interrupts are handled by locations 62-76 instead of 42.

- Input A/D, and output D/A multiplexors.  IMX and OMX devices.

**Comment by larsbrinkhoff** [comment]
CC @rcornwell.  Does this makes it more clear?  It's not all clear to me. :-)

**Comment by larsbrinkhoff** [comment]
@rcornwell now says the first bullet, I/O bus multiplexer, and the second, PI channel 1 multiplexing are not separate.  I'd like to see more information on this.

**Comment by larsbrinkhoff** [comment]
My plan for IMP support is to implement whatever's needed for C1MXP, but don't do anything for DSDP (deselection device) unless it turns out to be necessary.  This is to make it possible to use the IMP and TM10A at the same time.  At this point, there's no need to coordinate a shared PDP-6/10 bus.

**Comment by larsbrinkhoff** [comment]
Hardware memo # 1 describe the deselection device.  The device code 20 is mentioned.

**Comment by larsbrinkhoff** [comment]
From SYSTEM; IMPOLD WTHNCP:

```
; In particular, the "channel 1 multiplexing" feature of the ITS KA's
; is used, so that:
; When PI level 2 (NETCHN) is assigned, the IMP interface takes
;       all interrupts on the normal channel (goes to IMPINT).
; When PI level 1 (IMPCHN) is assigned,
;       IMPID+(-IMPLIW) => Pseudo channel 4, location 70 (IMPILC)-> various
;       IMPOD => Pseudo channel 5, location 72 (IMPOLC)-> various
;       else normal PI channel 1 (PI0LOC+2)-> IMPBRK

**Comment by larsbrinkhoff** [comment]
From David Moon:
> All our KA10's were modified to have an extra I/O bus cable which added seven additional interrupt levels, each with its own pair of interrupt instructions in locations 62-77. These were all at the same priority level as channel 1 in the standard interrupt levels (highest priority), hence this was called the "channel 1 multiplex feature."

**Comment by rcornwell** [comment]
This is what I worked out from the source. I will have to think on how to implement this.

**Comment by larsbrinkhoff** [comment]
Note that a device can make interrupts through both the normal PI channels, and through the alternative PI channels.  The KA IMP interface does this.

**Comment by larsbrinkhoff** [comment]
AIM-128 descibes SERVO, a program for manipulating the A/D and D/A channels.
