### ISSUE TITLE
SYS; PURQIO has incorrect version number

### ISSUE THREAD

**Issue by eswenson1** [PDP-10/its#704]
SYS; PURQIO >, as currently produced, is SYS; PURQIO 1.  This is actually version 2154.  The file should get renamed to SYS; PURQIO 2154. This will also ensure that the next version dumped will get version 2155.

**Comment by larsbrinkhoff** [comment]
I'm having some second thoughts here.  Wouldn't it be better to get the version number from LISP?  Where does LISP get its version from?

**Comment by ams** [comment]
> is the newest file, if that is version 1 that would that be what is returned?

**Comment by eswenson1** [comment]
I'm not really sure how the lisp naming convention worked -- however, SYS; PURQIO NNNNNN is pdumped from a binary created from L; *LISP NNNNNN.  The current version of this file is 154.  So I suspect 2000 is getting added to this file version number somewhere in the Midas source for Lisp.  I guess we could introspect the version of L; *LISP NNNNNN that is being assembled, add 2000 to that version number, and use that in the FN2 of PURQIO.  Not sure how to do that...

**Comment by eswenson1** [comment]
> IFE OSD10P,[
DEFINE A67IFY A,B,C
A=SIXBIT \C\
B=C
TERMIN
RADIX 10.
ZZ==.FVERS
 ;; Remember, somday cross over to 3000.
IFE .OSMIDAS-<SIXBIT \ITS\>, ZZ==2000.+ZZ
A67IFY LVRNO,LVRNON,\ZZ
RADIX 8
]       ;END OF IFE OSD10P

IFN OSD10P,[
IFNDEF LVRNO,LVRNO=.FNAM2
IFE LVRNO-SIXBIT \MID\,[
PRINTX /What is LISP's version number (type four octal digits) ?/
.TTYMAC VRS
LVRNO=SIXBIT \VRS\
LVRNON=VRS
TERMIN
]
.ELSE,[
LVRNO==<LVRNO_-6>+<SIXBIT \1\>                  ;HACK FOR CROSSING 1000'S
IFN <<LVRNO_-30>&77>-'9, LVRNO==LVRNO+<1_36>    ;HACK FOR CROSSING 2000'S
;;; REMEMBER! SOMEDAY WE MAY HAVE TO CROSS TO 3000'S  - JONL, 9 JUL 1980
LVRNO==0
]               ;END OF IFGE LVRNO
]       ;END OF IFN OSD10P


PRINTX \MACLISP VERSION \       ;PRINT OUT VERSION OF THIS LISP
.TYO6 LVRNO
PRINTX \ ASSEMBLED ON \
.TYO6 .OSMIDAS
PRINTX \ AT \
IFE <.SITE 0>, PRINTX \UNKNOWN SITE\
.ELSE REPEAT 20, IFE <.SITE .RPCNT>,[.ISTOP] .TYO6 <.SITE .RPCNT>
PRINTX \
\                               ;TERPRI TO FINISH VERSION MESSAGE

**Comment by larsbrinkhoff** [comment]
> I guess we could introspect the version of L; *LISP NNNNNN that is being assembled, add 2000 to that version number

I was thinking getting the number from the *LISP file name and add 2000 in TCL.  But of course, that could come out wrong if the Midas source is changed to do some other version number computation.

Oh well, not very important.

**Comment by eswenson1** [comment]
I say we enter a ticket for a better way to come up with the version number and get to it when we have time....
