### ISSUE TITLE
Experimental commits made to master branch

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#709]
I messed up and pushed some commits to master which should have done to an experimental branch.  Sorry!

I'll remove those commits from the history.  To update your local repos:

    git fetch origin
    git checkout master
    echo Warning, next step will delete unsaved data.
    echo Are you sure?  Type "^C" to stop.
    read yes
    git reset --hard origin/master

**Comment by larsbrinkhoff** [comment]
Fixed now.

**Comment by larsbrinkhoff** [comment]
Also this:

    git submodule sync
    git submodule update

**Comment by eswenson1** [comment]
That fixes it. Thanks.
