### ISSUE TITLE
LIBLSP LISP Packages

### ISSUE THREAD

**Issue by eswenson1** [PDP-10/its#713]
There are a bunch of missing LISP packages from the LIBLSP; directory. Here is a list:

- [x] %PRINT FASL
- [x] 6BIT   FASL
- [x] APROPO FASL
- [x] ARITH  FASL
- [x] ARYADR FASL
- [x] ARYFIL FASL
- [x] ASKUSR FASL
- [x] ATAN   FASL
- [x] AUTODF FASL
- [x] BBOOLE FASL
- [x] BENCH  FASL
- [x] BINPRT FASL
- [x] BREAK  FASL
- [x] BS     FASL
- [x] BSSQ   FASL
- [x] CARCDR FASL
- [x] CGPRIN FASL
- [x] CHAR   FASL
- [x] COMRD  FASL
- [x] CPYHNK FASL
- [x] DBG    FASL
- [x] DEBUG  FASL
- [x] DEBUG* FASL
- [x] DEFSTA FASL
- [x] DEFVST FASL
- [x] DOCTOR FASL
- [x] DOW    FASL
- [x] DPRINT FASL
- [x] DRIBBL FASL
- [x] DUMPGC FASL
- [x] FAKE-S
- [x] FASDMP FASL
- [x] FASLRE FASL
- [x] FFORMA FASL
- [x] FFT    FASL
- [x] FILBIT FASL
- [x] FLOAD  FASL
- [x] FONTRD FASL
- [x] FOR    FASL
- [x] FORMAT FASL
- [x] GCDEMN FASL
- [x] GENFNS FASL
- [ ] GETSYN FASL
- [x] GPRINT FASL
- [x] GRAPH$ FASL
- [ ] GRAPH3 FASL
- [x] GRAPHA FASL
- [x] GRAPHS FASL
- [x] GRAPHT FASL
- [ ] HASH   FASL
- [x] HUMBLE FASL
- [x] IMPDEF FASL
- [x] IOTA   FASL
- [ ] ITER   FASL
- [x] LAUGH  FASL
- [x] LCHSTR FASL
- [ ] LEDIT* FASL
- [x] LET    FASL
- [x] LETFEX FASL
- [x] LETS   FASL
- [x] LINERE FASL
- [x] LINK   FASL
- [x] LISPM  FASL
- [x] LISPT  FASL
- [x] LOOP   FASL
- [x] LSCALL FASL
- [x] LSPMAC FASL
- [x] LUSETS FASL
- [x] MACITS FASL
- [x] MORE   FASL
- [x] NSHARE FASL
- [x] OCTAL  FASL
- [x] OPTDEF FASL
- [x] PHASE  FASL
- [x] PHSPRT FASL
- [x] PRIVOB FASL
- [x] PROMPT FASL
- [x] QTRACE FASL
- [x] READS  FASL
- [x] REDO   FASL
- [x] SAVE   FASL
- [x] SETS   FASL
- [x] SHARAB FASL
- [x] SHARE  FASL
- [x] SHARPM FASL
- [x] SIXBIT FASL
- [x] SMURF  FASL
- [x] SPLIT  FASL
- [x] STACK  FASL
- [ ] STACKS FASL
- [x] STATTY FASL
- [x] STEPMM FASL
- [x] STEPR  FASL
- [x] STRING FASL
- [x] STRUCT FASL
- [x] SUN    FASL
- [x] TIME   FASL
- [ ] TIMER  FASL
- [x] TRAP   FASL
- [x] TTY    FASL
- [x] TTYHAK FASL
- [x] WIFS   FASL
- [x] WINDOW FASL

**Comment by larsbrinkhoff** [comment]
BINPRT looks interesting.

**Comment by larsbrinkhoff** [comment]
I checked COMRD and STRUCT.

**Comment by eswenson1** [comment]
LIBDOC; %PRINT GROSS2 will no longer compile due to changes in the interpretation of "defun macro xxx".  I'll commit a LIBDOC; %PRINT EJS3 that uses defmacro instead of this old syntax.

**Comment by eswenson1** [comment]
LIBDOC; ASKUSR PSZ1 no longer compiles. The (newio t) within the declare special form causes the compiler to barf.  Also, this file depends on MACRODEF, which appears to have been defined in GLS; MACROS >, which we don't yet have.  I used a version of MACRODEF defined in LIBDOC; SET IRA1, loaded into the compiler, and was able to get a modified version of ASKUSR to compile.  The modification is to comment out the (newio t) within the declare.

**Comment by eswenson1** [comment]
I don't think all of these are done yet.

**Comment by eswenson1** [comment]
Removed "MACRO FASL from the list since ticket #750 covers this missing source.

**Comment by eswenson1** [comment]
Removed DIDL FASL from the list since ticket #751 covers this package.

**Comment by eswenson1** [comment]
Removed DIRSIZ FASL from the list since ticket #751 covers this package.

**Comment by eswenson1** [comment]
Removed LDDT FASL from the list since ticket #753 covers this package.

**Comment by eswenson1** [comment]
Removed NDONE FASL from the list since ticket #728 covers this package

**Comment by eswenson1** [comment]
Removing PLOT and PLOT3 since these are covered by ticket #729.

**Comment by eswenson1** [comment]
Removing PRIME from the list since it is covered by ticket #730

**Comment by eswenson1** [comment]
Removed RDTAGS from the list since the new ticket #754 covers this file.

**Comment by eswenson1** [comment]
Removing STEP from the list since ticket #755 covers this package.

**Comment by eswenson1** [comment]
Removed TTYVAR from the list as ticket #756 covers this package and there are issues that need to be resolved.

**Comment by eswenson1** [comment]
Removed UTILS from the list as ticket #757 covers this package and this currently doesn't compile.

**Comment by eswenson1** [comment]
Removed VSAID from the list since ticket #758 covers this package and the source for this currently doesn't compile.
