### ISSUE TITLE
Datapoint

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#721]
ITS 768 only had Datapoint and Imlac smart terminals.

**Comment by larsbrinkhoff** [comment]
Control codes used by ITS:

- 10 - backspace / move left
- 12 - linefeed / move down
- 30 - forward space
- 32 - move up
- 34 - home down
- 35 - home up
- 36 - clear eol
- 37 - clear eof

**Comment by larsbrinkhoff** [comment]
2.11BSD termcap entry for Datapoint 3360:

    :do=^J:am:le=^H:bs:cd=^_:ce=^^:cl=^]^_:co#82:ho=^]:li#25:nd=^x:up=^z:

**Comment by larsbrinkhoff** [comment]
Datapoint 3300, supposedly at MIT.
![dp3300](https://user-images.githubusercontent.com/775050/51766097-f8763800-20d9-11e9-9385-e9fdea0ad40d.png)

**Comment by aap** [comment]
But it says CONTROL DATA on the left.

**Comment by larsbrinkhoff** [comment]
My mistake.  Maybe this one?
![dp3300](https://user-images.githubusercontent.com/775050/52415498-66adf800-2ae7-11e9-912d-6ef6fc116a2a.jpg)

**Comment by larsbrinkhoff** [comment]
Similar CONTROL DATA terminal?  Used with TORTIS.

![](https://raw.githubusercontent.com/walterbender/logothings/master/images/radia1a.jpg)
![](https://raw.githubusercontent.com/walterbender/logothings/master/images/radia2.jpg)

**Comment by larsbrinkhoff** [comment]
PHW and maybe Datapoint?  From https://people.csail.mit.edu/bkph/phw_copy_demo.shtml
![Patrick_Winston_4](https://user-images.githubusercontent.com/775050/87188355-fc5a4200-c2ee-11ea-8092-2ac633cfa76c.jpg)

**Comment by larsbrinkhoff** [comment]
Photos from a Portugese seller.  It's a HP 2600A which is an OEM Datapoint 3300.

![hp2600a-1](https://user-images.githubusercontent.com/775050/94546350-0afd2900-024e-11eb-8fba-e069cda8be3a.jpg)
![hp2600a-2](https://user-images.githubusercontent.com/775050/94546394-1d776280-024e-11eb-9742-057770e2bce4.jpg)
![hp2600a-3](https://user-images.githubusercontent.com/775050/94546402-1f412600-024e-11eb-9096-73c791419b46.jpg)
![hp2600a-4](https://user-images.githubusercontent.com/775050/94546412-22d4ad00-024e-11eb-8dea-e505ec9bb8e3.jpg)
![hp2600a-5](https://user-images.githubusercontent.com/775050/94546421-25cf9d80-024e-11eb-82b6-42c221439bb9.jpg)
![hp2600a-6](https://user-images.githubusercontent.com/775050/94546426-2831f780-024e-11eb-85a0-66e693bda17e.jpg)
![hp2600a-7](https://user-images.githubusercontent.com/775050/94546435-2a945180-024e-11eb-969c-402228e30710.jpg)
