### ISSUE TITLE
How to install KL ITS?

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#744]
We don't have any instructions for installing KL ITS.  Maybe some frontend magic is required similar to running KSFEDR for KS ITS.

**Comment by larsbrinkhoff** [comment]
From AI WP 227:

Cool Booting

- Ensure disks are mounted.
- Make sure ENABLE switch is pushed in.
- Push the DISK button.  Get `DECSYSTEM10 DIAGNOSTIC CONSOLE`
- Type `RP0`.
- Type `J KLINIT`
- ...
- Type `J NTSDDT`
- Reload the IO-11 by typing `$L .; BOOT11`, then `$G`.

**Comment by larsbrinkhoff** [comment]
KLDCP; FEDUMP 10 is a standalone program which does something with the frontend file system.

**Comment by larsbrinkhoff** [comment]
Note above that NTSDDT is loaded, which then can read files from disk.  So there's no DSKDMP.

David Moon posted this to ITS-LOVERS about cold booting ITS:
> The procedure varied depending on the type of machine.  You're probably most interested in the KS10 procedure, but that's the one I remember least well.  In general, if starting from a totally cold machine but with good disk contents, one loaded a bootstrap from paper tape, magnetic tape, or disk depending on the type of machine (using read-in mode on a KA) [on a pdp-6 the bootstrap actually had to be keyed in from switches in the unlikely event that it had been wiped out of core memory].  The bootstrap loaded microcode (if a microcoded machine), then loaded a non-timesharing program (DSKDMP on some machines, exec DDT with file system capability on others), which could then be used to load an SBLK file containing a core image of ITS, SALV, and NTSDDT (exec DDT). Starting that program ($G in exec DDT, otherwise just pressing return) would run SALV to verify and repair the file system, then start ITS.  If one didn't want to run time sharing one went into exec DDT first and patched one or two locations to control what should happen when ITS came up.  You never start ITS without running SALV first, since it only takes a minute or less due to the small, compact, and simple file system (which I did NOT write in a weekend or any other length of time).

Note "exec DDT with file system capability".

**Comment by larsbrinkhoff** [comment]
Indeed there was a KL frontend file system tool: KLFEDR, #771.

And a .KLFE. directory related to this file system.

**Comment by larsbrinkhoff** [comment]
UCODE; UCODE INFO has some information about installing microcode.

After assembling, use UCNVRT to make an "asciized" microcode.  Then put that file on the front end filesystem using `:KLFEDR WRITE <file>`.

**Comment by larsbrinkhoff** [comment]
More about the front end filesystem:

>  there does seem to be this file KLDCP (DIR) which macgically contains the actual blocks of the RSX-11 directory.

Note, I think the MC front end ran a severely hacked KLDCP (KL diagnostics console program), not RSX-11 (or RSX-20).

**Comment by larsbrinkhoff** [comment]
> We don't use the RSX-11 file system, we use the KLDCP file system which DEC later flushed..  Also the front-end files aren't in any one place on the disk, but are scattered all over.  Some of them, especially the larger ones, reside in individual ITS files, others are pieces portions of an ITS file.  And if you move or delete anything on the .KLFE. directory you screw it up since somewhere there is a KLDCP directory containing absolute disk addresses.

**Comment by larsbrinkhoff** [comment]
From KLFEDR 83.

```
;ON DISK, SECTORS 1 AND 10 DECIMAL
;ARE "HOME BLOCKS" WHICH CONTAIN PHYSICAL DISK ADDRESS AND NUMBER
;OF SECTORS OF THE DIRECTORY.  HOME BLOCKS AND DIR HAVE TO BE
;SET UP BY HAND.  THE DIRECTORY IS A FILE IN THE ITS FILE SYSTEM.
;SECTOR 0 CONTAINS A BOOT PROGRAM WHICH IS READ IN BY THE BOOT ROM
;WHEN THE DISK BUTTON IS PUSHED.  IT'S A PDP-11 PROGRAM.  IT READS
;IN THE "PRIMARY BOOTSTRAP" FROM A DISK ADDRESS HARD-WIRED INTO IT.
;THE PRIMARY BOOTSTRAP FINDS KLDCP IN THE DIRECTORY AND RUNS IT.
;TO CHANGE THE DISK SIZE, YOU MUST CHANGE SEVERAL ADDRESSES IN THE
;HOME BLOCKS AND IN THE SECTOR 0 BOOT PROGRAM.  OF COURSE YOU MUST
;ALSO CHANGE SEVERAL PDP10 PROGRAMS.

;THE FILE KLDCP;HOME BLOCKS CONTAINS A COPY OF SECTORS 0-15. OF THE DISK.
;THE FILE KLDCP;PRIMRY BOOT CONTAINS A COPY OF THE PRIMARY BOOTSTRAP.
;THESE ARE JUST REFERENCE COPIES, THEY AREN'T STORED IN THE ACTUAL
;SPECIAL DISK ADDRESSES WHERE THOSE THINGS GO.

;THERE IS ALSO AN INDEX FILE AND A BIT MAP, WHICH WE DON'T USE.
;THEY ARE SET UP TO BE UP IN THE MAINTENANCE CYLINDERS SOMEPLACE,
;TO MAKE KLDCP HAPPY, ALTHOUGH IT DOESN'T USE THEM EITHER.
;ALSO, THE FIRST 6 SECTORS OF CYLINDER 406 (DECIMAL)
;CONTAIN THE "PRIMARY BOOTSTRAP."  THIS HAS TO BE SET UP BY HAND.

;ALLOCATION OF CYLINDERS ON AN RP04:
;     0-405. ITS FILE SYSTEM
;       406. PRIMARY BOOTSTRAP, KLDCP NOT-USED FILES
;       407. DSKDMP BOOT AND SWAP AREA
;       408. NOT USED
;       409. NOT USED
;       410. DDT BOOT AND SWAP AREA

;FORMAT OF SECTOR 0:
; ONE PDP-11 WORD PER PDP-10 HALFWORD
; RH(20) IS THE CYLINDER NUMBER OF THE PRIMARY BOOTSTRAP
; IT'S ON HEAD 0, SECTORS 0-4

; INDEX FILE OFFSETS - IN PDP-10 HOME BLOCK

**Comment by larsbrinkhoff** [comment]
The KL10 had two PDP-11s attached.  The primary front end with Chaosnet and other peripherals, and another attached over DL10 running disks.

The code for these is assembled with PALX.  There are various pieces, and I'm not sure how they fit together:
- SYSTEM; IOELEV >
- SYSENG; KLRUG >
- KLDCP; 11DDT >
- KLDCP; KLDCP > (main entry point)

Probably, the primary IO-11 should have both KLDCP and IOELEV, and maybe 11DDT.  These should be linked together with 11STNK.  Note that 11DDT should be assembled for the correct memory size, which maybe is 28K.

Maybe the axiliary should have just IOELEV and 11DDT (16K?).  That leaves KLRUG; what was it used for?  11STNK has special commands for 11DDT and KLRUG.

(For the AI PDP-11, I think it's just IOELEV.)

The linked binary should then be converted with PCNVRT.  The resulting A11 file should be put in the front end filesystem.

**Comment by larsbrinkhoff** [comment]
Oops, wait a minute.  I found this:

```
TITLE 11BOOT - BOOT I/O 11 ON KL10

;LOADS DSK:KLRUG BIN AND DSK:IOELEV BIN, GIVES SYMBOLS TO RUG, AND
;MAKES DSK:@ BOOT11 WHICH IS TO BE PUT ON THE MAGDMP TAPE.

**Comment by larsbrinkhoff** [comment]
```
;IOELEVEN RESIDES IN THE BOTTOM 14K OF THE CONSOLE PDP11, ALONG WITH 11DDT.
;I.E. LOCATIONS 0-70000.  BE SURE TO USE .;11DDT 14K VERSION OF DDT.
;THE UPPER 14K CONTAIN KLDCP.

**Comment by larsbrinkhoff** [comment]
11STNK can write a standalone PDP-10 program which loads a PDP-10 through DL10.

It can also load the code in timesharing.

**Comment by larsbrinkhoff** [comment]
There's a PDP-11 DSKDMP with a command E which does "Initialize a disk to DOS format."  But KLDCP, KLFEDR, or FEDUMP doesn't say "DOS" anywhere so I'm not at all sure that's the KLDCP filesystem format.

**Comment by eswenson1** [comment]
I wonder if KLH has any interest in doing a KL10 emulator?  :-)

**Comment by larsbrinkhoff** [comment]
KLH10 does have a KL10 model B mode.  But ITS needs a model A, and special microcode on top of that.

**Comment by larsbrinkhoff** [comment]
Probably a 1080 with RH10.  Kind of an odd duckling, isn't it?

**Comment by eswenson1** [comment]
It looks like the KL10-A and KL10-B were quite similar with the B having more microcode memory than an A and having RH20 internal channels where the A didn't.  How much work would it be to get ITS to run on a KL10-B?  Do we have the microcode that ITS needs for an "A"?  Would it work on a B or would it work with some conversion?  Or, how much effort would be involved in making KLH10 support a model A?

**Comment by larsbrinkhoff** [comment]
Yes, we do have the ITS microcode.  I recently added the source and assembler, and it does assemble cleanly.

I think there may be microengine differences other than the size of the store.  E.g. there's a conditional in the sources where model A needs some contortions to make a call but model B has a nice call microinstruction.  I'd expect handing of memory addresses and paging to have some differences since model B supports extended addressing.

Maybe much of the effort making ITS run on a model B might be adding support for RH20.

Conversely, running KL ITS on KLH10 would need adding RH10.  And of course all the microcode tweaks would have to be grafted onto the CPU emulation.  Probably paging is the biggest hurdle.

**Comment by larsbrinkhoff** [comment]
I see many .; CONS11 BINnnn files, and I think that's the console IOELEV.  I.e. the amalgam of IOELEV, 11DDT, and KLDCP.

**Comment by rmaldersoniii** [comment]
There are a lot of differences beyond the size of the microcode between the A and B varieties of the KL-10. This can be observed by running the A diagnostics on a B machine (from personal, painful, experience).
As for KLDCP, WAITS also uses a hacked variant of KLDCP which even handles the Xerox PDP-11 Ethernet interface and a TOY clock.

**Comment by larsbrinkhoff** [comment]
@rmaldersoniii, did you make a WAITS front end file system from scratch?  If KL ITS were to be resurrected, that's one crucial thing I dont' know how to do.

**Comment by rmaldersoniii** [comment]
@larsbrinkhoff WAITS never used a front end file system on disk. The system was always booted from DECtape. (I suspect that MC was the same way, since it is a 1080.) What we had to do was connect an ugly, magenta+purple PDP-11 rack with TU56s to the 1095, and cable it to a TC11 in the 1095's front end.
I did, of course, create a WAITS file system by hand, which was an adventure in itself, since there was never any such thing as a "WAITS install tape"!

**Comment by eswenson1** [comment]
I’m pretty sure we booted MC from the front end file system and not from tape. I think there are even extant instruction around that describe how to do this.

**Comment by larsbrinkhoff** [comment]
Thanks @rmaldersoniii, I suppose we're on our own creating the front end file system.

@eswenson1, the second comment in this issue details how MC was booted from disk.

**Comment by rmaldersoniii** [comment]
A further wrinkle in the WAITS saga: I cannot boot the system from DECtape, and I have not figured out how to debug the issue. There are 2 commands in Stanford KLDCP which accomplish monitor loading and startup. The first command loads a bootstrap program into the -10 memory, the other tells it which monitor version (by extension: SAV, NEW, OLD, or DBG) to load into -10 memory from the disk. ???
So to boot WAITS, I use RSX-20F, the Tops-10 BOOT program, a Tops-10 format RP06 (image on the MDE), the RSX BOO program, and Stanford KLDCP from the same disk: Boot the -11 into KLINIT and let that start BOOT, _**WAITS/L**_, ^\ to get to the parser, _**HALT**_, _**MCR BOO**_, and boot the DBOOT.SYS file to load and start KLDCP.
It's more of a crock than it sounds. I'd like to get the real boot method working someday.

**Comment by larsbrinkhoff** [comment]
@tlhackque wrote something interesting to the SIMH mailing list:

> For -10 comm front ends, a bit in the -10 interface (DL10 or DTE20) causes the M93xx (or other) ROM to assert AC LO on the Unibus, allowing the host to gain control of the -11 for load or dump.
> 
> Any emulation of these (and there's been recent discussion of it) would need an equivalent mechanism.
> 
> If a ROM device emulation provided an API for this feature, that cause would be advanced. 
> 
> There are two parts to making it work: 
> 
> Adding an API in the CPU of the form assert_powerfail( vector) - where the default is the usual 24/26, but a ROM can specify an alternate (usually its base address + 24/26). This is common to all initiators.
> 
> Getting the ROM, host interface, or network device to call it (or expose a suitable API) to gain control of the CPU. This varies by device.
> 
> For the -11, the existing boot snippets could be migrated to set the switches & use the "real" ROMs, though as you point out, this is not necessary.  Originally, it seemed simpler to extract (or recreate) small fragments from the boot ROMs than to find emulate all the ROM variants. But SimH & its community has grown, and with current demands, moving to a more faithful emulation would be appropriate. There's no rush - it can evolve. But if the GT40 (and somewhere on my list, ANF-10 network, plus the attempts at KA/KI/KL) emulation provide the mechanism, in the long run it would be a better emulation.

**Comment by larsbrinkhoff** [comment]
Comment in KLFEDR explains a bit about the front end file system, and how the front end boots from disk.  Apparently there's a boot ROM.  And a "primary boostrap" program on disk, which then starts KLDCP.

```
;ON DISK, SECTORS 1 AND 10 DECIMAL
;ARE "HOME BLOCKS" WHICH CONTAIN PHYSICAL DISK ADDRESS AND NUMBER
;OF SECTORS OF THE DIRECTORY.  HOME BLOCKS AND DIR HAVE TO BE
;SET UP BY HAND.  THE DIRECTORY IS A FILE IN THE ITS FILE SYSTEM.
;SECTOR 0 CONTAINS A BOOT PROGRAM WHICH IS READ IN BY THE BOOT ROM
;WHEN THE DISK BUTTON IS PUSHED.  IT'S A PDP-11 PROGRAM.  IT READS
;IN THE "PRIMARY BOOTSTRAP" FROM A DISK ADDRESS HARD-WIRED INTO IT.
;THE PRIMARY BOOTSTRAP FINDS KLDCP IN THE DIRECTORY AND RUNS IT.
;TO CHANGE THE DISK SIZE, YOU MUST CHANGE SEVERAL ADDRESSES IN THE
;HOME BLOCKS AND IN THE SECTOR 0 BOOT PROGRAM.  OF COURSE YOU MUST
;ALSO CHANGE SEVERAL PDP10 PROGRAMS.

;THE FILE KLDCP;HOME BLOCKS CONTAINS A COPY OF SECTORS 0-15. OF THE DISK.
;THE FILE KLDCP;PRIMRY BOOT CONTAINS A COPY OF THE PRIMARY BOOTSTRAP.
;THESE ARE JUST REFERENCE COPIES, THEY AREN'T STORED IN THE ACTUAL
;SPECIAL DISK ADDRESSES WHERE THOSE THINGS GO.

;THERE IS ALSO AN INDEX FILE AND A BIT MAP, WHICH WE DON'T USE.
;THEY ARE SET UP TO BE UP IN THE MAINTENANCE CYLINDERS SOMEPLACE,
;TO MAKE KLDCP HAPPY, ALTHOUGH IT DOESN'T USE THEM EITHER.
;ALSO, THE FIRST 6 SECTORS OF CYLINDER 406 (DECIMAL)
;CONTAIN THE "PRIMARY BOOTSTRAP."  THIS HAS TO BE SET UP BY HAND.

;ALLOCATION OF CYLINDERS ON AN RP04:
;     0-405. ITS FILE SYSTEM
;       406. PRIMARY BOOTSTRAP, KLDCP NOT-USED FILES
;       407. DSKDMP BOOT AND SWAP AREA
;       408. NOT USED
;       409. NOT USED
;       410. DDT BOOT AND SWAP AREA

;FORMAT OF SECTOR 0:
; ONE PDP-11 WORD PER PDP-10 HALFWORD
; RH(20) IS THE CYLINDER NUMBER OF THE PRIMARY BOOTSTRAP
; IT'S ON HEAD 0, SECTORS 0-4

**Comment by larsbrinkhoff** [comment]
We have a copy of HOME BLOCKS and PRIMRY BOOT, so we should be able to make a bootable disk image.  However, we don't have the directory file.  Maybe it could be manufactured from information about the directory format.

Or, it would be possible to cheat by loading KLDCP directly.  It does run in 11SIM, see #974.  We'd still need a working front end file system.

**Comment by larsbrinkhoff** [comment]
Alderson posted the front end bootstrap ROM to #375.

**Comment by larsbrinkhoff** [comment]
We now also have a copy of .KLFE.; KLDCP (DIR)

**Comment by larsbrinkhoff** [comment]
I have verified that the two copies of the home block inside HOME BLOCKS are identical, and have plausibly OK contents.  Sector 0 has something that could be PDP-11 code.  There are 15 sectors as documented.

**Comment by larsbrinkhoff** [comment]
The ENABLE and DISK switches mentioned above.
![kl10-enable](https://user-images.githubusercontent.com/775050/57797917-cdc4f380-774b-11e9-8ab5-be2aaa093bb8.jpg)

**Comment by larsbrinkhoff** [comment]
Information not to be trusted.  Alan Bawden says the red handwriting is his.

The last photo is blurry.  The printed text is from MAINT; DDMMG SWITCH

![kl-mem1](https://user-images.githubusercontent.com/775050/57798120-4cba2c00-774c-11e9-8855-8bd195172ca9.jpg)
![kl-mem2](https://user-images.githubusercontent.com/775050/57798131-52b00d00-774c-11e9-9518-1ebe47552cb3.jpg)
![kl-mem3](https://user-images.githubusercontent.com/775050/57798141-593e8480-774c-11e9-8d89-f545e9eec559.jpg)

**Comment by larsbrinkhoff** [comment]
I'm closing this.

New development will happen here: #1632

**Comment by larsbrinkhoff** [comment]
Still adding new info though...

```
After it types "ITS NOT IN OPERATION" the lights on the memories will
blink for a while, then the system console will type a carriage return.
You are now in exec DDT.  Hitting break then control-C will get you to KLDCP.
```

**Comment by larsbrinkhoff** [comment]
Reformatted from PUB.


COLD BOOT PROCEDURE

This procedure is to be used to restart ITS after running diagnostics or the DEC system, after a power failure, or after the warm boot procedure has been tried and found wanting.

Make plenty damn sure the right disks are mounted.  Currently "ITS PK0 #0 + KLDCP" should be on unit 0, not write-protected, "ITS PK1 #1" should be on unit 1, not write-protected, and "ITS SECONDARY PACK #13" should be on unit 2, not write-protected.

If there was a power failure, some circuit breakers may need to be reset.  Push stop on disk unit 0, wait until it stops spinning, then open the back and turn "CB1" (lower right corner) off and on.  Then push start.  If there are no lights lit on the disk DF10C (second box from the left on the right-hand side), open its rear door and reset the white circuit breaker near the bottom of the inside of the door.  Check the *fault* light on the KL10.  If it is on, open the rear door of the right-hand KL10 cabinet and check the fault lights on the power control.  (Column of LED's near the bottom of the cabinet.)

Push the DISK button on the KL10, to reload KLDCP.  If it doesn't work, check the top of the ENABLE switch is pushed in.  If this fails, try doing the preceding paragraph.  If it wins, "DECSYSTEM10 DIAGNOSTIC CONSOLE" will be typed out on the system console.

Type RP0 \<return>.

Type J \<space> KLINIT \<return>.  Wait for a \<greater than> \<period> prompt.  (Several lines will be typed out first.)  If a "2-way interleave" note is on the console, use KLINI2 instead of KLINIT.

If, while running KLINIT you get a message such as ?10 ERR ADR=nn COR=nn ACT=nn there is probably a failing memory.  Get help.

Type J \<space> NTSDDT \<return>.  If this responds with I NTSDDT <return> <return>, then you are winning and exec ddt is now running.  Otherwise, get a system hacker.

Reload the I/O pdp11 by typing \<altmode> L BOOT11 <return>, wait for blank line, type <altmode> G, wait for blank line.  If you get file not found (FNF), try \<altmode> L \<period> \<semicolon> BOOT11 \<return>.

Continue with the warm boot procedure.

WARM BOOT PROCEDURE

Type \<altmode> L *sys* <return>, where *sys* is the name of the current system, which will be found on a punch card on the LA36.  Type \<altmode> G.  It should reply "SALVAGER.nnn", then after a half minute it should say "ITS IN OPERATION".  If it says "*** ERROR SYSTEM MAY NOT BE BROUGHT UP ***", or any other ominous error message, do not attempt to do anything further.  Get a system hacker.

If it types "ITS IN OPERATION" but then doesn't seem to do anything further, you may need to reload the I/O pdp11.  See the Cold Boot procedure.
```

**Comment by larsbrinkhoff** [comment]
If MAGDMP is useful to bootstrap ITS on a clean machine:

```
;On KL10, load with a J MAGDMP command to KLDCP,
;which does the following:
;
;Reset KL10 and start microcode
;Set EPT location to ITS standard (currently 2000)
;Turn OFF the cache
;Load the following into memory:
;100/ 763760777176      ;DF10-C command for locs 777177-777777
;101/ 0
;102/ 734540000107      ;DATAO MTS,107          ;SET ICWA
;103/ 734200072200      ;CONO MTC,072200        ;READ CONTIN, ODD PAR, 800 BPI, CORE DUMP
;104/ 734740000100      ;CONSO MTS,100          ;AWAIT JOB DONE
;105/ 254000000104      ;JRST .-1
;106/ 254000777200      ;JRST 777200            ;JUMP TO MAGDMP
;107/ 100               ;ICWA
;START AT 102
```

This is a comment from MAGDMP.

**Comment by larsbrinkhoff** [comment]
A 1983 directory listing from @cstacy's unpublished AI memo 694:

```
 MC .  FREE BLOCKS #0=686 #1=1505 #13=1076 #15=1757 #14=1619 #16=1514
  1   11DDT  14K    11   4/13/77 04:29:53
  1   11DDT  16K    11   3/31/76 19:24:26
  1   11DDT  28K    11   12/23/75 16:09:39
  0   @      BOOT11 9   1/6/82 02:45:17
  1   @      DDT    5   9/6/79 01:09:00
  L   @      FEDUMP KLDCP FEDUMP BIN
  0   @      ITS    59   11/9/82 07:05:31
  0   @      NITS   59   8/14/82 00:00:00
  0   @      SALV   8   12/8/79 04:08:08
  1   DSKDMP BIN.AI 2   9/13/79 21:54:10
  1   IOELEV 407BIN 8   5/20/81 22:26:03
  0   IOELEV 410BIN 8   1/6/82 02:34:54
  L   IOELEV BIN    . IOELEV 410BIN
  0   ITS    BIN    58   11/9/82 06:54:40
  0   NITS   BIN    58   8/14/82 04:23:23
  1   SALV   297BIN 8   12/13/80 23:36:26
  L   SALV   BIN    . SALV 294BIN
  L   TS     BOOT11 MOON TS 11STNK
```

I suppose we should try to get close to this.  I wonder why so many 11DDT versions are needed?  Sometimes there's also a CONS11 BIN.
