### ISSUE TITLE
NGAME - Game selection frontend

### ISSUE THREAD

**Issue by atsampson** [PDP-10/its#787]
No binary or source, but GAME is in the list of game programs that JOBS knows about, and there's a 1980 post from @eswenson1 in ITS OBUGS0:

> I'm getting tired of people telling me that the GAME program bites the royal... because of the system load restrictions (determined from the system Fair Share and the number of users).

So was GAME a frontend that only let you play a game if the load was sufficiently low? Does the source still exist?

Are the dot-prefixed names that JOBS knows (.CHESS, .WUMP, .JOTTO etc.) the programs that GAME could launch?

**Comment by eswenson1** [comment]
Yes, GAME was an original game frontend we developed for MC (probably for all ITS systems).  It was replaced by NGAME (enhanced version).  The source was in EJS; NGAME 271, and i have that source.  I believe I or Lars created a ticket to get TS NGAME installed.  NGAME imposed all sorts of restrictions and allowed access to a bunch of games.  This is the list, I believe:

> A -- Adventure II	           M -- Adventure I.V
B -- Baisley's Chess Program	   N -- Nimlin
C -- Greenblatt's Chess Program	   O -- Othello
D -- Doctor			   P -- KMP's Psychiatrist
E -- Chase (W. Kornfeld's)	   Q -- Qubic
F -- Backgammon			   S -- Star Trek
G -- Go				   T -- Stone (for displays only)
J -- Jotto			   U -- Sprouts
K -- Animal II			   W -- Wumpus
L -- Limerick			   X -- Wumpus Advisor
. -- Think			   Y -- Yahtzee
7 -- Guess!			   Z -- Zork!
^A -- Lists games available
^C -- Lists program commands

**Comment by atsampson** [comment]
Cool - thanks very much! That list seems to correspond to the dot-prefixed names in JOBS.

NGAME was mentioned in the discussion about ADVENT in #167, but I don't think there's another ticket for it, so I'll add it to the title here. It sounds like it'd be nice to have in the distribution now that we've got some of these games available.

**Comment by larsbrinkhoff** [comment]
I don't see an NGAME issue, actually.

I want option Z! :-)

**Comment by eswenson1** [comment]
That just ran the dummy zork app that Told you (in a humorous way) that it was the wrong machine. Not the ! after Zork.

**Comment by eswenson1** [comment]
Ok. You can assign to me.

-- Eric

**Comment by eswenson1** [comment]
I have the source for NGAME, have assembled and patched it to get it to run. I'm locating all the games that were accessible from this frontend and once I have them and can build them (or provide binaries) I'll commit NGAME and related files.  I've successfully played a bunch of the games but there are few still missing.

**Comment by atsampson** [comment]
That's great! If there's anything I can help with then please let me know.

**Comment by eswenson1** [comment]
Ok, I now have ngame able to run all games that I have installed, including the 448 point adventure, the 350 point adventure, and star trek.  Now, I just need to get all the games built from source (if possible) or included as binaries in the build and then I'll commit ngame.

**Comment by larsbrinkhoff** [comment]
I see the two chess programs in the list.  I suppose the binaries shoud move from GAMES to BMT1.

By the way, who or what is BMT?

**Comment by eswenson1** [comment]
#907
