### ISSUE TITLE
JOTTO - Word game

### ISSUE THREAD

**Issue by atsampson** [PDP-10/its#789]
In the list of games in JOBS.

MC:SYS1;TS JOTTO

No assembly information. But SAILDART has nearly the same program, with FAIL source and a larger external dictionary:

https://www.saildart.org/JOTTO[CSP,SYS]
https://www.saildart.org/JOTTO.DIC[CSP,SYS]

It looks like it could be easily reconstructed from that if we don't have the ITS source.

**Comment by larsbrinkhoff** [comment]
Another idea: Use a file name translation from UTn: to DSK:

**Comment by larsbrinkhoff** [comment]
Oops, wrong issue.
