### ISSUE TITLE
Problem running SUDS

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#792]
I haven't been able to make SUDS use the 340 display.  When I try, DECUUO calls .DSTART but shortly after there's a %PIDIS interrupt which I belive indicates there was something wrong with the data passed to .DSTART.

@ams, have you made any attempt to run SUDS?

**Comment by larsbrinkhoff** [comment]
To run SUDS, use

    :dec draw;d /iii/meta

`/iii` means emulate the SAIL Triple-I display system.  `/meta` means emulate the SAIL bucky bits.

**Comment by larsbrinkhoff** [comment]
When running SUDS as per above, you'll get a DDT message like:

    DPY; LODHGH+1>>.CALL LODOPN (OPEN)

This means DECUUO was stopped because there's an unhandled DPY = %PIDIS interrupt.

**Comment by larsbrinkhoff** [comment]
SRCY1C+12 jumps to SRCY2B which jumps to DISLOS.  DISLOS is what sets the %PIDIS interrupt bit in the job.

**Comment by larsbrinkhoff** [comment]
@philbudne, I `set dpy debug` and got this?  Can you see what's going on, or why there is an interrupt ITS doesn't like?

```
DBG(628543930)> DPY DEBTAB_ISNULL: DPY  132 CONI PC=102374 400000000200^M
DBG(628543981)> DPY DEBTAB_ISNULL: DPY 133 CONO 000000 PC=102252 000200^M
DBG(628546879)> DPY DEBTAB_ISNULL: DPY 133 CONO 005146 PC=002527 000246^M
DBG(628549749)> DPY DEBTAB_ISNULL: DPY 131 DATO 000000003000 PC=106311^M
DBG(628549768)> DPY DEBTAB_ISNULL: DPY  132 CONI PC=101437 400000000646^M
DBG(628549774)> DPY DEBTAB_ISNULL: DPY  132 CONI PC=101442 400000000646^M
DBG(628549801)> DPY DEBTAB_ISNULL: DPY  132 CONI PC=101533 400000000646^M
DBG(628549808)> DPY DEBTAB_ISNULL: DPY  132 CONI PC=101537 400000000646^M
DBG(628549858)> DPY DEBTAB_ISNULL: DPY 133 CONO 000146 PC=102024 000246^M
DBG(628552666)> DPY DEBTAB_ISNULL: DPY 131 DATO 000000034137 PC=106226^M
DBG(628552674)> DPY DEBTAB_ISNULL: DPY 131 DATO 221700060000 PC=106226^M
DBG(628552682)> DPY DEBTAB_ISNULL: DPY 131 DATO 403737403737 PC=106226^M
DBG(628552701)> DPY DEBTAB_ISNULL: DPY  132 CONI PC=101437 400000000646^M
DBG(628552707)> DPY DEBTAB_ISNULL: DPY  132 CONI PC=101442 400000000646^M
DBG(628552734)> DPY DEBTAB_ISNULL: DPY  132 CONI PC=101533 400000000646^M
DBG(628552741)> DPY DEBTAB_ISNULL: DPY  132 CONI PC=101537 400000000646^M
DBG(628552793)> DPY DEBTAB_ISNULL: DPY 133 CONO 000100 PC=102040 000200^M
DBG(628589251)> DPY DEBTAB_ISNULL: DPY 133 CONO 000000 PC=102252 000200^M
DBG(628592044)> DPY DEBTAB_ISNULL: DPY  132 CONI PC=102374 400000000200^M
DBG(628592843)> DPY DEBTAB_ISNULL: DPY 133 CONO 000000 PC=102252 000200^M
DBG(628593402)> DPY DEBTAB_ISNULL: DPY 133 CONO 000000 PC=102210 000200^M
DBG(628593452)> DPY DEBTAB_ISNULL: DPY 133 CONO 005146 PC=002527 000246^M
DBG(628596095)> DPY DEBTAB_ISNULL: DPY 131 DATO 000000003000 PC=013733^M
DBG(628596114)> DPY DEBTAB_ISNULL: DPY  132 CONI PC=101437 400000000646^M
DBG(628596120)> DPY DEBTAB_ISNULL: DPY  132 CONI PC=101442 400000000646^M
DBG(628596147)> DPY DEBTAB_ISNULL: DPY  132 CONI PC=101533 400000000646^M
DBG(628596154)> DPY DEBTAB_ISNULL: DPY  132 CONI PC=101537 400000000646^M
DBG(628596465)> DPY DEBTAB_ISNULL: DPY 133 CONO 000146 PC=102157 000246^M
DBG(628596544)> DPY DEBTAB_ISNULL: DPY 133 CONO 000100 PC=102040 000200^M
DPY; 750576>>POPJ 7,

**Comment by philbudne** [comment]
No thoughts off hand.... My offhand guess from glancing at the code is that:
        SUBI E,N340PB
        JUMPG E,SRCY2B  ;CANT MAKE IT IN ONE WHACK
means the supplied display list won't fit in the (ten) page window of exec memory?!

I'd be curious to know the value of register E at SRCY2B, and whether increasing N340PB by that much gets you any further...

**Comment by larsbrinkhoff** [comment]
I took a look at the argument passed to .DSTART.  It's DLVIS, which points to a word which points to a BLKO pointer with three words.  These words are the display list.  But it doesn't resemble the DATAOs to the display.

```
DLVIS/   DLPP,,0
DLPP/   -3,,PPBLK-1
PPBLK/   001160,,200000
PPBLK+1/   201777,,333436
PPBLK+2/   373737,,000000

**Comment by larsbrinkhoff** [comment]
Actually, all of DECUUO lives in high address space, so I don't know how this could work at all.  Maybe some bitrot has set in.

**Comment by philbudne** [comment]
> Maybe some bitrot has set in.

I'd be surprised if no bitrot had happend!

**Comment by larsbrinkhoff** [comment]
Patched ITS to make 400000,,0-777000,,0 be a linked list address, and an address above that a BLKO pointer.  Now SUDS runs fine, except I haven't been able to make it display anything.

**Comment by larsbrinkhoff** [comment]
I think I spoke to soon.  SUDS does not run fine.  It runs further along, but then ITS halts.  At that point, a few .DSTART calls have been made.  According to debug output, some reasonable looking words have been transferred to the 340.  But near the end is more supicious data.

Here's an example.  Two 18-bit words with 403737.  Does that make sense?

```
DBG(1138177760)> DPY DEBTAB_ISNULL: DPY 131 DATO 403737403737 PC=001341^M
type340 mode 03 status 0^M
type340 char 403737^M
type340 mode 0 status 0^M
type340 reserved param bits set 0403737^M
type340 set intensity 7^M
type340 set scale 2^M
type340 stop^M
type340 stop int^M

**Comment by larsbrinkhoff** [comment]
Full log attached.
[340.log](https://github.com/PDP-10/its/files/1920773/340.log)

**Comment by philbudne** [comment]
I didn't notice any plotting commands, but all the "reserved param bits"
messages suggest someone is confused (could be my code) trying to interpret
a command while in the wrong mode.


phil@p27:~/Downloads$ grep reserved 340.log | sort -u 
type340 reserved param bits set 0200000
type340 reserved param bits set 0200400
type340 reserved param bits set 0201700
type340 reserved param bits set 0201740
type340 reserved param bits set 0201777
type340 reserved param bits set 0333436
type340 reserved param bits set 0403737

The first five could be "point mode" commands (200000 specifies
vertical coordinate), and the last two could be character mode, with
six-bit (but not SIXBIT!) characters:

33 is line feed
34 is carriage return
36 switches to lower case
40 is space
37 is escape from character mode

But none of the above would plot anything on the screen.

**Comment by larsbrinkhoff** [comment]
Thanks Phil.

I'm not sure what is supposed to be displayed when SUDS starts.  Maybe a little bit of text and a cursor?

Maybe there's still something wrong with how the display list is passed to the system.  Certainly something is wrong when ITS hangs.

**Comment by larsbrinkhoff** [comment]
I have examined the display lists sent to .DSTART.  These are the last two ones.  After the second, ITS hangs.

```
dlvis/   DLPP,,DLVIS+1
dlpp/   -3,,DLSTOP
$q+1/                   001160,,200000
PPBLK+1/                200400,,333436
PPBLK+2/                343335,,513737
dlvis+1/   DLPG,,0
dlpg/   -26,,601156
$q+1/                   000160,,200000
601160/                 200000,,201700
601161/                 201740,,201740
601162/                 200000,,001160
601163/                 351517,,040575
601164/                 024040,,402303
601165/                 147560,,654040
601166/                 401426,,147557
601167/                 404040,,366335
601170/                 753737,,000000
601171/                 201000,,001000
601172/                 000002,,201000
601173/                 201000,,201000
601174/                 201000,,201000
601175/                 201000,,201000
601176/                 201000,,201000
601177/                 201000,,201010
601200/                 201010,,000001
601201/                 710220,,000001
601202/                 201010,,200770
601203/                 000001,,710020
601204/                 000000,,000000
```

```
dlvis/   DLPP,,DLVIS+1
dlpp/   -3,,DLSTOP
$q+1/                   001160,,200000
PPBLK+1/                200400,,333436
PPBLK+2/                343335,,513737
dlvis+1/   DLPG,,0
dlpg/   -31,,601156
$q+1/                   000160,,200000
601160/                 200000,,201700
601161/                 201740,,002160
601162/                 355137,,000000
601163/                 201740,,000000
601164/                 000002,,201740
601165/                 200000,,001160
601166/                 351517,,040575
601167/                 024040,,402303
601170/                 147560,,654040
601171/                 401426,,147557
601172/                 404040,,366335
601173/                 753737,,000000
601174/                 201000,,001000
601175/                 000002,,201000
601176/                 201000,,201000
601177/                 201000,,201000
601200/                 201000,,201000
601201/                 201000,,201000
601202/                 201000,,201010
601203/                 201010,,000001
601204/                 710220,,000001
601205/                 201010,,200770
601206/                 000001,,710020
601207/                 000000,,000000

**Comment by philbudne** [comment]
I'm assuming this is with ITS patched to allow addresses above 128K
(memory inside the DECUUO simulator)?  That fact alone makes me
wonder whether the configuration you're testing was ever used or ever
worked.

The last time I looked at decoded/debug output from type340.c for a
SUDS display list, it wasn't happy (saw bit patterns that weren't
expected given the current state of the display word interpreter).

Did you say you had SUDS sources?  It might be interesting to look at
the code driving the 340 and see what it's trying to do!

**Comment by larsbrinkhoff** [comment]
Yes, this is with a patched ITS.  I think I saw information that the GT40 was used for SUDS at MIT.  Beoynd that I don't think I have seen anything else about which displays were used with DECUUO or SUDS, so you may be right that this configuration isn't quite working.

I'm not sure if the display list type340.c receives is the same that DECUUO sends.  It's one of the things I'd like to verify in the near future.

Yes, we now have SUDS sources.  SUDS is built to use the SAIL III displays, and then DECUUO translates the display lists ("pieces of glass" in SAIL terminology) to the MIT output device.

**Comment by larsbrinkhoff** [comment]
This small program will reliably hang ITS.

```
a==1
p==17

go:     .dstart [-dlen,,dlist-1]
         .lose
        movei a,5*30.
        .sleep a,
        .logout 1,

dlist:  373737,,3000    ;Escape, Stop
dlen=.-dlist

end go

**Comment by philbudne** [comment]
dlist:  373737,,3000    ;Escape, Stop

Not saying that hanging ITS doesn't indicate a problem, but the above
assumes the 340 starts in character mode, rather than parameter mode.

**Comment by larsbrinkhoff** [comment]
Right.  It was a quick copy from another program - a bit too quick!  But anyway it's a good test case it if triggers a fatal error.

I'll try it with just the Stop word.

**Comment by larsbrinkhoff** [comment]
If I change it to `dlist:  3000,,3000` it still crashes, so maybe it's not because of a bad command in the display list.

**Comment by larsbrinkhoff** [comment]
Another problem could be that DECUUO support for the Stanford keyboard has bit rotted.  I haven't tested it, but from inspection it doesn't look functional.

**Comment by larsbrinkhoff** [comment]
One possible theory is that D worked with the 340 display and the Stanford keyboard when it was called DRAW; DITS.  Maybe the code was reworked later and was split into separate files DRAW; D and DECSYS; DECUUO.

**Comment by larsbrinkhoff** [comment]
I'm inclined to believe DECUUO either has suffered bitrot, or that the 340 never really worked.

I did find an older version of D which displays on the 340, but it's not using DECUUO: #1732
