### ISSUE TITLE
MDL can't purify high address space

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#831]
@atsampson:

> MDL's PURIMP routine, which adjusts the memory map before dumping the final interpreter binary, fails on its final CORBLK call. We've stubbed this out for now, but this means that some pages which should be read-only are writable.

**Comment by larsbrinkhoff** [comment]
Related to #830.

**Comment by atsampson** [comment]
I wonder if this might be the same [problem that we saw with MIDAS 76/77](https://github.com/PDP-10/its/issues/681#issuecomment-382141785), where a CBLK call obviously wasn't doing what the program expected.

**Comment by atsampson** [comment]
I wrote a [testcase for this](https://github.com/atsampson/its-tests/blob/master/its/purcor.mid) -- CORBLK stops with an %EROPG error if you ask it to change the permissions of a page that doesn't exist. So either:

- CORBLK's behaviour changed at some point in the past, or...

- ... when MDL last ran on ITS, it happened that the last page was 377, so there was no unmapped page for CORBLK to run into. (It's only about a page away from this in the current version if BOT is 700000.)
