### ISSUE TITLE
PR - fancy file printer

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#85]
SYSEN1; PR 87  
INFO; PR 5

**Comment by eswenson1** [comment]
SYS1; TS PR
SYS1; TS CALL -- displays ITS CALLS
SYS1; TS DOC -- displays documentation types (CALL, UUO, USET, SUSET, TTYVAR, INTRUP, MUD)
SYS1; TS INTRUP - displays ITS Interrupts
SYS1; TS LSC -- displays the LSC movie guide (missing)
SYS1; TS USET -- displays ITS USETS
SYS1; TS UUO - displays ITS UUOs
SYS2;TS TTYVAR -- displays ITS TTY variables

These are all links to SYS1; TS PR (except, of course, SYS1; TS PR).  They provide all sorts of very useful system documentation.
