### ISSUE TITLE
Versatec Spooler

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#856]
DCP; VERSA 210

Can read many file formats:
- ARDS
- Tektronix
- XGP scan
- Harvard scan
- Dover press

Can display bitmaps using SUPDUP graphics.

**Comment by atsampson** [comment]
Sounds useful. If it's doing rasterisation already, I wonder if it could be modified to produce PBM output files for modern systems...

**Comment by atsampson** [comment]
Having dug into the (elegant and well-documented) code for this a bit... when invoked as VERSA, it goes into a test mode where it loads a fixed series of files and displays them using SUPDUP graphics.

If you invoke it with a different name (perhaps SPOOLR), it operates as MC's general-purpose printer spooler, reading files from .GLPR.; in various formats, and feeding them to various output devices (e.g. Gould and Versatec printers). One of the output devices is "hargld", which writes 200DPI run-length-encoded bitmap files to .TEMP.;, and it looks like it'd be straightforward to convert those to a modern format, or add a similar backend to write a different format.

The .GLPR. directory came from the Gould spooler, which is documented in INFO; GLP >. AI: SYSENG; XQUEUE > is the program to add files to the queue.

On the downside, XGP input support is commented out, and ITS OBUGS0 includes a 1982 post from DCP which says:

> In theory (if I turned on XGP file recognition in the spooler), XGP files produced by R come out correctly, but XGP files produced by TJ6 or BOLIO (and I think @) cause it to crash.

**Comment by larsbrinkhoff** [comment]
Bolio?  Yet another typesetting thing?!?  For the Lisp machine, it seems.  I'll let @ams handle that.

**Comment by ams** [comment]
I have some hacks to convert Bolio to XML written by (I think) @hanshuebner.  I'll plop them in https://github.com/LM-3/bolio .
