### ISSUE TITLE
Printing

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#862]
Add support for printing.  Over the years some of these devices came and went:

- XGP - Xerox Graphics Printer.  An early laser printer.
- Dover - A newer Xerox laser printer.  Attached to an Alto running Spruce.
- Calcomp plotter.
- Versatec 80.
- Gould electrostatic printer.  Attached to MC.  Later in Building 38.

**Comment by larsbrinkhoff** [comment]
Of the three hardcopy devices, the XGP seems most promising.  Most typesetting applications support it, and the Dover is backwards compatible with SCAN files.

There are many options:

- Run the PDP-11 code in SYSEN2; XGP 31.
- Intercept files sent from SYSEN2; XGPSPL 197.  This is a PDP-10 program which sends files from the spooling directory to the XGP 11.
- Convert SCAN files to PDF without any PDP-10 or 11 involvement.

**Comment by larsbrinkhoff** [comment]
Hardcopy file formats:

- Plain ASCII.
- SCAN.  XGP bitmap.
- PRESS.  Dover.
- PLT.  Written by SUDS.

**Comment by larsbrinkhoff** [comment]
I see e.g. TJ6 writes output with text still in ASCII form, i.e. not SCAN files.  So font rendering happens in the PDP-11.  So the third option (converting SCAN to PDF) isn't useful in this case.

**Comment by atsampson** [comment]
Yep, XGP sounds like a good bet. Going from XGP to PDF directly would probably produce the nicest output - some of the fonts used could be mapped to the standard PDF fonts, and others could be converted (which'd be a bit of work) or rendered as bitmaps.

A lower-tech approach would be to modify XD (#635) or VERSA (#856) to write their rasterised output as a bitmap file, then convert to PDF from there. It'd probably look OK but not be searchable.

It looks like SAIL used a similar format for their XGP - [this description](https://www.saildart.org/j5/J17_html/XGPSER.html#XGPSER:0023) is nearly the same as [INFO;XGP](https://github.com/PDP-10/its-vault/blob/master/files/info/xgp.24#L341).

**Comment by larsbrinkhoff** [comment]
There's something to be said for pixel-perfect rendering.  Also, I'd like to see SUDS drawings.  Maybe XD would be the way to go for this.

But you have a good point about searchability.  I suppose (given enough effort) the fonts could be embedded into the PDFs.

**Comment by atsampson** [comment]
Here's a SUDS drawing:

![rdrs](https://user-images.githubusercontent.com/436317/39788747-b8d71f04-5323-11e8-9f6a-bd6d05846e98.png)

SUDS -> SCNV -> [VERSA (modified)](https://github.com/PDP-10/its/tree/ats/versa) -> [gldtopbm](https://github.com/atsampson/pdp10-its-disassembler/tree/gould).

**Comment by ams** [comment]
So getting SUDS output works, even if a bit convulsed? Great!  Any (dumbed down) instructions for how to do this?

**Comment by ams** [comment]
Is this in the versa branch?

**Comment by ams** [comment]
I’ll figure it out instead of asking lazy questions :-)

**Comment by atsampson** [comment]
Yes, what @larsbrinkhoff said :-)

SCNV and VERSA can both handle multiple files at once, which saves a bit of time - SCNV converts all * PLT files in the current directory, and VERSA can take multiple filenames separated by commas.

VERSA writes HARSCN 1, HARSCN 2... into .TEMP.; those are the files you need for gldtopbm. Dump them to a tape and extract with itstar. Drop any that are zero-length; at the moment VERSA writes an empty file when it starts up, which I need to fix. 

The output is rotated 180 degrees, so do something like this to get a usable file:

```
gldtopbm <harscn.2 | pnmflip -r180 | pnmtopng >2.png
```

**Comment by ams** [comment]
The `:link` command on the versa branch seems incomplete, no?

**Comment by larsbrinkhoff** [comment]
The _ should be a ,

Not the first time that mistake - or the reverse - was made!

**Comment by atsampson** [comment]
Fixed - thanks!

**Comment by larsbrinkhoff** [comment]
It would be interesting to put a time frame on the various printers.

- XGP - made around 1970
- Dover - ?
- Gould - late 70s
- Versatec 80 - early 80s

**Comment by atsampson** [comment]
The Versatec V80 arrived in October 1981, going by the comments at the top of VERSA.

**Comment by atsampson** [comment]
(I was going to post this to #863, but I think it makes more sense here!)

VERSA talks to both Gould and Versatec printers over the CHAOSNET. It looks like the printers were controlled by MINITS machines, since MINITS has [gould](https://github.com/PDP-10/minits/blob/master/mits_s/gould.17) and [v80](https://github.com/PDP-10/minits/blob/master/mits_s/v80.4) drivers.

The `gdest` table in VERSA includes the printers it can spool for:

- `pfc`, Versatec "V80 at PFC" on CHAOS host 3641
- `ts7`, "Tech Square 200bpi Versatec" V80 on CHAOS host 3117, added after the above
- `b38`, "Gould in building 38" on CHAOS host 500
- `har`, "the Harvard Gould (creates disk files)"
- `xgp`, the AI XGP (not implemented)

[IOELEV](https://github.com/PDP-10/its/blob/master/src/system/ioelev.432) also has a Gould printer driver, which appears to be the same hardware as the MINITS driver above going by the register definitions. It's not enabled for any machines: "DOESN'T HAVE GOULD LPT (ANYMORE)".

**Comment by larsbrinkhoff** [comment]
Thanks.  Looks like the Gould printer was attached to MIT-MC's IO-11, later moved to Building 38.  Or something like that.

**Comment by larsbrinkhoff** [comment]
I think this subject is well covered in #427, #628, and #863.
