### ISSUE TITLE
Tech Square 9th floor

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#871]
An idea for a museum exhibit:

Recreate parts of MIT Tech Square 9th floor.  It's the perfect habitat for:
- PDP-10s big and small
- A 340 display
- Text terminals
- A few 11s
- One of which could control a  Logo turtle?
- Lisp machines
- Multics
- CTSS
- Maybe even a Knight TV some time in the future.

**Comment by dabridgham** [comment]
Did Multics ever live in Tech Square?  When I was there, the 9th floor gained rows of VAX 11/750s.

**Comment by larsbrinkhoff** [comment]
This is from an inverview with Greenblatt, and it has also been checked by Noel Chiappa.  I believe @eswenson1 should be able to fill in some details about the Multics hardware.

![](http://gunkies.org/w/images/2/29/9th_floor_techsquare.png)

**Comment by larsbrinkhoff** [comment]
Some more details here, including the VAX farm:  
http://gunkies.org/wiki/Talk:Tech_Square

**Comment by eswenson1** [comment]
Multiple was not in Tech Square when I was at MIT (1976-1980). It was in IPC in building 10, I think. To get to the floor where Multics was, you had to take an elevator. That elevator did NOT stop at the Multics machine room floor (unless you had some magic key). Wanting to see it one day, I timed my elevator ride just right and pushed the emergency stop button. I pride open the elevator doors, and lo and behold, the machine room was in front of me. I looked around a bit in fear i’d Be caught, and then scidaddled.

**Comment by eswenson1** [comment]
I meant building 38, I think. IPC was the Information Processing Center, and the org by the same name provided computer services for the institute.

**Comment by larsbrinkhoff** [comment]
Supposedly there was a 645 on the 9th floor: http://multicians.org/tech-square.html

**Comment by eswenson1** [comment]
I suspect the 645 was there years before I was. It wasn’t there when I was there.

**Comment by atsampson** [comment]
Melinda Varian's [VM and the VM Community](http://www.leeandmelindavarian.com/Melinda/25paper.pdf) has an IBM perspective on 545 Tech Square; no ITS but some interesting comments on CTSS and Multics, and lots on what IBM's Cambridge Scientific Centre was up to.

> The building was a hotbed of time-sharing activity. "At one time in the mid-60s, I counted ten or fifteen time-sharing systems being coded or tested or accessed in Tech Square." (J.B. Harmon, private communication, 1989.)

**Comment by larsbrinkhoff** [comment]
There was also a secret CIA office.

And Computer Corporation of America rented space.  They hosted the ARPA Datacomputer running on TENEX, and sold an early Emacs clone for Unix.

**Comment by eswenson1** [comment]
The secret CIA office wasn’t so secret — well it was, but many folks who worked in that building knew about it and joked about what we thought they we up to. I suspect it was just for recruiting.

**Comment by larsbrinkhoff** [comment]
"The CIA Is Still At Tech Square"  
https://www.thecrimson.com/article/1973/10/6/the-cia-is-still-at-tech/

**Comment by larsbrinkhoff** [comment]
Some of the 2nd floor.
![tech_square_2nd](https://user-images.githubusercontent.com/775050/90682108-c781c900-e264-11ea-9a2a-e9de1ab90a55.png)

**Comment by larsbrinkhoff** [comment]
Comment from Tom Knight regarding the [9th floor plan](https://github.com/PDP-10/its/issues/871#issuecomment-388345859):

> This diagram is largely correct, but was not a snapshot in time. 1401 was gone before Multics 635 installation. 936/936A had not lisp machines until much later. 7090 was replaced by the 645 Multics machine. 908 had the Kludge PDP-7, and the AI PDP-1 was traded in for the PDP-6. The DM PDP-10 and the IMP were located near the DM PDP-6, toward what is labeled 1401. For those of you following along, synthetic biology was started in my lab in rooms 922/923.

Source: https://twitter.com/TomKnightSynBio/status/1480629226990567428
