### ISSUE TITLE
Document disk drive/unit/pack etc

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#876]
Configuring ITS for more than one disk, and formatting them, can be tricky if you don't know what you're doing.  Document these concepts:

- RH0.0 and RH0.1 etc in KLH10.
- Drive number.
- Unit number.
- Pysical units and virtual units.
- Pack number.
- FIRSPK and LASTPK in the salvagers.
- DSKn: devices.
- PKn: devices.
- SECOND: etc devices.

Maybe throw in how the Grim File Reaper works.

**Comment by eswenson1** [comment]
The SECOND: device seems to be supported.  On ES-ITS, when I do:

   copy ejs;foo bar,second:

I get the error message:

  SECOND: EJS; _COPY_ OUTPUT - PACK NOT MOUNTED

And there are plenty of references to SECOND: in the various docs and sources.  It appears that SYS: ATSIGN DEVICE has support for named disk packs, of which SECOND is one.

**Comment by eswenson1** [comment]
There appears to be code in SYSENG; @DEV > to handle the SECOND:, THIRD:, and FOURTH: devices.  They appear to require configuration as to what machines have these devices -- by default, there always a SECOND: device which maps to a secondary pack.  Machines named MX define a THIRD: and FOURTH: device, and machines named AI define a THIRD: device.  I haven't investigated (yet) what a secondary pack is and how one is defined.

**Comment by larsbrinkhoff** [comment]
The Grim File Reaper in DUMP can make use of SECOND: as an intermediate stage before moving files to tape.

**Comment by larsbrinkhoff** [comment]
RH0.0 etc corresponds to the physical drive.

In SALV, unit number seems to correspond closely to the hardware disk drive.  But maybe there's some kind of mapping between them.

Pack numbers are written to disk.  And read back when a pack is accessed by SALV or ITS.  Still, I don't think a pack can be put in any drive.  Unsure about this.

FIRSPK and LASTPK defines the range of pack numbers to use in SALV and ITS.

**Comment by larsbrinkhoff** [comment]
A file listing will display free blocks and number for each block.  Are those pack numbers?

**Comment by eswenson1** [comment]
The first number on a directory display line is the pack number.

**Comment by larsbrinkhoff** [comment]
I think this can go into #1812.
