### ISSUE TITLE
YAHTZE

### ISSUE THREAD

**Issue by eswenson1** [PDP-10/its#890]
bmt1;yahtze (init)
bmt1;yahtze fasl
drb; yahtze 27
sca; mode fasl -- source missing

Need to locate sca; mode > (or sca;mode fasl) in order to build yahtze fasl from source

**Comment by eswenson1** [comment]
Found sca;mode 191.  But in order to build that, I need sca;modeb >.  And sca;mode 191 needs to get modified to not locate sca;modeb from MC:

**Comment by larsbrinkhoff** [comment]
Ping.

**Comment by eswenson1** [comment]
Turns out that we need SCA; MACROS > too. Trying to locate it.

**Comment by eswenson1** [comment]
Could not figure out how to get SCA;MODE > to compile. When you try to compile it, the compiler ends up in a (READ) and never finishes. Wasn't able to figure out why.  However, you can compile SCA; MACROS >, SCA; MODEB >, and GAMES; YAHTZE now. YAHTZE loads the interpreted SCA; MODE > and the other FASL files, and the resulting FASL runs fine.
