### ISSUE TITLE
Greenblatt CHESS 144

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#897]
Snyder has a printout.

**Comment by larsbrinkhoff** [comment]
![chess144](https://user-images.githubusercontent.com/775050/40620487-4b944a36-6299-11e8-9867-4e4883d0aed2.jpg)

**Comment by larsbrinkhoff** [comment]
Scanned:
http://lars.nocrew.org/its/chess144.pdf

**Comment by atsampson** [comment]
Interesting - I wonder how it relates to the other chess programs we've got? It's very different from OCM (even the register names aren't the same!). From the table of commands on p15, it's missing some of the commands used in Krakauer's 1968 transcript of MacHack, so maybe it's a copy of a *very* early version... it would be interesting to compare it to the 1970 DECUS binary.

**Comment by larsbrinkhoff** [comment]
OCM and RG; C 524 have some similarities, at least enough to say they probably share history.  But this CHESS 144 could well be something else.

**Comment by larsbrinkhoff** [comment]
https://github.com/PDP-10/its-vault/blob/master/ocr/chess144.txt

**Comment by larsbrinkhoff** [comment]
Hello @cbfiddle,

Thank you for mailing the CHESS 144 printout.  In this GitHub issue, there are links to the scanned PDF and a OCR'd text file.  There are also some thoughts about how it compares to other versions of Greenblatt's MacHack VI.  Do you remember anything about this history behind your copy of the file?

**Comment by cbfiddle** [comment]
Unfortunately, I do not recall anything about the file.

**Comment by larsbrinkhoff** [comment]
@TheFausap has transcribed the listing to text: #1024.

**Comment by larsbrinkhoff** [comment]
It seems to have nothing in common with RG; C 524, RG; CHESS2 614 and CHPROG; OCM 470.

**Comment by larsbrinkhoff** [comment]
There's a copy in MRC; CHESS 144, dated 1976-07-12.
