### ISSUE TITLE
@ Cross Reference Listing Tool

### ISSUE THREAD

**Issue by eswenson1** [PDP-10/its#90]
SYSEN1; @ 695
SYSEN1; @ DIFF
SYSEN2; @MUDDL 64
INFO; @ 22

**Comment by larsbrinkhoff** [comment]
In the MC snapshot, there's a binary called SYS3; TS @BIG which has been assembled from MIDAS; @ 662.  The PI distribution has a source file called MIDAS; ATSIGN 696, but it's identical to SYSEN; @ 695.

**Comment by larsbrinkhoff** [comment]
Added Muddle file.

**Comment by eswenson1** [comment]
Source for SYSEN1;@ 695 has an .INSRT for SYSEN1;@MUDDL > even though the file existed in SYSEN2;@MUDDL 64. Should I place a link in SYSEN1; to the SYSEN2 file? Or should I update the filename when prompted by midas?

**Comment by eswenson1** [comment]
I chose to update the filename when prompted for the failed INSRT. We can always add a link later.

**Comment by larsbrinkhoff** [comment]
In general, I think we should add unmodified files first, and then do necessary updates in a later commit.  That way, we have a record of the original state and the changed we have made.

This record is even more clear if we make an issue or pull request for all changes, but that may be a bit too much work to do for every single modification.

**Comment by eswenson1** [comment]
Sound good.
