### ISSUE TITLE
MACSYMA tensor package

### ISSUE THREAD

**Issue by TheFausap** [PDP-10/its#920]
Hello,

I'm trying to use the tensor package in MACSYMA.
I'm using the MACSYMA_RefMan_V9 (Dec. 77) (http://bitsavers.org/pdf/mit/macsyma/MACSYMA_RefMan_V9_Dec77.pdf) and it refers to two files in the SHARE directory:

DSK:SHARE;ETENSR FASL
DSK.SHARE;ITENSR FASL

According to the reference manual, ETENSR should be loaded automatically when the user calls the setup procedure TSETUP().
If I do that, MACSYMA tries to load CTENSR FASL (!)

tsetup();
Could not find file with matches "DSK:SHARE;CTENSR FASL"

Are those file missing ? 

thanks,
Fausto

**Comment by larsbrinkhoff** [comment]
Indeed no CTENSR FASL is installed at this time.

I see there exists files MACSYM; ITENSR FASL and TENSOR; CTENSR FASL in backups.  Those seem promising.  @eswenson1, can you take a look at this?

**Comment by TheFausap** [comment]
Maybe ETENSR became CTENSR later... so the refman is not updated, even if we have the version 9 of MACSYMA.

**Comment by larsbrinkhoff** [comment]
I have placed the TENSOR; CTENSR FASL files in the [its-vault](https://github.com/PDP-10/its-vault) repository.  @TheFausap, if you like, you can copy this file to your ITS image (presumably to the SHARE directory, or make a link) and see it MACSYMA gets any further.

**Comment by eswenson1** [comment]
From MACDOC; OUPDAT 352:

> RP@MIT-MC 02/16/80 1629-EST  To: INFO-MACSYM
The new tensor packages are operational.  The ETENSR pack is now called
CTENSR and is available by doing LOADFILE(CTENSR,FASL,SHARE); for 
component tensor manipulation.  The ITENSR pack, as before, is loaded by 
doing LOADFILE(ITENSR,FASL,SHARE); for indicial tensor manipulation.  
Both packages have many new functions as well as old ones which have been 
modified.  A full description is available by printing SHARE;TENSOR DESCR.
In addition, demos exist on the TENSOR; directory under the first 
filenames CTENSR and ITENSR.  Send bugs or comments to RP or TENSOR.

**Comment by eswenson1** [comment]
So ETENSR is old -- replaced with CTENSR.  This file was not included in the normal build scripts -- not sure why.  I do see a reference in JPG; SUPRV > to the adding of an autoload property for tsetup to SHARE; CTENSR FASL, so this should definitely get added to the build.  Now, I'm not sure where the correct source for this is -- this was written in Macsyma and translated to lisp, resulting in the source TENSOR; CTENSR TRLISP.  That last file was then compiled to TENSOR; CTENSR FASL, which got installed as SHARE; CTENSR FASL.  I can certianly add CTENSR TRLISP to the build and buid it to CTENSR FASL.  However, the "right" thing to do would be to compile the Macsyma source to the TRLISP and then compile the TRLISP file to the FASL file.  Not sure where the Macsyma source for CTENSR is....

**Comment by eswenson1** [comment]
The macsyma source for CTENSR is in TENSOR;CTENSR FUNCS.  We don't have this source, but I can see if we can find it.

**Comment by eswenson1** [comment]
I moved a copy of TENSOR; CTENSR FASL to SHARE; CTENSR FASL, and then, within Macsyma, ran tsetup(); Here is what I got:

> *:copy tensor;ctensr fasl,share;
>*macsym^K!
>
>This is MACSYMA 999
>
> (C1) tsetup();
> 
> CTENSR FASL DSK SHARE being loaded
> CTENSR source DSK:TENSOR;CTENSR FUNCS
> TRMODE FASL DSK MACSYM being loaded
> Loading done
> oading done
> Enter the dimension of the coordinate system:

So I guess it is likely to work -- but I don't know how to use this and haven't read the doc.

I'll make sure CTENSR gets into the build (either from LISP or Macsyma source), or, I can't compile it, I'll just include the FASL file.

**Comment by eswenson1** [comment]
I tried compiling CTENSR TRLISP to CTENSR FASL, and it seemed to work fine when I loaded it. So even if we can't get the Macsyma source for CTENSR, we have the translated lisp (TRLISP) source and can compile the FASL from it.

> *complr^K!
> LISP COMPILER 2155 [in LISP 2154]
> _ejs;_tensor;ctensr trlisp
> _
> 50074)   XCT 11   $^X. MACSYM$J
> *$^X.
> *macsym^K!
> This is MACSYMA 999
> (C1) loadfile(ctensr,fasl,dsk,ejs);
> 
> CTENSR FASL DSK EJS being loaded
> CTENSR source DSK:TENSOR;CTENSR FUNCS
>
> TRMODE FASL DSK MACSYM being loaded
> Loading done
> Loading done
> (D1)                                                          DONE
> (C2) tsetup();
> Enter the dimension of the coordinate system:

This does beg the question of what version number we should be using when building Macsyma.  I picked 999 to make sure it was bigger than any other version.  I'll enter a new ticket for that.

**Comment by eswenson1** [comment]
Looking at an old version of the macsyma source for CTENSR, it seems it will require SHAREM; PACKG FASL in order to successfully translate.  We do have the source for that (SHAREM; PACKG 7) as well as a fasl file (SHAREM; PACKG FASL), so when I get TENSOR; CTENSR FUNCS, I should be able to translate it to lisp and compile it to FASL.

**Comment by TheFausap** [comment]
@larsbrinkhoff I know the question could be stupid, but how can I do that without recreating the disks? :-)

**Comment by eswenson1** [comment]
@TheFausap I recommend you create a tape with itstar and then mount that tape on your running ITS system, and use the DUMP (LOAD) program to load the file(s) you need. That’s what I did to test it. If you need help with this, let me know. And I could share with you the tape I made to test all this.

**Comment by larsbrinkhoff** [comment]
Remaking the disk image from scratch is very slow.  Much faster is to
put the files on a tape, and then extraxt them in ITS.  There's a guide
for that in the doc directory.

**Comment by eswenson1** [comment]
I'm closing this ticket now that CTENSR FUNCS is being translated and compiled in the current build.
