### ISSUE TITLE
Macsyma Compiler / Translator

### ISSUE THREAD

**Issue by eswenson1** [PDP-10/its#922]
You can write code in Macsyma and then compile this to LISP and then using the lisp compiler, create a FASL file.  Where is the macsyma compiler?  MAXTUL; TS MCL appears to be a way of compiling LISP source files that make up Macsyma.  But how do you compile Macsyma source files, or translate them to LISP (TRLISP) files?

**Comment by eswenson1** [comment]
It may be that you use the Macsyma translate_file() command.  Attempting to use it from DB-ITS Macsyma gives:

> (C3) translate_file(foo,bar,baz,buz);
> Could not find file which matches "DSK:MACSYM;TRANSS FASL"
> 
> (C4)

I believe TRANSS was a source that I was unable to compile.  See the build_macsyma_portion function in build.tcl -- where I explicitly exclude TRANSS from the build.  I

So we need to either a) figure out how to build TRANSL;TRANSS >, or b) include MACSYM; TRANSS FASL in our Macsyma build.

**Comment by eswenson1** [comment]
Adding the file MACSYM; TRANSS FASL to DB allows translate_file() to get a little further, but it then attempts to load MACSYM; TRHOOK FASL.  That was another file that I was unable to build, and that was skipped in the DB macsyma build process.

**Comment by eswenson1** [comment]
Adding MACSYM; TRHOOK FASL to the system gets further, but then Macsyma bombs out with:

> (C5) translate_file(foo,bar,baz,buz);
> 
> TRANSS FASL DSK MACSYM being loaded
Loading done
[TRANSS, 80, DSK, MAXER1]  FILE NOT FOUND
(C6)

That file would have been produced by the macsyma build process when building TRANSS (which we can't yet build).

**Comment by eswenson1** [comment]
Adding MAXER1; TRANSS 80 to the system results in successful creation of a TRLISP file.  Here is a transcript:

> *macsym^K!
>
> This is MACSYMA 999
>
> C1) translate_file(ode2);
>
> TRANSS FASL DSK MACSYM being loaded
> TRANSL AUTOLO DSK MACSYM being loaded
> Loading done
> Loading done
>
> Translation begun on DSK:EJS;ODE2 69.
>
> You have run out of LIST space.
> Do you want more?
> Type ALL; NONE; a level-no. or the name of the space.
>
> ALL;
>
> STATUS FASL DSK MAXOUT being loaded
> Loading done
> (D1)                            ["DSK:EJS;ODE2 69", "DSK:EJS;ODE2 TRLISP", "DSK:EJS;ODE2 UNLISP"]
>
> (C2)

So it appears we can build macsym files that were written in Macsyma, through use of the Macsyma translator.  JPG; ODE2 > is an example of such a file, as is TENSOR; CTENSR FUNCS.  

So all we need to do is either figure out how to build TRANSS and TRHOOK or include the FASL files for these in the build.

**Comment by eswenson1** [comment]
As proof that JPG; ODE2 > (a macsyma source file) can be translated into lisp (EJS; ODE2 TRLISP) and then compiled into a FASL, see below:

> ***:maxtul;mcl
> Macsyma Source Compiler
> 
> LISP COMPILER 2155 [in LISP 2154]
> 
> _ejs;ode2 trlisp
> 
> _

**Comment by TheFausap** [comment]
Here there're some sources, with also some hints for the version number

http://www.unf.edu/public/cap4630/kmartin/gradfall94/maxima/src/

there's transs.lisp but not trhook.lisp

I'm not sure if these are too recent

**Comment by eswenson1** [comment]
These are for Common Lisp, not MacLisp. There is no CL for ITS. These sources were ported from MacLisp to CL. They are useful in cases that we have to recreate lost/missing sources, but not directly usable. I have located the required CTENSR FUNCS file and have requested a copy.

**Comment by larsbrinkhoff** [comment]
I suppose it should be possible to back port all updates from the latest Common Lisp version, i.e. Maxima.  But it's probably a lot of work!

**Comment by eswenson1** [comment]
Yes, that is a lot of work. There were some substantial changes.

**Comment by eswenson1** [comment]
I'm closing this ticket since translate_file is working fine in the current build.
