### ISSUE TITLE
TJ6 problems when building TJ6MEM

### ISSUE THREAD

**Issue by atsampson** [PDP-10/its#925]
There are a few problems with our current version of TJ6 that are visible in TJ6MEM:

- .TRANS doesn't work as described in the manual. The example in the manual (page 15.1) ends up setting up a translation that turns all the commas in the rest of the manual into `e`s!

- ~~^D (insert the date) formats the year as 1918.~~ Fixed in #947.

- ~~TJ6 does superscript and subscript by changing the XGP's font baseline adjustment. The XGP documentation says that the baseline adjustment is only reset to 0 when you change font. However, in the superscript examples in the manual (e.g. page 16.1), TJ6 emits an extra baseline adjustment after the font change, leaving the baseline where it was until another font change happens to reset it some time later. So either TJ6 is confused, or the XGP doesn't work exactly the way the documentation describes.~~ Fixed in #924.

**Comment by atsampson** [comment]
Both the MIT and SAIL XGP drivers reset the baseline adjustment at the start of each line:

- https://github.com/PDP-10/its-vault/blob/master/files/sysen2/xgp.31#L1210
- https://www.saildart.org/j5/J17_html/XGPSER.html#XGPSER:0028

So TJ6 is correct. I've fixed VERSA to match.

**Comment by larsbrinkhoff** [comment]
I have now tested this with TJ6, and the XGP output looks pretty good.

The problem with e is there, however!

**Comment by larsbrinkhoff** [comment]
This is clearly wrong.  The comma is still in A on re-entry to ATRANS.  There should be another call to RCSV.  OTJ6 138 does this right.

```
ATRANS: MOVE    K,A             ;.TRANS
        PUSHJ   P,RCSV
        MOVEM   A,TRNTBL(K)
        PUSHJ   P,RCSV
        CAIN    A,",
        JRST    ATRANS
        POPJ    P,
```
