### ISSUE TITLE
CROCK - running analog clock

### ISSUE THREAD

**Issue by eswenson1** [PDP-10/its#93]
SYS1; TS CROCK
SYSEN1; CROCK 1008

**Comment by larsbrinkhoff** [comment]
Oh, I want this!

**Comment by larsbrinkhoff** [comment]
It also wants SYSEN1; SYSTEM >, but that's in SYSENG.

When it runs, there's an error:

    ILOPR; 320>>XCT 437(10)   452/   33

**Comment by eswenson1** [comment]
The PI distrubution binary runs for me without ILOPR.

**Comment by larsbrinkhoff** [comment]
I get the same error when I copy the PI binary to the DB system.  Did you run it in PI or DB?

**Comment by larsbrinkhoff** [comment]
I'm running in SIMH, so maybe that's why.

**Comment by larsbrinkhoff** [comment]
Done in #149.
