### ISSUE TITLE
writing TJ6 file from EMACS

### ISSUE THREAD

**Issue by TheFausap** [PDP-10/its#946]
Hello,

I'm trying to write down the example in printing.md using emacs and supdup terminal.

All is fine, except for the font switching. According to the TJ6 manual, I should use CTRL-F (|F and font number), but this, in EMACS, move the cursor.

In the emacs.guide I find something related, I should use M-# with an argument (M- is ESC, right?), but if I type ESC then # (shift-3) I have no way to write the font number, the M-# (at bottom) disappear.

How can I do that ?

thanks,
Fausto

**Comment by eswenson1** [comment]
Are you sure those are control-Fs there?  Or are they just ^F (circumflex followed by F)?  If that is the case, then just use emacs to insert the characters ^ and F (followed by font number).

If you really need to add a Control-F to a file, then you need to tell emacs to "quote" the next character. You do that by using the Control-Q prefix.  So typing Control-Q Control-F would insert a Control-F in the file.  Again, I'm not sure this is what is required -- but I don't know TJ6.  

The control-q prefix will also work for inserting a literal <esc> character in the buffer.

**Comment by eswenson1** [comment]
By the way, I successfully followed the instructions in printing.md to create that DEMO 1 file, run TJ6 on it, producing an XGP file and then on the host converting to PBM files.  So the characters that are supposed to switch fonts are ^F1 (to select font 1).  That is circumflex (^) followed by F followed by 1.  It is not a control-f.

**Comment by larsbrinkhoff** [comment]
Looks like this should be resolved. @TheFausap, feel free to ask more questions if your problem isn't solved.

**Comment by TheFausap** [comment]
@eswenson1 I tried the example but in my case I got ^F, but I used the conversion to pdf, so maybe this could be the problem.
I want to try with pbm.

**Comment by larsbrinkhoff** [comment]
I'm looking at the TJ6MEM document, and it does use Control-F for font selection.  So in EMACS, type Control-Q and then Control-F to insert a single ^F control character in the buffer.

@eswenson1, can you double check your file?  Is it really two characters, ^ and F?

**Comment by TheFausap** [comment]
@larsbrinkhoff Using CTRL-Q + CTRL-F, according the TJ6 manual it should display an "epsilon", and using supdup terminal it displays correctly an "epsilon".

**Comment by atsampson** [comment]
Apologies for the confusion. I entered the font changes as single characters (with ^Q^F in Emacs). I wouldn't be surprised if TJ6 does have another way of doing the same thing, though... remember the original version of the manual has a section on how to use TJ6 if your terminal doesn't support lowercase letters!

Maybe we need a notation for "this is a single character" in our documentation. Some of the early ITS docs draw circles around altmodes and control characters...

**Comment by larsbrinkhoff** [comment]
Can Unicode help here or does it just have crap like ☃? 😡

**Comment by larsbrinkhoff** [comment]
Funky brackets? 【^F】

**Comment by TheFausap** [comment]
Hello, I can confirm using CTRL-Q and CTRL-F, the bold font is displayed correctly in PDF.
Here my EMACS screen (using SUPDUP terminal, under Ubuntu):
![screenshot from 2018-06-04 12-58-44](https://user-images.githubusercontent.com/1846443/40914115-399c3060-67f7-11e8-8230-971b265563b3.png)
I have to check with my loongson laptop (ITS + KLH10, under debian 8, runs very smoothly under MIPS Yeelong... RMS should be happy :) ) using a standard terminal.

**Comment by TheFausap** [comment]
I tried on yeloong, after a change in /etc/default/console-setup 
```
CHARMAP="UTF-8"
CODESET="guess"
FONTFACE="Terminus"
FONTSIZE="8x16"
```
I am able to display the epsilon char also in the console

**Comment by larsbrinkhoff** [comment]
The appearance of an episolon isn't critical to entering ^F in EMACS.  On terminals that aren't capable of displaying the SAIL charset, the two characters ^ and F can be displayed instead.

Of course, if your terminal isn't displaying anything useful, that's a problem.  You can type `:TCTYP NO SAIL` to switch to from the SAIL charset to ASCII  mode.

**Comment by atsampson** [comment]
Another option for marking up keypresses in the documentation is the `<kbd>` element, which GitHub's CSS styles like a keycap - the downside being that you have to write `<code>` or `<pre>` rather than single/triple backticks.

For example, to kill a job you type <code><kbd>^Z</kbd>:kill</code>, or here's my EVARS file:

<pre>
..<kbd>^R</kbd>{: M.M ^R Backward Paragraph<kbd>$</kbd>
..<kbd>^R</kbd>}: M.M ^R Forward Paragraph<kbd>$</kbd>
..<kbd>^R</kbd>[: MM Make Prefix Character<kbd>$</kbd>.Y<kbd>$</kbd>
:.Y(<kbd>^^</kbd>A): M.M ^R Up Real Line<kbd>$</kbd>
:.Y(<kbd>^^</kbd>B): M.M ^R Down Real Line<kbd>$</kbd>
:.Y(<kbd>^^</kbd>C): <kbd>^^</kbd><kbd>^F</kbd>FS ^R INIT<kbd>$</kbd>
:.Y(<kbd>^^</kbd>D): <kbd>^^</kbd><kbd>^B</kbd>FS ^R INIT<kbd>$</kbd>
</pre>

**Comment by larsbrinkhoff** [comment]
That looks good, I think.
