### ISSUE TITLE
FTP or TFTP jobdev

### ISSUE THREAD

**Issue by atsampson** [PDP-10/its#953]
As part of a comprehensive discussion of ITS filenames, Christopher Stacy wrote in news:uzo3ee88v.fsf@spacy.Boston.MA.US:

> The long filenames feature was most useful for remotely accessing files on other file servers besides ITS, [...] For less fancy access to the more conventional file systems (TOPS-20, VMS, UNIX) there was eventually an FTP or TFTP device.

I can't see a DEVICE; JOBDEV FTP or similar, though...

**Comment by larsbrinkhoff** [comment]
I have never seen anything else to suggest there were.  Maybe ask Mr Stacy or the mailing list?

By the way, is there a way to retrieve messages from message IDs from, say, Google Groups.  I tried another service at random, but it couldn't find all messages I wanted.

**Comment by atsampson** [comment]
Usually pasting the message ID (without news: or <>) into the Google Groups search box will find it, but it looks like they don't have that message. I've put a copy [here](https://stuff.offog.org/its/news/2002-cstacy).

**Comment by larsbrinkhoff** [comment]
Hello @cstacy,

A Usenet post of yours quoted in this issue says there was an FTP or TFTP device in ITS.  Do you remember any more details about this?

There's FTP for ARPANET, Chaosnet, and TCP/IP of course, but we haven't found any JOBDEV thing.

**Comment by larsbrinkhoff** [comment]
Maybe it was RMTDEV.

I'm closing this since it seems to be a dead end.  Feel free to reopen if more information appears.

**Comment by cstacy** [comment]
This must have been fairly late in the game, after the SOPEN call was developed by RMS.  That was originally for accessing the Lisp Machine file system that he wrote (rather different from the Symbolics one).  I have a vague recollection of this being used to access TOPS-20.  But I can't remember anything else.   My guess is that the source resided in someone's personal directory, and so quite possibly now lost.  One device name that would have been linked would be "OZ", the name of our TOPS-20 machine.

**Comment by cstacy** [comment]
Side note: JTW started writing an NFS implementation for ITS but you'd have to ask him about it.

**Comment by eswenson1** [comment]
I do see a device driver (IFILE) that talks about OZ FTP support and uses the SOPEN call. The TITLE of that program is IFILE SERVER.  It includes this comment:
```
;MODIFIED FOR ITS/OZ FTP.  from MINIC from MINI.
;
; 2-Sep-85 17:54:14, GZ - use SOPEN, fix EOF handling
```
I also see the DQ device that also uses SOPEN.  It was written by you (CSTACY) in 1985 and has the following TITLE:  "DQDEV - Domain Device".

**Comment by eswenson1** [comment]
I also found another program (in an archive) called OZDEV.  It's title is OZDEV - FILE protocol OZ device for ITS. It also uses PKTSIOT for its I/O (no SOPEN).

**Comment by cstacy** [comment]
On 1/9/19 5:28 PM, Eric Swenson wrote:
>
> RMTDEV appears to have a few hostnames burned into it: KANSAS, OZKS, 
> SP, SPEECH. I don't see any calls to SOPEN,
>
Yeah,  the SOPEN happens in the client process: it's the (only) way tp 
get a long filename.
The JOBDEV (RMTDEV) gets its parameters from JOBCAL (word 7 
corresponding to SOPEN).

The host names would still have to be linked like  DEVICE;JOBDEV KANSAS 
=> DEVICE;ATSIGN RMTDEV.
That code with the hardcoded host names s is just doing some host name 
canonicalization (for some reason).
Maybe those are for links that serve as machine-local aliases for host's 
that don't really have those aliases.
There is also some business with some "DNRF" which I have no idea what 
that's about,
and a default host name "PS" which sounds like something I should recall 
but do not :)

**Comment by larsbrinkhoff** [comment]
Branching off topic here, but this is also in the Usenet post.  I haven't seen anything resembling this encrypting JOBDEV either.  But then I haven't looked.

> Files that you didn't want people reading were stored in the encrypting file system, which was just a device that you could specify as part of a regular old file name; it basically implemented a front-end on the regular disk device. Hardly anyone ever used it because of speed considerations,  and because of the culture, and I don't even remember the device name or how you specified your file's passphrase to it, or anything!  Maybe you had to do something bizarre, like write on it for input, or open two files in succession.  I'll have to go ask someone else who might remember.

**Comment by larsbrinkhoff** [comment]
> a default host name "PS" which sounds like something I should recall
but do not

Isn't PS: the primary file structure on TOPS-20?  Or something like that, I'm not a Twenex user.

**Comment by larsbrinkhoff** [comment]
I see in backup listings from 1976 that on ML there was a file SYS; ATSIGN OTHER, and it was linked from DEVICE; JOBDEV AI, DM, MC, and MUL.  This seems something like MLDEV, except MUL... would that be Multics?

**Comment by larsbrinkhoff** [comment]
I do see a DEVICE; LBSIGN RFC105 which could be a Trivial File Transfer server.  Not a JOBDEV, though.

I wonder where the name LBSIGN comes from?  A pun on ATSIGN I suppose, but the LB part?

**Comment by eswenson1** [comment]
I think it very likely that MUL would be Multics. Both the Mathlab and the Macsyma groups used Multics regularly. And Macsyma was kept working and up-to-date on Multics from MC. Surprised we don’t see that device on MC.

**Comment by eswenson1** [comment]
And PS: is a prefix on TOPS-20 for the “primary structure” (disk).

**Comment by eswenson1** [comment]
Regarding the encrypted disk storage device, it is existed it must have been after my time (post 1980). We used SCRMBL and USCRM to store and decrypt encrypted files. This was not a device but a TS program that prompted for a password on use. I think there was another program (SCRAM) that was also in use earlier.
