### ISSUE TITLE
MACSYMA : declare command not working properly (?)

### ISSUE THREAD

**Issue by TheFausap** [PDP-10/its#960]
Hello,

I'm trying to port some new MAXIMA code in MACSYMA, and I stumbled upon this command: DECLARE.
Its usage is related to variable and/or functions properties (user-defined or not).

So I tried this test (quite simple):

![screenshot from 2018-06-08 15-57-04](https://user-images.githubusercontent.com/1846443/41161959-b7388c04-6b34-11e8-8c5c-a5f9003e15e0.png)

The MACSYMA reply at C2 is correct.

So, two questions arise:

1) Is some file missing in our distribution ?

or 

2) Am I using something not properly ? (I didn't find any mention about this "declare" command in old manuals)

What do you think ?

regards,
Fausto

**Comment by larsbrinkhoff** [comment]
I don't know anything about Macsyma, but wouldn't it complain about `DECLARE` rather than `WN`?  I'm guessing wildly that DECLARE is there, but it winds up making a call to WN which may be missing.  Or not loaded or something.

**Comment by eswenson1** [comment]
Right. Declare is there. It is just broken. Maybe we have inconsistent sources. Needs investigation. I can look into it when I next have some time.

**Comment by eswenson1** [comment]
Well, it appears that $DECLARE is calling (eventually), MARK+0, code in MRG; DB >.  In this function, it invokes the LEXPR (declared earlier) function WN.  I can see no definition for this function in any sources I have.  I will have to go look for this -- it is clearly not loaded in our Macsyma build nor autoloaded.

**Comment by eswenson1** [comment]
I upgraded various versions of macsyma source files and now I get this:

> *macsym^K!
> 
> This is MACSYMA 999
> 
> (C1) assume(a>b);
> Call to an undefined function 'INTERSECT*' at Lisp level.
> 
> (C2)

So more to debug.....

**Comment by eswenson1** [comment]
Looks like INTERSECT* is defined in DSK: JPG; COMM > according to MACSYM; MACSYM TAGS.  THe version of JPG; COMM we have is version 395.  The MAXERR; COMM version is 408.  So it looks like INTERSECT* was added after 395.  I'll try to locate later versions of this file.

**Comment by TheFausap** [comment]
Also other function are affected by WN

```
(C5) polarform(d1);

ATAN2 FASL DSK MAXOUT being loaded 
Loading done
Call to an undefined function 'WN' at Lisp level.

```

where d1 is SIN(EXP(%I*Y+X))

**Comment by eswenson1** [comment]
I believe a found the WN issue. It was renamed to SEL (I think) and we’re running some old code for which updates are available. I’m trying to get the updated code. I’ve found old source that defined WN but later versions that replaced it with SEL.

**Comment by eswenson1** [comment]
In my environment, I get the following.  Note that I have to load LISP; MLSUB FASL first (I've got to figure out why ARRAYP is not defined on startup):

> macsym^K
> 
> This is MACSYMA 999
> 
> (C1)
> ;BKPT LISP  (Type <Alt>P<Space> to continue.)
> (load '((lisp) mlsub))
> 139217
> $p
> (C1) d1 = SIN(EXP(%I*Y+X));
>                                                                  %I Y + X
> (D1)                                                  D1 = SIN(%E        )
> 
> (C2) polarform(d1);
> 
> RPART FASL DSK MACSYM being loaded
> Loading done
> Is  D1  positive, negative, or zero?
> 
> zero;
> 
> HYPER FASL DSK MAXOUT being loaded
> Loading done
> 
> ATAN2 FASL DSK MAXOUT being loaded
> Loading done
>                  2   X             2   X              2   X             2   X
> (D2) 0 = SQRT(COS (%E  COS(Y)) SINH (%E  SIN(Y)) + SIN (%E  COS(Y)) COSH (%E  SIN(Y)))
> 
>                                                                     X                X                X                X
>                                                      %I ATAN2(COS(%E  COS(Y)) SINH(%E  SIN(Y)), SIN(%E  COS(Y)) > COSH(%E  SIN(Y)))
>                                                    %E
> 
> (C3)

So ensuring ARRAYP is defined causes this to work properly (I guess).  Can you confirm?

**Comment by eswenson1** [comment]
The formatting of that output is all off, but I can't get GitHub to make it prettier.

**Comment by eswenson1** [comment]
When I try to do:

>  (C3) assume(a>b);
> Call to an undefined function 'INTERSECT*' at Lisp level.
> 
> (C4)

I get the undefined function INTERSECT* error.   This, according to MACSYM; MACSYM TAGS is supposed to be defined in JPG; COMM >.  It isn't (in our version of COMM, which is 395.  I see that there was a version 415, and that version 408 was the last version built on MC at least according to the MAXERR; COMM 408 file.  So I'm trying to track down versions of COMM >= 408.  This will presumably fix this INTERSECT* issue.

**Comment by eswenson1** [comment]
I found JPG; COMM 415, and indeed, it does defined INTERSECT*.  So with the following two patches, I can now do the assume(x>y) without error.  

> *macsym^K!
> 
> This is MACSYMA 999
> 
> (C1)
> ;BKPT LISP  (Type <Alt>P<Space> to continue.)
> (load ".temp.;comm fasl")
> 142945
> (load "lisp;mlsub fasl")
> 143375
> $p
> (C1) assume(x>y);
> (D1)                                                         [X > Y]
> 
> (C2) is(f(a)>f(b));
> MACSYMA was unable to evaluate the predicate:
> F(A) > F(B)
> 
> (C3) declare(f,increasing);
> (D3)                                                          DONE
> 
> (C4) is(f(a)>f(b));
> MACSYMA was unable to evaluate the predicate:
> F(A) > F(B)
> 
> (C5)

@TheFausap is Macsyma supposed to be able to evaluate that "IS" function successfully given that f is known to be increasing?

**Comment by eswenson1** [comment]
Sorry for being stupid.  I used x>y rather than a>b.  Things work now for me (with the above patches).  I'm running a new local Macyma:

> This is MACSYMA 1000
> 
> (C1) assume(x>y);
> (D1)                                                         [X > Y]
> 
> (C2) declare(f,increasing);
> (D2)                                                          DONE
> 
> (C3) is(f(x)>f(y));
> (D3)                                                          TRUE
> 
> (C4)

I'll commit changes to use JPG; COMM 415 and to load LISP; MLSUB FASL at macsyma dump time.

**Comment by eswenson1** [comment]
With my latest macsyma, I get this:

> (C8) d1 = SIN(EXP(%I*Y+X));
>                                                                    %I Y + X
> (D8)                                                [X > Y] = SIN(%E        )
>
> (C9) polarform(d1);
>
> RPART FASL DSK MACSYM being loaded
> Loading done
>
> ATAN2 FASL DSK MAXOUT being loaded
> Loading done
>                                          %I ATAN2(0 > 0, X > Y)             2          2
> (D9)                                  [%E                       SQRT((X > Y)  + (0 > 0) )]
>
> (C10)

Is this what is supposed to happen?
