### ISSUE TITLE
Atari Logo

### ISSUE THREAD

**Issue by atsampson** [PDP-10/its#964]
MAPS lists files in ATLOGO dated 1981, including ATLOGO; ATARI and ATLOGO; SUPDUP. (Compare #934, Apple II Logo.)

That's three years before LCSI's Atari Logo was released. Perhaps related to https://logothings.wikispaces.com/Atari+Cambridge+Research (link now dead, [archived version](http://web.archive.org/web/20100821142302/https://logothings.wikispaces.com/Atari+Cambridge+Research)):

> Atari Cambridge Research 1982-84: In this very short lived lab a group of us, many of whom had been part of the MIT AI Lab's Logo Group, imagined a children's playstation of the future.

HSTINF RECENT says "Atari Cambridge has gone belly up" as of June 1984. IOELEV lists two Chaosnet subnets belonging to Atari, and they had two MINITS machines,  "System 75: Atari Sunnyvale Bridge" and "System 77: Atari Cambridge Bridge".

@savetz, have you heard anything about an Atari Logo from MIT, or talked to anyone who worked at Atari Cambridge Research?

**Comment by larsbrinkhoff** [comment]
I received this information:

> I'm not sure what ATLOGO was.  I might have started an Atari Logo project, but we never did any work on it.  LCSI got the Atari contract, after the MIT Logo lab closed.

**Comment by larsbrinkhoff** [comment]
We now have ATLOGO; AR2 ATARI.  Some interesting files, but not an implementation of Logo.

```
File name       Words  Modified            Referenced    Byte
ATARI  1         4020  1981-05-03 19:12:21(1982-05-10)  36
ATARI  KST       2440  1981-11-18 23:22:55(1982-05-10)  36
ATARI  OS        4596  1981-04-11 14:54:32(1982-05-09)  36
ATARI  STUB      1058  1981-04-25 02:24:05(1982-08-14)  36
CONVER 1          251  1981-09-16 15:31:16(1982-05-10)  36
CONVER FASL       308  1981-09-16 15:31:40(1982-05-10)  36
DOWN   BASIC      522  1981-04-03 23:26:23(1981-11-15)  36
HEXTEX LSP        512  1981-04-04 22:29:41(1981-11-15)  36
MASTER BASIC      707  1981-04-03 23:40:07(1982-06-27)  36

**Comment by larsbrinkhoff** [comment]
@everyfan maybe this is something for you.  There's 6502 code BASIC programs.  Not quite C64 of course, but close.

**Comment by everyfan** [comment]
Looks interesting! I'd love to take a look attem

**Comment by larsbrinkhoff** [comment]
You know the secret vault with all the files, right?  The
PDP-10/its-vault repository.  It's the file files/atlogo/ar2.atari in
there.  Now get the itsarc program.  It's in the
larsbrinkhoff/pdp10-its-disassembler repository, but if you have the its
repository checked out, it's in tools/dasm.

Run `itsarc -x ar2.atari` to extract the files.

**Comment by everyfan** [comment]
It looks like some initial tests for Atari LOGO. They wrote some kind of uploader/downloader in BASIC to transfer with ITS (a comment says FTP), and a LISP program to convert binary output to text-based HEX output so they could transfer binary files to the Atari. Then, they wrote a simple machine language test in what appears to be CROSS. However, the test does not appear to be any kind of implementation of LOGO, just something to mess around with the hardware.

**Comment by savetz** [comment]
Folks,

 Can someone  explain to me what this mailing list is? What is PDP-10/its?
What does it have to do with Atari?

 It seems interesting, but I am confused.

 I don’t think I’m on this list, I think I’m being cc’d.

Help?

Thanks
Kevin

**Comment by larsbrinkhoff** [comment]
Forgot to explain, PDP-10/its is the GitHub repository for the PDP-10 operating system called ITS.  See the README.md for more information, or Wikipedia: https://en.wikipedia.org/wiki/Incompatible_Timesharing_System

**Comment by leighklotz** [comment]
I think these were mine and a colleague's and not lcsi staff.  Ed worked on lcsi logo for the Atari.  We tried at the logo lab and bid on it but lost out.  I went to terrapin and supported the apple 2 logo from MIT and then on to C64 and Mac

**Comment by larsbrinkhoff** [comment]
Thank you.

I'd say this can probably be closed.

**Comment by larsbrinkhoff** [comment]
ATLOGO; LOGO 6, dated 1981-04-21.

```
.TITLE MIT Atari Logo

;  Logo Language Interpreter for the Atari 800 Microcomputer,

;  Written and developed by Patrick G. Sobalvarro, Leigh L. Klotz,
;  and John H. Palevich with the M.I.T. Logo Group, at the Massachusetts
;  Institute of Technology. It is derived from from MIT Apple II Logo
;  by Stepehn L. Hain, Sobalvarro, and Klotz.
```

**Comment by larsbrinkhoff** [comment]
I believe @jackpal mentioned above also wrote a terminal emulator supporting SUPDUP and VT52 cursor codes.

**Comment by larsbrinkhoff** [comment]
Does not assemble.  It seems like a work in progress.

**Comment by joaopa00** [comment]
Hello. Is the source code of ATlogo available for public, even if it does not compile?

.TITLE MIT Atari Logo

;  Logo Language Interpreter for the Atari 800 Microcomputer,

;  Written and developed by Patrick G. Sobalvarro, Leigh L. Klotz,
;  and John H. Palevich with the M.I.T. Logo Group, at the Massachusetts
;  Institute of Technology. It is derived from from MIT Apple II Logo
;  by Stepehn L. Hain, Sobalvarro, and Klotz.

**Comment by larsbrinkhoff** [comment]
Hello @joaopa00,

Sorry, that file is not available.  Some files with interesting background material are here: https://github.com/PDP-10/its-vault/tree/master/files/atlogo  

 The "ar" files are ITS archives.  Use this to extract files: https://github.com/larsbrinkhoff/pdp10-its-disassembler/blob/master/itsarc.c

**Comment by joaopa00** [comment]
Ah bad news. Can you confirm that ATLogo was written in Assembly Z80?

**Comment by larsbrinkhoff** [comment]
I believe it's 6502.

**Comment by larsbrinkhoff** [comment]
I found a LOGIN file with these lines:

```
:tag atari
:tctyp soft hei 24 wid 39 +%tosai +%tolid +%tocid full +%tprsc no overwrite
:ttyloc Logo 327
```

This suggests there was an Atari (800? as above) computer in room 327, running a program capable of interpreting ITS terminal codes.  I think it probably is ATLOGO; SUPDUP 1.
