### ISSUE TITLE
MACSYMA : example command missing function

### ISSUE THREAD

**Issue by TheFausap** [PDP-10/its#967]
Hello,

I got the same problem as DECLARE command, with "example" command:

![screenshot from 2018-06-11 14-59-37](https://user-images.githubusercontent.com/1846443/41232961-3c1be52e-6d88-11e8-99df-a7ec95d9e505.png)

In this case I found a definition of FEXPRCHK in maxdoc/mdoc.47, at least an example, also in intro.errors.
I do not understand if this a user-defined function I have to load into macsyma by hand, or can be defined during the build process.

thanks,
Fausto

**Comment by eswenson1** [comment]
Without having (yet) looked at this, I'd say it is a problem with the build process. There was no documentation on the correct way to build Macsyma and we don't know whether we have a consistent set of sources. It is quite possible that there is a missing dependency here. In cases like this one, where you get an undefined function at the Lisp level, it is either that a required macro was not available at compile time -- manifesting as an undefined function at run time, or that a required external function is not loaded (or autoloaded) in the environment.  The documentation in mdoc.47 does suggest that this function should be available.  I'll look around to see if I can find it defined anywhere, and if so, try to understand why it is not in the dumped Macsyma image (or an autoload).

**Comment by eswenson1** [comment]
FEXPRCHK is supposed to be defined in MACSYM; SUPRV FASL.  MAXDOC; DCL AUTOLD defines an autoload property for 'FEXPRCHK to load it from SUPRV FASL.  Interestingly, JPG; SUPRV FASL, the source for MACSYM; SUPRV FASL, defines a Macsyma macro FEXPRCHECK (not FEXPRCHK).  More investigation is necessary -- it is clear that we have some version mismatches between sources used to build Macsyma.  It isn't (yet) clear to me which reference or definition is old.

**Comment by eswenson1** [comment]
It is interesting, though, that there is this comment in MAXDOC; MDOC.47:  

> Demo:		;; One might implement FEXPRCHK as follows
>		(DEFUN FEXPRCHK (L FN)
>		  (IF (OR (NULL L) (CDR L))
>		      (MERROR "Wrong number of args to ~:@M~%~M" FN L)))

The use of the conditional there almost suggests, as you've said @TheFausap, that the user is supposed to define this. Strange, however, that there is an entry just afterwards in MDOC.47 that documents the function as though it should exist.  Also, the definition for FEXPRCHECK in JPG; SUPRV is different than suggested in MDOC 47 -- it is a macro, not a function, and as such takes a single argument (the form to macroexpand) rather than two args. These are clearly not interchangeable.

**Comment by eswenson1** [comment]
I now believe, based on various hints, that FEXPRCHK is supposed to be defined in JPG; SUPRV >.  We currently have JPG; SUPRV 619, but there appears to have been a few later versions. I'm trying to track down SUPRV 642 now.  With luck, the function will appear then.  Until that time, please try using the definition in my comment of 9 days ago.

**Comment by eswenson1** [comment]
If I define FEXPRCHK at a lisp breakpoint from within macsyma, I get this:

> (DEFUN FEXPRCHK (L FN)
> (IF (OR (NULL L) (CDR L))
> (MERROR "Wrong number of args to :@m%-M" FN L)))
> FEXPRCHK
> $p
> (C1) example("mat_funm");
> 
> EXAMPL FASL DSK MAXOUT being loaded
> Loading done
> 
> MLMAC FASL DSK LISP being loaded
> Loading done
> [MANUAL, DEMO, DSK, DEMO]  NON-EXISTENT DIRECTORY
> (C2)

That suggests we also need DEMO; MANUAL DEMO.  I'll try to locate that too and add to the build.

**Comment by eswenson1** [comment]
Hmm....I put a file from minimal; manual demo into demo; manual demo and reran the above.  Now I get this:

> *macsym^K
> 
> This is MACSYMA 999
> 
> (C1)
> ;BKPT LISP  (Type <Alt>P<Space> to continue.)
> (DEFUN FEXPRCHK (L FN)
> (IF (OR (NULL L) (CDR L))
> (MERROR "Wrong number of args to :@m%-M" FN L)))
> FEXPRCHK
> $p
> (C1) example("mat_funm");
> 
> EXAMPL FASL DSK MAXOUT being loaded
> Loading done
> 
> MLMAC FASL DSK LISP being loaded
> Loading done
> mat_funm not found in file
> 
> (C2)

Do you know how this is supposed to work?  The file demo; manual demo doesn't define anything for "mat_funm".  Should it?

**Comment by TheFausap** [comment]
Maybe I was wrond about the function name (I was looking to a too much recent manual), can you try with mat_fun? 
It applies a function to a matrix, using a taylor series (or similar).

**Comment by eswenson1** [comment]
I get the same error:

> *macsym^K!
>
> This is MACSYMA 1000
> 
> (C1)
> ;BKPT LISP  (Type <Alt>P<Space> to continue.)
> (DEFUN FEXPRCHK (L FN)
> (IF (OR (NULL L) (CDR L))
> (MERROR "Wrong number of args to :@m%-M" FN L)))
> FEXPRCHK
> QUIT
> (C1) example(mat_fun);
> 
> EXAMPL FASL DSK MAXOUT being loaded
> Loading done
> 
> MLMAC FASL DSK LISP being loaded
> Loading done
> MAT_FUN not found in file

(C2)

**Comment by eswenson1** [comment]
The example function loads DEMO; MANUAL DEMO and can accept a parameter that matches one of the sections in this file.  So, for example, the file has these:  functions, arrays, lambda, lists, mactrices, equations, if, block, do; evaluation, exp, trig, complex, ev, zeroequiv, etc.  

So you can do example(lists); and it will show you an example and then give you a _ prompt. Typing space moves to the next example.  When there are no more for the chosen topic, you will be shown the next topic name followed by &&.  Then you can use example(topic) to see that one.  

Not sure if we have a "good" copy of DEMO; MANUAL DEMO.  It probably is missing mat_fun.  Haven't found a copy that defines mat_fun. Also, I got the MANUAL DEMO file from the MINIMA; directory.  There may be other copies that are less "minimal".  :-)

**Comment by eswenson1** [comment]
Note that mat_fun is not in the DEMO; MANUAL DEMO (71) that we have. There is a matrices entry. Look for entries that are appended with two ampersand characters— &&.
