### ISSUE TITLE
LMODEM - serial file transfer

### ISSUE THREAD

**Issue by atsampson** [PDP-10/its#969]
CPM; TS LMODEM
.INFO.; LMODEM HELP
CPM; HELP LMODEM  
GUMBY; LMODEM INFO  
FJW; LMODEM > (also PLUKEL; and EB;)
MC: CPM; MODEM2 PROTO

GZ in news:2539@sri-arpa.UUCP:

> Actually, the current ITS version is MMODEM, and it supports CRC's. Source in GZ;MMODEM >.
>
> LMODEM is still supported on ITS, also it works on Multics.  Source in FJW;LMODEM > (although I think the running version on ITS is patched). Yes, it's written in Lisp. Author is EB@MC.

So LMODEM implements the XMODEM protocol, and MMODEM implements either XMODEM-CRC or YMODEM...

**Comment by atsampson** [comment]
And if anyone needs XMODEM for a different PDP-10 OS...

> Date: 05 Oct 1982 1133-PDT
> From: Max Diaz <MMD@Su-Ai>
> Subject: XMODEM for TENEX...
> To:   info-cpm at BRL [...]
>
> New version in AR60:CPM; XMODEM SAI has a few bugs corrected (^C capability...), and slightly better doc.
>
> This version is for TENEX/TOPS20/WAITS, but has no TAC functions yet; it is primarily for transfers  to/from a hard-wired or dial-in micro.

**Comment by larsbrinkhoff** [comment]
ITS can run WAITS programs...

**Comment by atsampson** [comment]
[XMODEM.SAI[SUB,SYS]](https://www.saildart.org/XMODEM.SAI[SUB,SYS]) on SAILDART.

**Comment by larsbrinkhoff** [comment]
Split off MMODEM to #2020.

**Comment by larsbrinkhoff** [comment]
The LMODEM code loads UMLMAC, IOTA, LOOP,  GCDEMN, FORMAT, SHARPM, YESNOP, DEFMAX, MACAID, which are already present in this repository.  It also loads SIGNAL and ERRMAC which aren't.  But there are copies in the EJS directory, so that may be fixable.  The one missing file is DSK8.

**Comment by larsbrinkhoff** [comment]
```
Date: 5 Jun 1982 1726-PDT
Sender: BILLW at SRI-KL
Subject: Re: LMODEM
From: BILLW at SRI-KL

There is a TWENEX version of MODEM in SRI-KL::<BillW>MODEM.MAC
It supports the standard MODEM2 user interface (such as it is)
and includes hacks and hooks to enable it to be the initiating
programs, given an autodialer or TTY line connected to a "remote
host".  It does not, however, attempt to do anything fancy to be
able to talk over the arpanet...
```

@WestfW's MODEM.MAC:
https://www.oocities.org/westfw/modem.mac.txt

**Comment by larsbrinkhoff** [comment]
We have located copies of all necessary LMODEM files, but there is a problem compiling them.  The `condition-handlers` macro (from SIGNAL) generates a bad call to `CASEQ`.  @eswenson1 tracked down the problem to the version of LOOP; it works with 809 and older, but not 818 (latest from MIT) or 819 (current on GitHub).

**Comment by larsbrinkhoff** [comment]
The macro condition-handlers in SIGNALS uses the LOOP macro in a way that's no longer allowed.  The COLLECT clause is followed by two forms: the first is a check, and the second is actual data for the list.  This was allowed up until LOOP version 809, but no longer in 818.  Moving the check do a DO clause fixes the problem.

**Comment by larsbrinkhoff** [comment]
LMODEM checks the TTY line parameters.  First it examines the %TYDIL bit in TTYTYP, to see if it's a dial-up line.  If not, it must be an STY or else LMODEM will balk.

Second, it checks what type of TTY controller it is.  Only TK-10, Morton, or DTE-20 are recognized but a unknown type will be accepted.  Only DTE-20 works with full 8-bit transfers, the others get 7-bit.

**Comment by larsbrinkhoff** [comment]
From http://oldcomputers.dyndns.org/public/pub/manuals/zcpr/zcpr3_the_manual_(ocr).pdf
![lmodem](https://user-images.githubusercontent.com/775050/140922930-d6462fe8-4af6-470c-92f3-a8a53b630928.png)

**Comment by atsampson** [comment]
That text in the ZCPR3 manual is a bit mangled, but it's copied from [The Great SIMTEL20 Archive Blurb](https://github.com/larsbrinkhoff/its-archives/blob/master/usenet/1984-towson-simtel2-blurb#L179) which was periodically posted to Usenet. It's meant to say:

> On ITS machines, file transfer using the Christensen protocol can be done using MMODEM (type :MMODEM for instructions), or LMODEM.  Documentation for LMODEM is in file .INFO.;LMODEM HELP. Other useful ITS utilities include TYPE8, which types an ASCII file stored in ITS binary format; TYPESQ, which types an ITS binary format "squeezed" file (see the first paragraph under FILE TYPES); USQ, which creates an unsqueezed version of a squeezed file; HEXIFY, which creates an Intel hex format file from an ITS binary format COM file; COMIFY which creates a COM file from an Intel hex file; and CRC, which computes the Cyclic Redundancy Check value for a file, using the same algorithm that is used by the CP/M program CRCK.  Brief instructions for any of these utilities except LMODEM can be obtained by typing ":utility_name" (for example, :CRC).

**Comment by WestfW** [comment]
> TWENEX version of MODEM ...  does not, however, attempt to do anything fancy to be
able to talk over the arpanet...

Actually, it did.  There were essentially two broken versions of tops20 floating around at the time; one of which did Telnet Binary Mode wrong, and one of which did not negotiate Binary Mode when the TTY (VTY) was set that way.  Or something like that.  The Tops20 modem code has hacks to try to get things to work in either case.

The oocities copy seems truncated.  I've uploaded a fresh copy of the tops20 code to https://github.com/WestfW/TOPS20-MODEM/tree/master (along with a bit of historical exposition.)

**Comment by larsbrinkhoff** [comment]
Closing this because LMODEM is now installed and working, see #2090.

Checked with KL10 DTE20 TTY line that has %TYDIL set.  It's available on port 10015.  I have not tested this with an (X)MODEM program on the other side though.

```
*lmodem^K!
Opened log file #FILE-OUT-|DSK:LARS;LARS LMDLOG|-72750.
Setting up for 8-bit protocol.

T
```
