### ISSUE TITLE
MACSYMA : ALGSYS bug (?)

### ISSUE THREAD

**Issue by TheFausap** [PDP-10/its#977]
Hello,

I think I got a bug in the latest code of ALGSYS (ALGSYS.480), even with a simple and banal (with solution x=0 and y=0) equation system, it tooks forever to run (I stopped after more 20 hours).

The old code (ALGSYS.149), in pdp-10/macsyma, works very fast and without any problem.

Below the steps to reproduce this behaviour (I'm using KLH10 as emulator):

![screenshot from 2018-06-15 17-11-47](https://user-images.githubusercontent.com/1846443/41475608-87051828-70bf-11e8-8c56-84d92179bb6d.png)

and I'm stuck (only ^z works), but with the old code, I have the correct result:

![screenshot from 2018-06-15 17-13-51](https://user-images.githubusercontent.com/1846443/41475630-982915a0-70bf-11e8-88d5-34fa3939c889.png)

The weird behaviour is also during the batchloading of the file... it seems this file (algsys.480) doesn't call any other functions (algsys.149 is more chatty).

regards,
Fausto

**Comment by TheFausap** [comment]
I think ALGSYS.480 is a partial file... or something broken. ALGSYS.1 or ALGSYS.149 starts with:

```
;;;;;;;;;;;;;;;;;;; -*- Mode: Lisp; Package: Macsyma -*- ;;;;;;;;;;;;;;;;;;;
;;;     (c) Copyright 1981 Massachusetts Institute of Technology         ;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(macsyma-module algsys)
(load-macsyma-macros ratmac)
```
etc... but not only comments... more is missing in ALGSYS.480

ALGSYS.480 starts with:

```
;;*(SETSYNTAX '/" 322. NIL)

(DECLARE (SPECIAL $GRINDSWITCH MAXNOFTRS BAKEQNS $ALGDELTA EQUATIONS $RATEPSILON
		 $ALGEPSILON B DN UP VARXLIST $KEEPFLOAT PARAM VAR GENVAR
		  VARLIST EPS *MAX *VAR EXTRAPARAM TVARXLIST *ROOTS *FAILURES
		  $RATPRINT FTRDFLAG $NUMER $RATFAC)
	 (*FEXPR $EV )
	 (GENPREFIX ALG)) 
```

**Comment by eswenson1** [comment]
I compared ALGSYS 477, ALGSYS 479, and ALGSYS 480 and it looks to me that ALGSYS 480 is a natural progressing that stems from the other too.  As you said, ALGSYS 149 and ALGSYS 150 are totally different.  In fact, it appears the Macsyma that was last built on MC used ALGSYS 149 as the source (as there exists the file MAXERR; ALGSYS 149).  So perhaps the right thing to do is is to commit ALGSYS 149 (or ALGSYS 150) as the source and remove ALGSYS 480.  Looking into the tape backup history for RAT; ALGSYS seems to indicate that ALGSYS 477,479,480 are circal 1976, and ALGSYS 149,150 are circa 1984. So clearly, we want the lineage from 149, 150.

**Comment by eswenson1** [comment]
I'll try to fix this soon.

**Comment by eswenson1** [comment]
I'll commit and submit a PR shortly.  I just tried it with ALGSYS 150 (full macsyma build) and get this:

> macsym^K!
>
> This is MACSYMA 999
> 
> (C1) eq1:[x*2+y,x-y]$
> 
> (C2) var:[x,y]$
> 
> (C3) algsys(eq1,var);
> 
> ALGSYS FASL DSK MACSYM being loaded
> SOLVE FASL DSK MACSYM being loaded
> Loading done
> Loading done
> 
> MRESUL FASL DSK MAXOUT being loaded
> Loading done
> 
> SUBRES FASL DSK MAXOUT being loaded
> Loading done
> (D3)                                                                                           [[X = 0, Y = 0]]
> 
> (C4)
