### ISSUE TITLE
LUSER - Provide help to users

### ISSUE THREAD

**Issue by eswenson1** [PDP-10/its#98]
SYS1; TS LUSER => SYSBIN; LUSER BIN
SYSENG; LUSER 85

**Comment by eswenson1** [comment]
Note, that with the unmodified sources, it is pretty useless, since none of the hard-coded lists users is likely to be logged in.  Same with the hard-coded list of machines.

**Comment by larsbrinkhoff** [comment]
Can you make a new issue that there's room for improvement?

**Comment by eswenson1** [comment]
Yes.

**Comment by eswenson1** [comment]
See #194
