### ISSUE TITLE
KLH10 default network interface

### ISSUE THREAD

**Issue by TheFausap** [PDP-10/its#981]
Could be possible modify the start script (for KLH10) in order to specify a network interface, if the system has more than one ? 
This could be useful, if you are in a VM with a NAT interface and a HostOnly (virtualbox for example), or if you are on a laptop without external network connection, but with a dummy network interface you can anyway use supdup or ftp.

Something like this:
```
#!/bin/sh

# Optional; needed for networking.
SUDO=sudo
NET_DEFAULT_IF=eth1

cd build/klh10
$SUDO KLH10_NET_DEFAULT_IF=$NET_DEFAULT_IF ./kn10-ks-its dskdmp.ini
```
thanks
Fausto

**Comment by larsbrinkhoff** [comment]
Yes, that would be useful.  Can you test this and open a pull request?

**Comment by TheFausap** [comment]
I already tested it. This is the method I'm currently using on my laptop.
How can exactly I do that? Can I open a branch in my forked repo then doing a pull request? Or do I have to create a new branch here ?

**Comment by TheFausap** [comment]
I figured out how to do that. I created a pull request. I hope it's ok.

**Comment by larsbrinkhoff** [comment]
Thanks.  It looks fine.
