### ISSUE TITLE
LISP COMPILER issue (?)

### ISSUE THREAD

**Issue by TheFausap** [PDP-10/its#984]
During my tests with EIGEN (#965), I discovered a bug in ALGSYS, used to recover eigenvectors (#977).
I mostly sorted out the issues with those two files, but I have a weird behavior  using LISP compiler.

If I run a MACSYMA session loading the ALGSYS lisp file (not FASL), then EIGEN (compiled or not), I'm able to calculate the eigenvectors.
If I compile ALGSYS 149 into ALGSYS FASL (with complr command), and use this one in the procedure above, I have an error:

```
ACALL FASL DSK MACSYM being loaded
Loading done

MDOT FASL DSK MACSYM being loaded
Loading done

LETFLEX FASL DSK LIBLSP begin loaded
Loading done

;DELET  - MACRO NOT PERMITTED IN UUO CALL 
```

then MACSYMA returns to his prompt.
So, it seems something is broken when that file (ALGSYS 149) is compiled.

regards,
Fausto

**Comment by TheFausap** [comment]
No problem @eswenson1 . I'll look into it. Thanks for the hint.

**Comment by eswenson1** [comment]
Ticket #990 will add EIGEN to the build.
