### ISSUE TITLE
MONIT - DM HACTRN alternative

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#996]
SYS; TS MONIT  
SYSENG; MONIT 114  
DMCG; MONIT 200

**Comment by atsampson** [comment]
I've had a go at getting MONIT 114 working on the [ats/monit branch](https://github.com/PDP-10/its/tree/ats/monit). It's from 1971 so it's bitrotted a bit - it uses the .LOGIN UUO which doesn't exist any more, and if it's not the top-level process, it tries to invoke DDT to set up a translation in a way that doesn't work now. It does seem to basically work if you patch out the top-level-process check, though!

**Comment by atsampson** [comment]
We know from transcripts that DM had newer versions than 114, so if MONIT 200 can be found (and is actually a newer version of this program, rather than something completely different) it would be worth giving that a try.

**Comment by larsbrinkhoff** [comment]
Interesting, can we get a preview?

MONIT 200 should be incoming, never know when though.

**Comment by larsbrinkhoff** [comment]
I think AI/ML ITS 785 from 1973 has .LOGIN flushed.  Maybe if some DM files were to appear, there could be an archaic ITS version that could run MONIT 114.

**Comment by larsbrinkhoff** [comment]
This description of the RELOAD .CALL sounds like what MONIT is trying to do.

```
        Most of the job's system variables are initialized;
        the file  SYS:ATSIGN <jname>  is then loaded and
        started up, where <jname> is the jname of the job
        (see the .JNAME user variable).
        For example, if the jname of the job is HACTRN,
        then the file  SYS:ATSIGN HACTRN  (which is DDT)
        is loaded and started.  This is how DDT performs
        the ^[U. command.  Note that the translation lists for
        the job are not cleared before this loading; thus one
        can translate the file names  SYS:ATSIGN <jname>  and
        cause a different file to be loaded.

**Comment by larsbrinkhoff** [comment]
So MONIT 114 may in fact have been running on a non paging ITS.

**Comment by larsbrinkhoff** [comment]
Diffing 114 and 200 shows a lot of commonalities.

**Comment by larsbrinkhoff** [comment]
@atsampson, ITS 724 does have .LOGIN, if you want to have another try with MONIT 114.  The next available version, 768, doesn't.
